### PR TITLE
Slip and slide

### LINKED ISSUE #1266: Too much friction when flicking (short-distance panning) the map
@lbud showed me today that the way `MGLMapView` handles panning gestures seems to impede navigation more than MapKit and the Google Maps SDK, as measured by the (very handy!) ease-of-getting-across-town metric. Part of this perception may come from #1258, but we definitely differ from those frameworks in other ways as well.

Here’s the first thing that comes to mind: in Mapbox GL, “flicking” the map doesn’t cause it to travel as far, and it takes a more robust pan gesture to register a flick. Both MapKit and the Google Maps SDK are more sensitive to flicks. The result is that you feel more friction while navigating.

I don’t have a good setup for scientifically comparing our gesture recognition, but in the name of pseudoscience, I positioned an `MGLMapView` and a `MKMapView` both so that [Twp. Rd. E in Williams Co., OH](https://www.mapbox.com/mapbox-gl-styles/#16/41.4859/-84.7995), is at the bottom at roughly the same zoom level. (This county built roads in a mostly regular grid, numbering north-south roads and lettering east-west roads, surely anticipating this experiment.) In the screen recordings below, 16 downward flicks of roughly the same length and speed sent the `MGLMapView` north to [Co. Rd. I](https://www.mapbox.com/mapbox-gl-styles/#16/41.5432/-84.7991) but the `MKMapView` all the way to [SR 34](https://www.mapbox.com/mapbox-gl-styles/#16/41.5566/-84.7976) (which would be J on the grid):

mapbox mapkit

On a device, the same gestures also took the `MGLMapView` to Co. Rd. I but sent the `MKMapView` past I-80/90 (roughly O on the grid). Google Maps sped all the way to Co. Rd. S.

It’s important to get this gesture right because it’s probably going to be the most common.

### PR DESCRIPTION
**Pull request by 1ec5**
On the perceived performance front, we’ve made the map feel far too “heavy” when it comes to gestures. Our gesture recognition impacts the map’s responsiveness pretty heavily. So here’s what I’d like to do to make the map have the same slippery feel as `UIScrollView`:

 - [x] Drift-pan more aggressively after flicking (fixes #1266)
 - [x] Drift-zoom after pinching
 - [x] Drift-rotate after rotating

After a flick of the finger, `MGLMapView` now drifts much more naturally than before. It’s just _ever-so-slightly_ more aggressive than `MKMapView` but still a lot less aggressive than Google Maps.

/cc @mourner @incanus

### CODE REVIEW

**Comment by 1ec5** [comment]
Currently working on getting the zoom animation right. There are apparently edge cases that cause the map to zoom out to NaN and get all wonky.

**Comment by 1ec5** [comment]
33aeecef220af5ee78551de56a2573d6b1145fd6 makes it really easy to hit #1199, so #1295 should be applied in conjunction with this PR.

**Comment by 1ec5** [comment]
2bc63f76a4c3200c61902e7133898d7ba35fedc1 makes #1258 that much more aggravating, so #1296 should also be applied in conjunction with this PR.

**Comment by 1ec5** [comment]
Ginormous [before](https://slack-files.com/T02G2QA3A-F04FWP8S1-be560012be) and [after](https://slack-files.com/T02G2QA3A-F04F8SJJN-564e9aeead) screen recordings, courtesy of the good citizens of Knockemstiff and Wapakoneta.

**Comment by mourner** [comment]
:+1:

**Comment by incanus** [comment]
Gonna check this out a bit.

**Comment by incanus** [comment]
This feels really awesome. I am seeing the occasional rotation though when trying to pinch zoom out.

**Comment by incanus** [comment]
Per voice we are going to merge this and iterate.

**Comment by 1ec5** [comment]
:banana::running::dash:

**Pull request merged**
