### PR TITLE
[android] #4529 - update DISTRIBUTE.md

### LINKED ISSUE #4529: Update docs on distribution
Currently we have a document for [distribution on Android](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/DISTRIBUTE.md). This is incomplete we should take some time updating it.

### PR DESCRIPTION
**Pull request by tobrun**
closes #4529 

Would love some :eyes: on this. Can someone review?

cc @bleege @zugaldia @tmpsantos

### CODE REVIEW

**Comment by bleege** [comment]
I'll :eyes: this for ya!

**Comment by tmpsantos** [comment]
:+1:

**Comment by bleege** [comment]
There's going to be some wording / ABI naming issues involved as Android officially supports one set while the `Makefile` currently supports another.  @jfirebaugh @kkaefer were talking recently about converting to the Android names in a ticket that sadly I can't find right now.

screen shot 2016-03-31 at 11 47 26 am
_Android ABI Names_

screen shot 2016-03-31 at 11 49 41 am
_Makefile's Current ABI Names_

**Comment by tmpsantos** [comment]
> were talking recently about converting to the Android names

This would be awesome.

**Comment by jfirebaugh** [comment]
https://github.com/mapbox/mason/issues/130

**Comment by bleege** [comment]
I just updated the doc to map the current Makefile ABI to the Android ABI.  This will let help people understand the current setup immediately and when the renaming in Mason is done we can update this to match.

**Comment by bleege** [comment]
Rebased and merged!

**Comment by tobrun** [comment]
@bleege great job on the doc side. I might take up mapbox/mason#130 at some point, it's about time that I learned how masons internals work..

**Pull request closed without merging**
