### PR TITLE
[WIP] Add solution for shape overlays to cross antimeridian

### PR DESCRIPTION
**Pull request by boundsj**
#4974 points out how GL Native cannot support a shape overlay that crosses the antimeridian. This PR is to provide support that use case by:

- [x] Adding tests that describe the problem
- [x] Changing Core GL to support shapes going over the antimeridian

The change in core should be a continuation of the work done in https://github.com/mapbox/mapbox-gl-native/commit/026b6d4c01a3d96af9629cc1790373137ecab950 which fixed several issues related to points surrounding the antimeridian but removed support for expressing shapes crossing the antimerdian with longitudinal values +-180º.

### CODE REVIEW

**Comment by boundsj** [comment]
The diff in the new `AntimeridianAnnotationSmall` test illustrates the case we would like to support but currently cannot. A shape with points greater than or less than +- 180º is not fully rendered. It is cut off at the antimeridian.

diff

cc @brunoabinader

**Comment by brunoabinader** [comment]
This looks related: https://github.com/mapbox/mapbox-gl-native/issues/5600

**Comment by brunoabinader** [comment]
Another observation: the full triangle is drawn when we duplicate each polyline coordinate with its 360 degrees negative counterpart, so the following workaround draws the full small triangle:
```c++
mbgl::Polygon<double> polygon = {{
    {{ { 190, 0 }, { 170, 10 }, { 170, -10 } }},
    {{ { -170, 0 }, { -190, 10 }, { -190, -10 } }}
}};
```

**Comment by mourner** [comment]
The triangle bug above will be fixed by https://github.com/mapbox/geojson-vt-cpp/pull/57

**Comment by brunoabinader** [comment]
Cherry-picked this commit in #6088 with a minor update to the expectation from `AntimeridianAnnotationLarge`: because we are now properly painting on both sides, the red line fill for the right tile now appears (you can notice it is bolder now):
expected

**Pull request closed without merging**
