### PR TITLE
[android] #4500 - OnMapReady not invoked for offline maps

### LINKED ISSUE #4500: onMapReady not getting called when offline when a (largish) offline region is present
Following up on #4486: Turns out the issue that I encountered only seems to occur when a offline region larger than a particular size has been downloaded. In my test case this occurs with a region of 87.353 megabytes but **not** with a region of 74.243 megabytes.

Testing steps are mostly the same as I outlined in #4486. The difference being that a OfflineRegion of ~87MB (or probably larger) is downloaded the first time application is loaded with the WiFi enabled.

@zugaldia, @jfirebaugh does that make sense?

I am putting together a test Activity in the TestApp to demonstrate.

### PR DESCRIPTION
**Pull request by tobrun**
closes #4500.

cc @jfirebaugh @zugaldia @bleege

### CODE REVIEW

**Comment by jfirebaugh** [comment]
I believe this change is safe and will have the intended effect. I want to try to understand why `DID_FINISH_LOADING_MAP` isn't working as expected though. That may indicate an issue that affects iOS and node as well as Android.

**Comment by bleege** [comment]
Picking this up now.

**Comment by bleege** [comment]
I just successfully tested by:

* Opening TestApp
* Opening Offline Map Activity
* Downloading Region
* Quiting Test App
* Turning WiFi Off (no cellular connection)
* Opening TestApp
* Opening Offline Map Activity
* Load Saved Region From `List Regions` Button

Will merge this into `release-ios-3.2.0-android-4.0.0` now.

**Comment by bleege** [comment]
Rebased and Merged!

**Pull request closed without merging**
