### PR TITLE
[Android] SupportMapFragment: Check KEY_META_DATA

### PR DESCRIPTION
**Pull request by vacxe**
If I try add SupportMapFragment in XML (i know it not good way, but any people can try do this) that than has NPE, because Bundle is empty. I think it simple solution to fix set access token. After, user can set style and other parameters when he get map async.

### CODE REVIEW

**Comment by tobrun** [comment]
@vacxe will review soon

**Comment by tobrun** [comment]
Going to pick this up, it seems valid suggestion to fallback to `meta-data` key even if we have removed the `APIAccess` class in previous release. This should also open up the possibility of having a `newInstance` method a parameter.

**Comment by tobrun** [comment]
I'm going to pull this in our repo so our CI tests can be run, this will also require me to open up another PR. You can follow along there.

**Comment by tobrun** [comment]
@vacxe separate PR created in #4610, I added some extra checks, ported code to MapFragment and allowed the possibility to use the `mapbox_access_token` string resource.

**Comment by vacxe** [comment]
@tobrun Thanks, nice improvement.

**Comment by tobrun** [comment]
@vacxe I just merged in #4610. Thank you for the contribution and great job on this!

**Pull request closed without merging**
