### PR TITLE
[core] Vendor libbenchmark

### PR DESCRIPTION
**Pull request by alexshalamov**
Prebuilt binaries for libbenchmark might be incompatible with some environments, for example, when mbgl-benchmark target is compiled on host with GCC and linked against mason's clang 5.0 compiled binaries. 
Vendored libbenchmark avoids aforementioned issue, as the target and the binary compiled with same compiler / options.

### CODE REVIEW

**Comment by alexshalamov** [comment]
/cc @kkaefer Used vendoring approach that you've mentioned.

@tmpsantos is this ok or you want libbenchmark to be a submodule?

**Comment by alexshalamov** [comment]
Talked to @tmpsantos, will rewrite PR and add libbenchmark as a submodule.

**Comment by kkaefer** [comment]
In the past, we've run into issues with out-of-date submodules. We now use cmake to automatically ensure module freshness; could you please add it in there as well?

**Comment by alexshalamov** [comment]
@kkaefer I think @tmpsantos added it in [vendor.cmake](https://github.com/mapbox/mapbox-gl-native/blob/master/cmake/vendor.cmake#L2)

**Pull request merged**
