### PR TITLE
Avoid calling -mapView:didUpdateUserLocation: in the background

### PR DESCRIPTION
**Pull request by 1ec5**
Per the documentation and MapKit behavior.

/cc @incanus @friedbunny

### CODE REVIEW

**Comment by incanus** [comment]
:+1:

**Comment by friedbunny** [comment]
Was this happening? Does this affect the blue "using location" status bar? (Still, looks good. :+1:)

**Comment by 1ec5** [comment]
> Was this happening?

PEBKAC, no, it wasn’t happening in the first place. Thanks for catching that, @friedbunny.

**Comment by incanus** [comment]
lol great catch

**Pull request closed without merging**
