### PR TITLE
autopublish node-pre-gyp binary

### PR DESCRIPTION
**Pull request by mikemorris**
Refs #2365

If a git tag beginning with `node-v*` points at `$TRAVIS_COMMIT`.

/cc @lucaswoj @bsudekum

### CODE REVIEW

**Comment by bsudekum** [comment]
:+1: slick

**Comment by mikemorris** [comment]
@jfirebaugh Is there a good way to differentiate between the [branch push](https://travis-ci.org/mapbox/mapbox-gl-native/builds/89487307), [tag push](https://travis-ci.org/mapbox/mapbox-gl-native/builds/89487288) and pull request Travis builds here?

**Comment by lucaswoj** [comment]
Awesome! :ship:

**Comment by jfirebaugh** [comment]
:+1: `$TRAVIS_TAG`

**Comment by mikemorris** [comment]
Just a word of caution that this will always publish a binary named after the version in `package.json`, not  named after the tag (although those should match for regular releases).

**Comment by mikemorris** [comment]
Ignoring Travis failures (ticketed in https://github.com/mapbox/mapbox-gl-native/issues/2860#issuecomment-152365429), as build is successful and binaries are still published.

**Pull request merged**
