### PR TITLE
[iOS] Using contentInset for setCenterCoordinate: and flyToCamera met…

### PR DESCRIPTION
**Pull request by RomainQuidet**
Using contentInset for setCenterCoordinate: and flyToCamera methods everywhere.

### CODE REVIEW

**Comment by 1ec5** [comment]
If edgePaddingForFollowing doesn't include the content inset, it should.

**Comment by RomainQuidet** [comment]
@1ec5 What do you mean it should? I thought the logic behind edgePaddingForFollowing was for a former usage, I simply replaced it by the contentInset as everywhere else in the mapView class. It's working according to my basic tests. 
If I must use this method, what is the logic behind it? Thanks.

**Comment by 1ec5** [comment]
`-edgePaddingForFollowing` should be used here, but its implementation is incorrect. The method is meant to account for the fact that the user dot may be somewhere other than the center of the map (even after accounting for content insets). For example, if you set `userLocationVerticalAlignment` to `MGLAnnotationVerticalAlignmentTop` or `MGLAnnotationVerticalAlignmentBottom`, this method should return quite a large top inset. However, [this line](https://github.com/mapbox/mapbox-gl-native/blob/7b40cbcfd949371e04944a23ffe08b69862f6a1a/platform/ios/src/MGLMapView.mm#L3384) is incorrect: we should start out with `contentFrame`, not `bounds`. `bounds` should only be used to calculate the final return value, since edge padding is always based on the view’s non-inset bounds.

**Comment by RomainQuidet** [comment]
I agree that - (UIEdgeInsets)edgePaddingForFollowing implementation is wrong and a little bit strange for me. Nowhere it uses the userLocationVerticalAlignment...
I'll try to adapt if to return the correct insets.
Everywhere else the method _setCenterCoordinate is used, it simply pass the self.contentInset to the edgePadding parameter. (see https://github.com/mapbox/mapbox-gl-native/blob/7b40cbcfd949371e04944a23ffe08b69862f6a1a/platform/ios/src/MGLMapView.mm#L1763)

**Comment by RomainQuidet** [comment]
correct edgePaddingForFollowing, using contentInset and vertical alignment.

**Comment by boundsj** [comment]
> Everywhere else the method _setCenterCoordinate is used, it simply pass the self.contentInset to the edgePadding parameter.

I agree. It seems to me like the fix should actually be https://github.com/mapbox/mapbox-gl-native/pull/4067/commits/ccbdeaa451c7ec125e5b7b7af0f4eaa32ac8cce8, the original commit in this PR. 

This rect created in `userLocationAnnotationViewCenter` is based off of `contentFrame` and [already accounts for user location vertical alignment](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/ios/src/MGLMapView.mm#L4704-L4713) which is the concern @1ec5 brought up above. The paths `[MGLMapView glkView:drawInRect:]` -> `[MGLMapView updateUserLocationAnnotationView]` ->  `[MGLMapView updateUserLocationAnnotationViewAnimatedWithDuration:]` and also `[MGLMapView locationManager:didUpdateLocations:]`  -> `[MGLMapView locationManager:didUpdateLocations:animated:]` -> `[MGLMapView updateUserLocationAnnotationViewAnimatedWithDuration:]` all end up using `userLocationAnnotationViewCenter` to get the `userPoint` used to position the user dot view via its `center` property.

Therefore, I think that `[MGLMapView _setCenterCoordinate:edgePadding:zoomLevel:direction:duration:animationTimingFunction:completionHandler:]` should expect the edgePadding to be the `contentInset` for the case of updating for contentInset changes like it does for all other cases.

**Note: I'm using an orange, semi-transparent UIView to visualize the `contentFrame` that is created [here](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/ios/src/MGLMapView.mm#L4695).** I update the `contentInset` on a timer every 5 seconds. With only https://github.com/mapbox/mapbox-gl-native/pull/4067/commits/ccbdeaa451c7ec125e5b7b7af0f4eaa32ac8cce8 applied, adjusting the map's contentInset works like I would expect for the following cases:

### `MGLAnnotationVerticalAlignmentCenter`, contentInset oscillated between left=200 and left=0 on a loop:
contentinsetfix

### `MGLAnnotationVerticalAlignmentBottom`, contentInset oscillated between left=200 and left=0 on a loop:
contentinsetfixbottom

### `MGLAnnotationVerticalAlignmentTop`, contentInset oscillated between left=200 and left=0 on a loop:
contentinsetfixtop

If I use the implementation of `edgePaddingForFollowing` we have in the current release version or update the implementation of `edgePaddingForFollowing` as suggested in https://github.com/mapbox/mapbox-gl-native/pull/4067#issuecomment-187941664 the result is incorrect because the [implementation](https://github.com/mapbox/mapbox-gl-native/blob/7b40cbcfd949371e04944a23ffe08b69862f6a1a/platform/ios/src/MGLMapView.mm#L3384-L3388) of `edgePaddingForFollowing` results in `UIEdgeInsetsZero`. This causes the map to not move based on the `contentInset` input by the developer even though the user dot does move. This matches the [original issue report](https://github.com/mapbox/mapbox-gl-native/issues/3778):

> Then set the user tracking to follow. The map then "moves back" to its original position and only the user location is inset. 

contetinsetincorrect

In any case, there is no reason that I can see to use `edgePaddingForFollowing` since the user dot is moved as noted above and the map just needs the raw `contentInset` value. The final commit in this PR causes incorrect behavior when something other than `MGLAnnotationVerticalAlignmentCenter` is used.

I propose that we reduce this PR to just https://github.com/mapbox/mapbox-gl-native/pull/4067/commits/ccbdeaa451c7ec125e5b7b7af0f4eaa32ac8cce8 (the first commit) and merge it.

**Comment by 1ec5** [comment]
OK, I’m convinced. 😄 Thanks for the visual verification.

**Comment by boundsj** [comment]
Subsumed by https://github.com/mapbox/mapbox-gl-native/pull/6216

**Comment by 1ec5** [comment]
This caused a regression that reproduces when the user dot is top- or bottom-aligned: #6257.

**Pull request closed without merging**
