### PR TITLE
Integrate Metrics

### PR DESCRIPTION
**Pull request by bleege**
This branch builds out the capability for the Mapbox GL SDK to collect anonymous usage data from applications using the SDK. The data will be used to power developer analytics dashboards on Mapbox.com and make improvements to Mapbox tools. End-users or developers can disable data collection at any time.

### CODE REVIEW

**Comment by mikemorris** [comment]
> It's probably not reasonable to expect this to move to opt-in/out, but I feel that the privacy policy should be amended to be as explicit as possible about what information is sent over the air.

@friedbunny To answer your question from https://github.com/mapbox/mapbox-gl-native/issues/1033#issuecomment-84090971, we're planning on updating our privacy policy in conjunction with this work to accurately reflect what information is collected. Furthermore, we will be offering a way for both developers and end-users to opt-out of data sharing.

**Comment by friedbunny** [comment]
That's great to hear, good for you guys. I was mainly worried that this was a continuation of something I had missed with the older SDK, rather than a new thing still being fleshed out. :dizzy_face:

**Comment by friedbunny** [comment]
Oh, I should also apologize for jumping to the conclusion that Mapbox was going evil — you are all demonstrably and refreshingly unevil. I regret the mistake!

**Comment by bleege** [comment]
No worries @friedbunny.  I just got a little ahead of myself this morning when creating the tickets.  Sorry about all the confusion.

**Comment by bleege** [comment]
Everything has been merged, tested, and confirmed working.  As soon as Travis green lights the build we can merge this PR.

**Comment by bleege** [comment]
Just got a Green Bar from Travis -> https://travis-ci.org/mapbox/mapbox-gl-native/builds/55701082

Merging!

**Pull request merged**
