### PR TITLE
[android] Use hardware layer for compass fade

### PR DESCRIPTION
**Pull request by ljbade**
Set minimum API level to 14 (don't know why it 15)
Set test app version to 2.2.0

### CODE REVIEW

**Comment by mb12** [comment]
@ljbade The following code will crash on all devices below jelly bean if withLayer method is not available. 

'''
if (android.os.Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN) {
                                    mFadeAnimator.withLayer();
                                }
'''

**Comment by ljbade** [comment]
@mb12 That is what the `if` statement checks for. It wont run the function below jelly bean

**Comment by mb12** [comment]
It will still fail in ClassLoader. The best option would be to write a helloworld testcase with just these 3 lines and test on below jellybean emulator. There was a similar crash <a href="https://github.com/mapbox/mapbox-gl-native/blob/master/android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/MapView.java#L613">here</a> as well. To resolve it, I believe the minsdkversion was bumped up.

**Comment by ljbade** [comment]
I will switch in `ViewCompat` here.

**Comment by ljbade** [comment]
None of the Android API 14 or 15 emulators support OpenGL so I can't test for support properly.

I am going to try and get an old Galaxy Nexus off ebay to wipe and install fresh Android 4.0 on

**Pull request merged**
