### PR TITLE
[android] - remove obsolete filters

### LINKED ISSUE #7617: Remove Object[] based filter methods
The following filter methods appear to be type-unsafe (#7555) and duplicative of the functionality of other runtime styling API methods:

* `*Layer::setFilter(Object[] filter)`
* `*Layer::withFilter(Object[] filter)`

If so, we should remove them.

cc @tobrun @ivovandongen

### PR DESCRIPTION
**Pull request by tobrun**
Closes #7617

Review @ivovandongen

### CODE REVIEW

**Comment by tobrun** [comment]
It seems that our template ejs files were not updated to our checkstyle correctly. 
cc @cammace

**Comment by tobrun** [comment]
Blocked by https://github.com/mapbox/mapbox-gl-native/issues/7659

**Comment by cammace** [comment]
Checkstyle is failing since the indention of the files are now 4 instead of 2 in this PR. Checked master and I'm getting no checkstyle errors.

**Comment by tobrun** [comment]
@cammace all that code was generated. Not updating the template files will do that for you..

**Comment by tobrun** [comment]
@ivovandongen I rebased this PR on the latest master, care to do a review?

**Pull request merged**
