### PR TITLE
add support for RelWithDebInfo and MinSizeRel

### PR DESCRIPTION
**Pull request by tobrun**
Closes https://github.com/mapbox/mapbox-gl-native/issues/15556. 

This PR adds support for 2 more CMAKE_BUILD_TYPES:
 - RelWithDebInfo 
 - MinSizeRel

The configuration seems to be working correctly as this generates so files with different sizes:
  - Release 95mb
  - RelWithDebInfo 103mb
  - MinSizeRel 192mb

Todo:
  - [ ] create RelWithDebInfo as part of release workflow on CI
  - [ ] store .so file as build artefact
  - [ ] integrate slack bot to notify when a release finished building (makes it easier for looking up releases) 
  - [ ] update release documentation to also add .so file to git tag

### CODE REVIEW

**Comment by zugaldia** [comment]
What does `MinSizeRel` do / is used for, and how is it different from `RelWithDebInfo`?

**Comment by tobrun** [comment]
> What does MinSizeRel do / is used for, and how is it different from RelWithDebInfo?

RelWithDebInfo is the same as release except that it allows you to have symbol files for debugging
MinSizeRel is the same as release but with optimisation set to [minimize size maximum speed](https://docs.microsoft.com/en-us/cpp/build/reference/o1-o2-minimize-size-maximize-speed?redirectedfrom=MSDN&view=vs-2019).

**Comment by alexshalamov** [comment]
@tobrun what about `MaxPerfRel` :smile: ? I think @tmpsantos tried that and got a quite good performance increase, binary size increased a bit tho. Some customers might want to trade performance over binary size.

**Comment by tmpsantos** [comment]
`MaxPerfRel` == `-O3`

**Comment by tmpsantos** [comment]
To clarify, today we build with `-Os` IIRC, that implies `-O2` which is not so bad.

**Comment by julianrex** [comment]
Also, on iOS we have `-Oz`: https://github.com/mapbox/mapbox-gl-native/issues/14856 - not sure if that exists elsewhere.

**Comment by tmpsantos** [comment]
> Also, on iOS we have `-Oz`: #14856 - not sure if that exists elsewhere.

On the `next` Android bots + ARMv7 it is being built with `-Oz` too.

**Comment by tobrun** [comment]
We are migrating android project to https://github.com/mapbox/mapbox-gl-native-android, closing as we need to re implement it in that repo.

**Pull request closed without merging**
