### PR TITLE
[qt] add missing const

### PR DESCRIPTION
**Pull request by nunojpg**

### CODE REVIEW

**Comment by nunojpg** [comment]
Still current

**Comment by nunojpg** [comment]
Still current

**Comment by tmpsantos** [comment]
@nunojpg could you please rebase your branch? The `sanity-checks` bot was broken but I fixed it now.

**Comment by nunojpg** [comment]
There you go

**Comment by tmpsantos** [comment]
:robot: kicked!

**Comment by tmpsantos** [comment]
Clang format complaining about indentation. :(

**Comment by nunojpg** [comment]
I used your clang format for the touched lines only, but most of the file is not well formatted.

**Pull request closed without merging**
