### PR TITLE
boringssl

### PR DESCRIPTION
**Pull request by mikemorris**
Move to mason-installed `libcurl-7.38.0-boringssl` instead of relying on system `libcurl`

/cc @ljbade @springmeyer

### CODE REVIEW

**Comment by mikemorris** [comment]
For some reason this build is still erroring on my Ubuntu 14.04 VM:
```
* Loading install script 'https://github.com/mapbox/mason/blob/libcurl-7.38.0-boringssl/script.sh'...
######################################################################## 100.0%
* Downloading binary package linux-ubuntu-14.04-x86_64/libcurl/7.38.0-boringssl.tar.gz...
* Binary not available yet for linux-ubuntu-14.04-x86_64/libcurl/7.38.0-boringssl.tar.gz
* Downloading http://curl.haxx.se/download/curl-7.38.0.tar.gz...
######################################################################## 100.0%
/home/mikemorris/mapbox-gl-native/mason_packages/.scripts/libcurl-7.38.0-boringssl.sh: line 20: /home/mikemorris/mapbox-gl-native/openssl.patch: No such file or directory
make: *** [config.gypi] Error 1
```

Possibly some cached script isn't being cleaned properly?

**Comment by springmeyer** [comment]
A quick workaround would be to move the patching (https://github.com/mapbox/mason/blob/libcurl-7.38.0-boringssl/script.sh#L20) to the `mason_prepare_compile` or `mason_compile` step. So, if binaries are available then this failing step would not be run at all (and only fail for source compiles, /cc @ljbade ).

**Comment by ljbade** [comment]
oh yeah @springmeyer I need to implement you trick to download the file

**Comment by mikemorris** [comment]
The build gets a little further now, but still errors during the `libcurl` install, looks like just a bad `pushd`/`popd` or something though.
```
+ popd
~/mapbox-gl-native/mason_packages/.build/curl-7.38.0
+ cp -r 'gyp/*' /home/mikemorris/mapbox-gl-native/mason_packages/.build/curl-7.38.0/mason_packages/.build/boringssl
cp: cannot stat ‘gyp/*’: No such file or directory
make: *** [config.gypi] Error 1
mikemorris@ubuntu:~/mapbox-gl-native$
```

**Comment by mikemorris** [comment]
All fixed up by copying the `libcurl-7.38.0-boringssl` Ubuntu 12.04 binary over to Ubuntu 14.04 as well.

**Comment by mikemorris** [comment]
Looks like `libcurl-7.38.0-boringssl` is currently being built without `https` protocol support.
```
[WARNING] General: failed to load source TileJSON
[WARNING] Sprite: Failed to load sprite info: Error -1: Unsupported protocol
[WARNING] Sprite: Failed to load sprite image: Error -1: Unsupported protocol
```
```
mikemorris@ubuntu:~/mapbox-gl-native$ mason_packages/linux-ubuntu-14.04-x86_64/libcurl/7.38.0-boringssl/bin/curl -V
curl 7.38.0 (x86_64-unknown-linux-gnu) libcurl/7.38.0 zlib/1.2.8
Protocols: http
Features: IPv6 Largefile libz
```

**Comment by ljbade** [comment]
Ah libcurl `configure` script must be not detecting boringssl.

**Comment by mikemorris** [comment]
That sounds like a likely culprit @ljbade. Running `make linux run-linux` on OS X yields a linker error
```
  ./gyp-mac-tool flock ../Release/linker.lock c++ -lz /Users/mikemorris/Projects/mapbox-gl-native/mason_packages/osx-10.10/sqlite/3.8.6/lib/libsqlite3.a /Users/mikemorris/Projects/mapbox-gl-native/mason_packages/osx-10.10/glfw/e1ae9af5/lib/libglfw3.a -framework Cocoa -framework OpenGL -framework IOKit -framework CoreFoundation -framework CoreVideo /Users/mikemorris/Projects/mapbox-gl-native/mason_packages/osx-10.10/libcurl/7.38.0-boringssl/lib/libcurl.a -L/Users/mikemorris/Projects/mapbox-gl-native/mason_packages/osx-10.10/libcurl/7.38.0-boringssl/lib -lcurl -lssl -lcrypto -lz -lz /Users/mikemorris/Projects/mapbox-gl-native/build/libmbgl.a -lz -L/Users/mikemorris/Projects/mapbox-gl-native/mason_packages/osx-10.10/jpeg/v8d/lib -ljpeg -lpthread -ldl -framework CoreFoundation -framework CoreServices -L/Users/mikemorris/Projects/mapbox-gl-native/mason_packages/osx-10.10/libcurl/7.38.0-boringssl/lib -lcurl -lssl -lcrypto -lz -L/Users/mikemorris/Projects/mapbox-gl-native/mason_packages/osx-10.10/nunicode/1.5.1/lib -lnu -Wl,-dead_strip -mmacosx-version-min=10.9 -arch x86_64 -L../Release -stdlib=libc++  -o "../Release/mapbox-gl" ../Release/obj.target/linuxapp/linux/main.o ../Release/obj.target/linuxapp/platform/default/settings_json.o ../Release/obj.target/linuxapp/platform/default/glfw_view.o ../Release/obj.target/linuxapp/platform/default/log_stderr.o ../Release/libmbgl-linux.a ../Release/libmbgl-core.a /Users/mikemorris/Projects/mapbox-gl-native/mason_packages/osx-10.10/libpng/1.6.13/lib/libpng.a
Undefined symbols for architecture x86_64:
  "_BN_num_bytes", referenced from:
      _servercert in libcurl.a(libcurl_la-openssl.o)
  "_BIO_get_mem_ptr", referenced from:
      _servercert in libcurl.a(libcurl_la-openssl.o)
      _x509_name_oneline in libcurl.a(libcurl_la-openssl.o)
  "_OpenSSL_add_all_algorithms", referenced from:
      _Curl_ossl_init in libcurl.a(libcurl_la-openssl.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [../Release/mapbox-gl] Error 1
make: *** [linux] Error 2
```

**Comment by mikemorris** [comment]
So running this today `make run-linux` is working on OS X now, linking everything into `libmbgl.a` and passing `curl_ldflags` on to the next target...
```
/Users/mikemorris/Projects/mapbox-gl-native/mason_packages/osx-10.10/libcurl/7.38.0-boringssl/lib/libcurl.a -L/Users/mikemorris/Projects/mapbox-gl-native/mason_packages/osx-10.10/libcurl/7.38.0-boringssl/lib -lcurl -lssl -lcrypto -lz -lz
-L/Users/mikemorris/Projects/mapbox-gl-native/mason_packages/osx-10.10/libcurl/7.38.0-boringssl/lib -lcurl -lssl -lcrypto -lz
```

while `-lssl` seems to be missing on Linux still
```
/home/mikemorris/mapbox-gl-native/mason_packages/linux-ubuntu-14.04-x86_64/libcurl/7.38.0-boringssl/lib/libcurl.a -L/home/mikemorris/mapbox-gl-native/mason_packages/linux-ubuntu-14.04-x86_64/libcurl/7.38.0-boringssl/lib -lcurl -lz -lrt -ldl -lz
```

**Comment by mikemorris** [comment]
Okay, so it looks like `libcrypto.a` in `boringssl-d3bcf13` is a malformed archive.
```
configure:21328: PKG_CONFIG_LIBDIR will be set to "/home/mikemorris/mapbox-gl-native/.mason/mason_packages/.build/curl-7.38.0/mason_packages/linux-ubuntu-14.04-x86_64/boringssl/d3bcf13/lib/pkgconfig"
configure:21540: checking for CRYPTO_lock in -lcrypto
configure:21562: gcc -o conftest -O2 -Wno-system-headers  -I/home/mikemorris/mapbox-gl-native/.mason/mason_packages/.build/curl-7.38.0/mason_packages/linux-ubuntu-14.04-x86_64/boringssl/d3bcf13/include -I/home/mikemorris/mapbox-gl-native/.mason/mason_packages/.build/curl-7.38.0/mason_packages/linux-ubuntu-14.04-x86_64/boringssl/d3bcf13/include/openssl  -L/home/mikemorris/mapbox-gl-native/.mason/mason_packages/.build/curl-7.38.0/mason_packages/linux-ubuntu-14.04-x86_64/boringssl/d3bcf13/lib conftest.c -lcrypto  -lz -ldl  >&5
/home/mikemorris/mapbox-gl-native/.mason/mason_packages/.build/curl-7.38.0/mason_packages/linux-ubuntu-14.04-x86_64/boringssl/d3bcf13/lib/libcrypto.a: error adding symbols: Malformed archive
collect2: error: ld returned 1 exit status
```

**Comment by mikemorris** [comment]
Okay working on making `boringssl` build locally in `mason` in the [`boringssl-d3bcf13-local`](https://github.com/mapbox/mason/tree/boringssl-d3bcf13-local) branch, where did the `deps` and `gyp` folders in the `mason` branch originally come from though @ljbade? I'm not seeing any reference to them on https://boringssl.googlesource.com/boringssl/

**Comment by mikemorris** [comment]
Found the external deps, tracking this over at https://github.com/mapbox/mason/issues/50

**Comment by ljbade** [comment]
@ljbade Oh yeah I should have mentioned they were from Chromium.

**Comment by springmeyer** [comment]
branch is passing now (except from one job which timed out in tests and which I just restarted): https://travis-ci.org/mapbox/mapbox-gl-native/builds/47810383

**Comment by springmeyer** [comment]
@mikemorris all builds now passed (after restarting that one job), so back to you on this. My sense is that the next step is to decide how conditional use of boringssl should or should not work: Should we force all platforms to use it? If not then which gyp files set which flags might need some work.

**Comment by mikemorris** [comment]
@springmeyer I'm fine forcing all platforms to use it, although it's really only used with `make linux` currently. I previously attempted dropping `libcurl` from the OS X build, but this would've [broken `make linux` on OS X](https://github.com/mapbox/mapbox-gl-native/pull/755#issuecomment-70155591) with how the code is currently structured.

This may eventually be superceded by @kkaefer's work on asset request handling, pushing `libcurl` linking down from the library level to the actual executable (to enable alternative asset request implementations through Node.js for example), and at that point some refactoring may be in order to prevent unnecessarily building on OS X, but I think it would be fine to punt for now.

**Comment by ljbade** [comment]
@springmeyer Does it actually work? Ie does it load tiles?

**Comment by mikemorris** [comment]
@ljbade `make run-linux` is successfully compiling, linking and loading tiles now for me on OS X and my Ubuntu 14.04 VM

**Comment by ljbade** [comment]
omg I can't believe it works first time.

**Comment by mikemorris** [comment]
Ack, should fix https://github.com/mapbox/mason/issues/53 (building `boringssl` with `-fPIC`) before merging.

**Comment by mikemorris** [comment]
From @springmeyer:

> not viable: we cannot us a custom openssl or boringssl in a node C++ binding or in a library that is linked by a node C++ binding (like libmbgl). This is because any custom versions of openssl/boringssl would conflict with the openssl statically linked into available node binaries.

**Pull request closed without merging**
