### PR TITLE
[android] #3832 - improve unit testing geometry package

### LINKED ISSUE #3832: Improve unit testing of geometry package
Since #3830 it is possible to unit test the Android `Parceable` interface using mockito.
This allowed us to achieve 100% code coverage on the `LatLng` model class.
We should aim to bring same coverage to the others classes in the `geometry` package as well.

Current state:
 
screen shot 2016-02-05 at 10 24 22

### PR DESCRIPTION
**Pull request by tobrun**
closes #3832

### CODE REVIEW

**Comment by tobrun** [comment]
@zugaldia 
this PR contains the `MockParcel` class.
Would love some :eyes: on this since I might want to migrate this to a separate library at some point.

Currently I'm thinking about 2 ways how to expose this:
 - one is the way it's currently implemented:

   ```java
 +    @Test
 +    public void testParcelable() {
 +        LatLngSpan object = new LatLngSpan(1, 2);
 +        Parcel parcel = MockParcel.obtain(object);
 +        LatLngSpan parcelable = LatLngSpan.CREATOR.createFromParcel(parcel);
 +        assertEquals("parcel should match initial object", object, parcelable);
 +    }
   ````

 - other one is making it even more easy for end developers:

   ```java
 +    @Test
 +    public void testParcelable() {
 +        LatLngSpan object = new LatLngSpan(1, 2);
 +        LatLngSpan parcelable = MockParcel.mock(object);
 +        assertEquals("parcel should match initial object", object, parcelable);
 +    }
   ````

cc @bleege

**Comment by tobrun** [comment]
CI approved, going to rebase and merge

**Comment by tobrun** [comment]
Landed with https://github.com/mapbox/mapbox-gl-native/commit/9fc8cf39a8ee0704db70dd500d258cb2465c5a75

**Comment by zugaldia** [comment]
@tobrun any further thoughts on getting `MockParcel` as a separate component? This could come in handy to MAS eventually.

**Pull request closed without merging**
