### PR TITLE
Feature/logo attributions icon

### PR DESCRIPTION
**Pull request by tobrun**
As discussed in #2074 

Notes:
- I'm using Drawable tinting from support library using ColorStateList for attribution control. Currently their is a [bug](https://code.google.com/p/android/issues/detail?id=172067) in support library not showing the pressed state for Lollipop and higher. 

- Dialog for attribution control is not styled

### CODE REVIEW

**Comment by tobrunvannuland** [comment]
2 other notes:
- Mapbox logo for different screen densities
- Need to add location to url for improve maps attribution

**Comment by incanus** [comment]
This looks good so far in my cursory scan, but I'll defer to @bleege @ljbade on final judgement here :smile:

**Comment by ljbade** [comment]
@tobrunvannuland Can you save the various gravity/margin stuff into the instance state saving for `onCreate` and `onSaveInstanceState`

**Comment by tobrunvannuland** [comment]
@ljbade nicely spotted, 
I added the requested methods. 
Let me know if the commits may be squashed together

**Comment by ljbade** [comment]
@tobrunvannuland looks good!

**Comment by tobrun** [comment]
Thx, Will add the style for dialog and location to url this weekend

**Comment by bleege** [comment]
I'm not sure the state of this PR so if this is a known issue my apologies in advance.

I tried running this branch and got the following error at startup that immediately crashed the app.  I'm running this on at HTC One M9 that's at API 21 / Android 5.0.2.  It looks like an incompatible version of `Resources.getColorStateList()` is being used.  Specifically the [one used in the code](https://github.com/mapbox/mapbox-gl-native/blob/00945a5181f3445667885198f2da42e417505f1e/android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxgl/views/MapView.java#L366) is only available in [API 23 and above](http://developer.android.com/reference/android/content/res/Resources.html#getColorStateList%28int,%20android.content.res.Resources.Theme%29).  Although it appears that the [previous version of this method](http://developer.android.com/reference/android/content/res/Resources.html#getColorStateList%28int%29) is now deprecated in favor of the new version we'll have to use it as we need to support API 15+.  Maybe there's a ResourcesCompat that can be used instead?

```
-04 10:51:20.803    1958-1958/? E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.mapbox.mapboxgl.testapp, PID: 1958
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mapbox.mapboxgl.testapp/com.mapbox.mapboxgl.testapp.MainActivity}: android.view.InflateException: Binary XML file line #33: Error inflating class com.mapbox.mapboxgl.views.MapView
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2411)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2474)
            at android.app.ActivityThread.access$800(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1359)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:155)
            at android.app.ActivityThread.main(ActivityThread.java:5721)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1029)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)
     Caused by: android.view.InflateException: Binary XML file line #33: Error inflating class com.mapbox.mapboxgl.views.MapView
            at android.view.LayoutInflater.createView(LayoutInflater.java:633)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
            at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:257)
            at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:109)
            at com.mapbox.mapboxgl.testapp.MainActivity.onCreate(MainActivity.java:80)
            at android.app.Activity.performCreate(Activity.java:5961)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1129)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2364)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2474)
            at android.app.ActivityThread.access$800(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1359)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:155)
            at android.app.ActivityThread.main(ActivityThread.java:5721)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1029)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)
     Caused by: java.lang.reflect.InvocationTargetException
            at java.lang.reflect.Constructor.newInstance(Native Method)
            at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
            at android.view.LayoutInflater.createView(LayoutInflater.java:607)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
            at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:257)
            at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:109)
            at com.mapbox.mapboxgl.testapp.MainActivity.onCreate(MainActivity.java:80)
            at android.app.Activity.performCreate(Activity.java:5961)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1129)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2364)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2474)
            at android.app.ActivityThread.access$800(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1359)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:155)
            at android.app.ActivityThread.main(ActivityThread.java:5721)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1029)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)
     Caused by: java.lang.NoSuchMethodError: No virtual method getColorStateList(ILandroid/content/res/Resources$Theme;)Landroid/content/res/ColorStateList; in class Landroid/content/res/Resources; or its super classes (declaration of 'android.content.res.Resources' appears in /system/framework/framework.jar)
            at com.mapbox.mapboxgl.views.MapView.initialize(MapView.java:366)
            at com.mapbox.mapboxgl.views.MapView.<init>(MapView.java:252)
            at java.lang.reflect.Constructor.newInstance(Native Method)
            at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
            at android.view.LayoutInflater.createView(LayoutInflater.java:607)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
            at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:257)
            at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:109)
            at com.mapbox.mapboxgl.testapp.MainActivity.onCreate(MainActivity.java:80)
            at android.app.Activity.performCreate(Activity.java:5961)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1129)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2364)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2474)
            at android.app.ActivityThread.access$800(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1359)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:155)
            at android.app.ActivityThread.main(ActivityThread.java:5721)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1029)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)
09-04 10:51:20.803    1055-8042/? E/ActivityManager﹕ App crashed! Process: com.mapbox.mapboxgl.testapp
```

**Comment by ljbade** [comment]
@bleege there is no `ResourcesCompat` method for this. I would say we just use the deprecated function.

**Comment by tobrun** [comment]
@bleege thanks for the feedback and testing out the PR.  

I find it a bit odd, Lint did not show any min.Sdk warning.. Will verify this, and if true will open an ticket at google's issue tracker. 

I will be migrating away from ColorStateList. Besides that it is [broken](https://code.google.com/p/android/issues/detail?id=172067) it is also not completely backward compatible without doing it ourselves. I will add the same 'fixed-color' blue icon as on iOS. 

The whole setup behind current ColorStateList setup was that the attribution control would be automatically tinted in colors from the users theme. They would be able to apply an own theme tag in xml if they wanted to override the colors from their own theme. I will be on the lookout if something changes in this space. 

Personal reminder: do regression test on older platforms before submitting a PR.
Thanks again for looking at PR, glad this was spotted before merging!

**Comment by tobrun** [comment]
@ljbade @bleege 

- added dynamic url for improve this map

- styled appcompat AlertDialog

- added a drawable selector instead of a ColorStateList
  - will wait for google to release [vector support](https://youtu.be/ssayKH0tudk?t=27m18s) in android studio v1.4. By then there will be a clear strategy from them how to handle tinted selectors.

**Comment by ljbade** [comment]
@tobrun Looks good so far, few things to finish:
- in TestApp move info button over a bit so not behind the location FAB (good test of our position customization hooks)
- use `WebView` for links

**Comment by ljbade** [comment]
@tobrun One more thing I picked up trying to implement the attribution offset for the FAB, there is no set of getter functions for the added margin and gravity settings.

**Comment by ljbade** [comment]
This is what I have managed so far in the TestApp:

image

This was using this code snippet in the `MainActivity.onCreate()`:
```
// Move attribution button to left of FAB
        mLocationFAB.getViewTreeObserver().addOnGlobalLayoutListener(new ViewTreeObserver.OnGlobalLayoutListener() {
            @Override
            public void onGlobalLayout() {
                float screenDensity = getResources().getDisplayMetrics().density;
                int sixteenDp = (int)(16 * screenDensity);
                mMapView.setAttributionMargins(sixteenDp, sixteenDp, mLocationFAB.getWidth() + 2 * sixteenDp, sixteenDp);
            }
        });
```

Is that the best place to put the icon?

**Comment by tobrun** [comment]
I'm not convinced, it is a bit confusing for the enduser to have 2 clickable items side by side. But not having the same look/size. 

I see following possibilities:
 - putting it in top left corner for the sample app (sdk default right bottom)
 - remove the icon and placing the functionality on Mapbox logo instead

**Comment by bleege** [comment]
> I'm not convinced, it is a bit confusing for the enduser to have 2 clickable items side by side.

I completely agree.  FABs are likely going to a regular thing in Android map apps so I think it's best to steer clear of the lower right side for anything.

I'm thinking the best place for the Info icon (btw, let's use [this one](https://www.google.com/design/icons/#ic_info_outline) from Google's Material Design toolbox) would be to the right (or left?) of the Mapbox word mark in the lower left hand corner.  It's not ideal, but content wise it makes more sense there and it'll be out of the way for the majority of app developers.

**Comment by tobrun** [comment]
@bleege I will try out both suggestions and post screenshots. 
And actually that is that icon, only coloured with Mapbox blue.. 
This was only a temp solution for the first milestone. 
SVG support will soon be available in gradle 1.4 

@ljbade will implement the webview asap and resolve conflicts with master.
btw the javascript vulnerability for webview pre jelly bean is not a problem?

**Comment by bleege** [comment]
@tobrun Sounds great!

BTW, just to be clear we keep talking about WebView but I want to make sure that what I'm actually referring to is firing an "open in Web browser" INTENT and NOT integrating an actual WebView into the SDK.  In other words:

```java
// Open In User's preferred Web browser
String url = "http://www.openstreetmap.org"
Intent intent = new Intent(Intent.ACTION_VIEW, Uri.parse(url)));
startActivity(intent);
```

**Comment by incanus** [comment]
What about how Google Maps does it? With the logo at center? 

Tablet: 

screenshot_2015-09-08-10-46-01

Updating my phone to see what the latest there is.

**Comment by bleege** [comment]
I think it's only middle on tablets, because on phones it's back on the left side.  Though Google often hides / removes it when other content needs that space.

screenshot_2015-09-08-13-06-51

**Comment by incanus** [comment]
> I'm thinking the best place for the Info icon (btw, let's use this one from Google's Material Design toolbox) would be to the right (or left?) of the Mapbox word mark in the lower left hand corner.

This seems the best approach to me. I vote for 'after', e.g. `Mapbox (ℹ︎)`.

**Comment by tobrun** [comment]
> "open in Web browser" INTENT

This is already in place, including the improve this map with parsed LatLng and zoomlevel 

> 'after', e.g. Mapbox (ℹ︎).

Seems most logical, will add this and squash it into commit

**Comment by bleege** [comment]
>>  'after', e.g. Mapbox (ℹ︎).

>Seems most logical, will add this and squash it into 1 commit

Excellent!  Super excited to get this in.  :+1:

**Comment by tobrun** [comment]
device-2015-09-09-184120
device-2015-09-09-184135

**Comment by incanus** [comment]
Checking this out now. This is looking good @tobrun! One thing I'd change is that the `attributionsDialogTitle` should be `Mapbox Android SDK`.

**Comment by tobrun** [comment]
@incanus thx for heads up, will adjust and sqaush.

**Comment by incanus** [comment]
Rebased this over in https://github.com/mapbox/mapbox-gl-native/pull/2292. @tobrun, you could do this here as well, or I can just grab over there is this is otherwise done (which it looks like to me).

**Comment by incanus** [comment]
We typically do: 

1. `git rebase master`
1. `git push -f`
1. Then, to merge: `git checkout master; git merge --ff-only <branch>`

**Comment by incanus** [comment]
Grabbed in https://github.com/mapbox/mapbox-gl-native/pull/2292.

**Comment by tobrun** [comment]
@incanus Thanks for resolving this. Rebasing is something I haven't used in corporate environments. Will use it more from now on! awesome feature of git

**Comment by incanus** [comment]
@tobrun We've been experimenting with it in gl-native as a way to: 

1. Avoid specific merge commits in `master` and just bring their component commits.
1. Land commits in `master` by the order they were applied, not written.

**Comment by bleege** [comment]
Great job @tobrun!  Thanks for getting everything properly pulled in @incanus!  :+1:

**Comment by tobrun** [comment]
>Avoid specific merge commits in master and just bring their component commits.
Land commits in master by the order they were applied, not written.

Noted!

**Pull request closed without merging**
