### PR TITLE
Introduce MapboxMap

### LINKED ISSUE #3145: Integrate MapboxMap class
Copies GoogleMap implementation as indicated by @bleege in https://github.com/mapbox/mapbox-gl-native/issues/2616#issuecomment-160478281.
This will boil down to applying composition/delegation to our current MapView class.
This is the first step towards making the project more modular and testable.

### PR DESCRIPTION
**Pull request by bleege**
Closes #3145 

/cc @zugaldia

### CODE REVIEW

**Comment by tobrun** [comment]
I wouldn't merge it yet, there are still some rough edges

**Comment by bleege** [comment]
> I wouldn't merge it yet, there are still some rough edges 

Yep, no plans to do that just yet.  Creating the PR make it easier to see comments on the commit(s) and work through the rough edges.

**Comment by tobrun** [comment]
Going to take some part of this branch integrate it in a clean one with discussions points mentioned in  #3145

**Comment by tobrun** [comment]
Closing in favour of #3500

**Pull request closed without merging**
