### PR TITLE
[ios] Added 2 new mid alignment position in MGLAnnotationVerticalAlignment

### PR DESCRIPTION
**Pull request by iDevid**
Added MidBottom and MidTop MGLAnnotationVerticalAlignment.

### CODE REVIEW

**Comment by iDevid** [comment]
@anandthakker

**Comment by 1ec5** [comment]
Hi @iDevid, can you describe your use case, so that we can better understand what you’re trying to accomplish?

**Comment by iDevid** [comment]
I wanted to align the user annotation in the middle between the center of the frame and the bottom/top. 
schermata 2018-03-05 alle 23 14 11
schermata 2018-03-05 alle 23 14 40

**Comment by iDevid** [comment]
@1ec5

**Comment by 1ec5** [comment]
Have you considered changing the map view’s `contentInsets` property instead?

**Comment by iDevid** [comment]
@1ec5 of course, but when following the user, sometimes the map glitches and the insets goes back to  default (I think because there is verticalAlignment center by default)

**Comment by iDevid** [comment]
As seen in the video, while following the user with contentInset, it will get restored to .center
[ScreenRecording_03-13-2018 17-38-12.MP4.zip](https://github.com/mapbox/mapbox-gl-native/files/1807837/ScreenRecording_03-13-2018.17-38-12.MP4.zip)

**Comment by iDevid** [comment]
UP

**Comment by 1ec5** [comment]
I don’t think we’re going to want to add these halfway alignment values. The user puck is supposed to respect the map view’s content inset. Following #7716, it should respect the containing view controller’s layout guides, and following #12147, it’ll also respect the safe area.

If there are bugs in how the map view interacts with content insets, layout guides, or the safe area, I suspect #6566 has something to do with it. Please open a new issue about it with a reproducible test case.

Ultimately, it was a mistake to expose something as simplistic as `MGLAnnotationVerticalAlignment`. #12203 would supplant this enumeration with a delegate method, which you could use to decide exactly where on screen you want the user puck (and the camera’s focal point) to appear.

**Pull request closed without merging**
