### PR TITLE
line-progress expression + line-gradient example

### PR DESCRIPTION
**Pull request by tobrun**
Refs https://github.com/mapbox/mapbox-gl-native/pull/12575

This PR adds an example integration of `line-gradient` property added in #12575 and adds expression for the `line-progress` expression from the style spec [here](https://www.mapbox.com/mapbox-gl-js/style-spec/#expressions-line-progress).

Currently the example isn't rendering as expected, to be fixed before merging:

Todo:
 - [x] fix above rendering
 - [ ] add example to expression javadoc

@pozdnyakov are you seeing this correctly being rendered on other platforms?

### CODE REVIEW

**Comment by pozdnyakov** [comment]
@tobrun thanks for pointing this out! I'll investigate what's happening there

**Comment by tobrun** [comment]
Capturing from @pozdnyakov that we are missing integration for lineMetrics (see render test example [here](https://github.com/mapbox/mapbox-gl-js/blob/master/test/integration/render-tests/line-gradient/gradient/style.json#L54). We will need to expose this as a GeoJsonOptions configuration.

**Comment by pozdnyakov** [comment]
The latest patch at https://github.com/mapbox/mapbox-gl-native/pull/12575 fixes the issue. Thanks.

**Comment by pozdnyakov** [comment]
screenshot_20180820-194557

**Comment by tobrun** [comment]
@pozdnyakov this PR targets merging into your branch so we can merge everything together. 
I will merge after CI approves.

**Pull request merged**
