### PR TITLE
added custom popup view

### PR DESCRIPTION
**Pull request by erf**
Made a custom popup view as disscussed in #894

### CODE REVIEW

**Comment by tmcw** [comment]
@bleege can you review this PR?

**Comment by bleege** [comment]
@erf Thanks for the PR.  I've been sidetracked the last few days, but hope to get to this soon!

**Comment by erf** [comment]
No problem. Btw. This is just a suggestion as a starting point and is not ready for prime time.

**Comment by bleege** [comment]
@erf Cool!  BTW, this actually is one of the next things on the TODO list once things settle.  I'm really looking forward to getting this feature added!

**Comment by erf** [comment]
Great! I added a minor commit that makes the popup update better. This however requires API lvl 11. What API level are you aiming for?

**Comment by erf** [comment]
Also elevation would also make the popup stand out more and create contrast. This however requires API level 22, you could also just add a border somehow

**Comment by bleege** [comment]
> What API level are you aiming for?

The SDK will support API 15 (Ice Cream Sandwich) and above.

**Comment by bleege** [comment]
@erf I took an initial stab at integrating the PR with the latest from `master`.  Is this what you're seeing?

screen shot 2015-08-26 at 8 10 55 am

**Comment by erf** [comment]
Yes should be about right. Just put some dummy items in there. Maybe you should consider putting the content in a PopupWindow. For it to fit to screen when outside and such. But maybe it's better to create something from scratch..

**Comment by bleege** [comment]
Thanks @erf!  We decided to port InfoWindow API from Mapbox Raster SDK in #894.

**Comment by erf** [comment]
:+1:

**Pull request closed without merging**
