### PR TITLE
[build] Remove mkdirp from node deps

### PR DESCRIPTION
**Pull request by brunoabinader**
Simple replacement for `mkdirp`, reducing the amount of npm development dependencies.

### CODE REVIEW

**Comment by mourner** [comment]
It's a really tiny dependency and it's battle-tested across many mapbox repos. Should we really replace it with a custom script? That increases maintenance overhead.

**Comment by tmpsantos** [comment]
This is a good thing I think. It removes the dependency on NPM and makes "offline building" easier, specially for embedded devices.

Rationale is on Linux embedded distributions like Yocto you can have nodejs pre-installed via apt-get, but not `mkdirp`.

**Comment by jfirebaugh** [comment]
I'm aiming to eliminate the need for a mkdirp operation entirely in #7942 and a followup PR for build-version.js.

**Comment by brunoabinader** [comment]
Deferring in favor of #7942.

**Pull request closed without merging**
