### PR TITLE
[android] - ensure access token is set when trying to load a style

### LINKED ISSUE #6242: mapView setStyleUrl method not loading in style
`mapView.setStyleUrl(Style.SATELLITE);` isn't rendering the style, just getting a 401 error:

```
loading style failed: HTTP status code 401
```

Example of this can be found in the `ManualZoomActivity` found in the [testapp](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/camera/ManualZoomActivity.java#L41). Setting the map style using mapboxMap or through XML still works as expected.

cc: @mapbox/android

### PR DESCRIPTION
**Pull request by tobrun**
closes #6242

### CODE REVIEW

**Comment by tobrun** [comment]
Review @zugaldia?

**Comment by zugaldia** [comment]
@tobrun This only a stopgap then, meaning, this doesn't close the issue, right?

**Comment by tobrun** [comment]
correct, I'm feel we can fix everything related to this with https://github.com/mapbox/mapbox-gl-native/issues/5621.

**Comment by zugaldia** [comment]
@tobrun 👍

**Pull request merged**
