### PR TITLE
[android] - add print example

### PR DESCRIPTION
**Pull request by tobrun**
Add print example to the test app. 

```java
    @Override
    public void onSnapshotReady(Bitmap snapshot) {
        PrintHelper photoPrinter = new PrintHelper(this);
        photoPrinter.setScaleMode(PrintHelper.SCALE_MODE_FIT);
        photoPrinter.printBitmap("map.jpg - mapbox print job", snapshot);
    }
```

Example:

ezgif com-video-to-gif 56

### CODE REVIEW

**Comment by zugaldia** [comment]
@tobrun Love it.

**Comment by bleege** [comment]
Very useful!  Does this only work with TextureView though?

**Comment by tobrun** [comment]
@bleege see https://github.com/mapbox/mapbox-gl-native/pull/5826

**Comment by tobrun** [comment]
CI approved, going to rebase and merge

**Pull request merged**
