### PR TITLE
[ios] Cherry-pick #13427 - Expose "local ideograph font family" in map snapshotters

### PR DESCRIPTION
**Pull request by jmkiley**
This PR cherry-picks #13427 into the iOS 8 branch.

cc @lloydsheng @chriswu42

### CODE REVIEW

**Comment by jmkiley** [comment]
@ChrisLoer Yeah, it looks like a higher version of cmake is required than is in the branch. I'm not sure if there is something I can bring into the branch so that they can pass.

**Comment by ChrisLoer** [comment]
@kkaefer Do you have any pointers for getting the linux builds running on the ios8 branch again? It also seems somewhat reasonable to just ignore or disable these builds, since this branch is only used for iOS (although the sanitize builds are meant to catch errors that could show up on any platform).

**Comment by kkaefer** [comment]
https://github.com/mapbox/mapbox-gl-native/commit/918e57178c579da1e0a4f580d56684978610681f should fix this build

**Comment by jmkiley** [comment]
Thanks @kkaefer!

**Pull request merged**
