### PR TITLE
Do not include CJK ideographs in the offline packs by default

### PR DESCRIPTION
**Pull request by LukasPaczos**
Closes https://github.com/mapbox/mapbox-gl-native/issues/14201.

/cc @ChrisLoer :)

### CODE REVIEW

**Comment by LukasPaczos** [comment]
Currently blocked by https://github.com/mapbox/mapbox-gl-native/issues/14271.

**Comment by LukasPaczos** [comment]
This is ready for a review.

/cc @Chaoba @chloekraw

**Comment by Chaoba** [comment]
Both of these two classes not add `includeIdeographs` in `writeToParcel` method, can you add it? 
BTW, why does  `OfflineRegionDefinition` need extends `Parcelable`?

**Comment by LukasPaczos** [comment]
@Chaoba I believe it's required for the offline plugin.

**Comment by Chaoba** [comment]
LGTM

**Pull request merged**
