### PR TITLE
[android] - Update to Android Studio 2.2.2 with tools/dependencies

### PR DESCRIPTION
**Pull request by tobrun**
Android Studio 2.2 has been officially released in the stable channel:
This as a trigger to update other dependencies/tools in the project as upgrading the target SDK version to Nougat (officially released a month a go and now running on multiple devices in the wild). This change results in updating the support lib versions and android gradle tools version. Also updated the test app version number to reflect the 4.2.0 release.

@mapbox/android any objections?

### CODE REVIEW

**Comment by zugaldia** [comment]
> upgrading the target SDK version to Nougat 

Let's not merge this before we decide on https://github.com/mapbox/mapbox-gl-native/issues/6197.

**Comment by tobrun** [comment]
We have now a release branch for v.4.2.0, I rebased and fixed the merge conflicts. 
@ivovandongen want to review?

**Comment by tobrun** [comment]
I have done another round of updating and increased to the recent release of 7.1.0 and the related build tools and dependencies `25.0.0`.

**Comment by tobrun** [comment]
Master is now using the latest tools and targeting Nougat as target SDK.

cc @mapbox/android

**Pull request merged**
