### PR TITLE
[android] - add realtime geojson example from gl-js

### PR DESCRIPTION
**Pull request by tobrun**
Adds same example as GL-JS [here](https://www.mapbox.com/mapbox-gl-js/example/live-geojson/). 

device-2016-10-19-134427

Review @ivovandongen

### CODE REVIEW

**Comment by tobrun** [comment]
Note the update doesn't work, same issue as https://github.com/mapbox/mapbox-gl-native/issues/6744.

**Comment by zugaldia** [comment]
Is this example the equivalent of [`SpaceStationLocationActivity`](https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/labs/SpaceStationLocationActivity.java) but using Runtime Style API?

cc: @cammace

**Comment by tobrun** [comment]
> Is this example the equivalent of SpaceStationLocationActivity but using Runtime Style API?

Yes, the only difference is that this PR doesn't animate, only updates the source each 2 seconds.

**Comment by tobrun** [comment]
Going to rebase on merge from #6759, also forgot to include testing configuration.

**Comment by ivovandongen** [comment]
@tobrun https://github.com/mapbox/mapbox-gl-native/pull/6770 Should fix your issue. Will merge after review asap.

**Pull request merged**
