### PR TITLE
[ios] remove ios-sim

### PR DESCRIPTION
**Pull request by frederoni**
Cherry picked https://github.com/mapbox/mapbox-gl-native/pull/10070 (https://github.com/mapbox/mapbox-gl-native/pull/10070/commits/564136d55d5e90f4e9553ae553c04e796ee29824)

@fabian-guerra @friedbunny 👀

### CODE REVIEW

**Comment by boundsj** [comment]
Since we expect v3.7.0 to be our next iOS release off of master and this did not make the [latest merge of the release branch to master](https://github.com/mapbox/mapbox-gl-native/pull/10071) should we go ahead and close it?

cc @fabian-guerra

**Comment by fabian-guerra** [comment]
If this is already in master I think we can close this branch.

**Comment by friedbunny** [comment]
I was under the impression it was blocking progress on the Android release, but if that happened then we’re 👌.

**Comment by boundsj** [comment]
Yeah I think we temporarily disabled iOS required status checks for Android to expedite the process. Thanks @frederoni for doing this anyway!

**Comment by frederoni** [comment]
> @tobrun: Thank you, @frederoni, for running with https://github.com/mapbox/mapbox-gl-native/pull/10070, the iOS build is now made required again.

**Pull request closed without merging**
