### PR TITLE
Ensure worker tasks are complete before destroying TileData

### PR DESCRIPTION
**Pull request by jfirebaugh**
This is the sure-fire fix for #1309. Should have gone this route earlier.

### CODE REVIEW

**Comment by incanus** [comment]
`README` is going to need updated for C++14 req.

**Comment by springmeyer** [comment]
You mentioned at https://github.com/mapbox/mapbox-gl-native/issues/1403#issue-72661577 that only clang-3.4 is required. I see you bumped to clang-3.6 - is that needed specifically or did you just bump to the latest clang available for good practice? The reason I ask is that I've been noticing crashes which look like some kind of ABI incompatiblity when c++ binaries built with clang-3.5 are linked and run against other c++ binaries built with clang-3.6 https://github.com/mapnik/mapnik/issues/2785. I've not had a chance to investigate much but until I do I've been sticking with clang-3.5.

**Comment by jfirebaugh** [comment]
@incanus README update is included.

@springmeyer [Previously](https://github.com/mapbox/mapbox-gl-native/pull/1250#issuecomment-91736051) I encountered a conflict between gcc 4.9 and clang 3.4/3.5. But the Travis infrastructure has changed in the meantime and this may no longer be an issue. I'll try reverting back to 3.4.

**Comment by jfirebaugh** [comment]
clang-3.4 does not seem to support `-std=c++14`. I'll try 3.5.

**Comment by incanus** [comment]
@jfirebaugh Would this be accurate to change as well in the `README`? 

> An OpenGL renderer for [Mapbox Vector Tiles](https://www.mapbox.com/blog/vector-tiles),
implemented in C++14, currently targeting iOS, OS X, Android, and Ubuntu Linux.

**Comment by jfirebaugh** [comment]
Yes, I'll do that.

**Pull request merged**
