### PR TITLE
fixes #2350: remove iOS-specific SQLite cache wrapper

### LINKED ISSUE #2350: Replace MGLFileCache with SharedSQLiteCache
After #2345 we can replace the iOS specific `MGLFileCache` with the new C++ `SharedSQLiteCache`.

/cc @incanus

### PR DESCRIPTION
**Pull request by incanus**
Still needs some testing, but this is the route I'm likely to take, following the lead in https://github.com/mapbox/mapbox-gl-native/commit/529a7cc93c7819c62d81bd825e8682cf3f93b495.

### CODE REVIEW

**Comment by ljbade** [comment]
Code looks good to me. (with the caveat I am ObjC illiterate)

**Comment by incanus** [comment]
Digging back into this and never seeing the `SharedSQLiteSource` getting destroyed. Double-checking my work.

**Comment by incanus** [comment]
False alarm — my view controller was over-retaining my last map view. All is clear here and the shared `SQLiteCache` smart pointer gets destroyed when the last map view is gone, and is only ever reacquired while 2+ map views live. 

Working on getting tests to pass again, then will merge. This will stay just in `master`; merely a refactor.

**Comment by incanus** [comment]
Tests are blocked by the same thing that's going on over in https://github.com/mapbox/mapbox-gl-native/pull/2391#issuecomment-142706082 with Travis and Clang. Will revisit.

**Comment by incanus** [comment]
As this only affects iOS code and tests pass there, I'm going to merge. 

```
$ git d master..head | grep ^diff
diff --git a/gyp/platform-ios.gypi b/gyp/platform-ios.gypi
diff --git a/platform/ios/MGLFileCache.h b/platform/ios/MGLFileCache.h
diff --git a/platform/ios/MGLFileCache.mm b/platform/ios/MGLFileCache.mm
diff --git a/platform/ios/MGLMapView.mm b/platform/ios/MGLMapView.mm
```

**Pull request merged**
