### PR TITLE
[android] #2273 - Adjust InfoWindow triangle for edge of screen annotations

### LINKED ISSUE #2273: Adjust InfoWindow triangle for edge of screen annotations
If an annotation is near the edge of the screen so the InfoWindow gets pushed over to stay on the screen the triangle no longer aligns with the marker:
image

Somehow the triangle should be moved to stay in line with the marker.

### PR DESCRIPTION
**Pull request by tobrun**
closes #2273

### CODE REVIEW

**Comment by bleege** [comment]
One of the Travis build variants (Linux) didn't work.  Restarting it to see if it'll take and then we can merge.

**Comment by bleege** [comment]
This looks like an issue with Node.  I've asked @jfirebaugh @mikemorris to :eyes: at it.  Will hold off on merging until they :+1:.

https://travis-ci.org/mapbox/mapbox-gl-native/jobs/85113789

screen shot 2015-10-13 at 11 12 08 am

**Comment by bleege** [comment]
@jfirebaugh pointed out that this is a [known issue with Node right now](https://github.com/mapbox/mapbox-gl-native/issues/2597).

**Comment by bleege** [comment]
I just tried running the code locally on HTC M9 and saw that while the triangle was moving properly back and forth per pin location on screen, there's a consistent big gap between the top of the Marker and bottom of the InfoWindow Triangle.  This occurred both in the `MainActivity` and `PressForMarkerActivity`.  I also couldn't get the `InfoWindowActivity` to load... it just showed a black screen but didn't crash.  Below are some screenshots:

device-2015-10-13-115810
_MainActivity Centered_

device-2015-10-13-115836
_MainActivity Left_

device-2015-10-13-115908
_MainActivity Right_

device-2015-10-13-120056
_PressForMarkerActivity_

**Comment by ljbade** [comment]
Hmm could be related to https://github.com/mapbox/mapbox-gl-native/issues/2599

**Comment by tobrun** [comment]
@bleege after reverting master, I'm not seeing these issues anymore:
device-2015-10-14-102653

device-2015-10-14-102740


Waiting for travis to complete before merging

**Comment by tobrun** [comment]
Travis approved

**Pull request merged**
