### PR TITLE
[core] Fix Integer overflow when converting tileCoordinates to LatLon

### PR DESCRIPTION
**Pull request by zmiao**
Fix an issue that potential integer overflow would happen with high zoom level.

### CODE REVIEW

**Comment by chloekraw** [comment]
@zmiao in addition to `queryRenderedFeatures` returning incorrect results at high zoom levels, what other operations were negatively affected by this bug?

**Comment by zmiao** [comment]
@chloekraw  it will also affect `querySourceFeatures`.

**Comment by chloekraw** [comment]
Thanks @zmiao. Thank you for remembering to provide a changelog entry! It’s much appreciated. Your changelog entry is accurate and concise, two things that are hard to get right about changelog entries. Great job.

Our changelog entries should target someone like me as the audience. A product manager / CEO should be able to understand what the bug that’s fixed is and what the new features added do. Why? So that they will want to upgrade to the release! And if someone like me understands the changelog, then certainly developers who use the mobile SDK will as well, so we’d know we’re serving our main audience well. 

The reality is this is very hard to do well, and I understand that. Many of our changelog entries could use improvement from this perspective. Forgive me for picking on your changelog entry as a demonstration, but I’m taking this opportunity to clarify what changelog entries should be because I happen to know how this bug manifests.

> Fixed an issue of integer overflow when converting `tileCoordinates` to `LatLon`.

This doesn’t mean much to me, and I’d wager it wouldn’t mean much to most casual users of our mobile SDKs either, as we don’t know when converting `tileCoordinates` to `LatLon` happens. To show our audience what the impact of fixing this bug is, you could write:

> Fixed a bug that caused `queryRenderedFeatures` and `querySourceFeatures` to return incorrect coordinates at zoom levels 20 and higher. 

Developers know if they are using `queryRenderedFeatures` or `querySourceFeatures` and need to upgrade to this release. So this would be a good changelog entry.

Let’s say this integer overflow bug causes many different bugs and you’re not sure if you know of all of them. You could then keep what you wrote but include an example to put the problem in context for the developer. For example: 

> Fixed an integer overflow bug that caused issues such as  `queryRenderedFeatures` and `querySourceFeatures` returning incorrect coordinates at zoom levels 20 and higher. 

I hope this is clear and that it helps elucidate what we’re looking for from changelogs! Thanks as always for your fantastic contributions. I’m really happy to have you on the team.

cc @mapbox/gl-native @mapbox/maps-android @mapbox/maps-ios

**Comment by zmiao** [comment]
@chloekraw Thanks a lot for bringing this up! It is quite a helpful and clear guidance that how I could write changelogs in the future.

**Pull request merged**
