### PR TITLE
[ios] Ignore Smart Invert

### PR DESCRIPTION
**Pull request by jmkiley**
I set `accessibilityIgnoresInvertColors` for the views so that they can be overridden as needed.

Addresses https://github.com/mapbox/mapbox-gl-native/issues/9859

cc @friedbunny

### CODE REVIEW

**Comment by fabian-guerra** [comment]
@friedbunny do we need to update the xcode build version in bitrise? the test is failing with ` unrecognized platform name iOS`

**Comment by friedbunny** [comment]
> do we need to update the xcode build version in bitrise? the test is failing with ` unrecognized platform name iOS`

This error is because `@available()` is new to Objective-C in Xcode 9 — we can’t use it yet. 😞 

There have been many, many ways to check system availability ([good overview here]()) and I think that iOS 8’s [`-[NSProcessInfo isOperatingSystemAtLeastVersion:version:]`](https://developer.apple.com/documentation/foundation/nsprocessinfo/1414876-isoperatingsystematleastversion?language=objc) is the best way to go, given our requirements. We recently used this in [#9869](https://github.com/mapbox/mapbox-gl-native/pull/9869/files#diff-20502b6bc02986a4398d0da84b2d4b94R4165).

**Comment by friedbunny** [comment]
Errrm, scratch my version availability suggestion — because this PR relies on a property that doesn’t exist until iOS 11, we’ll have to check if that property is available using something like `respondsToSelector:`.

This is complicated by the fact that we don’t compile with Xcode 9 or support iOS 11 yet, so our base SDK does not have this property/methods yet.

**Comment by jmkiley** [comment]
Updated it to use `respondsToSelector:` rather than `@available`.

**Pull request merged**
