### PR TITLE
[android] Disable compass sensor.

### LINKED ISSUE #2577: Memory churn when location tracking is enabled
Memory usage when app is idle and location tracking is disabled:
screen shot 2015-10-09 at 12 35 27

Memory usage when app is idle and location tracking is enabled:
screen shot 2015-10-09 at 12 32 52

### PR DESCRIPTION
**Pull request by ljbade**
Fix location marker position.
Fixes #2577

### CODE REVIEW

**Comment by ljbade** [comment]
This is an alternative to #2049 in case that PR is not ready in time for v2.1.0 release. It fixes known bugs in the current user location implementation.

If #2049 lands before v2.1.0 release, then this PR can be deleted. Otherwise this PR should be merged into the release branch ready for the final v2.1.0 SNAPSHOT.

/cc @bleege @tobrun

**Comment by tobrun** [comment]
@ljbade yeah, in the branch, I divided the user tracking mode from registering listeners hence location tracking doesn't require sensor data. Will work on the branch today to get something merge able. Ideally I would like to move the sensor code to a refactored GPSMarker View.

**Comment by tobrun** [comment]
I will cherry pick required functionality for 2.1.0 milestone to this branch

**Comment by tobrun** [comment]
@ljbade thank you for covering me on this.
I pickup this up myself, needed to cherry pick some other stuff from User tracking.
Removed bearing part a bit more thoroughly.

**Pull request closed without merging**
