### PR TITLE
fixes #2044: add -showAnnotations:animated:

### LINKED ISSUE #2044: Add -[MGLMapView showAnnotations:animated:]
MapKit has a method since iOS 7 which sets the visible region so that the map displays all specified annotations. It would be nice if `MGLMapView` has a method like this:
```
- (void)showAnnotations:(NSArray<id<MGLAnnotation>> * _Nonnull)annotations animated:(BOOL)animated
```

### PR DESCRIPTION
**Pull request by incanus**

### CODE REVIEW

**Comment by incanus** [comment]
Want to give it a spin @jncn?

**Comment by incanus** [comment]
We decided there may be some more subtlety in MapKit's implementation than a flat `100px` all around (something to do with map aspect ratio and/or the poles), but this is a good first cut.

**Comment by incanus** [comment]
Also we may want to do something with view controller layout guides using `-[UILayoutSupport length]` and the current meters/pixel, but again, we can iterate later.

**Comment by jncn** [comment]
Great! It does the job, thanks. Might indeed need some refinements. MapKit's counterpart isn't perfect either, btw.

**Pull request merged**
