### PR TITLE
[android] Check for second callback in HttpRequestAndroid

### LINKED ISSUE #2400: Fix uv_async crash (aka Option B)
While investigating #2295 @ljbade discovered that [OkHttp](http://square.github.io/okhttp/) and `uv_async` were not working properly together.  The result was the decision to ship `0.1.0` using `curl` instead.  This ticket will be about restoring OkHttp by working out [the issues with `uv_async` as documented](https://github.com/mapbox/mapbox-gl-native/issues/2295#issuecomment-142465668) by @ljbade.  Specifically:

>- on curl all completed `HTTPRequest` handling happens in the same thread that creates `HTTPContext` as curl uses a loop pump to process everything (this is enforced via `MBGL_VERIFY_THREAD` macro)
- on NSUrl and OkHTTP we farm `HTTPRequest` out to the system so we get the result back async on a different thread from the one that created `HTTPContext`
- that is why both NSUrl and OkHTTP use `uv_async` to hand the final request processing back to the `HTTPContext` thread

>So to remove `uv_async` we need an alternative way to get the request back to the `HTTPContext` thread.

>I think @kkaefer will need to help us here with Option C, or he might be able to persue Option B.

@incanus @ljbade @kkaefer

### PR DESCRIPTION
**Pull request by ljbade**
Fixes #2400

### CODE REVIEW

**Comment by ljbade** [comment]
@zugaldia @bleege @tobrun This PR seems to fix the crash. But I still not sure why the callback gets called twice. It shouldn't.

I need to dig into this more to see if I can find the actual problem here.

**Comment by ljbade** [comment]
I have squashed and tidied up the commit.

@bleege @zugaldia One last review/test will be appreciated.

Final step is to wait for CI then merge when all happy.

**Comment by bleege** [comment]
> I have squashed and tidied up the commit.

Does this mean that you've found out [why the callback gets called twice](https://github.com/mapbox/mapbox-gl-native/pull/2905#issuecomment-153237111)?  If so can you explain what's going on?  Thanks!

**Comment by ljbade** [comment]
@bleege I think @zugaldias changes prevented the double callback, though I should go and double check this again with logging.

I suspect it had something to with how we handle `IOExceptions` in `onResponse`. Particularly the change from just returning on an exception, to rethrowing it.

**Comment by tobrun** [comment]
@ljbade 

I did the following to get the code:
 - git fetch origin
 - git checkout -b 2400-lock origin/2400-lock
 - git merge master

followed by a `make clean` and `make android`

> Nurbot:mapbox Nurbot$ make android
build: osx/x86_64
host: android/arm-v7
libs: headless=none  platform=android  asset=zip  http=android  cache=sqlite
* Recreating project...
This build is within a git repository
* Using Python 2.7.10
* Already installed at /Users/Nurbot/mapbox/mason_packages/headers/boost/1.59.0
* Not using boost_libprogram_options
* Not using openssl
* Not using libcurl
* Not using glfw
* Already installed at /Users/Nurbot/mapbox/mason_packages/android-arm-v7-9/libpng/1.6.18
* Already installed at /Users/Nurbot/mapbox/mason_packages/android-arm-v7-9/jpeg/v9a
* Already installed at /Users/Nurbot/mapbox/mason_packages/android-arm-v7-9/sqlite/3.9.1
* Already installed at /Users/Nurbot/mapbox/mason_packages/android-arm-v7-9/libuv/1.7.5
* Using system-provided zlib 1.2.3
* Linking zlib system dynamically
* Already installed at /Users/Nurbot/mapbox/mason_packages/android-arm-v7-9/nunicode/1.6
* Already installed at /Users/Nurbot/mapbox/mason_packages/android-arm-v7-9/libzip/0.11.2
* Already installed at /Users/Nurbot/mapbox/mason_packages/android-arm-v7-9/geojsonvt/2.1.6.3
* Already installed at /Users/Nurbot/mapbox/mason_packages/headers/variant/1.0
* Already installed at /Users/Nurbot/mapbox/mason_packages/headers/rapidjson/1.0.2
* Linking rapidjson 1.0.2 dynamically
* Not using gtest
#Do not edit. Generated by the configure script.
{
  'target_defaults': {
    'cflags%': [],
    'default_configuration': 'Release',
    'defines': [],
    'include_dirs': [],
    'libraries': [],
  },
  'variables': {
    'opengl_cflags%': [],
    'opengl_ldflags%': [],
    'boost_cflags%': ['-I/Users/Nurbot/mapbox/mason_packages/headers/boost/1.59.0/include'],
    'libpng_static_libs%': ['/Users/Nurbot/mapbox/mason_packages/android-arm-v7-9/libpng/1.6.18/lib/libpng.a'],
    'libpng_cflags%': ['-I/Users/Nurbot/mapbox/mason_packages/android-arm-v7-9/libpng/1.6.18/include/libpng16'],
    'libpng_ldflags%': ['-lz', '-lm'],
    'jpeg_static_libs%': ['/Users/Nurbot/mapbox/mason_packages/android-arm-v7-9/jpeg/v9a/lib/libjpeg.a'],
    'jpeg_cflags%': ['-I/Users/Nurbot/mapbox/mason_packages/android-arm-v7-9/jpeg/v9a/include'],
    'jpeg_ldflags%': [],
    'sqlite_static_libs%': ['/Users/Nurbot/mapbox/mason_packages/android-arm-v7-9/sqlite/3.9.1/lib/libsqlite3.a'],
    'sqlite_cflags%': ['-I/Users/Nurbot/mapbox/mason_packages/android-arm-v7-9/sqlite/3.9.1/include'],
    'sqlite_ldflags%': [],
    'libuv_static_libs%': ['/Users/Nurbot/mapbox/mason_packages/android-arm-v7-9/libuv/1.7.5/lib/libuv.a'],
    'libuv_cflags%': ['-I/Users/Nurbot/mapbox/mason_packages/android-arm-v7-9/libuv/1.7.5/include'],
    'libuv_ldflags%': ['-ldl'],
    'zlib_static_libs%': [],
    'zlib_cflags%': ['-I/Users/Nurbot/mapbox/mason_packages/android-arm-v7-9/zlib/system/include'],
    'zlib_ldflags%': ['-L/Users/Nurbot/mapbox/mason_packages/android-arm-v7-9/zlib/system/lib', '-lz'],
    'nunicode_static_libs%': ['/Users/Nurbot/mapbox/mason_packages/android-arm-v7-9/nunicode/1.6/lib/libnu.a'],
    'nunicode_cflags%': ['-I/Users/Nurbot/mapbox/mason_packages/android-arm-v7-9/nunicode/1.6/include'],
    'nunicode_ldflags%': [],
    'libzip_static_libs%': ['/Users/Nurbot/mapbox/mason_packages/android-arm-v7-9/libzip/0.11.2/lib/libzip.a'],
    'libzip_cflags%': ['-I/Users/Nurbot/mapbox/mason_packages/android-arm-v7-9/libzip/0.11.2/include', '-I/Users/Nurbot/mapbox/mason_packages/android-arm-v7-9/libzip/0.11.2/lib/libzip/include'],
    'libzip_ldflags%': ['-lz'],
    'geojsonvt_static_libs%': ['/Users/Nurbot/mapbox/mason_packages/android-arm-v7-9/geojsonvt/2.1.6.3/lib/libgeojsonvt.a'],
    'geojsonvt_cflags%': ['-I/Users/Nurbot/mapbox/mason_packages/android-arm-v7-9/geojsonvt/2.1.6.3/include'],
    'geojsonvt_ldflags%': [],
    'variant_static_libs%': [],
    'variant_cflags%': ['-isystem', '/Users/Nurbot/mapbox/mason_packages/headers/variant/1.0/include', '-I/Users/Nurbot/mapbox/mason_packages/headers/variant/1.0/include'],
    'variant_ldflags%': [],
    'rapidjson_static_libs%': [],
    'rapidjson_cflags%': ['-I/Users/Nurbot/mapbox/mason_packages/headers/rapidjson/1.0.2/include'],
    'rapidjson_ldflags%': [],
  }
}

>* Recreating project...
* Building target androidapp...
  ACTION gyp_mbgl_gyp_shaders_target_Build_Shaders Release/obj/gen/include/mbgl/shader/shaders.hpp
  TOUCH Release/obj.target/gyp/shaders.stamp
  ACTION gyp_mbgl_gyp_version_target_Build_Version_Header Release/obj/gen/include/mbgl/util/version.hpp
  TOUCH Release/obj.target/gyp/version.stamp
  CXX(target) Release/obj.target/core/src/clipper/clipper.o
  CXX(target) Release/obj.target/core/src/csscolorparser/csscolorparser.o
  CXX(target) Release/obj.target/core/src/mbgl/annotation/annotation_manager.o
  CXX(target) Release/obj.target/core/src/mbgl/annotation/annotation_tile.o
  CXX(target) Release/obj.target/core/src/mbgl/annotation/point_annotation_impl.o
  CXX(target) Release/obj.target/core/src/mbgl/annotation/shape_annotation_impl.o
  CXX(target) Release/obj.target/core/src/mbgl/annotation/sprite_image.o
  CXX(target) Release/obj.target/core/src/mbgl/annotation/sprite_parser.o
  CXX(target) Release/obj.target/core/src/mbgl/annotation/sprite_store.o
  CXX(target) Release/obj.target/core/src/mbgl/geometry/circle_buffer.o
  CXX(target) Release/obj.target/core/src/mbgl/geometry/collision_box_buffer.o
  CXX(target) Release/obj.target/core/src/mbgl/geometry/debug_font_buffer.o
  CXX(target) Release/obj.target/core/src/mbgl/geometry/elements_buffer.o
  CXX(target) Release/obj.target/core/src/mbgl/geometry/fill_buffer.o
  CXX(target) Release/obj.target/core/src/mbgl/geometry/glyph_atlas.o
  CXX(target) Release/obj.target/core/src/mbgl/geometry/icon_buffer.o
  CXX(target) Release/obj.target/core/src/mbgl/geometry/line_atlas.o
  CXX(target) Release/obj.target/core/src/mbgl/geometry/line_buffer.o
  CXX(target) Release/obj.target/core/src/mbgl/geometry/sprite_atlas.o
  CXX(target) Release/obj.target/core/src/mbgl/geometry/static_vertex_buffer.o
  CXX(target) Release/obj.target/core/src/mbgl/geometry/text_buffer.o
  CXX(target) Release/obj.target/core/src/mbgl/geometry/vao.o
  CXX(target) Release/obj.target/core/src/mbgl/gl/debugging.o
  CXX(target) Release/obj.target/core/src/mbgl/layer/background_layer.o
  CXX(target) Release/obj.target/core/src/mbgl/layer/circle_layer.o
  CXX(target) Release/obj.target/core/src/mbgl/layer/fill_layer.o
  CXX(target) Release/obj.target/core/src/mbgl/layer/line_layer.o
  CXX(target) Release/obj.target/core/src/mbgl/layer/raster_layer.o
  CXX(target) Release/obj.target/core/src/mbgl/layer/symbol_layer.o
  CXX(target) Release/obj.target/core/src/mbgl/map/camera.o
  CXX(target) Release/obj.target/core/src/mbgl/map/geometry_tile.o
  CXX(target) Release/obj.target/core/src/mbgl/map/map.o
  CXX(target) Release/obj.target/core/src/mbgl/map/map_context.o
  CXX(target) Release/obj.target/core/src/mbgl/map/map_data.o
  CXX(target) Release/obj.target/core/src/mbgl/map/raster_tile_data.o
  CXX(target) Release/obj.target/core/src/mbgl/map/source.o
  CXX(target) Release/obj.target/core/src/mbgl/map/sprite.o
  CXX(target) Release/obj.target/core/src/mbgl/map/tile.o
  CXX(target) Release/obj.target/core/src/mbgl/map/tile_cache.o
  CXX(target) Release/obj.target/core/src/mbgl/map/tile_data.o
  CXX(target) Release/obj.target/core/src/mbgl/map/tile_id.o
  CXX(target) Release/obj.target/core/src/mbgl/map/tile_worker.o
  CXX(target) Release/obj.target/core/src/mbgl/map/transform.o
  CXX(target) Release/obj.target/core/src/mbgl/map/transform_state.o
  CXX(target) Release/obj.target/core/src/mbgl/map/vector_tile.o
  CXX(target) Release/obj.target/core/src/mbgl/map/vector_tile_data.o
  CXX(target) Release/obj.target/core/src/mbgl/map/view.o
  CXX(target) Release/obj.target/core/src/mbgl/platform/gl.o
  CXX(target) Release/obj.target/core/src/mbgl/platform/log.o
  CXX(target) Release/obj.target/core/src/mbgl/renderer/circle_bucket.o
  CXX(target) Release/obj.target/core/src/mbgl/renderer/debug_bucket.o
  CXX(target) Release/obj.target/core/src/mbgl/renderer/fill_bucket.o
  CXX(target) Release/obj.target/core/src/mbgl/renderer/frame_history.o
  CXX(target) Release/obj.target/core/src/mbgl/renderer/gl_config.o
  CXX(target) Release/obj.target/core/src/mbgl/renderer/line_bucket.o
  CXX(target) Release/obj.target/core/src/mbgl/renderer/painter.o
  CXX(target) Release/obj.target/core/src/mbgl/renderer/painter_circle.o
  CXX(target) Release/obj.target/core/src/mbgl/renderer/painter_clipping.o
  CXX(target) Release/obj.target/core/src/mbgl/renderer/painter_debug.o
  CXX(target) Release/obj.target/core/src/mbgl/renderer/painter_fill.o
  CXX(target) Release/obj.target/core/src/mbgl/renderer/painter_line.o
  CXX(target) Release/obj.target/core/src/mbgl/renderer/painter_raster.o
  CXX(target) Release/obj.target/core/src/mbgl/renderer/painter_symbol.o
  CXX(target) Release/obj.target/core/src/mbgl/renderer/raster_bucket.o
  CXX(target) Release/obj.target/core/src/mbgl/renderer/symbol_bucket.o
  CXX(target) Release/obj.target/core/src/mbgl/shader/box_shader.o
  CXX(target) Release/obj.target/core/src/mbgl/shader/circle_shader.o
  CXX(target) Release/obj.target/core/src/mbgl/shader/dot_shader.o
  CXX(target) Release/obj.target/core/src/mbgl/shader/icon_shader.o
  CXX(target) Release/obj.target/core/src/mbgl/shader/line_shader.o
  CXX(target) Release/obj.target/core/src/mbgl/shader/linepattern_shader.o
  CXX(target) Release/obj.target/core/src/mbgl/shader/linesdf_shader.o
  CXX(target) Release/obj.target/core/src/mbgl/shader/outline_shader.o
  CXX(target) Release/obj.target/core/src/mbgl/shader/pattern_shader.o
  CXX(target) Release/obj.target/core/src/mbgl/shader/plain_shader.o
  CXX(target) Release/obj.target/core/src/mbgl/shader/raster_shader.o
  CXX(target) Release/obj.target/core/src/mbgl/shader/sdf_shader.o
  CXX(target) Release/obj.target/core/src/mbgl/shader/shader.o
  CXX(target) Release/obj.target/core/src/mbgl/shader/uniform.o
  CXX(target) Release/obj.target/core/src/mbgl/storage/default_file_source.o
  CXX(target) Release/obj.target/core/src/mbgl/storage/http_context_base.o
  CXX(target) Release/obj.target/core/src/mbgl/storage/http_request_base.o
  CXX(target) Release/obj.target/core/src/mbgl/storage/network_status.o
  CXX(target) Release/obj.target/core/src/mbgl/storage/request.o
  CXX(target) Release/obj.target/core/src/mbgl/storage/request_holder.o
  CXX(target) Release/obj.target/core/src/mbgl/storage/response.o
  CXX(target) Release/obj.target/core/src/mbgl/style/applied_class_properties.o
  CXX(target) Release/obj.target/core/src/mbgl/style/class_dictionary.o
  CXX(target) Release/obj.target/core/src/mbgl/style/class_properties.o
  CXX(target) Release/obj.target/core/src/mbgl/style/filter_expression.o
  CXX(target) Release/obj.target/core/src/mbgl/style/function.o
  CXX(target) Release/obj.target/core/src/mbgl/style/paint_properties_map.o
  CXX(target) Release/obj.target/core/src/mbgl/style/property_fallback.o
  CXX(target) Release/obj.target/core/src/mbgl/style/property_parsing.o
  CXX(target) Release/obj.target/core/src/mbgl/style/style.o
  CXX(target) Release/obj.target/core/src/mbgl/style/style_bucket_parameters.o
  CXX(target) Release/obj.target/core/src/mbgl/style/style_layer.o
  CXX(target) Release/obj.target/core/src/mbgl/style/style_parser.o
  CXX(target) Release/obj.target/core/src/mbgl/style/style_properties.o
  CXX(target) Release/obj.target/core/src/mbgl/style/types.o
  CXX(target) Release/obj.target/core/src/mbgl/style/value.o
  CXX(target) Release/obj.target/core/src/mbgl/text/check_max_angle.o
  CXX(target) Release/obj.target/core/src/mbgl/text/collision_feature.o
  CXX(target) Release/obj.target/core/src/mbgl/text/collision_tile.o
  CXX(target) Release/obj.target/core/src/mbgl/text/font_stack.o
  CXX(target) Release/obj.target/core/src/mbgl/text/get_anchors.o
  CXX(target) Release/obj.target/core/src/mbgl/text/glyph.o
  CXX(target) Release/obj.target/core/src/mbgl/text/glyph_pbf.o
  CXX(target) Release/obj.target/core/src/mbgl/text/glyph_store.o
  CXX(target) Release/obj.target/core/src/mbgl/text/quads.o
  CXX(target) Release/obj.target/core/src/mbgl/text/shaping.o
  CXX(target) Release/obj.target/core/src/mbgl/util/clip_id.o
  CXX(target) Release/obj.target/core/src/mbgl/util/clip_lines.o
  CXX(target) Release/obj.target/core/src/mbgl/util/compression.o
  CXX(target) Release/obj.target/core/src/mbgl/util/constants.o
  CXX(target) Release/obj.target/core/src/mbgl/util/default_styles.o
  CXX(target) Release/obj.target/core/src/mbgl/util/geo.o
  CXX(target) Release/obj.target/core/src/mbgl/util/geojsonvt/geojsonvt.o
  CXX(target) Release/obj.target/core/src/mbgl/util/geojsonvt/geojsonvt_clip.o
  CXX(target) Release/obj.target/core/src/mbgl/util/geojsonvt/geojsonvt_convert.o
  CXX(target) Release/obj.target/core/src/mbgl/util/geojsonvt/geojsonvt_simplify.o
  CXX(target) Release/obj.target/core/src/mbgl/util/geojsonvt/geojsonvt_tile.o
  CXX(target) Release/obj.target/core/src/mbgl/util/gl_object_store.o
  CXX(target) Release/obj.target/core/src/mbgl/util/io.o
  CXX(target) Release/obj.target/core/src/mbgl/util/mapbox.o
  CXX(target) Release/obj.target/core/src/mbgl/util/mat2.o
  CXX(target) Release/obj.target/core/src/mbgl/util/mat3.o
  CXX(target) Release/obj.target/core/src/mbgl/util/mat4.o
  CXX(target) Release/obj.target/core/src/mbgl/util/math.o
  CXX(target) Release/obj.target/core/src/mbgl/util/merge_lines.o
  CXX(target) Release/obj.target/core/src/mbgl/util/raster.o
  CXX(target) Release/obj.target/core/src/mbgl/util/run_loop.o
  CXX(target) Release/obj.target/core/src/mbgl/util/scaling.o
  CXX(target) Release/obj.target/core/src/mbgl/util/stopwatch.o
  CXX(target) Release/obj.target/core/src/mbgl/util/texture_pool.o
  CXX(target) Release/obj.target/core/src/mbgl/util/thread_context.o
  CXX(target) Release/obj.target/core/src/mbgl/util/tile_cover.o
  CXX(target) Release/obj.target/core/src/mbgl/util/time.o
  CXX(target) Release/obj.target/core/src/mbgl/util/transition.o
  CXX(target) Release/obj.target/core/src/mbgl/util/url.o
  CXX(target) Release/obj.target/core/src/mbgl/util/uv.o
  CXX(target) Release/obj.target/core/src/mbgl/util/vec4.o
  CXX(target) Release/obj.target/core/src/mbgl/util/version_info.o
  CXX(target) Release/obj.target/core/src/mbgl/util/work_queue.o
  CXX(target) Release/obj.target/core/src/mbgl/util/work_request.o
  CXX(target) Release/obj.target/core/src/mbgl/util/work_task.o
  CXX(target) Release/obj.target/core/src/mbgl/util/worker.o
  CC(target) Release/obj.target/core/src/libtess2/bucketalloc.o
  CC(target) Release/obj.target/core/src/libtess2/dict.o
  CC(target) Release/obj.target/core/src/libtess2/geom.o
  CC(target) Release/obj.target/core/src/libtess2/mesh.o
  CC(target) Release/obj.target/core/src/libtess2/priorityq.o
  CC(target) Release/obj.target/core/src/libtess2/sweep.o
  CC(target) Release/obj.target/core/src/libtess2/tess.o
  CC(target) Release/obj.target/core/src/mbgl/util/parsedate.o
  CXX(target) Release/obj.target/core/gen/src/shader/shaders_gl.o
  CXX(target) Release/obj.target/core/gen/src/shader/shaders_gles2.o
  AR(target) Release/obj.target/gyp/libmbgl-core.a
  COPY Release/libmbgl-core.a
  CXX(target) Release/obj.target/platform-android/platform/android/log_android.o
  CXX(target) Release/obj.target/platform-android/platform/android/asset_root.o
  CXX(target) Release/obj.target/platform-android/platform/default/thread.o
../../platform/default/thread.cpp:23:9: warning: Building without thread
      priority control [-W#pragma-messages]
#pragma message("Building without thread priority control")
        ^
1 warning generated.
  CXX(target) Release/obj.target/platform-android/platform/default/string_stdlib.o
  CXX(target) Release/obj.target/platform-android/platform/default/image.o
  CXX(target) Release/obj.target/platform-android/platform/default/image_reader.o
  CXX(target) Release/obj.target/platform-android/platform/default/png_reader.o
  CXX(target) Release/obj.target/platform-android/platform/default/jpeg_reader.o
  AR(target) Release/obj.target/gyp/libmbgl-platform-android.a
  COPY Release/libmbgl-platform-android.a
  CXX(target) Release/obj.target/http-android/platform/android/http_request_android.o
../../platform/android/http_request_android.cpp:194:59: warning: unused
      parameter 'message' [-Wunused-parameter]
void HTTPAndroidRequest::onResponse(int code, std::string message, std::...
                                                          ^
../../platform/android/http_request_android.cpp:253:76: warning: unused
      parameter 'loop' [-Wunused-parameter]
  ...HTTPContextBase::createContext(uv_loop_t* loop) {
                                               ^
2 warnings generated.
  AR(target) Release/obj.target/gyp/libmbgl-http-android.a
  COPY Release/libmbgl-http-android.a
  CXX(target) Release/obj.target/asset-zip/platform/default/asset_request_zip.o
  CC(target) Release/obj.target/asset-zip/platform/default/uv_zip.o
  AR(target) Release/obj.target/gyp/libmbgl-asset-zip.a
  COPY Release/libmbgl-asset-zip.a
  CXX(target) Release/obj.target/cache-sqlite/platform/default/sqlite_cache.o
  CXX(target) Release/obj.target/cache-sqlite/platform/default/sqlite3.o
  AR(target) Release/obj.target/gyp/libmbgl-cache-sqlite.a
  COPY Release/libmbgl-cache-sqlite.a
  CXX(target) Release/obj.target/android-lib/platform/android/native_map_view.o
  CXX(target) Release/obj.target/android-lib/platform/android/jni.o
  SOLINK(target) Release/obj.target/gyp/libmapbox-gl.so
/Users/Nurbot/mapbox/mason_packages/osx-10.11/android-ndk/arm-9-r10e/bin/../lib/gcc/arm-linux-androideabi/4.9/../../../../arm-linux-androideabi/bin/ld.gold: error: /Users/Nurbot/mapbox/mason_packages/android-arm-v7-9/geojsonvt/2.1.6.3/lib/libgeojsonvt.a(geojsonvt.o): multiple definition of 'mapbox::util::geojsonvt::GeoJSONVT::intersectX(mapbox::util::geojsonvt::ProjectedPoint const&, mapbox::util::geojsonvt::ProjectedPoint const&, double)'
/Users/Nurbot/mapbox/mason_packages/osx-10.11/android-ndk/arm-9-r10e/bin/../lib/gcc/arm-linux-androideabi/4.9/../../../../arm-linux-androideabi/bin/ld.gold: ./Release/obj.target/gyp/libmbgl-core.a(geojsonvt.o): previous definition here
/Users/Nurbot/mapbox/mason_packages/osx-10.11/android-ndk/arm-9-r10e/bin/../lib/gcc/arm-linux-androideabi/4.9/../../../../arm-linux-androideabi/bin/ld.gold: error: /Users/Nurbot/mapbox/mason_packages/android-arm-v7-9/geojsonvt/2.1.6.3/lib/libgeojsonvt.a(geojsonvt.o): multiple definition of 'mapbox::util::geojsonvt::GeoJSONVT::intersectY(mapbox::util::geojsonvt::ProjectedPoint const&, mapbox::util::geojsonvt::ProjectedPoint const&, double)'
/Users/Nurbot/mapbox/mason_packages/osx-10.11/android-ndk/arm-9-r10e/bin/../lib/gcc/arm-linux-androideabi/4.9/../../../../arm-linux-androideabi/bin/ld.gold: ./Release/obj.target/gyp/libmbgl-core.a(geojsonvt.o): previous definition here
/Users/Nurbot/mapbox/mason_packages/osx-10.11/android-ndk/arm-9-r10e/bin/../lib/gcc/arm-linux-androideabi/4.9/../../../../arm-linux-androideabi/bin/ld.gold: error: /Users/Nurbot/mapbox/mason_packages/android-arm-v7-9/geojsonvt/2.1.6.3/lib/libgeojsonvt.a(geojsonvt.o): multiple definition of 'mapbox::util::geojsonvt::GeoJSONVT::toID(unsigned char, unsigned int, unsigned int)'
/Users/Nurbot/mapbox/mason_packages/osx-10.11/android-ndk/arm-9-r10e/bin/../lib/gcc/arm-linux-androideabi/4.9/../../../../arm-linux-androideabi/bin/ld.gold: ./Release/obj.target/gyp/libmbgl-core.a(geojsonvt.o): previous definition here
/Users/Nurbot/mapbox/mason_packages/osx-10.11/android-ndk/arm-9-r10e/bin/../lib/gcc/arm-linux-androideabi/4.9/../../../../arm-linux-androideabi/bin/ld.gold: error: /Users/Nurbot/mapbox/mason_packages/android-arm-v7-9/geojsonvt/2.1.6.3/lib/libgeojsonvt.a(geojsonvt.o): multiple definition of 'mapbox::util::geojsonvt::GeoJSONVT::getTile(unsigned char, unsigned int, unsigned int)'
/Users/Nurbot/mapbox/mason_packages/osx-10.11/android-ndk/arm-9-r10e/bin/../lib/gcc/arm-linux-androideabi/4.9/../../../../arm-linux-androideabi/bin/ld.gold: ./Release/obj.target/gyp/libmbgl-core.a(geojsonvt.o): previous definition here
/Users/Nurbot/mapbox/mason_packages/osx-10.11/android-ndk/arm-9-r10e/bin/../lib/gcc/arm-linux-androideabi/4.9/../../../../arm-linux-androideabi/bin/ld.gold: error: /Users/Nurbot/mapbox/mason_packages/android-arm-v7-9/geojsonvt/2.1.6.3/lib/libgeojsonvt.a(geojsonvt.o): multiple definition of 'mapbox::util::geojsonvt::Time::activities'
/Users/Nurbot/mapbox/mason_packages/osx-10.11/android-ndk/arm-9-r10e/bin/../lib/gcc/arm-linux-androideabi/4.9/../../../../arm-linux-androideabi/bin/ld.gold: ./Release/obj.target/gyp/libmbgl-core.a(geojsonvt.o): previous definition here
/Users/Nurbot/mapbox/mason_packages/osx-10.11/android-ndk/arm-9-r10e/bin/../lib/gcc/arm-linux-androideabi/4.9/../../../../arm-linux-androideabi/bin/ld.gold: error: /Users/Nurbot/mapbox/mason_packages/android-arm-v7-9/geojsonvt/2.1.6.3/lib/libgeojsonvt.a(geojsonvt_clip.o): multiple definition of 'mapbox::util::geojsonvt::Clip::newSlice(mapbox::util::geojsonvt::ProjectedGeometryContainer&, mapbox::util::geojsonvt::ProjectedGeometryContainer&, double, double)'
/Users/Nurbot/mapbox/mason_packages/osx-10.11/android-ndk/arm-9-r10e/bin/../lib/gcc/arm-linux-androideabi/4.9/../../../../arm-linux-androideabi/bin/ld.gold: ./Release/obj.target/gyp/libmbgl-core.a(geojsonvt_clip.o): previous definition here
clang36++: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [Release/obj.target/gyp/libmapbox-gl.so] Error 1
make[1]: *** [Makefile/androidapp] Error 2
make: *** [android-lib] Error 2

**Comment by zugaldia** [comment]
To help debugging requests I just added an application interceptor (it's disabled by default): https://github.com/mapbox/mapbox-gl-native/commit/561a36c55c7041bcec26d8d153dd383e1b8e2313

This interceptor does not change the request or response in any way, it simply logs the outgoing request and the incoming response data. To see it in action, you need to enable it in the `HTTPContext` constructor.

**Comment by ljbade** [comment]
Awesome @zugaldia.

I will also rebase this branch to bring in API 15 fixes for next SNAPSHOT

**Comment by zugaldia** [comment]
:+1:

**Comment by bleege** [comment]
> I will also rebase this branch to bring in API 15 fixes for next SNAPSHOT

Just checking, but if we're done with this why not just merge into `master`?  Remember, the only reason that the last SNAPSHOT was based off this branch is because we wanted to isolate and test the OkHttp work.

**Comment by ljbade** [comment]
@bleege oh true... quick question, should we run a perf benchmark somehow before we merge just to test out concerns around JNI overhead (https://github.com/mapbox/mapbox-gl-native/issues/2400#issuecomment-156214757)

**Comment by bleege** [comment]
> should we run a perf benchmark somehow before we merge just to test out concerns around JNI overhead

Sounds like a great idea.  Please make it happen.

**Comment by manimaul** [comment]
+1 for Merging this into master.  Having the networking in the Java could allow for implementing tile data providers in the Java layer with minimal effort.  (E.g. https://github.com/manimaul/mapbox-gl-native/tree/offline)

**Comment by ljbade** [comment]
@tobrun @zugaldia Do you have some ideas on how we can benchmark the HTTP library?

There isn't an easy to request a bunch of tiles to load directly without modifying the C++ lib. Otherwise we could try panning to a set of locations after clearing the cache. We would need to add some logging or stat tracking code in the C++ layer to measure the difference however.

**Comment by ljbade** [comment]
I think I am going to merge this branch now. We can then go back and benchmark before and after once we figure out how best to do this.

**Comment by ljbade** [comment]
Ah damn the PR was marked as closed not merged!

It was merged in https://github.com/mapbox/mapbox-gl-native/commit/af2d034e9d1ea9d55d022025ce0f99005ca3af58

**Pull request closed without merging**
