### PR TITLE
fixes #6523: remove custom Bitrise CI-skipping stuff

### LINKED ISSUE #6523: remove custom Bitrise [skip ci] hack
Per [UserVoice](https://bitrise.uservoice.com/forums/235233-general/suggestions/10519956-allow-for-configurable-commit-message-pattern-s-t?tracking_code=307631e248b028c6c457e1082a2ae414) and the [new docs](https://bitrise-io.github.io/devcenter/tips-and-tricks/skip-a-build/), Bitrise supports this natively via https://github.com/bitrise-io/bitrise-webhooks/pull/8. 

We should back out https://github.com/mapbox/mapbox-gl-native/commit/f5bb746f6a3e68268c23125ca7acdf549a9cacda (https://github.com/mapbox/mapbox-gl-native/issues/2843) and just defer to their implementation.

### PR DESCRIPTION
**Pull request by incanus**
Fixes #6523 since Bitrise does this internally now.

### CODE REVIEW

**Comment by tobrun** [comment]
:shipit:

**Comment by incanus** [comment]
Going to test that this actually works first with a throwaway commit or two here.

**Comment by incanus** [comment]
I'm also curious if we get any Slack output, which we suppressed in our custom version.

**Comment by incanus** [comment]
Heh, this doesn't seem to work.

**Comment by incanus** [comment]
Note that per the docs: 

> *If you push more than one commit*, only the last ("head") commit's message will be checked for the skip ci pattern!

**Comment by incanus** [comment]
Pinged Bitrise on this over in https://github.com/bitrise-io/bitrise-webhooks/issues/2 to get to the bottom of things.

**Comment by incanus** [comment]
Seems like this is PR-wide and requires the `[skip ci]` to be in the PR title. That means all commits on the PR won't be tested, or all will—one or the other.

**Comment by incanus** [comment]
Bitrise needs improvement here and is likely working on it per https://github.com/bitrise-io/bitrise-webhooks/issues/2#issuecomment-250807501, so stay tuned. This can sit in the meantime.

**Comment by 1ec5** [comment]
@incanus, does bitrise-io/bitrise-webhooks#21 address the problem mentioned in https://github.com/mapbox/mapbox-gl-native/pull/6525#issuecomment-250803966?

**Comment by jfirebaugh** [comment]
⇢ #8346

**Pull request closed without merging**
