### PR TITLE
Add YCM config file for VIM users

### PR DESCRIPTION
**Pull request by tmpsantos**
Tailor-made for Mapbox GL Native.

For instructions of how to use, see:
https://github.com/Valloric/YouCompleteMe

### CODE REVIEW

**Comment by tmpsantos** [comment]
@brunoabinader can you test this on OSX ?

**Comment by brunoabinader** [comment]
@tmpsantos :+1: will do, testing now.

**Comment by brunoabinader** [comment]
OSX does not add `:` to the end of the object file, so we should try this:
```
if platform == 'linux':
    relative_obj_path += ':' 

make_cmd = 'make -pn |grep %s |grep NDEBUG |cut -d\' \' -f3- |head -n1' % relative_obj_path```

**Comment by tmpsantos** [comment]
Merged.

**Pull request closed without merging**
