### PR TITLE
Set GCC_GENERATE_DEBUGGING_SYMBOLS in Xcode

### PR DESCRIPTION
**Pull request by kkaefer**
Fixes https://github.com/mapbox/mapbox-gl-native/issues/12668

### CODE REVIEW

**Comment by mb12** [comment]
@kkaefer and @friedbunny  Can we keep this enabled for debug builds? Without this breakpoints do not work in xcode for any code compiled as part of mbgl-core target.

**Comment by julianrex** [comment]
Revisiting - @kkaefer @friedbunny what are the downsides if we just enable this for `Debug` and `RelWithDebugInfo` builds? If a developer wants complete call stacks, we could offer a `RelWithDebugInfo` release too?

**Comment by friedbunny** [comment]
Using `RelWithDebInfo` with the iOS Maps SDK’s `symbols` releases seems logical to me, though there is some contention over that scheme — [it sets `-O3`](https://github.com/mapbox/mapbox-gl-native/blob/9afe75aa76c02db21209e8f92b09be4b596a3983/CMakeLists.txt#L94-L95) and the iOS Maps SDK needs `-Os`, so we’d want to make `-O3` node-only.

... that said, I’m currently of the opinion that this PR fixed a bug and that framework binary/dSYM size doesn’t matter very much.

**Comment by friedbunny** [comment]
29c6647e139635a0abdf92e85698921ffdf94e72 changed our Xcode projects to set `GCC_GENERATE_DEBUGGING_SYMBOLS` for every configuration _except_ `Release` — use `RelWithDebInfo` if you need debug symbols.

**Pull request merged**
