### PR TITLE
[Qt] Don't regen BackendScope on every QMapboxGL::render() call

### PR DESCRIPTION
**Pull request by brunoabinader**

### CODE REVIEW

**Comment by jfirebaugh** [comment]
But why? `BackendScope` is intended to be used as a stack-allocated object, not as a heap-allocated object. Using it in this way risks creating extremely difficult to debug context management bugs.

**Comment by brunoabinader** [comment]
> But why?

For Qt we use the implicit scope type, so no backend management is required from our side.

In fact, the only reason we needed this is to satisfy the condition `BackendScope::exists()` when we render, which we do by keeping an instance of the scope alive together with the `QMapboxGL` pimpl. This also does not modify the linked scopes mechanism for debugging, so I'd say we're safe there too.

Do you see another situation in which this could complicate debugging?

**Comment by jfirebaugh** [comment]
`BackendScope` is not just about doing the activation/deactivation, it's about asserting that the correct context is active when we do GL operations. By keeping a `BackendScope` permanently in scope, you're asserting that your context is the only one that's _ever_ active in the program. If there were to be a bug where mbgl core did GL operations at an improper time, when the expected context might not actually be the active context, the `BackendScope::exists()` assertions would not catch it.

**Comment by brunoabinader** [comment]
@jfirebaugh fair enough, I'll revert these then.

**Pull request merged**
