### PR TITLE
Upgrade OHHTTPStubs to 4.3.0

### PR DESCRIPTION
**Pull request by 1ec5**
This PR upgrades [AliSoftware/OHHTTPStubs@4.3.0](https://github.com/AliSoftware/OHHTTPStubs/releases/tag/4.3.0) in the ios-tests project, fixing warnings we’ve been seeing such as:

```
⚠️  /Users/travis/build/mapbox/mapbox-gl-native/test/ios/OHHTTPStubs/OHHTTPStubs/Sources/OHHTTPStubsResponse.m:46:17: method override for the designated initializer of the superclass '-init' not found [-Wobjc-designated-initializers]

@implementation OHHTTPStubsResponse

                ^
```

and hopefully mitigating our issues with [stalled iOS builds](https://travis-ci.org/mapbox/mapbox-gl-native/jobs/85754799).

Note that I had to revert AliSoftware/OHHTTPStubs@806ba99fb71d0b8bebe505b3a939c0a755606bd8 to get the test sources to compile again. In the future, we might want to move OHHTTPStubs to a separate framework target so that these source modifications aren’t necessary.

/cc @incanus @ljbade

### CODE REVIEW

**Comment by 1ec5** [comment]
No more warnings, but the build still stalls. :disappointed:

**Comment by 1ec5** [comment]
The build is stalling on `-[MapViewTests testMarkerAddWithoutDelegate]`. This is a regression from #2612.

**Comment by 1ec5** [comment]
I can reproduce the stall in the iPad 2 simulator. The test is waiting for Location Services authorization:

ipad 2

**Comment by ljbade** [comment]
Ha-ha wow. Need an extra tap?

**Pull request merged**
