### PR TITLE
Sets the loading flag in the style request handler to ensure that the…

### PR DESCRIPTION
**Pull request by PaulZed**
… correct Map event fires when a stale style gets refreshed from the server.

### CODE REVIEW

**Comment by jfirebaugh** [comment]
I'm pretty sure we don't want to change the semantics of `MapChangeDidFinishLoadingMap` such that it fires more than once per call to `setStyle{URL,JSON}`. That would likely violate the assumptions of existing users of the event.

What's the underlying need you're trying to satisfy here?

**Comment by PaulZed** [comment]
The problem here is that setStyle doesn't get called when a resource expires and is refetched. This means that the map reloads, but the MapChangeDidFinishLoadingMap event never fires, which is wrong. If someone is relying on that event to say, add a custom layer to the style, then when the style expires that custom layer will disappear forever, until the style is explicitly changed.

**Comment by PaulZed** [comment]
Perhaps a cleaner solution is to not keep the same request around to handle resource expiration,  and explicitly call `setStyleURL` to load the new style when the resource expires.

**Comment by PaulZed** [comment]
@tmpsantos @brunoabinader thoughts?

**Comment by brunoabinader** [comment]
I suggest we add a new enum e.g. `MapChangeDidFinishRefreshStyle` - this ensures that the semantic concerns mentioned by @jfirebaugh are sustained while providing a mean for the client to be notified about it.

**Comment by tmpsantos** [comment]
> MapChangeDidFinishRefreshStyle

I like the idea.

**Comment by PaulZed** [comment]
I don't really understand what the difference is. If you have something that you want to happen whenever the map finishes loading, why wouldn't you want to do it when the map reloads? Can anyone actually come up with an example where semantics are being violated, because i'm struggling to.

**Comment by jfirebaugh** [comment]
@PaulZed Thanks for bringing this to my attention. This exposed a wider issue with the intersection of runtime styling and style revalidation that I think needs discussion independent of this specific proposal. Opened #5665 for discussion.

**Pull request closed without merging**
