### PR TITLE
Grab app-wide data from Info.plist

### LINKED ISSUE #1535: MGLAccountManager should get its data from Info.plist entries, not class setter method calls
`MGLAccountManager` currently forces the developer to send it `-setMapboxMetricsEnabledSettingShownInApp:` (optionally) and `-setAccessToken:` sometime at startup, in that order, before the first `MGLMapView` is initialized. The exact place where these setters must be called depends on how and where they use `MGLMapView` – whether programmatically or in a storyboard, whether in the initial view controller or some later view controller, etc.

iOS has an affordance for settings that need to be set right at launch: the Info.plist that comes with every project. `MGLAccountManager` should look there for the access token and in-app opt-out flag. For beta 2, we should deprecate the class setters and add code to `+[MGLAccountManager initialize]` (which is called as soon as MapboxGL.a loads) that looks inside the Info.plist using `-[NSBundle objectForInfoDictionaryKey:]`.

/cc @incanus @bleege

### PR DESCRIPTION
**Pull request by 1ec5**
That way there’s no ambiguity about when you should call things like `+[MGLAccountManager setMapboxMetricsEnabledSettingShownInApp:]`. In fact, that method is now deprecated because it’s so easy to call in the wrong place.

Fixes #1535.

/cc @incanus @bleege

### CODE REVIEW

**Comment by incanus** [comment]
Do we need to deprecate, vs. just pulling? We're still in beta.

**Comment by 1ec5** [comment]
I want the compiler warning to say what the alternative is rather than "I don't know what you're talking about", but come to think of it, an UNAVAILABLE macro makes more sense, as it's unignorable.

**Comment by 1ec5** [comment]
Does it make sense to keep `-[MGLMapView setAccessToken:]`? It’s a mostly redundant code path, since setting `MGLMapboxAccessToken` in Info.plist – either in the property list editor or in the project editor – is by far the preferred way to set the access token. The only use case I can think of for keeping this extra property is different access tokens for different `MGLMapView`s in the same app. But Metrics would be quite confused in that case, sending events tied to different maps based on which one happens to have been initialized last.

If we decide to remove `-[MGLMapView setAccessToken:]`, I’d probably mark it unavailable with a helpful message, as I’ve done for `+[MGLAccountManager setMapboxMetricsEnabledSettingShownInApp:]`, and I’d make the implementation assert with a helpful message for apps built with storyboards. (The assertion message would appear in the Issue navigator as an error while designing in Interface Builder.)

**Comment by 1ec5** [comment]
With these changes, if you wanted to upload your project to GitHub, leave out your access token (#1404), and avoid accidentally checking in your access token after you develop locally, you could employ the following Run Script build phase in Xcode (add it anywhere after the Copy Bundle Resources build phase):

```bash
token="$(cat ~/.mapbox)"
if [ "$token" ]; then
  plutil -replace MGLMapboxAccessToken -string $token $TARGET_BUILD_DIR/$INFOPLIST_PATH
fi
```

There’s no need to interact with `MGLAccountManager` at all: the plist entry is read the very moment the framework is loaded.

**Comment by friedbunny** [comment]
I still see using `-[MGLMapView setAccessToken:]` in the app delegate as the primary way developers will want to set access tokens.

If token security is a priority, the plist will be the go-to option, but if it's a lone developer or a private codebase, setting the token in code feels like the easiest path to me. Using the app delegate's `application:didFinishLaunchingWithOptions:` method is also a [super-common and expected pattern in other SDKs](https://www.google.com/search?q=set+api+key+in+didFinishLaunchingWithOptions).

**Comment by 1ec5** [comment]
@friedbunny, that would be an argument for keeping `+[MGLAccountManager setAccessToken:]` around. `-[MGLMapView setAccessToken:]` is kinda weird because it affects the app globally via `MGLAccountManager` but looks like a view-local property.

@bsudekum, does React Native let you modify the Info.plist that customarily comes with a project? I’m thinking about obsoleting `-[MGLMapView setAccessToken:]` now that you can add the token to the Info.plist, but if that isn’t an option in your environment, that might be a good reason to keep the method around.

**Comment by friedbunny** [comment]
Ah, bleh on my late night reading comprehension.

**Comment by bleege** [comment]
`-[MGLMapView setAccessToken:]` was originally put in as a way for `+[MGLAccountManager setAccessToken:]` to update it.  It's not likely to be a volatile data object, but I like the idea of `+[MGLAccountManager setAccessToken:]` being the "ultimate source of access token truth at runtime".

**Comment by 1ec5** [comment]
`-[MGLMapView setAccessToken:]` has been around forever, but that was before we had any singletons like `MGLAccountManager`. In further defense of the Info.plist approach, note that the installation guide we have planned for beta 1 already has developers fiddle with settings in the project editor, so the UI won’t be foreign to them.

**Comment by bsudekum** [comment]
From a react-native point of view it would not be a deal breaker, but it would be :-1: to have to set the access token in the plist. One of the goals/advantages of react-native is to keep out of xcode.

**Comment by 1ec5** [comment]
OK, I’m definitely convinced that `+[MGLAccountManager setAccessToken:]` should stay (and be used by react-native-mapbox-gl, but I’m souring on `-[MGLMapView setAccessToken:]` with each passing day.

To clarify, the intent of this PR is not about keeping the access token private – it just happens to make that easier. Rather, the intent is to replace a tricky setup dance with something that looks more like plain-vanilla, all-UIKit development.

Currently, if you want to implement the Metrics switch inside your app, rather than in Settings, you need to call `+[MGLAccountManager setMapboxMetricsEnabledSettingShownInApp:]` before calling any other `MGLAccountManager` method, initializing any `MGLMapView` with an access token (whether programmatically or in a storyboard), or calling `-[MGLMapView setAccessToken:]`. The number of settings to set this way may even go up over time. It’s fine to expect developers to modify `-[UIApplicationDelegate application:didFinishLaunchingWithOptions:]`, but not to require an order that’s only enforced at runtime, with assertions that can’t really tell you what you did wrong.

**Comment by 1ec5** [comment]
Before merging this PR, I’m also going to create an `-[MGLMapView initWithFrame:styleURL:]` and deprecate or remove the initializers that take access tokens. That’ll simply things greatly in `MGLMapView`.

**Pull request merged**
