### PR TITLE
Added some basic macros to handle pending tests.

### PR DESCRIPTION
**Pull request by julianrex**
Added a macro that picks up the env var `MAPBOX_RUN_PENDING_TESTS`, so it looks like:
```
MGL_PENDING_TEST(testSelectingADisabledAnnotationView)
    ...test code...
}
```

Unfortunately, this doesn't give us nicely paired braces, but we could have two macros to enable this, a `MGL_PENDING_TEST_START` and `MGL_PENDING_TEST_END`. But that didn't seem necessary at this point.

If the environment variable isn't set, the test is also skipped.

### CODE REVIEW

**Comment by julianrex** [comment]
It might be worth moving `MGLTestUtility.h` into the Darwin hierarchy.

**Comment by friedbunny** [comment]
Hrm, this seems like a slightly convoluted way to ignore a test — can you say more about the benefits to this approach, versus using Xcode’s built-in ignore or doing the `PENDING` bit yourself?

If we do go this way, let’s add docs about how/why to use this.

**Comment by akitchen** [comment]
The lack of brace symmetry makes my eye twitch a bit. Not sure how others feel about it.

I feel I should defer to @friedbunny and others for a 👍 since it affects me less.

**Comment by julianrex** [comment]
Rebasing due to release-boba merge...

**Pull request merged**
