### PR TITLE
[android] Adding Bintray Gradle plugin for artifact publishing

### PR DESCRIPTION
**Pull request by langsmith**
Because of recent artifact publishing issues with Sonatype and CircleCI, this pr adds https://github.com/bintray/gradle-bintray-plugin so that we can publish Maps SDK for Android artifacts to Bintray. We can pass them on to Maven Central once in Bintray.

cc @mapbox/maps-android

### CODE REVIEW

**Comment by langsmith** [comment]
This pr is still a work in progress, but I think things are close to being done. I opened the pr for visibility

**Comment by langsmith** [comment]
Progress! After lots of tweaking, `bintrayUpload` finally successfully created https://bintray.com/mapbox/mapbox/mapbox-android-sdk . Not sure why https://bintray.com/mapbox/mapbox/mapbox-android-sdk#files is empty but at least we've moved forward on this. Yes, the `0.0.0` version _can_ be deleted 😄 

File issue seems to be related to the POM file setup:

screen shot 2019-03-04 at 6 05 35 pm

**Comment by langsmith** [comment]
Seems that the error mentioned above is one that many others have seen

https://github.com/bintray/gradle-bintray-plugin/issues/88

https://github.com/bintray/gradle-bintray-plugin/issues/81

**Comment by langsmith** [comment]
`MapboxGLAndroidSDK` seems to be used by the Gradle Bintray plugin and set as the `artifactId`, rather than the `artifactId` value of `mapbox-android-sdk` which I set at https://github.com/mapbox/mapbox-gl-native/pull/13999/files#diff-e8814550c6b8959b69ba7bdabdd97566R25

Despite that, latest commit was able to create the `aar` and `pom` files and their signed `.asc` version.

screen shot 2019-03-05 at 5 26 03 pm

The POM file goes to https://bintray.com/mapbox/mapbox/mapbox-android-sdk, however it's incomplete 😕 The POM generated by this branch is still missing some fields that the POM found at https://search.maven.org/artifact/com.mapbox.mapboxsdk/mapbox-android-sdk/7.2.0/aar has . Each dependency in the Bintray POM is missing the `scope` and `exclusion` fields, and I've yet to figure out why.  The Bintray POM is also missing opening fields such as `url`, `description`, and `developers`. I set that info in `gradle-bintray.gradle`, so I'm not sure why it's not carrying over. Remedy is in this comment/thread?: https://github.com/novoda/bintray-release/issues/19#issuecomment-99160153 ?

Bintray POM:
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.mapbox.mapboxsdk</groupId>
  <artifactId>MapboxGLAndroidSDK</artifactId>
  <version>7.3.0-SNAPSHOT</version>
  <packaging>aar</packaging>
  <dependencies>
    <dependency>
      <groupId>com.mapbox.mapboxsdk</groupId>
      <artifactId>mapbox-sdk-turf</artifactId>
      <version>4.3.0</version>
    </dependency>
    <dependency>
      <groupId>com.android.support</groupId>
      <artifactId>appcompat-v7</artifactId>
      <version>27.1.1</version>
    </dependency>
    <dependency>
      <groupId>com.android.support</groupId>
      <artifactId>support-annotations</artifactId>
      <version>27.1.1</version>
    </dependency>
    <dependency>
      <groupId>com.android.support</groupId>
      <artifactId>support-fragment</artifactId>
      <version>27.1.1</version>
    </dependency>
    <dependency>
      <groupId>com.squareup.okhttp3</groupId>
      <artifactId>okhttp</artifactId>
      <version>3.12.0</version>
    </dependency>
    <dependency>
      <groupId>com.getkeepsafe.relinker</groupId>
      <artifactId>relinker</artifactId>
      <version>1.3.1</version>
    </dependency>
    <dependency>
      <groupId>com.mapbox.mapboxsdk</groupId>
      <artifactId>mapbox-android-telemetry</artifactId>
      <version>4.2.0</version>
    </dependency>
    <dependency>
      <groupId>com.mapbox.mapboxsdk</groupId>
      <artifactId>mapbox-sdk-geojson</artifactId>
      <version>4.3.0</version>
    </dependency>
    <dependency>
      <groupId>com.mapbox.mapboxsdk</groupId>
      <artifactId>mapbox-android-gestures</artifactId>
      <version>0.4.0</version>
    </dependency>
  </dependencies>
</project>
``` 

**----Instructions if you'd like to try yourself------**

Switch to this branch, `cd` to this repo's root folder on the command line, and then run `make apackage` to create the artifact files. Add `BINTRAY_USER`, `BINTRAY_KEY`, and GPG passphrase and their respective values to your `gradle.properties` file (e.g. `BINTRAY_KEY=key`). Another option is to just hardcode them (_but don't commit/push them to Github!!!_) in the `user` and `key` fields at the top of the `bintray {}` section of the `gradle-bintray.gradle` file (e.g. `key = "key"`). You can set `passphrase` in the `gpg` section at the bottom of the `gradle-bintray.gradle` file. Once the artifact creation process is done and you've set the bintray user/key, run `make run-android-upload-to-bintray` on the command line.  You should see something similar to:

screen shot 2019-03-05 at 3 37 28 pm


Still need to figure out:
1. why the POM isn't being filled out with all of the various information, which I set in the `gradle-bintray.gradle` file
2. finishing figuring out how to upload the files that are part of a Maps SDK release (javadoc.jar, sources.jar, etc.) https://search.maven.org/artifact/com.mapbox.mapboxsdk/mapbox-android-sdk/7.2.0/aar 

screen shot 2019-03-05 at 3 54 44 pm

3.  why `MapboxGLAndroidSDK` is being filled into the POM file as `artifactId`. Related to https://github.com/bintray/gradle-bintray-plugin/issues/81#issuecomment-152763978?

**Comment by LukasPaczos** [comment]
Thanks for kicking this off @langsmith!

I've made some changes to resolve the `Still need to figure out` points. Key takeaways are:
- [`maven-publish` plugin](https://docs.gradle.org/current/userguide/publishing_maven.html) doesn't fill out `POM` files automatically, to tackle this, I've used [this Gradle plugin](https://github.com/wupdigital/android-maven-publish) which reduces the boilerplate of including the deps manually, however, the additional info like names and URLs still had to be added manually.
- Javadocs are generated as they were before and included in the artifact.
- Because of the improved `POM` file generation, we are actually going to ship dependencies with correct scopes (`runtime`/`compile`) and prevent leaks.

**Comment by LukasPaczos** [comment]
Since we are still waiting for the jCenter account to be opened in order to server `SNAPSHOT`s, https://github.com/mapbox/mapbox-gl-native/pull/13999/commits/7a09e80396f9cd97308999053abc6ba8881b21e8 disables those builds for now, so that we can ship the `alpha` build without delaying further.

**Pull request merged**
