### PR TITLE
[android] #4929 - rewrite MyLocationView

### LINKED ISSUE #4929: off-centered accuracy ring
Tilting the mapview while `myLocationEnabled` will result in the accuracy ring becoming off-centered around the user dot. 

screenshot_20160502-124843

cc: @tobrun

### PR DESCRIPTION
**Pull request by tobrun**
closes #4929 

Before we can merge this PR, I noticed I need to fix the following items:
 - [x] drawable API vs requiring calling them
 - [x] Foreground drawable with bearing tracking enabled
 - [x] MyLocationView becomes detached from world location when we receive a location update when tracking mode is not enabled.
 - [x] Integrate rotate in camera approach
 - [x] Setting tilt in xml doesn't apply tilt, orientation change doesn't restore tilt

### CODE REVIEW

**Comment by tobrun** [comment]
Before we can merge this PR, I noticed I need to fix the following items:
 - [ ] Foreground drawable with bearing tracking enabled
 - [ ] MyLocationView becomes detached from world location when we receive a location update when tracking mode is not enabled.
 - [ ] Auto zoom when enabling tracking mode (parity with iOS)

**Comment by bleege** [comment]
Is this ready to be merged?

**Comment by bleege** [comment]
I just tested this out and it looks good!  I'm going to merge it in.  Great job @tobrun!  👍 

device-2016-06-02-171828

**Comment by bleege** [comment]
Rebased and Merged!

screen shot 2016-06-02 at 5 22 07 pm

**Pull request closed without merging**
