### PR TITLE
tvOS map SDK and tvOS demo application

### PR DESCRIPTION
**Pull request by 1ec5**
This PR introduces a new tvOS-compatible flavor of the iOS map SDK. The goal is to minimize maintenance overhead, so that we can get tvOS support more or less “for free” in the course of supporting iOS. Unlike the macOS map SDK introduced in #3135, the tvOS map SDK is compiled from a strict subset of the iOS map SDK codebase and lives inside the same Xcode project generated by `make iproj`. Ultimately, the tvOS map SDK would be distributed as just another binary in an iOS map SDK release, alongside the dynamic and static builds.

Conditional compilation is used extensively to exclude incompatible features like user location tracking and and most gesture recognizers. Telemetry-related files are excluded outright from the target. The conditional compilation is particularly intrusive around the gesture recognition code in MGLMapView. I think MGLMapView remains more readable than, for instance, much of the MGLStyleValue code, but on the other hand my personal tolerance for conditional macros is relatively high.

tvosapp

The tvOS SDK isn’t ready for a debut, and we haven’t made any plans to officially support tvOS. This PR merely provides a convenient place to collect technical feedback. We’d need to address most of these caveats before we could even consider merging the PR:

* ~~The same ICU dependency that enables correctly rendered Arabic is available as an iOS static library. Using it as a tvOS or watchOS library anyways technically works, but Apple plans to remove support for this approach soon, so there are [lots of URGENT warnings](https://gist.github.com/1ec5/5139318b90febad4902c7da76f4a7436). Before this PR can land, we’d want Mason to produce a tvOS binary of ICU to avoid future breakage. Alternatively, maybe we could find a way to build the tvOS flavor of ICU from scratch, on demand, as part of `make iproj`.~~
* ~~CMake, which generates mbgl.xcodeproj, is [unable to place a single file reference in multiple targets](https://gitlab.kitware.com/cmake/cmake/issues/17805#note_384884) – https://github.com/mapbox/mapbox-gl-native/pull/5942#issuecomment-286497762 – so we have to compile mbgl-core as a single fat binary supporting both iOS and tvOS. This shouldn’t add to the iOS map SDK’s size, since unused symbols would get stripped away as part of the SDK build process.~~
* Due to the Apple Remote’s limited gesture support, it’s expected that most applications would rely on programmatic camera changes more than user gestures. However, it would be desirable to figure out how to implement the same pan and zoom menu that MapKit has implemented.
* ~~The attribution button does nothing when pressed.~~ MapKit puts a clickable Legal button inside the pan/zoom menu. We should do likewise, but there’s also enough horizontal real estate to display an unobtrusive copyright notice on-screen, similar to the macOS map SDK’s attribution view.

To do:

* [x] Sort out ICU build situation
* [ ] Implement menu with pan, zoom, and attribution buttons
* [ ] Implement zoom slider
* [ ] Add macOS-style attribution view
* [ ] Implement keyboard shortcuts (#7625)
* [x] Make tvosapp more compelling
* [x] Set up CircleCI for tvOS targets
* [ ] Add CocoaPods podspec
* [ ] Add tvOS-specific jazzy docset generator
* [ ] Update DEVELOPING.md

Prior art in #2340 and #2778.

/cc @friedbunny @kkaefer

### CODE REVIEW

**Comment by boundsj** [comment]
This is 😎 

I've been thinking lately about refactoring `MGLMapView` to make it more testable and less... long 😄. It'd be nice to address (or at least plan to address) some of that debt before this eventually gets merged. One improvement I can think of is that some of the map view behaviors could be captured in classes and the map view could be composed with subclasses of those behaviors depending on the platform it is compiled for which could reduce some of the conditionals and keep things more readable.

**Comment by 1ec5** [comment]
After rebasing 50c873efc7d39543c6cf82f8de2119a4f0a390a3 onto 64c75b442c4d387e4867757abf49462c561e5955 as fd132084d4a942877a75c6ddc3df1bc997d4badc, tvosapp no longer builds in Xcode 9:

```

Showing All Messages
Ld /Users/mxn/hub/mapbox-gl-native-2/build/ios/ios.build/Debug-iphonesimulator/tvosapp.build/Objects-normal/i386/tvosapp normal i386
    cd /Users/mxn/hub/mapbox-gl-native-2/platform/ios
    export IPHONEOS_DEPLOYMENT_TARGET=8.0
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch i386 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.0.sdk -L/Users/mxn/hub/mapbox-gl-native-2/build/ios/Debug-iphonesimulator -F/Users/mxn/hub/mapbox-gl-native-2/build/ios/Debug-iphonesimulator -filelist /Users/mxn/hub/mapbox-gl-native-2/build/ios/ios.build/Debug-iphonesimulator/tvosapp.build/Objects-normal/i386/tvosapp.LinkFileList -mios-simulator-version-min=8.0 -dead_strip -Xlinker -object_path_lto -Xlinker /Users/mxn/hub/mapbox-gl-native-2/build/ios/ios.build/Debug-iphonesimulator/tvosapp.build/Objects-normal/i386/tvosapp_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -Xlinker -objc_abi_version -Xlinker 2 -fobjc-arc -fobjc-link-runtime -Xlinker -sectcreate -Xlinker __TEXT -Xlinker __entitlements -Xlinker /Users/mxn/hub/mapbox-gl-native-2/build/ios/ios.build/Debug-iphonesimulator/tvosapp.build/tvosapp.app.xcent -framework Mapbox -Xlinker -dependency_info -Xlinker /Users/mxn/hub/mapbox-gl-native-2/build/ios/ios.build/Debug-iphonesimulator/tvosapp.build/Objects-normal/i386/tvosapp_dependency_info.dat -o /Users/mxn/hub/mapbox-gl-native-2/build/ios/ios.build/Debug-iphonesimulator/tvosapp.build/Objects-normal/i386/tvosapp

ld: warning: ignoring file /Users/mxn/hub/mapbox-gl-native-2/build/ios/Debug-iphonesimulator/Mapbox.framework/Mapbox, file was built for x86_64 which is not the architecture being linked (i386): /Users/mxn/hub/mapbox-gl-native-2/build/ios/Debug-iphonesimulator/Mapbox.framework/Mapbox
Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_MGLAccountManager", referenced from:
      objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)


Showing All Messages
CreateUniversalBinary /Users/mxn/hub/mapbox-gl-native-2/build/ios/Debug-iphonesimulator/tvosapp.app/tvosapp normal i386\ x86_64
    cd /Users/mxn/hub/mapbox-gl-native-2/platform/ios
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo -create /Users/mxn/hub/mapbox-gl-native-2/build/ios/ios.build/Debug-iphonesimulator/tvosapp.build/Objects-normal/i386/tvosapp /Users/mxn/hub/mapbox-gl-native-2/build/ios/ios.build/Debug-iphonesimulator/tvosapp.build/Objects-normal/x86_64/tvosapp -output /Users/mxn/hub/mapbox-gl-native-2/build/ios/Debug-iphonesimulator/tvosapp.app/tvosapp

fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: can't open input file: /Users/mxn/hub/mapbox-gl-native-2/build/ios/ios.build/Debug-iphonesimulator/tvosapp.build/Objects-normal/i386/tvosapp (No such file or directory)

CompileStoryboard tvosapp/Base.lproj/Main.storyboard
    cd /Users/mxn/hub/mapbox-gl-native-2/platform/ios
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    export XCODE_DEVELOPER_USR_PATH=/Applications/Xcode.app/Contents/Developer/usr/bin/..
    /Applications/Xcode.app/Contents/Developer/usr/bin/ibtool --errors --warnings --notices --module tvosapp --output-partial-info-plist /Users/mxn/hub/mapbox-gl-native-2/build/ios/ios.build/Debug-iphonesimulator/tvosapp.build/Main-SBPartialInfo.plist --auto-activate-custom-fonts --target-device iphone --target-device ipad --minimum-deployment-target 8.0 --output-format human-readable-text --compilation-directory /Users/mxn/hub/mapbox-gl-native-2/build/ios/ios.build/Debug-iphonesimulator/tvosapp.build/Base.lproj /Users/mxn/hub/mapbox-gl-native-2/platform/ios/tvosapp/Base.lproj/Main.storyboard

/* com.apple.ibtool.errors */
/Users/mxn/hub/mapbox-gl-native-2/platform/ios/tvosapp/Base.lproj/Main.storyboard: error: tvOS storyboards do not support target device type "iphone".

LinkStoryboards
    cd /Users/mxn/hub/mapbox-gl-native-2/platform/ios
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    export XCODE_DEVELOPER_USR_PATH=/Applications/Xcode.app/Contents/Developer/usr/bin/..
    /Applications/Xcode.app/Contents/Developer/usr/bin/ibtool --errors --warnings --notices --module tvosapp --target-device iphone --target-device ipad --minimum-deployment-target 8.0 --output-format human-readable-text --link /Users/mxn/hub/mapbox-gl-native-2/build/ios/Debug-iphonesimulator/tvosapp.app /Users/mxn/hub/mapbox-gl-native-2/build/ios/ios.build/Debug-iphonesimulator/tvosapp.build/Base.lproj/Main.storyboardc

/* com.apple.ibtool.warnings */
/Users/mxn/hub/mapbox-gl-native-2/build/ios/ios.build/Debug-iphonesimulator/tvosapp.build/Base.lproj/Main.storyboardc: warning: Unable to validate Storyboard References for Main.storyboard.
```

**Comment by 1ec5** [comment]
> CMake, which generates mbgl.xcodeproj, is unable to place a single file reference in multiple targets

As a workaround, we can have `make iproj` run a script that uses the [`xcodeproj`](https://rubygems.org/gems/xcodeproj/) gem to duplicate the mbgl-core target. It would run after CMake generates the mbgl-core target but before the `make` rule opens the workspace. There’s also a [node-xcode](https://github.com/apache/cordova-node-xcode/) npm package, which would be more compatible with our existing build system, but `xcodeproj` is the more established tool and it appears to support manipulating an Xcode project the way we’d need to.

**Comment by 1ec5** [comment]
> The same ICU dependency that enables correctly rendered Arabic is available as an iOS static library. Using it as a tvOS or watchOS library anyways technically works, but Apple plans to remove support for this approach soon, so there are [lots of URGENT warnings](https://gist.github.com/1ec5/5139318b90febad4902c7da76f4a7436).

This is just a warning when building for the simulator, but it’s a link error building for a device:

```
ld: in /Users/mxn/hub/mapbox-gl-native-2/mason_packages/ios-8.0/icu/58.1-min-size/lib/libicuuc.a(utypes.ao), building for tvOS, but linking in object file built for iOS, for architecture arm64
```

**Comment by 1ec5** [comment]
>> CMake, which generates mbgl.xcodeproj, is [unable to place a single file reference in multiple targets](https://gitlab.kitware.com/cmake/cmake/issues/17805#note_384884)
> 
> As a workaround, we can have `make iproj` run a script that uses the [`xcodeproj`](https://rubygems.org/gems/xcodeproj/) gem to duplicate the mbgl-core target. It would run after CMake generates the mbgl-core target but before the `make` rule opens the workspace.

[This gist](https://gist.github.com/ratazzi/f6d9217654d6605450a0) apparently duplicates a target similar to the Duplicate command in Xcode.

**Comment by 1ec5** [comment]
The link errors have been fixed, thanks to libicu being built from source. No changes are needed in Mason going forward.

Panning works fine. There isn’t currently a way for the user to zoom in or out using gestures, but pressing ⏯ starts the same world tour sequence seen in iosapp and macosapp following #12858.

world tour

Holding down on the ℹ️ brings up this menu. None of the links do anything, because there isn’t a Web browser to open the links in.

info

**Comment by 1ec5** [comment]
#12857 was marked as a semver-major change. While it doesn’t technically block this PR, it would be desirable to land it before this PR, to reduce the amount of conditional compilation. (Between the three Objective-C/Swift platforms, iOS ends up being the odd one out for the `com.mapbox.sdk.ios` bundle identifier.)

**Comment by 1ec5** [comment]
> MapKit puts a clickable Legal button inside the pan/zoom menu. We should do likewise, but there’s also enough horizontal real estate to display an unobtrusive copyright notice on-screen, similar to the macOS map SDK’s attribution view.

I’m thinking we could show the attribution on-screen on both iOS and tvOS if the map view is wide enough, similar to how GL JS switches between an ℹ️ button and inline attribution based on the map’s width. To avoid surprising existing users of the iOS map SDK, we could set the threshold to the width of an iPad screen in landscape.

**Comment by 1ec5** [comment]
Getting this build failure on CI but not locally:

```
▸ Compiling UIImage+MGLAdditions.mm

❌  /Users/distiller/project/platform/ios/src/UIImage+MGLAdditions.h:3:10: 'mbgl/style/image.hpp' file not found

#include <mbgl/style/image.hpp>
         ^~~~~~~~~~~~~~~~~~~~~~
```

**Comment by 1ec5** [comment]
The RelWithDebInfo configuration had been created but not configured to match the Release configuration. RelWithDebInfo is now configured properly.

**Comment by 1ec5** [comment]
Oh no, not after all this tvOS quest has been through.

**Comment by tmpsantos** [comment]
No longer relevant.

**Comment by nvolpe** [comment]
Hello there. I was hopeful to bring these changes to a fork of mine to create a tvOS build. After looking a little closer at the build steps, I am guessing that will not be possible? The mapbox native core framework is built internally and likely not built for tvOS. Therefore I am guessing it will not allow me to add it to a tvOS project. Is that correct? If it is possible I would be interested in contributing support for tvOS. Thanks.

**Pull request closed without merging**
