### PR TITLE
Configure OS X

### PR DESCRIPTION
**Pull request by mikemorris**
Break out a separate `configure` profile for OS X builds to skip unnecessarily linking `libcurl` and `nunicode`.

### CODE REVIEW

**Comment by mikemorris** [comment]
Looks like `gcc` on Linux is having some trouble linking `libcurl`, I probably missed something.

**Comment by ljbade** [comment]
@mikemorris what do you mean by the last comment?

**Comment by mikemorris** [comment]
Ah, was referencing the Travis build `gcc` build failure @ljbade, gonna try looking into this today.

**Comment by mikemorris** [comment]
Okay so for some reason `libcurl.a` is still looking for symbols from `openssl.o` at compile time - any ideas @springmeyer?

**Comment by mikemorris** [comment]
Well adding `curl_ldflags` in the [merge static libs action](https://github.com/mapbox/mapbox-gl-native/blob/master/gyp/mbgl-core.gypi#L87) didn't work, adding it in the `mbgl-standalone` [`ldflags`](https://github.com/mapbox/mapbox-gl-native/blob/master/gyp/mbgl-core.gypi#L70) didn't fix anything, and it looks like the [`mbgl-core`](https://github.com/mapbox/mapbox-gl-native/blob/master/gyp/mbgl-core.gypi#L3-L48) target doesn't supply any `ldflags` currently?

**Comment by mikemorris** [comment]
Scrapping this approach as it would prevent running `make linux` on OS X, waiting on https://github.com/mapbox/mapbox-gl-native/pull/754 instead.

**Comment by ljbade** [comment]
@mikemorris, you are linking both libssl and libcrypto right?

**Pull request closed without merging**
