### PR TITLE
Make redoPlacement faster

### PR DESCRIPTION
**Pull request by jfirebaugh**
With https://github.com/mapbox/mapbox-gl-native/commit/bafbf6c04b1bfd5da84411f52a72e26783f3bcb7, label placement is very slow. Label placement occurs when the map is rotated or tilted (but not on zoom or pan). It's slow because we're creating a copy of the StyleLayer* objects on essentially every frame when rotating.

/cc @jfirebaugh

### CODE REVIEW

**Comment by jfirebaugh** [comment]
:eyes: @kkaefer

**Comment by kkaefer** [comment]
Looks great!

Something that is out of scope for this patch: Now that `StyleLayer` isn't noncopyable anymore, we can make it movable and remove the indirection introduced by wrapping it in `std::unique_ptr`

**Comment by jfirebaugh** [comment]
`StyleLayer` is an abstract base class, so there still needs to be a type-erasing wrapper somewhere. I think `std::unique_ptr` is as good as any.

**Comment by kkaefer** [comment]
Ah, alright. :+1:

**Pull request merged**
