### PR TITLE
Introduce visible annotations API

### LINKED ISSUE #5467: Accessor for visible annotation views in the viewport
After MGLAnnotationView was introduced, it became possible to implement advanced presentations for annotations in the map. One of the possibilities is to adjust transparency of some layers in multilayered image depending on the zoom level (which is important feature for Stay.com).
At the same time to achieve such effect client needs to re-add the same annotations on every event that may trigger the need to refresh the UI (pan/zoom).

Please consider adding the following methods:
```
-[MGLMapView visibleAnnotationViewsInBounds:]
```
or
```
-[MGLMapView reloadAnnotationsinBounds:]
```
The first one is more preferable as it will not require the client to reallocate MGLAnnotationView

### PR DESCRIPTION
**Pull request by boundsj**
This adds an API for getting all annotations that are currently visible on the map. We can also add an additional API to query by a specific rect. That API can be used internally to power this one.

This also adds a new option to iosapp to test the feature. 

Fixes #5467

### CODE REVIEW

**Comment by 1ec5** [comment]
MGLMapView's accessibility hint also says the number of visible annotations. It currently does so using a different API. Maybe it should be migrated over to this API? Not sure.

**Comment by boundsj** [comment]
Since `-[MGLMapView accessibilityAnnotationCount]` just goes after the count, it may be better to just leave it as is instead of using the new `visibleAnnotations` method that creates, populates, and returns an NSArray of annotations.

**Comment by boundsj** [comment]
I rebased to include #6627 and this is a lot closer. The visible annotations query result works as expected except when the map is tilted. In that case, annotations are still returned as visible even when they are slightly offscreen. This does work now for all other cases (i.e. not tilted, with or without rotation)

**Comment by boundsj** [comment]
Resuming this since https://github.com/mapbox/mapbox-gl-native/issues/6055 is fixed.

**Pull request merged**
