### PR TITLE
Separate rendering part from specification part for sources

### PR DESCRIPTION
**Pull request by jfirebaugh**
Refs #8797, #8820

### CODE REVIEW

**Comment by jfirebaugh** [comment]
`[MGLSourceQueryTests testQueryShapeSource]` is failing intermittently; not sure why yet.

**Comment by jfirebaugh** [comment]
@1ec5 Can you see why this test might be failing on CI? There's no diagnostics in the CI log, and I've run it many times locally without failure.

**Comment by ivovandongen** [comment]
@frederoni Had a look and noticed that there seems to be a problem on the CI writing the crash log:

```
017-04-26 10:17:08.163 xcodebuild[2469:12542]  IDETestOperationsObserverDebug: (77500389-E03C-4473-8AE1-9920DBB4E704) OS X: Failure requesting crash reports in /Users/vagrant/Library/Logs/DiagnosticReports: Error Domain=com.apple.dt.Xcode.IDETesting.OSXCrashReportObserverError Code=1 "No file exists at /Users/vagrant/Library/Logs/DiagnosticReports" UserInfo={NSLocalizedDescription=No file exists at /Users/vagrant/Library/Logs/DiagnosticReports}
Failing tests:
    -[MGLSourceQueryTests testQueryShapeSource]
    -[MGLSourceQueryTests testQueryVectorSource]
```

No idea yet what the issue is. However, since both tests are failing, it might be in the setup. Maybe reading the json file? Going to add some logging to debug.

**Comment by jfirebaugh** [comment]
@frederoni reproduced this locally, with the following output: 

```
Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
terminating with uncaught exception of type std::__1::bad_function_call: std::exception
abort() called

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fffd81f7d42 __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fffd82e55bf pthread_kill + 90
2   libsystem_c.dylib             	0x00007fffd815d420 abort + 129
3   libc++abi.dylib               	0x00007fffd6cb384a abort_message + 266
4   libc++abi.dylib               	0x00007fffd6cd8c37 default_terminate_handler() + 243
5   libobjc.A.dylib               	0x00007fffd77e6713 _objc_terminate() + 124
6   libc++abi.dylib               	0x00007fffd6cd5d69 std::__terminate(void (*)()) + 8
7   libc++abi.dylib               	0x00007fffd6cd59f2 __cxa_rethrow + 99
8   libobjc.A.dylib               	0x00007fffd77e494a objc_exception_rethrow + 40
9   com.apple.dt.XCTest           	0x0000000102fbb1f0 -[XCTWaiter waitForExpectations:timeout:enforceOrder:] + 1082
10  com.apple.dt.XCTest           	0x0000000102fbd1b4 +[XCTWaiter waitForExpectations:timeout:enforceOrder:] + 90
11  com.apple.dt.XCTest           	0x0000000102fd4afc -[XCTTestRunSession runTestsAndReturnError:] + 555
12  com.apple.dt.XCTest           	0x0000000102f6caaa -[XCTestDriver runTestsAndReturnError:] + 254
13  com.apple.dt.XCTest           	0x0000000102fc42bd _XCTestMain + 773
14  xctest                        	0x0000000102f5f48d 0x102f5e000 + 5261
15  libdyld.dylib                 	0x00007fffd80c9235 start + 1
```

**Comment by jfirebaugh** [comment]
I figured out the test failures -- they were caused by the middle commit ("Load source TileJSON immediately"). The tests relied on source TileJSON _not_ being loaded, because they supplied a fake access token. In addition, they were testing a situation that that change eliminates. So I rewrote them to test querying a detached source instead.

**Pull request merged**
