### PR TITLE
4800 default locationview from start

### LINKED ISSUE #4800: Default UserlocationView is shown at start
Currently the default UserLocationView is instantly shown when we enable the user location through xml attributes. We should wait with showing it until the configuration of UserLocationView has finished initialising (drawable, tinting).

### PR DESCRIPTION
**Pull request by tobrun**
Closes #4800

### CODE REVIEW

**Comment by tobrun** [comment]
CI approved, going to rebase and merge

**Comment by tobrun** [comment]
Going to test one thing related to background offsets before merging

**Comment by tobrun** [comment]
Background offsets are back!

screen shot 2016-04-26 at 20 53 12

**Comment by tobrun** [comment]
This time CI approved and we are actually going to rebase/merge!
cc @bleege

**Comment by bleege** [comment]
\o/

**Pull request merged**
