### PR TITLE
Update Traditional Chinese localization

### PR DESCRIPTION
**Pull request by 1ec5**
Updated the Traditional Chinese translation of Mapbox Telemetry strings in the iOS SDK’s provided Settings bundle based on Transifex.

/cc @lily-chai @friedbunny

### CODE REVIEW

**Comment by friedbunny** [comment]
If there’s not going to be another iOS release on this branch, probably this should be targeted against `master`?

**Comment by 1ec5** [comment]
Yes, I'm going to do that once we merge the release branch to master. I'm just parking the PR here for now to avoid having to resolve conflicts later.

**Comment by 1ec5** [comment]
Rebased and retargeted onto master.

**Comment by friedbunny** [comment]
Hrm, [Qt5 on Bitrise](https://www.bitrise.io/build/759435424e90dcfe) got killed after 90 minutes and won’t load logs... 🤔

**Pull request merged**
