### PR TITLE
(Android) Crash when try to close map when it is displayed in black and no tiles

### PR DESCRIPTION
**Pull request by tmpsantos**
Map is being displayed in a dialog. MapBox crashes when map is displayed in black and no tiles.

> 	03-03 13:03:56.492 E/Surface: getSlotFromBufferLocked: unknown buffer: 0xb9c49b90
> 	03-03 13:03:56.521 E/Surface: getSlotFromBufferLocked: unknown buffer: 0xb9776348
> 	03-03 13:03:56.522 D/OpenGLRenderer: endAllActiveAnimators on 0xb9c2d428 (RippleDrawable) with handle 0xb958b570
> 	03-03 13:03:56.593 I/mbgl: {Map}[Android]: Not activating as we are not ready
> 	03-03 13:03:56.596 E/libEGL: call to OpenGL ES API with no current context (logged once per thread)
> 	03-03 13:03:56.607 I/mbgl: {Map}[Android]: Not deactivating as we are not ready
> 	03-03 13:03:56.658 W/com.mapbox.mapboxsdk.http.HTTPContext$HTTPRequest: [HTTP] Request could not be executed: Socket closed
> 	03-03 13:03:56.666 A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 17548 (HTTPAndroidCont)

Another variation of error message displayed.

> 	03-03 13:09:09.419 E/Surface: getSlotFromBufferLocked: unknown buffer: 0xb930d810
> 	03-03 13:09:09.479 E/Surface: getSlotFromBufferLocked: unknown buffer: 0xb930dc28
> 	03-03 13:09:09.573 I/mbgl: {Map}[Android]: Not activating as we are not ready
> 	03-03 13:09:09.593 E/libEGL: call to OpenGL ES API with no current context (logged once per thread)
> 	03-03 13:09:09.603 I/mbgl: {Map}[Android]: Not deactivating as we are not ready
> 	03-03 13:09:09.672 A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 23140 (HTTPAndroidCont)

This does not get displayed that often:

> 03-03 13:03:56.658 W/com.mapbox.mapboxsdk.http.HTTPContext$HTTPRequest: [HTTP] Request could not be executed: Socket closed

### CODE REVIEW

**Comment by tmpsantos** [comment]
:eyes: @tobrun @bleege

**Comment by tobrun** [comment]
@tmpsantos great stuff, as promised ->  :bow:

**Comment by jfirebaugh** [comment]
@tmpsantos Can you rebase this on master post-#4193, using jni.hpp stuff? Thanks!

**Comment by tobrun** [comment]
@tmpsantos requested extra :eyes: on this. Going to test on a real device (he only tested with emulator)

**Comment by tobrun** [comment]
@tmpsantos 

I did a test with master and that produced:
```java
3-07 17:59:40.367 2770-3163/? A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 3163 (Thread-7546)
03-07 17:59:40.469 201-201/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
03-07 17:59:40.469 201-201/? A/DEBUG: Build fingerprint: 'google/hammerhead/hammerhead:6.0/MPA44I/2172151:user/release-keys'
03-07 17:59:40.469 201-201/? A/DEBUG: Revision: '0'
03-07 17:59:40.469 201-201/? A/DEBUG: ABI: 'arm'
03-07 17:59:40.469 201-201/? A/DEBUG: pid: 2770, tid: 3163, name: Thread-7546  >>> com.mapbox.mapboxsdk.testapp <<<
03-07 17:59:40.469 201-201/? A/DEBUG: signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
03-07 17:59:40.504 201-201/? A/DEBUG:     r0 00000000  r1 00000c5b  r2 00000006  r3 9becd978
03-07 17:59:40.504 201-201/? A/DEBUG:     r4 9becd980  r5 9becd930  r6 00000000  r7 0000010c
03-07 17:59:40.504 201-201/? A/DEBUG:     r8 9a82b668  r9 914261c0  sl fffff484  fp 9becd3c0
03-07 17:59:40.504 201-201/? A/DEBUG:     ip 00000006  sp 9becd360  lr b6cbbaf1  pc b6cbde54  cpsr 400d0010
03-07 17:59:40.519 201-201/? A/DEBUG: backtrace:
03-07 17:59:40.519 201-201/? A/DEBUG:     #00 pc 00041e54  /system/lib/libc.so (tgkill+12)
03-07 17:59:40.519 201-201/? A/DEBUG:     #01 pc 0003faed  /system/lib/libc.so (pthread_kill+32)
03-07 17:59:40.520 201-201/? A/DEBUG:     #02 pc 0001c30f  /system/lib/libc.so (raise+10)
03-07 17:59:40.520 201-201/? A/DEBUG:     #03 pc 000194c1  /system/lib/libc.so (__libc_android_abort+34)
03-07 17:59:40.520 201-201/? A/DEBUG:     #04 pc 000174ac  /system/lib/libc.so (abort+4)
03-07 17:59:40.520 201-201/? A/DEBUG:     #05 pc 003f8970  /data/app/com.mapbox.mapboxsdk.testapp-2/lib/arm/libmapbox-gl.so
03-07 17:59:40.520 201-201/? A/DEBUG:     #06 pc 003f8aa0  /data/app/com.mapbox.mapboxsdk.testapp-2/lib/arm/libmapbox-gl.so
03-07 17:59:40.520 201-201/? A/DEBUG:     #07 pc 003e90f8  /data/app/com.mapbox.mapboxsdk.testapp-2/lib/arm/libmapbox-gl.so
03-07 17:59:40.520 201-201/? A/DEBUG:     #08 pc 003e91e4  /data/app/com.mapbox.mapboxsdk.testapp-2/lib/arm/libmapbox-gl.so (std::terminate()+136)
03-07 17:59:40.520 201-201/? A/DEBUG:     #09 pc 000e48e8  /data/app/com.mapbox.mapboxsdk.testapp-2/lib/arm/libmapbox-gl.so
03-07 17:59:40.620 3197-3197/? E/STIB mobile - UALib: In-App Purchase is enabled, but missing com.android.vending.billing.IMarketBillingService. Disabling...
03-07 17:59:40.620 3197-3197/? E/STIB mobile - UALib: If using Proguard, add the following lines to your proguard.cfg:
03-07 17:59:40.620 3197-3197/? E/STIB mobile - UALib: 	-keep class com.android.vending.billing.**
```

I did a test with this branch and was able to produce:
```java
03-07 18:06:14.406 4569-4611/? D/com.mapbox.mapboxsdk.http.HTTPRequest: [HTTP] Request with response code = 304: Not Modified
03-07 18:06:14.506 201-201/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
03-07 18:06:14.506 201-201/? A/DEBUG: Build fingerprint: 'google/hammerhead/hammerhead:6.0/MPA44I/2172151:user/release-keys'
03-07 18:06:14.506 201-201/? A/DEBUG: Revision: '0'
03-07 18:06:14.506 201-201/? A/DEBUG: ABI: 'arm'
03-07 18:06:14.507 201-201/? A/DEBUG: pid: 4569, tid: 4676, name: Thread-7572  >>> com.mapbox.mapboxsdk.testapp <<<
03-07 18:06:14.507 201-201/? A/DEBUG: signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
03-07 18:06:14.521 201-201/? A/DEBUG:     r0 00000000  r1 00001244  r2 00000006  r3 99ac3978
03-07 18:06:14.521 201-201/? A/DEBUG:     r4 99ac3980  r5 99ac3930  r6 00000000  r7 0000010c
03-07 18:06:14.521 201-201/? A/DEBUG:     r8 980def28  r9 9a9e5aa0  sl fffff484  fp 99ac33c8
03-07 18:06:14.521 201-201/? A/DEBUG:     ip 00000006  sp 99ac3368  lr b6cbbaf1  pc b6cbde54  cpsr 400b0010
03-07 18:06:14.532 201-201/? A/DEBUG: backtrace:
03-07 18:06:14.532 201-201/? A/DEBUG:     #00 pc 00041e54  /system/lib/libc.so (tgkill+12)
03-07 18:06:14.532 201-201/? A/DEBUG:     #01 pc 0003faed  /system/lib/libc.so (pthread_kill+32)
03-07 18:06:14.532 201-201/? A/DEBUG:     #02 pc 0001c30f  /system/lib/libc.so (raise+10)
03-07 18:06:14.533 201-201/? A/DEBUG:     #03 pc 000194c1  /system/lib/libc.so (__libc_android_abort+34)
03-07 18:06:14.533 201-201/? A/DEBUG:     #04 pc 000174ac  /system/lib/libc.so (abort+4)
03-07 18:06:14.533 201-201/? A/DEBUG:     #05 pc 003f1740  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
03-07 18:06:14.533 201-201/? A/DEBUG:     #06 pc 003f1870  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
03-07 18:06:14.533 201-201/? A/DEBUG:     #07 pc 003e1ec8  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
03-07 18:06:14.533 201-201/? A/DEBUG:     #08 pc 003e1fb4  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so (std::terminate()+136)
03-07 18:06:14.533 201-201/? A/DEBUG:     #09 pc 000e448c  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
03-07 18:06:15.326 201-201/? A/DEBUG: Tombstone written to: /data/tombstones/tombstone_09
03-07 18:06:15.326 201-201/? E/DEBUG: AM write failed: Broken pipe
```

Looking a the crash itself, it seems it's different than before.. for example it doesn't contain HttpContext.

**Comment by tmpsantos** [comment]
Thanks for testing, found a race condition. Patch updated.

**Comment by tobrun** [comment]
Until now unable to produce a crash with the typical open activity and quickly closing it :+1:

**Comment by bleege** [comment]
:+1: @tobrun @tmpsantos

**Pull request merged**
