### PR TITLE
[android] #6083 - add circle example

### PR DESCRIPTION
**Pull request by tobrun**
Refs #6083,
add circle example
Review @ivovandongen

### CODE REVIEW

**Comment by tobrun** [comment]
In this PR i'm adding a new feature activity to the test application. This activity is automatically picked up by our auto sanity test generation tool and now fails in firebase test lab with the following exception:

screen shot 2016-08-19 at 13 12 59

This happens since the sanity test will wait for `OnMapReadyCallback` to be called. This is validated by the test by checking if `mapboxMap` instance in your Activity is filled up. In this PR I didn't add an `mapboxMap` class member to CircleLayer. After adding that the test will pass.

cc @mapbox/android

**Comment by ivovandongen** [comment]
LGTM. Little documentation on the Activity class wouldn't be out of place though: https://github.com/mapbox/mapbox-gl-native/blob/0d92f7224ec78ff4f0c4af668412f0f27cea160b/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/CircleLayerActivity.java#L31

**Comment by zugaldia** [comment]
This is the new activity, looking good @tobrun :

video

**Comment by ivovandongen** [comment]
@tobrun Thanks for adding the documentation!

**Comment by tobrun** [comment]
cc @mapbox/android

**Pull request merged**
