### PR TITLE
Layer::getPaintProperty() -> Layer::getProperty()

### PR DESCRIPTION
**Pull request by pozdnyakov**

### CODE REVIEW

**Comment by pozdnyakov** [comment]
@astojilj The goal is to have `getProperty` and `setProperty`, the following changes are on the way

**Comment by astojilj** [comment]
> @astojilj The goal is to have `getProperty` and `setProperty`, the following changes are on the way

I understand that there would be no get/set LayoutProperty.

Will JS side get similar change, too?

**Comment by pozdnyakov** [comment]
> Will JS side get similar change, too?

I'd vote for it

**Comment by kkaefer** [comment]
Could you please provide a reasoning for this change?

**Pull request merged**
