### PR TITLE
Remove unused OffscreenTexture

### PR DESCRIPTION
**Pull request by kkaefer**
This got obsoleted a while ago when we introduced `OffscreenView`.

### CODE REVIEW

**Comment by kkaefer** [comment]
This is preparation for #8148

**Comment by jfirebaugh** [comment]
@lbud Are you using `OffscreenTexture` for any of the extrusions work?

**Comment by lbud** [comment]
😬 yes, for now, although it's not totally working and I'm not sure why yet — @kkaefer can we pair this week so I can get your thoughts on this?

**Comment by kkaefer** [comment]
Ok, then I'll transform this into a privatization rather than a removal. @lbud totally, lmk when you have time.

**Comment by mollymerp** [comment]
@kkaefer your terrain branch uses `OffscreenTexture` as well 😊  are you planning to refactor that to use `OffscreenTexture`?

**Comment by kkaefer** [comment]
haha, good call

**Comment by kkaefer** [comment]
Closing in favor of #8214

**Pull request closed without merging**
