### PR TITLE
Moved MGLAltitudeForZoomLevel and MGLZoomLevelForAltitude to public API

### LINKED ISSUE #5583: Public API to convert between zoom levels and altitudes
Internally, the iOS and macOS SDKs use `MGLAltitudeForZoomLevel()` to convert from a zoom level to an altitude given the map view’s current state. This functionality would be useful for developers who want to animate to a given zoom level and pitch or perform other zoom-level-dependent calculations.

Not sure whether `MGLAltitudeForZoomLevel()` is the best API to expose publicly or whether we should design a wrapper around it in MGLMapCamera.

/cc @dapetcu21

### PR DESCRIPTION
**Pull request by d-prukop**
Fixes #5583 

/cc @1ec5 @friedbunny @fabian-guerra

### CODE REVIEW

**Comment by julianrex** [comment]
These don't require an `MGLMapCamera` thought right? If they need some kind of namespace (which I don't think they do), we could consider class methods.

**Comment by d-prukop** [comment]
I think this is OK outside of MGLMapCamera. As @julianrex said, it doesn't require MGLMapCamera and MGLMapCamera doesn't use or need zoom level.
With these methods public I can abandon using the private property `isAltitudeAffectedByPitch` from #12938.
The way I'm using this is to get the altitude I need to frame the route line from `MGLMapView cameraThatFitsShape` then I can adjust this camera as needed and set it on the mapView. The problem is that this still exhibits the issue from the 'before' animation on that ticket. The way I'm solving this is to immediately set the zoomLevel property on the mapView right after `setCamera`
Since there is no direct property for altitude on the mapView, I need to convert the altitude to a zoomLevel.
I also have switched my code over to using zoom levels since this will make it easier to control the visuals with regards to the map style.

/cc @fabian-guerra @1ec5 @julianrex

**Comment by fabian-guerra** [comment]
I may be wrong by saying `MGLMapCamera`. What I am trying to say is if we can instead of providing 'raw' functions what about a "camera object/manager/controller" where we can set the distance/animation curves/etc to gain finer control of the camera (or perhaps both). As I understand the reason behind moving this into the public is mainly to help in the camera animations.

I am OK with this being public but was considering if we can provide an api with finer control instead.

**Comment by d-prukop** [comment]
@fabian-guerra 100% agree that we need that. This is baby steps... and we need this soon.

**Pull request merged**
