### PR TITLE
[android] Fixed x86_64 crash on startup

### PR DESCRIPTION
**Pull request by Malinskiy**
chrono's second is not an int64_t on x86_x64 and there is only a template for int64_t for bind and get.

Seems to start the demo app and work on x86_64 emulator

### CODE REVIEW

**Comment by tobrun** [comment]
This looks great, will review this soon.

**Comment by tmpsantos** [comment]
I'm curious of what is the datatype. The standard seems to mandate "_A signed integral type of at least 35 bits_" [1]. The method in theory should handle both `int` and `int64_t` (aka `long` on x86_64).

[1] http://www.cplusplus.com/reference/chrono/seconds/

**Comment by tmpsantos** [comment]
And `int` should be non-compliant as it is 32-bits long on x86_64.

**Comment by Malinskiy** [comment]
If you know what type has Ix name in symbol - that's your answer (_ZN6mapbox6sqlite9Statement3get**Ix**EET_i). And chrono8duration**Ix** is the issue judging from the symbol table.

ps. Android may invented a new signed integer type, hehe

**Comment by tmpsantos** [comment]
```
$ c++filt _ZN6mapbox6sqlite9Statement3getIxEET_i
long long mapbox::sqlite::Statement::get<long long>(int)
```

**Comment by tobrun** [comment]
@Malinskiy 
I wanted to test out this PR and see if it solves your issue on running on a x86-64bit emulator.

Before testing I tried reproducing your issue:
- building the library against x86 using:
 
   > make android-lib-x86

- create a x86 emulator:

  screen shot 2016-01-12 at 13 08 38
 
- run testapp:
  
   screen shot 2016-01-12 at 13 07 28

@Malinskiy:
As seen in the screenshot, I'm able to run without any issue and unable to reproduce your problem. Could add some information how I can reproduce your issue?

**Comment by Malinskiy** [comment]
@tobrun The problem with current stable release is the assumption that I don't use any external libraries. Right now my crash is happening because of another library that provides specific build for x86_64 and their x86 version crashes on x86_64 ABI.

I can't force Android to use x86 version if there are any x86_64 libs already in the jni libs. So there are two solutions in my case:
1. Strip the libs (that will cause the other lib to crash on startup on x86_64 since they advise specifically to use the x86_64 jni lib)
2. Build mapbox for x86_64 so that I don't have to strip libs and the other library will start correctly

**Comment by tobrun** [comment]
@Malinskiy thank you for clarifying. 
Pinging @bleege and @zugaldia for exta :eyes: .

**Comment by bleege** [comment]
Thanks for looking into this @Malinskiy.  You're absolutely correct about [the external libraries issue](https://github.com/mapbox/mapbox-gl-native/pull/3460#issuecomment-170894542).  For some background on this, we've gotten similar reports (arm64 in this case) of this ( #3128 ) but have left things as is due to it being [Google's statement on Android only needing 32 bit](http://developer.android.com/training/articles/perf-jni.html#64_bit).  That said [we also said that if someone could address this we'd be happy to consider adding support](https://github.com/mapbox/mapbox-gl-native/issues/3128#issuecomment-164473522).  It looks like that time is now.  :smiley: 

Here's how we'll go about doing that:

1. Have a more experienced C++ developer sign off on using `int64_t`.  /cc @tmpsantos @kkaefer @jfirebaugh 
1. Build `x86` only version of TestApp and run on 32bit Android device
1. Build `x86_64` only version of TestApp and run on 64bit Android device

If everything passes as expected we should also test this fix for `arm64` as well.

**NOTE:** This will noticeably increase the size of the Mapbox `.aar` file as compiled ABIs are between 5 MB and 6 MB in size.

screen shot 2016-01-12 at 9 37 46 am
_Current SNAPSHOT ABI File Sizes_

**Comment by Malinskiy** [comment]
@bleege ok, gotcha.
arm64-v8a only build still crashes on startup on samsung device for me. I believe it was SIGILL in the native stacktrace.
With regards to increasing the aar size - more and more developers are using [splits by apk](http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits) when they have native packages, so the issue of increasing the apk size can be addressed.

**Comment by bleege** [comment]
@kkaefer was able to review the code just now and is on board with it (see statement below for details).

> using `int64_t` in those places is good; we’re not going to change the internal representation `std::chrono` uses, but rather force the use of overloads where we actually need them

**Comment by bleege** [comment]
@Malinskiy I just merged your fixes in for `x86_64` support and it should be in the next `3.1.0-SNAPSHOT` (currently running through CI and should be available in about 30 minutes or so).  Thank you so much for working on this and contributing to the project!  :+1: 

**NOTE**
_This only affects `x86` and NOT `arm` ABI._

`arm` will still only provide 32 bit ABI in the Mapbox Android `.aar`.  As demonstrated with this PR and as [said previously](https://github.com/mapbox/mapbox-gl-native/issues/3128#issuecomment-164473522) we happily accept PRs so if `arm` 64 bit ABI is desired please feel free to submit a PR.  Otherwise we'll continue to follow [Google's recommendation on 32 bit support](http://developer.android.com/training/articles/perf-jni.html#64_bit) for `arm`.

**Pull request merged**
