### PR TITLE
[android] - only pin certificates on current used environement.

### PR DESCRIPTION
**Pull request by tobrun**
Resolves first todo for #5797. Other open todo is:
- [x] updating the sha256 of the staging certificate.

Review @zugaldia

### CODE REVIEW

**Comment by zugaldia** [comment]
@tobrun Looking good, I'll do final 👀 when we the `sha256` updated too.

**Comment by zugaldia** [comment]
Per chat with @mick , we need to follow the process in https://square.github.io/okhttp/3.x/okhttp/okhttp3/CertificatePinner.html in order to generate the new `sha256` values.

**Comment by tobrun** [comment]
@zugaldia everything reuired is now included, ready for review!

**Comment by zugaldia** [comment]
I relaunched Travis which had failed, it's passing now.

**Pull request merged**
