### PR TITLE
Update telemetry location manager to allow background location updates when required.

### PR DESCRIPTION
**Pull request by boundsj**
In iOS 9, it is now required to set the value of `allowsBackgroundLocationUpdates` on CLLocationManager to YES (in addition to previous requirements) to achieve location updates in the background. 

The Mapbox gl native telemetry location manager runs in the background to gather data for telemetry events for improving open map data. This PR updates that location manager to be compatible with iOS 9 for the applicable use cases. Bugs related to gaps in telemetry event data from devices running iOS 9 can probably be closed after we test this change.

cc @1ec5 @friedbunny

### CODE REVIEW

**Comment by boundsj** [comment]
Tagging this to future 3.2.0 so we can work on other enhancements first.

**Comment by mb12** [comment]
@boundsj Can you please clarify the following?

1.) What is the behavior if the application using MGLMapView does not included Location in UIBackgroundModes in the plist file?

2.) Is it possible to make sure that requestAlwaysAuthorization is also called before the call to startLocationUpdates?

**Comment by friedbunny** [comment]
@mb12:

1. Without `UIBackgroundModes Location`, this has no effect.
2. At this point, we're not going to require a minimum level of location permissions.

**Comment by boundsj** [comment]
Note: this will need a correction to check if background mode.location has been enabled by the developer. It is a fatal error to set `allowsBackgroundLocationUpdates` to true if background mode.location is false.

**Comment by boundsj** [comment]
Addressed by https://github.com/mapbox/mapbox-gl-native/pull/4115

**Pull request closed without merging**
