### PR TITLE
Make responses and response data shared

### PR DESCRIPTION
**Pull request by kkaefer**
In preparation for #896

### CODE REVIEW

**Comment by jfirebaugh** [comment]
@kkaefer Is this still relevant / necessary? Any `unique` ⇢ `shared` change makes me nervous.

**Comment by kkaefer** [comment]
The idea is that we need the Response data we loaded from the database in two places: For returning stale responses immediately, and for doing the `if-none-modified` request. I think this change is not critical since the Response object is a data-only object that has no side-effects on destruction and doesn't hold references to other objects.

**Comment by jfirebaugh** [comment]
Stale.

**Comment by kkaefer** [comment]
Implemented in 5173bf1bb8d21054b0dd6251d23eb37323d6c525

**Pull request closed without merging**
