### PR TITLE
Add emphasis-circle-color and emphasis-circle-radius to location-indicator

### PR DESCRIPTION
**Pull request by galinelle**
This PR adds the ability to draw an additional circle in the location-indicator
layer, called emphasis-circle.
This can be used to draw a pulsating circle to attract attention.
Example usage included in the glfw app.

## Launch Checklist

 - [x] briefly describe the changes in this PR
 - [ ] include before/after visuals or gifs if this PR includes visual changes
 - [x] write tests for all new functionality
 - [x] document any changes to public APIs
 - [ ] tagged `@mapbox/maps-android @mapbox/maps-ios @mapbox/core-sdk` if this PR adds or updates a public API
 - [ ] tagged `@mapbox/gl-js` if this PR includes shader changes or needs a js port
 - [ ] apply `needs changelog` label if a changelog is needed (remove label when added)

### CODE REVIEW

**Comment by chloekraw** [comment]
High level, this looks good to me too. Thanks @galinelle!

**Comment by pengdev** [comment]
@LukasPaczos @galinelle In symbol layer implementation [refs](https://github.com/mapbox/mapbox-gl-native-android/blob/2ee650901325f6a6867421e2d9c729c538f81422/MapboxGLAndroidSDK/src/main/res/values/styles.xml#L37),  we support the following configuration options: 
```
    <!-- Location pulsing circle -->
    <item name="mapbox_pulsingLocationCircleEnabled">false</item>
    <item name="mapbox_pulsingLocationCircleFadeEnabled">true</item>
    <item name="mapbox_pulsingLocationCircleColor">@color/mapbox_location_layer_blue</item>
    <item name="mapbox_pulsingLocationCircleDuration">2300</item>
    <item name="mapbox_pulsingLocationCircleRadius">35</item>
    <item name="mapbox_pulsingLocationCircleAlpha">0.4</item>
    <item name="mapbox_pulsingLocationCircleInterpolator">decelerate</item>
```
Shall we consider exposing these options for the location-indicator layer?

**Comment by LukasPaczos** [comment]
@pengdev ultimately, the layer should only expose radius, color, and alpha (or alpha baked into color). The transitions are platform-driven so the rest of the arguments should be handled on the platform side.

**Comment by pengdev** [comment]
> @pengdev ultimately, the layer should only expose radius, color, and alpha (or alpha baked into color). The transitions are platform-driven so the rest of the arguments should be handled on the platform side.

Sounds good.

**Comment by galinelle** [comment]
ping

**Pull request closed without merging**
