### PR TITLE
[core] Remove StyleSourcedAnnotation support

### PR DESCRIPTION
**Pull request by jfirebaugh**
The functionality this provided has been subsumed by the runtime styling API.

### CODE REVIEW

**Comment by jfirebaugh** [comment]
Putting this out for discussion. We probably don't _have_ to remove this if it's a key API in the Qt SDK, but it's duplicative of the runtime styling API and keeping it around is a slight drag on velocity whenever we go to make changes to the core style code, as we're doing now for async rendering.

**Comment by mb12** [comment]
The advantage of annotations over runtime styling is that they persist across style changes without any code changes required by the sdk user. Do layers added via runtime styling persist across style changes?  If not, this would require additional complexity to any application already using it.

**Comment by ivovandongen** [comment]
> Do layers added via runtime styling persist across style changes

It does on Qt specifically, not on other SDKs

**Comment by brunoabinader** [comment]
> it's duplicative of the runtime styling API and keeping it around is a slight drag on velocity whenever we go to make changes to the core style code

Agreed - we had this in mind when implementing the Mapbox GL QML plugin in the Qt SDK - and thus opted for avoiding annotations at all in favor of runtime styles.

Besides client needs in which we can adapt the style source annotation with runtime style behavior, I'm fine with removing this :+1: 

> Do layers added via runtime styling persist across style changes?

No - but for the Mapbox GL QML plugin we have persistent runtime style by caching all the style changes - e.g. see [here](https://github.com/qt/qtlocation/blob/dev/src/plugins/geoservices/mapboxgl/qgeomapmapboxgl_p.h#L90) - and re-applying them whenever needed e.g. when a style URL changes.

**Comment by 1ec5** [comment]
For what it’s worth, StyleSourcedAnnotation looked like relevant to https://github.com/mapbox/mapbox-gl-native/issues/1734#issuecomment-242802281, at least in terms of getting around the issues blocking #6181, although for https://github.com/mapbox/mapbox-gl-native/issues/1734#issuecomment-242802281 I had been prototyping something more direct, in which an annotation could hang onto a layer ID.

**Pull request merged**
