### PR TITLE
[ios, macos, build] Remove DEBUG from logging configuration.

### PR DESCRIPTION
**Pull request by fabian-guerra**
This adds a DEBUG flag to `mbgl-filesource` target. I'm trying to make this available only for the Debug config type but as is now is applied to all four types.

### CODE REVIEW

**Comment by kkaefer** [comment]
What’s the purpose of this flag? As @asheemmamoowala pointed out, we already have an `NDEBUG` flag which you should use instead (`#ifndef NDEBUG`).

**Comment by fabian-guerra** [comment]
@kkaefer the purpose was bring the `DEBUG` flag to `mgl-filesources` target. @asheemmamoowala reached out to me yesterday and let me know that I should use `NDEBUG` instead.

**Comment by julianrex** [comment]
If I'm reading this correctly, we have a mismatch here. iOS/macOS targets' debug configurations set `DEBUG` (this is an Xcode default), but not `NDEBUG`.

We should add `NDEBUG` to the build settings.

**Comment by asheemmamoowala** [comment]
> We should add NDEBUG to the build settings.

@julianrex Why does this need to be added manually? It is already inherited from the CMAKE settings as far as I can tell.

**Comment by julianrex** [comment]
> It is already inherited from the CMAKE settings as far as I can tell.

Where is this? Perhaps we're missing some settings to inherit

**Comment by kkaefer** [comment]
The iOS/macOS workspaces consist of two projects: One that is hand-maintained, and one that is generated by CMake. The former one probably doesn't have `NDEBUG` set, so we'd have to set it manually, while the latter _does_ have it set. There's no explicit code in our `CMakeLists.txt` files because it is built into the default CMake `CMAKE_CXX_FLAGS` that are inherited by every project.

**Comment by kkaefer** [comment]
This increased binary size by ~30 KB for armv7, but it sounds like removing debugging code from release build should have the opposite effect?

**Pull request merged**
