### PR TITLE
[ios] Ensure renderer is flushed when going into the background.

### PR DESCRIPTION
**Pull request by julianrex**
We have a number of crashes that appear to be related to rendering in the background: #13821, #13824, #13825 - which is counter to [Apple's recommendations](https://developer.apple.com/library/archive/qa/qa1766/_index.html).

Looking at [this comment from 13821](https://github.com/mapbox/mapbox-gl-native/issues/13821#issuecomment-467195893), it was determined that it's possible to put the app into a state where `MGLMapView` isn't dormant and GL rendering can occur. (This is probably in situations where the map view is created programmatically, or some other view controller is affecting the view hierarchy when backgrounding).

PR #14156 introduces `mbgl::Renderer::flush()` which allows us to ensure `glFinish()` is called when going into the background [as recommended](https://developer.apple.com/library/archive/documentation/3DDrawing/Conceptual/OpenGLES_ProgrammingGuide/ImplementingaMultitasking-awareOpenGLESApplication/ImplementingaMultitasking-awareOpenGLESApplication.html#//apple_ref/doc/uid/TP40008793-CH5-SW1).

This PR adds:
- An integration test to exercise the bug described (manipulating views - essentially remove and re-add).
- Some reorganization of how the display link is managed.
- A private `MGLApplication` protocol to aid with mocking.
- Flushing the renderer when backgrounding.
- A bug fix in `-glkView:drawInRect:`
 
Changes:
- Pauses the display link upon receiving `UIApplicationWillResignActiveNotification` - this needs some discussion as this is a change in behavior.

TODO?
- [x] Refactor `validateDisplayLink` - because of the situation above, it's possible to have a nil or non-nil display link when entering the background. I propose that we should only pause/unpause the display link - and perhaps be more explicit.
- [x] Test launch conditions, to investigate this [Firebase comment](https://github.com/mapbox/mapbox-gl-native/issues/13824). Propose we add this in a follow up PR, though this may be a SEMVER major change.
- [ ] Check how this affects external devices (AppleTV, CarPlay)
- [ ] Change log

cc @tmpsantos @chloekraw

### CODE REVIEW

**Comment by chloekraw** [comment]
cc/ @kkaefer

**Comment by julianrex** [comment]
For reference this PR is somewhat stale, now that some changes have landed in master. I'll be updating shortly, but the gist of the PR is still valid.

**Comment by julianrex** [comment]
Noting here that an intermediate PR (https://github.com/mapbox/mapbox-gl-native/pull/14439) has landed on master and on `release-liquid` that addresses the symptoms, whereas this PR is about fixing addressing the probable root cause.

**Comment by julianrex** [comment]
[4.10.0](https://github.com/mapbox/mapbox-gl-native/releases/tag/ios-v4.10.0) was released with #14439.

**Comment by racer1988** [comment]
@julianrex I have a displayLink crash like the other reported here. we might open a new issue with the stack trace, but I wanted to give some details as this PR is working on the renderer and I think the issue is not only in background.

I get the same crash when I pop from the stack the view controller that is displaying the map.
It only happens if I close the view controller immediately after it appears.
My impression is that the renderer is having a memory leak and keeps a reference to the mapView.

So my controller gets destroyed, and the updateDisplayLink is called to the mapView that is actually already gone.

**Comment by julianrex** [comment]
@racer1988 thanks for this insight! This PR is currently undergoing some refactoring due to recent changes in core, and we'll make sure to consider this scenario. 

What version of the SDK are you currently on? It would be interesting to know if you still see issues with a more recent SDK if that's applicable.

**Comment by racer1988** [comment]
Currently on 
` pod 'Mapbox-iOS-SDK', '~> 5.0.0'`

**Pull request closed without merging**
