### PR TITLE
refs #2684: integrate Twitter Fabric

### PR DESCRIPTION
**Pull request by incanus**
More to do here, but this is a start.

### CODE REVIEW

**Comment by incanus** [comment]
This is good once I get tests to pass. Will also update the [release process](https://github.com/mapbox/mapbox-gl-native/wiki/Releasing-Mapbox-GL-for-iOS) since we have to bump a version number as part of this.

**Comment by mb12** [comment]
@incanus What functionality does this add?

**Comment by incanus** [comment]
@mb12 This is related to our [partnership with Twitter](http://www.theverge.com/2015/10/22/9600792/twitter-fabric-developer-toolkit-stripe-aws) and only affects installs done via the forthcoming Fabric integration. It's dead code on other installs.

**Comment by incanus** [comment]
In case it looks particularly lightweight, we also have backend code supporting the heavy lifting in conjunction with this code. 

See also https://github.com/mapbox/mapbox-gl-native/commit/bb6fff0c5db8091b4af43e51e3411fcaca161f18.

**Pull request merged**
