### PR TITLE
disable -Wunused-local-typedef on OS X

### LINKED ISSUE #2390: Disable unused local typedef warnings to fix OS X builds
Due to [ticket #11240 in Boost](https://svn.boost.org/trac/boost/ticket/11240), we may need to disable `-Wunused-local-typedef` to fix `make osx` builds in Xcode 7.

/cc @mikemorris @jfirebaugh

### PR DESCRIPTION
**Pull request by mikemorris**
Fixes #2390

/cc @1ec5

### CODE REVIEW

**Comment by mikemorris** [comment]
Hrm, Travis OS X builds keep failing with `unknown warning option '-Wno-unused-local-typedef' [-Werror,-Wunknown-warning-option]` (still unknown with plural `typedefs`), but everything builds fine for me locally - what am I doing wrong here?

**Comment by 1ec5** [comment]
The iOS builds are happy but the OS X builds are not. I suspect the difference is that the OS X builds are still building on the Xcode 6.4 toolchain, whereas the iOS builds are building on the Xcode 7 toolchain.

**Comment by mikemorris** [comment]
https://github.com/mapbox/mason/pull/114 should be merged and the submodule pin updated before merging this.

**Comment by incanus** [comment]
Per https://github.com/mapbox/mason/pull/114#issuecomment-142677221, will test this in a moment, but is there a way we can limit this (on by default for a reason) compile flag just to Boost @mikemorris?

**Comment by mikemorris** [comment]
@incanus Does clang offer functionality similar to GCC for [using `#pragma` to disable compiler warnings](https://github.com/mapbox/mapbox-gl-native/blob/d89aa51e0f59b2465dbbe5e56dd7c59ed88b2e86/macosx/main.mm#L17)?

**Comment by 1ec5** [comment]
[It does](https://github.com/mapbox/mapbox-gl-native/blob/20ad0d51f6e6d82587e2beac34f390356409e152/include/mbgl/ios/MGLTypes.h#L32), so an alternative to this PR would be to surround any import of the problematic Boost header with the relevant `#pragma`.

**Comment by incanus** [comment]
Yes. 

https://github.com/mapbox/mapbox-gl-native/blob/20ad0d51f6e6d82587e2beac34f390356409e152/include/mbgl/ios/MGLTypes.h#L32

**Comment by mikemorris** [comment]
Updated the mason submodule pin now that https://github.com/mapbox/mason/pull/114 has landed. Switched to just ignore `-Wunused-local-typedef` around the problematic `boost/program_options.hpp` include instead of setting `-Wno-unused-local-typedef` in the gypfile.

**Comment by mikemorris** [comment]
Um, for some odd reason Travis can't find `clang` on Linux now...
```
make[2]: clang++-3.5: Command not found
```

**Comment by mikemorris** [comment]
Emailed support@travis-ci.com about the Missing Clang Mystery.

**Comment by incanus** [comment]
bilocchcuaasy_z jpg-large

_Travis_

**Comment by mikemorris** [comment]
It looks like I might've gotten tripped up by an llvm apt repository update - `llvm-toolchain-precise-3.5` is no longer listed as of very recently.
```
Precise (12.04) - Last update : Wed, 23 Sep 2015 20:28:19 UTC / Revision: 248380

deb http://llvm.org/apt/precise/ llvm-toolchain-precise main
deb-src http://llvm.org/apt/precise/ llvm-toolchain-precise main
# 3.6 
deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.6 main
deb-src http://llvm.org/apt/precise/ llvm-toolchain-precise-3.6 main
# 3.7 
deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.7 main
deb-src http://llvm.org/apt/precise/ llvm-toolchain-precise-3.7 main
```

**Comment by jfirebaugh** [comment]
If llvm removed the 3.5 packages, you'd presumably have to move to 3.6 as well as update the repository source.

**Comment by jfirebaugh** [comment]
We should remove `--force-yes` from the `apt-get install` command; I bet it's hiding a "package clang-3.5 not found in any sources; ignoring" type error.

**Comment by mikemorris** [comment]
> We should remove --force-yes from the apt-get install

Don't think we can do that, pretty sure that's happening on Travis' end?

**Comment by jfirebaugh** [comment]
Yeah, you're right, must be part of the apt addon.

**Comment by mikemorris** [comment]
> Could not connect to llvm.org:80 (192.17.58.186), connection timed out

Refs https://github.com/mapbox/mapbox-gl-native/issues/1828

**Comment by mikemorris** [comment]
Missing clang was llvm.org's fault -> #1828

**Pull request merged**
