### PR TITLE
Integrate node build into CI

### PR DESCRIPTION
**Pull request by kkaefer**
We should run the node module build and tests against the current commit to make sure we don't accidentally break it.

### CODE REVIEW

**Comment by jfirebaugh** [comment]
I think we should merge node-mapbox-gl-native into mapbox-gl-native, the same way we merged mapbox-gl-cocoa. The node bindings have essentially the same role as the Android and iOS SDKs, and the same arguments for keeping them in the same repository apply. I bet @mikemorris would welcome such a change profusely.

**Comment by mikemorris** [comment]
@jfirebaugh I'd actually prefer to keep node-mbgl as a separate project because [it integrates with mbgl on a much different level than Android or iOS](https://github.com/mapbox/mapbox-gl-cocoa/issues/28#issuecomment-72967012). The Node.js "bindings" are really just a library consuming the mbgl public API, and don't need the tight integration required by Android and iOS.

I had a long back-and-forth with @incanus about this in https://github.com/mapbox/mapbox-gl-cocoa/issues/28

**Comment by jfirebaugh** [comment]
That discussion was before we realized it would be _so much easier_ to have mapbox-gl-cocoa not be a separate repository. The same is true of node-mapbox-gl-native. Right now you're doing a complex dance with the build scripts, and still struggling to find the right incantations, in a way that's made accidentally complex because of the separate repositories.

> The Node.js "bindings" are really just a library consuming the mbgl public API

Replace 'Node.js "bindings"' with "iOS bindings" or "Android bindings" and you have an accurate description of those two things. Node is really just another runtime/language binding.

**Comment by incanus** [comment]
> The Node.js "bindings" are really just a library consuming the mbgl public API

Yeah, so are the mobile bindings. We just use `map.hpp` etc.

**Comment by mikemorris** [comment]
-> https://github.com/mapbox/mapbox-gl-native/pull/2179

**Pull request closed without merging**
