### PR TITLE
Move Settings.bundle into included iosapp

### PR DESCRIPTION
**Pull request by captainbarbosa**
Removes the settings target and gets rid of the included example `Settings.bundle` from this project, which would be moved to the `ios-sdk-examples` project in https://github.com/mapbox/ios-sdk-examples/pull/204. Closes https://github.com/mapbox/mapbox-gl-native/issues/12554.

This will not require a changelog entry.

### CODE REVIEW

**Comment by captainbarbosa** [comment]
@1ec5 I went ahead with your suggestion and moved the Settings.bundle into iosapp as well as removed the unused Settings target, please let me know if I've missed something.

**Comment by captainbarbosa** [comment]
@julianrex @friedbunny and I spoke about the direction of this PR. Since package.sh currently doesn't build iosapp, having it do so just to copy the Settings.bundle seems inefficient. We agreed that the Settings.bundle should remain in the iosapp but should not be packaged with the framework for now.

**Comment by 1ec5** [comment]
Change these two lines:

https://github.com/mapbox/mapbox-gl-native/blob/3ca20500bdef7f5c1b8ac789650c68c4a9ffda72/platform/ios/scripts/package.sh#L141 https://github.com/mapbox/mapbox-gl-native/blob/3ca20500bdef7f5c1b8ac789650c68c4a9ffda72/platform/ios/scripts/package.sh#L166

to:

```bash
cp platform/ios/app/Settings.bundle ${OUTPUT}
```

and nothing changes about the final built SDK.

**Comment by friedbunny** [comment]
@captainbarbosa Looks like `Root.strings` is still thought to exist in the SDK section of the Xcode project:

screen shot 2018-09-06 at 6 53 18 pm

**Comment by friedbunny** [comment]
@captainbarbosa If we’re going to keep the localizations, please check that they work in their new home.

**Comment by captainbarbosa** [comment]
@friedbunny I tested on-device by changing the language and checking the telemetry alert:

**Comment by captainbarbosa** [comment]
@friedbunny Gotcha - I'm now noticing that the settings do localize the first time the language is changed, but then remain stuck on the first localization when the language is changed again. Not sure what the cause is but I'm seeing this on the device and with the simulator.



_(After changing the default language from English to French and then to Japanese, the Settings remain localized to French.)_

**Comment by friedbunny** [comment]
> I'm now noticing that the settings do localize the first time the language is changed, but then remain stuck on the first localization when the language is changed again.

@captainbarbosa That also happens in `master`. It looks like Settings.app doesn’t use the Base localization in our Settings.bundle when it switches away from another localization — explicitly adding an English localization for Settings.bundle (with the same strings as Base) fixes this issue.

@1ec5 Does this behavior seem like a bug to you, or are we doing something incorrectly?

**Comment by 1ec5** [comment]
> I'm now noticing that the settings do localize the first time the language is changed, but then remain stuck on the first localization when the language is changed again.

Did you force-quit Settings between changing languages? If I’m not mistaken, the Settings application does cache its contents until you close it. What happens in other applications that specify localized settings pages?

**Comment by captainbarbosa** [comment]
@1ec5 force quitting the settings app doesn’t seem to work and other apps localize their custom settings as expected, so this only seems to be occurring with this project.

**Comment by captainbarbosa** [comment]
@friedbunny I added the English localization and its back to working as expected.

**Comment by friedbunny** [comment]
Did this ↓ end up being necessary, @captainbarbosa?

> Additionally, it may be necessary to update the [localization addition process](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/ios/DEVELOPING.md#adding-a-localization) to include manually adding a localization of Root.strings – not sure if Xcode automatically detects that strings file as being localizable when it lies within a Settings.bundle.

**Comment by captainbarbosa** [comment]
@friedbunny No, it was not necessary - @1ec5 and went through it together and localizations seemed to take with no issues 👍

**Pull request merged**
