### PR TITLE
[Android] SupportMapFragment: add  newInstance method with onMapReadyCallback

### PR DESCRIPTION
**Pull request by vacxe**
I think this easy way add callback, when you create fragment in code.

@tobrun @bleege what's you think about this?

### CODE REVIEW

**Comment by tobrun** [comment]
@vacxe the way we currently set up a fragment is on par with [MapFragment](https://developers.google.com/android/reference/com/google/android/gms/maps/SupportMapFragment) Google Maps SDK. 
Is there another reason behind this PR besides convenience?

**Comment by vacxe** [comment]
@tobrun no, just i think it be convenience. This solution not conflict with Google Maps SDK, but expands him. If you set strategy Mapbox develop of absolute migration gmSDK im agree with you (Not problem, close PR). 

Simply i'm just like make some things better )

**Comment by tobrun** [comment]
@vacxe 
> Simply i'm just like make some things better 

That is a great motivation! keep this up.

Related to the issue, For me it boils down to the responsibility an object (in this case a fragment) has when being created with a `newInstance` method. The object itself is responsible for managing the state introduced with `newInstance` and is responsible for making sure the state is restored after being destroyed/recreated (for this  a fragment using a bundle with arguments). This is a key difference between an `OnMapChangeListener` and `MapboxMapOptions`.  For the former it is not possible to restore/destroy/recreate it, for the latter it is.

**Comment by vacxe** [comment]
@tobrun im close this PR? Please look https://github.com/mapbox/mapbox-gl-native/pull/4735

**Pull request closed without merging**
