### PR TITLE
added click, longclick, scroll, fling events

### PR DESCRIPTION
**Pull request by erf**
as discussed in #1942

the event listeners should be converted to lists and the onfling and onscroll listeneers should probably have some parameters

### CODE REVIEW

**Comment by tmcw** [comment]
@bleege this looks solid to me - I'm not sure about the Java-ism but is it better to check whether a listener is null and then call it, or set it initially to a no-op function and always call it?

**Comment by bleege** [comment]
@erf Thanks for the PR.  I've been sidetracked the last few days, but hope to get to this soon!

**Comment by erf** [comment]
No problem. Btw. This worked for me, but i don't have complete overview of what is needed here..

**Comment by bleege** [comment]
Looking into this now.

**Comment by bleege** [comment]
This looks good.  Thanks @erf!

**Comment by altafrm3d** [comment]
Is there something like onZoom() Listener other than the one for buttons, i have not been able to find it anywhere.

**Comment by ljbade** [comment]
@altafrm3d Not yet. Open a feature request ticket.

**Pull request merged**
