### PR TITLE
[android] updated mapbox-sdk-services to 3.0.1

### PR DESCRIPTION
**Pull request by osana**
addresses https://github.com/mapbox/mapbox-java/issues/783

### CODE REVIEW

**Comment by osana** [comment]
Upgrade to MAS 3.0.1 resulted in the error below.
Note that I was able to build and run test app with no problems.
```FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':MapboxGLAndroidSDKTestApp:transformClassesAndResourcesWithProguardForRelease'.
> Job failed, see logs for details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 51s
56 actionable tasks: 29 executed, 27 up-to-date
Exception in thread "Thread-146" java.lang.NoClassDefFoundError: com/android/utils/PathUtils$1
    at com.android.utils.PathUtils.deleteIfExists(PathUtils.java:47)
    at com.android.utils.PathUtils.lambda$addRemovePathHook$0(PathUtils.java:125)
    at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: com.android.utils.PathUtils$1
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 3 more
Makefile:622: recipe for target 'apackage' failed
make: *** [apackage] Error 1
Exited with code 2
```

Search for  similar problems shows that other people have been having similar issue and that could be related to https://issuetracker.google.com/issues/69380617

Also here is a similar problem in another github project https://github.com/kiwix/kiwix-android/issues/518 I think they resolved it by upgrading to  to Android Gradle Plugin  3.1.0 from 3.0.1 ( the one we have).

**Comment by osana** [comment]
Tried bumping Android Gradle Plugin to 3.1.0

as per https://developer.android.com/studio/releases/gradle-plugin.html#updating-gradle
that means gradle wrapper should be at 4.4
and build tools 27.0.3

**Comment by osana** [comment]
cc @tobrun @LukasPaczos

**Comment by tobrun** [comment]
@osana CI is failing because it doesn't support 27.0.3, see the dockerfile in https://github.com/mapbox/mbgl-ci-images/blob/master/android-ndk-r16b/Dockerfile#L43. I'm waiting for the release of 28.0.0, which is now in RC.1, to update the CI images. I'm not seeing why we need to bump these items if I take a look at the mapbox-java configuration. Will dig a little bit deeper to find the root cause.

**Comment by osana** [comment]
@tobrun  I cannot reproduce the build problem building locally so this was a bit of experimentation. I will update the branch back to just updating MAS version so that you could see the error.

**Pull request merged**
