### PR TITLE
[android] Fix gradle developer config creation task with discussed suggestions

### LINKED ISSUE #8783: [android] Fix developer config creation task
Current [task](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDKTestApp/gradle-config.gradle) is not working when you don't have `MAPBOX_ACCESS_TOKEN` environment variable set. Actually, it always creates a file in which `mapbox_access_token` is `null` which throws a `MapboxConfigurationException` crashing the app.

It's fixed in [`mapbox-navigation-android`](https://github.com/mapbox/mapbox-navigation-android/blob/master/navigation/app/developer-config.gradle) so porting those changes would fix the issue.

### PR DESCRIPTION
**Pull request by Guardiola31337**
Fixes #8783

👀  @zugaldia @tobrun

### CODE REVIEW

**Comment by tobrun** [comment]
It seems you haven't picked up: `When we do token validation in the SDK, if we detect that the token value is YOUR_MAPBOX_ACCESS_TOKEN_GOES_HERE we know exactly what happened and we can provide additional logging/error messages.`

**Comment by Guardiola31337** [comment]
@tobrun Apart from [logging `Warning: access token isn't set.`](https://github.com/mapbox/mapbox-gl-native/blob/0ea1a92736c00557acac4ef54bb9451b0c66e1eb/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/MapboxApplication.java#L53-L55), do we need to add anything else? A `Toast`?

**Comment by tobrun** [comment]
The user will currently not know what exactly happened, as the same `InvalidAccessTokenException` will be thrown as before. Only an additional log message with "access token isn't set" has been added with no reference to our developer setup (eg. developer-config.xml or YOUR_MAPBOX_ACCESS_TOKEN_GOES_HERE).  I think @zugaldia wanted a concrete exception to be thrown but I will let me him follow up on this.

**Comment by zugaldia** [comment]
How about we leave the flow as it is, but we change the error message to look something like the following:

> In order to run the Test App you need to set a valid access token. During development, you can set the `MAPBOX_ACCESS_TOKEN` environment variable for the SDK to automatically include it. Otherwise, you can manually include it in the `res/values/developer-config.xml` file.

**Comment by tobrun** [comment]
> In order to run the Test App you need to set a valid access token. During development, you can set the MAPBOX_ACCESS_TOKEN environment variable for the SDK to automatically include it. Otherwise, you can manually include it in the res/values/developer-config.xml file.

This gives the end-user the idea that if they would set a MAPBOX_ACCESS_TOKEN environment variable that this will get picked up by the SDK. Which isn't the case, this will be created by the test application.

**Comment by zugaldia** [comment]
@tobrun Right. We can clarify further:

> In order to run the Test App you need to set a valid access token. During development, you can set the MAPBOX_ACCESS_TOKEN environment variable for the SDK to automatically include it in the Test App. Otherwise, you can manually include it in the res/values/developer-config.xml file in the MapboxGLAndroidSDKTestApp folder.

**Pull request merged**
