### PR TITLE
[do not merge - needs review] Android GL

### PR DESCRIPTION
**Pull request by ljbade**
Android GL is almost ready for merging.

Can I get a few sets of good eyes to look at the changes, since there is a lot in here.

### CODE REVIEW

**Comment by ljbade** [comment]
OK I have closed all remaining tickets that were blocking the merge.

Next steps:
- [ ] Test on my devices (feel free to test on yours too @bleege and @incanus if you have time)
- [ ] Code review (@jfirebaugh and anyone else)
- [ ] Work out merge strategy (squash?)
- [ ] Merge

**Comment by incanus** [comment]
Awesome work @ljbade. Yes, I'd say a squash is the maybe the best way to integrate this (so, a new PR) but /cc @jfirebaugh for input as he tends to approach dev history a different way than I do. 

I'll certainly take a look at the proposed merge and it's probably good to have @kkaefer @jfirebaugh @mikemorris do so as well. 

I'll test this PR on my devices today.

**Comment by jfirebaugh** [comment]
The goal you should strive for with commits that go into master is that each commit consists of logically related changes, and each commit is self-contained -- that it builds and tests successfully without needing any other commits. The purpose of rebasing a history (and squashing is a special case of rebasing) is to go from a history of work in progress, where you're figuring out what needs to be done and things are a bit messy (which is fine), to the logically-related-and-self-contained ideal.

There is much more than one logically related change here, so it wouldn't be appropriate to squash this to a single commit. Because it's such a big branch, it's going to be hard to figure out what the logical changes are. Plus there are commits from multiple people whose contributions should be acknowledged by the history. It's not ideal, but I'm leaning towards not rebasing in this case for these reasons.

**Comment by ljbade** [comment]
@jfirebaugh re no squash: fair enough. I guess the moral is avoid long lived branches at all costs!

**Comment by springmeyer** [comment]
>  Plus there are commits from multiple people whose contributions should be acknowledged by the history.

I originally created this branch `android-mason` and lots of other early android branches but I don't need any credit for my commits and so I'd be just fine if it were squashed it into a few commits.

**Comment by ljbade** [comment]
Hmm I think perhaps @jfirebaugh was talking about @hollinger's work.

**Comment by jfirebaugh** [comment]
There's commits from @ljbade, @artemp, @mikemorris, @jfirebaugh, @incanus and @vincent23 in this branch.

**Comment by ljbade** [comment]
ah vincent23?

**Comment by incanus** [comment]
Yeah you can examine with a URL like this: 

https://github.com/mapbox/mapbox-gl-native/commits/master?author=vincent23

**Comment by ljbade** [comment]
Oh so he was from master.

**Comment by incanus** [comment]
> I'll test this PR on my devices today.

This feels good on the Nexus 4 and 9. The 7 is dead (because it's a day ending in `y`, sigh...) and the Beeline Russian phone (`4.0.4`) won't work in Studio for some reason. But the two I got working look fantastic.

**Comment by bleege** [comment]
Congrats on the merge @ljbade!  I'm happy to test this on the Samsung S5 if you can get me build.

**Comment by mikemorris** [comment]
Congrats on the merge!

**Comment by emiltin** [comment]
looking forward to hopefully use this in our I Bike Cph bicycle navigation app :-)

**Pull request merged**
