### PR TITLE
Restore FBO and Viewport on GL reset

### PR DESCRIPTION
**Pull request by kkaefer**
When resetting the GL configuration object, we are currently not resetting the Framebuffer binding and the viewport.

### CODE REVIEW

**Comment by jfirebaugh** [comment]
The state management makes sense, but is there a reason why we need to add `CustomLayerRenderParameters::framebuffer`?

**Comment by kkaefer** [comment]
The idea of adding `framebuffer` is to allow custom layers to bind a different framebuffer, then restore the original (main) framebuffer.

**Comment by jfirebaugh** [comment]
In general we don't require that custom layers restore the original GL state. Instead, we call [`config.setDirty()`](https://github.com/mapbox/mapbox-gl-native/blob/0df60c46517648b18e65d860f5a9356ba751ca11/src/mbgl/renderer/painter.cpp#L267), which ensures that our own code resets the state when necessary. Can we follow the same pattern for the framebuffer?

**Comment by kkaefer** [comment]
@jfirebaugh we don't expect that they reset the state, but exposing the original framebuffer ID allows custom layers to switch to a different (offscreen) FBO, render to that FBO, then switch back to the original FBO and composite the offscreen buffer.

**Comment by jfirebaugh** [comment]
Ah, I understand now. Is `glGetIntegerv(GL_FRAMEBUFFER_BINDING, &id)` too inefficient to use for that use case?

**Comment by jfirebaugh** [comment]
Also, this addition would need to be plumbed through `MGLCustomStyleLayerDrawingHandler` in the iOS SDK, which I believe would be a breaking API change. Android uses the core `CustomLayerRenderParameters` struct directly, and because the addition is at the end of the struct I think the change is even ABI compatible.

**Comment by kkaefer** [comment]
Calling `glGet*` typically stalls the rendering pipeline and introduces considerable delay.

**Comment by kkaefer** [comment]
This was mostly merged already.

**Pull request closed without merging**
