### PR TITLE
[android] Add satellite streets style

### LINKED ISSUE #2739: Add all official styles to Styles
From https://github.com/mapbox/mapbox-gl-native/pull/2714#issuecomment-150370112

There is a list of official styles in https://github.com/mapbox/mapbox-gl-styles

We should add them all to our `Styles` constants, and add the useful ones to the test app and Sirius.

@1ec5 is there any update to ios test app needed too?

### LINKED ISSUE #2740: Add all official styles to styles
From https://github.com/mapbox/mapbox-gl-native/issues/2739#issuecomment-150385722

> we need to update both iosapp and scripts/ios/package.sh.

/cc @1ec5

### PR DESCRIPTION
**Pull request by ljbade**
Fixes #2739
Fixes #2740

### CODE REVIEW

**Comment by 1ec5** [comment]
We purposely excluded Bright, Basic, and Empty from the iOS SDK.

**Comment by ljbade** [comment]
@1ec5 Why is that?

**Comment by 1ec5** [comment]
#1264

In short, while these styles are useful as Mapbox Studio templates, they aren't what we would consider ready-made styles – particularly not Empty. 😉

**Comment by ljbade** [comment]
@1ec5 True. OK I'll just add satellite streets.

**Comment by ljbade** [comment]
PR updated, waiting for Travis then merge.

**Comment by 1ec5** [comment]
@ljbade, I think the new style should be called just Hybrid on iOS. "Satellite-Hybrid" is a bit unwieldy.

**Comment by 1ec5** [comment]
Or "Satellite Streets", per https://github.com/mapbox/mapbox-gl-native/issues/2740#issuecomment-150427309.

**Pull request merged**
