### PR TITLE
black flicker on iOS device rotation

### PR DESCRIPTION
**Pull request by kkaefer**
Rotate 90 degrees to repro.

### CODE REVIEW

**Comment by bleege** [comment]
This looks awesome @kkaefer!

Total nitpicking here, but the only question is that on rotation it looks like the GL Canvas is white and so for a split second before the GL map renders on rotation completes its visible against the black background of iOS.  This is most noticeable when rotating from landscape back to portrait.  I think the easy solution would be to [paint it black](https://www.youtube.com/watch?v=u6d8eKvegLI).

**Comment by incanus** [comment]
Yeah, we discussed this in chat yesterday @bleege. I may take a look at `UIView`/`UIViewController` resources to work around that, as MapKit doesn't have the problem. Also keep in mind not every view controller will default to a black view.

**Comment by bleege** [comment]
Thanks for the insight @incanus!  BTW, I just looked at Google Maps on iOS and it has the same momentary white flicker on rotation too.

**Comment by kkaefer** [comment]
I spent quite some time on triggering the view resize *during*, not *before* the animation, but couldn't find a good solution. One that comes to mind is adding a second subview behind the GLKView that is a static image of the map pre-transition, and keeping it centered with `UIViewContentModeCenter`, and setting the GLKView's background color to transparent.

**Pull request merged**
