### PR TITLE
Check glGetError in a loop

### PR DESCRIPTION
**Pull request by mikemorris**
As recommended in https://www.opengl.org/wiki/GLAPI/glGetError

/cc @tmpsantos

### CODE REVIEW

**Comment by kkaefer** [comment]
Any reason for moving the error message construction to a separate function?

**Comment by mikemorris** [comment]
@kkaefer Just seemed slightly cleaner that way, I can refactor it back into `checkError` quickly if you'd prefer.

**Comment by mikemorris** [comment]
@kkaefer Reworked this to move error construction back into `checkError`

**Comment by kkaefer** [comment]
The [previous code](https://github.com/mapbox/mapbox-gl-native/blob/f8f3f276c8dc2bd9cf032df5d0c180267e68374b/src/mbgl/gl/gl.cpp) always allocated a `std::vector` and a `std::string`, even when no error occurred (which is the vast majority of all cases). I updated the code to do the allocation lazily, and to print the errors in the order they were received, instead of backwards, and factored out the enum to string conversion.

**Pull request merged**
