### PR TITLE
[ios] read only annotation

### PR DESCRIPTION
**Pull request by fabian-guerra**
This fix was merged into master but should be merged into release branch.
\cc @boundsj

### CODE REVIEW

**Comment by 1ec5** [comment]
This went into the release branch as part of #8324. Nothing left to do here.

**Comment by fabian-guerra** [comment]
@1ec5 this branch raises an `NSException` instead of using an `NSAssert`

**Comment by 1ec5** [comment]
Ah, I missed that. Can you open a new PR that does just that, now that all the other changes are already included in the release branch?

**Pull request closed without merging**
