### PR TITLE
privatize SQLiteCache

### PR DESCRIPTION
**Pull request by jfirebaugh**
No code that uses `DefaultFileSource` wants to _not_ use `SQLiteCache`. We should make the `SQLiteCache` instance a member of `DefaultFileSource`, thus enforcing its use, and remove it and the `FileCache` base class from the public API.

cc @kkaefer

### CODE REVIEW

**Comment by jfirebaugh** [comment]
:eyes: @kkaefer @tmpsantos 

Despite all the architecture discussion above, I actually had a very simple change in mind to start out with. WDYT?

**Comment by tmpsantos** [comment]
> Despite all the architecture discussion above, I actually had a very simple change in mind to start out with. WDYT?

Looks good to me but we should handle something like empty path not creating a cache.

**Comment by jfirebaugh** [comment]
@tmpsantos Do we need that feature anywhere? If not, let's leave it out.

**Comment by tmpsantos** [comment]
> @tmpsantos Do we need that feature anywhere? If not, let's leave it out.

Not that I'm aware of.

**Pull request merged**
