### PR TITLE
Update `mapbox-events-ios` to `v0.9.2` (#14288)

### LINKED ISSUE #14288: ⨍ Integrate MapboxEvents 0.9.2 - Crash Fix
Release Ticket: https://github.com/mapbox/mobile-telemetry/issues/308

Hot Fix Issue: https://github.com/mapbox/mapbox-events-ios/issues/118

### PR DESCRIPTION
**Pull request by alfwatt**
Fixes #14288

### CODE REVIEW

**Comment by friedbunny** [comment]
GitHub tip: if you reference an issue in a pull request that you intend to close as a result of that pull request being merged, add the text `fixes #whatever-issue-number` to your pull request description and it’ll happen automatically — [other keywords](https://help.github.com/en/articles/closing-issues-using-keywords) are also available.

**Comment by friedbunny** [comment]
This pull request targets `release-liquid` directly — the flow for merging into release branches in this repo is to merge to `master` first, then cherry-pick that change to the release branch. In practice, it’s acceptable to do both concurrently, but the change must also separately happen in `master` (as we do not merge release branches back).

(Unfortunately, I can’t find where this process is documented, which is problem... sorry. 🙇‍♂️)

**Comment by friedbunny** [comment]
Other notes:

- Please prefix commits with the platform(s) that they affect — e.g., `[ios]`.
- If you intend an issue/PR to target a specific release, add it to that milestone.
- Add relevant tags to the issues/PRs.

**Comment by alfwatt** [comment]
Abandoning in favor of above cherry-pick process (and bad branch name)

**Pull request closed without merging**
