### PR TITLE
[core] make{Glyph,Image}Atlas only once for any number of symbol layers

### PR DESCRIPTION
**Pull request by jfirebaugh**
Fix an oversight from #9213 / f73f45107f02f5b1d945a7a41e3e6d1e88ecf9b8.

### CODE REVIEW

**Comment by jfirebaugh** [comment]
That it was re-making the atlases once for every symbol layer, even though they will be identical.

**Comment by kkaefer** [comment]
Do you mean SymbolLayout?

**Comment by jfirebaugh** [comment]
Yes, once per `SymbolLayout`.

**Comment by jfirebaugh** [comment]
@kkaefer 🍏 ?

**Pull request merged**
