### PR TITLE
[android] - #2862 Correct behaviour when switching between tracking modes, added javadoc

### LINKED ISSUE #2862: User location/bearing tracking modes to not switch properly
When changing between the different modes, things get a bit mixed up.

First if you set compass, then change to GPS, the old compass arrow still exists and is not replaced with the GPS right away. This means we need to separate the GPS and compass bearings into separate variables.

If you set compass (or gps) bearing mode, then enable location tracking the map is not instantly rotated.

When bearing mode is enabled with user location tracking on, the arrow is not drawn, this should always be drawn directly north in this mode.

/cc @tobrun

### PR DESCRIPTION
**Pull request by tobrun**
Closes #2862 
@ljbade

### CODE REVIEW

**Comment by tobrun** [comment]
Just verified in car that bearing with tracking enabled for GPS is not :100:% correct, wait for merge after fix

**Comment by tobrun** [comment]
@ljbade could you validate this PR?

**Comment by ljbade** [comment]
Sorry I thought you were still working on this. The code looks good to me. I'll give it a functional test tomorrow.

**Comment by tobrun** [comment]
@ljbade were you able to test it?

**Comment by tobrun** [comment]
Can someone validate this? @ljbade, @zugaldia, @bleege

**Comment by tobrun** [comment]
Did some tests, going to rebase and merge

**Pull request merged**
