### PR TITLE
[node] Expose map.onLowMemory()

### PR DESCRIPTION
**Pull request by brunoabinader**
:eyes: @mikemorris @miccolis

### CODE REVIEW

**Comment by brunoabinader** [comment]
As per conversations with @mikemorris, this hasn't proven to cause much impact in memory consumption, thus closing until further notice.

**Comment by mikemorris** [comment]
@brunoabinader I might actually have to rebase and test this again to verify, as it looks like this branch contains the leak introduced in 61dad6eae59e284fdba63fcd76d9192aba900db4 and fixed in https://github.com/mapbox/mapbox-gl-native/pull/5269

**Comment by brunoabinader** [comment]
Is this still revelant @mikemorris?

**Comment by mikemorris** [comment]
Rebased and checked again, confirmed that this doesn't appear to do anything to reign in memory growth.

**Pull request closed without merging**
