### PR TITLE
[core] Ensure correct GL context in Map::onLowMemory()

### LINKED ISSUE #5731: Crash rendering the map — mbgl::FillBucket::drawElements, glrAGXRenderVertexArray
**Platform:** iOS
**Mapbox SDK version:** 3.3.1

We see a high crash rate for this on fabric.

I can't reproduce this crash but it happens randomly when the app is in foreground and doing something with the map.

We use a custom style & draw a single polyline on the map

```
Crashed: com.apple.main-thread
0  libsystem_platform.dylib       0x181e5a2a0 _platform_memmove + 176
1  AGXGLDriver                    0x193d93f6c glrAGXRenderVertexArray(GLDContextRec*, unsigned int, unsigned int, int, int, unsigned int, void const*, int, void const*)
2  AGXGLDriver                    0x193d93f6c glrAGXRenderVertexArray(GLDContextRec*, unsigned int, unsigned int, int, int, unsigned int, void const*, int, void const*)
3  GLEngine                       0x194b36ea4 glDrawElements_ACC_ES2Exec
4  Mapbox                         0x1017739e4 mbgl::FillBucket::drawElements(mbgl::PlainShader&, mbgl::gl::ObjectStore&) + 284
5  Mapbox                         0x10177dd7c mbgl::Painter::renderFill(mbgl::FillBucket&, mbgl::style::FillLayer const&, mbgl::UnwrappedTileID const&, std::__1::array<double, 16ul> const&) + 3852
6  Mapbox                         0x10177abb0 void mbgl::Painter::renderPass<std::__1::reverse_iterator<std::__1::__wrap_iter<mbgl::RenderItem const*> > >(mbgl::RenderPass, std::__1::reverse_iterator<std::__1::__wrap_iter<mbgl::RenderItem const*> >, std::__1::reverse_iterator<std::__1::__wrap_iter<mbgl::RenderItem const*> >, int, signed char) + 688
7  Mapbox                         0x10177a244 mbgl::Painter::render(mbgl::style::Style const&, mbgl::FrameData const&, mbgl::SpriteAtlas&) + 1424
8  Mapbox                         0x1017682ac mbgl::Map::Impl::render() + 160
9  Mapbox                         0x10176811c mbgl::Map::render() + 128
10 Mapbox                         0x1016ec2a8 -[MGLMapView glkView:drawInRect:] + 48
11 GLKit                          0x18a89136c -[GLKView _display:] + 332
12 Mapbox                         0x1016eca44 -[MGLMapView updateFromDisplayLink] + 68
13 QuartzCore                     0x184d38234 CA::Display::DisplayLinkItem::dispatch() + 40
14 QuartzCore                     0x184d380e8 CA::Display::DisplayLink::dispatch_items(unsigned long long, unsigned long long, unsigned long long) + 424
15 IOKit                          0x182475e54 IODispatchCalloutFromCFMessage + 372
16 CoreFoundation                 0x18219d030 __CFMachPortPerform + 180
17 CoreFoundation                 0x1821b57d4 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ + 56
18 CoreFoundation                 0x1821b4f0c __CFRunLoopDoSource1 + 436
19 CoreFoundation                 0x1821b2c64 __CFRunLoopRun + 1800
20 CoreFoundation                 0x1820dcc50 CFRunLoopRunSpecific + 384
21 GraphicsServices               0x1839c4088 GSEventRunModal + 180
22 UIKit                          0x1873c6088 UIApplicationMain + 204
23 PACEApp                        0x1001b9ba8 main (AppDelegate.swift:27)
24 libdispatch.dylib              0x181c7a8b8 (Missing)
```

Other Threads:

```
DefaultFileSource
0  libsystem_kernel.dylib         0x181d7cfd8 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x181d7ce54 mach_msg + 72
2  CoreFoundation                 0x1821b4c60 __CFRunLoopServiceMachPort + 196
3  CoreFoundation                 0x1821b2964 __CFRunLoopRun + 1032
4  CoreFoundation                 0x1820dcc50 CFRunLoopRunSpecific + 384
5  CoreFoundation                 0x18212a3a4 CFRunLoopRun + 112
6  Mapbox                         0x10181b438 void mbgl::util::Thread<mbgl::DefaultFileSource::Impl>::run<std::__1::tuple<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long long&>, 0ul, 1ul>(std::__1::tuple<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long long&>&&, std::__1::integer_sequence<unsigned long, 0ul, 1ul>) + 156
7  Mapbox                         0x10181b358 std::__1::__thread_proxy<std::__1::tuple<mbgl::util::Thread<mbgl::DefaultFileSource::Impl>::Thread<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long long&>(mbgl::util::ThreadContext const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&&&, unsigned long long&&&)::'lambda'()> >(void*, void*) + 136
8  libsystem_pthread.dylib        0x181e63b28 _pthread_body + 156
9  libsystem_pthread.dylib        0x181e63a8c _pthread_body + 154
10 libsystem_pthread.dylib        0x181e61028 thread_start + 4
```

```
AssetFileSource
0  libsystem_kernel.dylib         0x181d7cfd8 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x181d7ce54 mach_msg + 72
2  CoreFoundation                 0x1821b4c60 __CFRunLoopServiceMachPort + 196
3  CoreFoundation                 0x1821b2964 __CFRunLoopRun + 1032
4  CoreFoundation                 0x1820dcc50 CFRunLoopRunSpecific + 384
5  CoreFoundation                 0x18212a3a4 CFRunLoopRun + 112
6  Mapbox                         0x101816150 void mbgl::util::Thread<mbgl::AssetFileSource::Impl>::run<std::__1::tuple<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&>, 0ul>(std::__1::tuple<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&>&&, std::__1::integer_sequence<unsigned long, 0ul>) + 104
7  Mapbox                         0x1018160a4 std::__1::__thread_proxy<std::__1::tuple<mbgl::util::Thread<mbgl::AssetFileSource::Impl>::Thread<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&>(mbgl::util::ThreadContext const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&&&)::'lambda'()> >(void*, void*) + 136
8  libsystem_pthread.dylib        0x181e63b28 _pthread_body + 156
9  libsystem_pthread.dylib        0x181e63a8c _pthread_body + 154
10 libsystem_pthread.dylib        0x181e61028 thread_start + 4
```

And a lot of worker threads that all look the same

```
Worker
0  libsystem_kernel.dylib         0x181d7cfd8 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x181d7ce54 mach_msg + 72
2  CoreFoundation                 0x1821b4c60 __CFRunLoopServiceMachPort + 196
3  CoreFoundation                 0x1821b2964 __CFRunLoopRun + 1032
4  CoreFoundation                 0x1820dcc50 CFRunLoopRunSpecific + 384
5  CoreFoundation                 0x18212a3a4 CFRunLoopRun + 112
6  Mapbox                         0x10180c924 void mbgl::util::Thread<mbgl::Worker::Impl>::run<std::__1::tuple<> >(std::__1::tuple<>&&, std::__1::integer_sequence<unsigned long>) + 88
7  Mapbox                         0x10180c888 std::__1::__thread_proxy<std::__1::tuple<mbgl::util::Thread<mbgl::Worker::Impl>::Thread<>(mbgl::util::ThreadContext const&)::'lambda'()> >(void*, void*) + 136
8  libsystem_pthread.dylib        0x181e63b28 _pthread_body + 156
9  libsystem_pthread.dylib        0x181e63a8c _pthread_body + 154
10 libsystem_pthread.dylib        0x181e61028 thread_start + 4
```

### PR DESCRIPTION
**Pull request by jfirebaugh**
Fixes #5731

### CODE REVIEW

**Comment by jfirebaugh** [comment]
This probably fixes #1509 as well.

**Comment by mb12** [comment]
It most likely doesn't fix #1509. It's a single map with memory under 25 MB the last time I tried. The geometries are literally quads that resselate into two triangles per quad. It doesn't use any symbols etc. The vector tiles are trivial quads literally.

**Comment by kkaefer** [comment]
FWIW, I tried to trigger this particular code path when I debugged the original issue, but couldn't get it to crash even in severely RAM constrained environments, however, I only used one map so there probably was no GL context conflict.

While we're at it: we should also move the call to `style->onLowMemory()` before the painter cleanup; it may release resources that are not cleaned up. We seem to be triggering a rerender, but I'm not sure this is strictly necessary. An alternative could be to not call `painter->cleanup()`, and exclusively rely on the cleanup call that happens as part of the repaint anyway. However, this could potentially worsen the memory situation since a redraw might potentially allocate even more memory.

**Comment by jfirebaugh** [comment]
@brunoabinader @kkaefer -- good ideas. Can you work on followup PRs for those?

**Pull request merged**
