### PR TITLE
Gradle Speed

### PR DESCRIPTION
**Pull request by bleege**
For #978.

### CODE REVIEW

**Comment by kkaefer** [comment]
Thanks for this change. Please don't merge into master if Travis doesn't pass.

**Comment by bleege** [comment]
>  Please don't merge into master if Travis doesn't pass.

Agreed.  This looked like another `false positive` from Travis considering the limited scope of the code change.

**Comment by ljbade** [comment]
@bleege just restart the failed sub job and you should be able to get green without too much fuss. I do wish Travis just 'worked'

**Comment by bleege** [comment]
>  I do wish Travis just 'worked'

+1 brother!

**Pull request merged**
