### PR TITLE
update emerald marker swatch, misc updates to emerald and streets

### PR DESCRIPTION
**Pull request by peterqliu**
fixes https://github.com/mapbox/mapbox-gl-native/issues/1489

also rolls in some minor style updates that we had put off til post-launch, but they seem :ok_hand: while testing them as custom styles. If need be, we can update only the sprite assets, to avoid potential breakage.

cc/ @1ec5 @incanus

### CODE REVIEW

**Comment by 1ec5** [comment]
So far so good with Emerald. What should I look out for when testing mapbox/mapbox-gl-styles@27e8ee84e58bc1a50342102ede000612ad39e49b?

**Comment by peterqliu** [comment]
@nickidlugash ^

**Comment by incanus** [comment]
> If need be, we can update only the sprite assets, to avoid potential breakage.

We should probably play it conservative and go with that. As for approach, one idea is that we could maintain a branch in `mapbox-gl-styles` that we roll into the shipping GL.

**Comment by incanus** [comment]
We've got offset problems now: 

ios simulator screen shot may 11 2015 9 04 33 am

**Comment by peterqliu** [comment]
@incanus those don't look like the markers in the swatch-- did we switch out?

image

**Comment by 1ec5** [comment]
@incanus, maybe you’re running into #1488? That can happen if you use the gear menu to add annotations, then change from Mapbox Streets to Emerald, then cause a redraw by zooming or panning. It wouldn’t be a regression if that’s the case.

**Comment by 1ec5** [comment]
@jfirebaugh and I are unable to reproduce the annotation artifacting in either the beta 1 branch or in the same version of the internal test app that I originally spotted this issue in. So it might be dependent on a more specific set of steps.

**Comment by nickidlugash** [comment]
> What should I look out for when testing mapbox/mapbox-gl-styles@27e8ee8?

@1ec5 Sounds like you guys decided not to add this change into the release, but this change just splits up the water_label layer into two layers, filtered by `area`. One layer is styled the same as the original, the other just has a different `min-zoom` and `text-size`, so I imagine it shouldn't break anything.

**Comment by jfirebaugh** [comment]
Moving to https://github.com/mapbox/mapbox-gl-native/pull/1506 instead.

**Pull request closed without merging**
