### PR TITLE
[core] Eliminate constant attribute bindings

### PR DESCRIPTION
**Pull request by jfirebaugh**
Even though #9185 switched to dynamically compiled shaders that use uniforms rather than constant attributes, we were still calling `glDisableVertexAttribArray` and `glVertexAttrib*` a lot. Although all of the calls are effectively no-ops, they still might have a performance impact, especially on low-end devices. This PR eliminates them.

cc @anandthakker for review of the first commit here.

### CODE REVIEW

**Comment by anandthakker** [comment]
@jfirebaugh good call on 6e3321b -- LGTM 👍

**Comment by kkaefer** [comment]
Added a fix for the render failures we were seeing on CI.

**Comment by jfirebaugh** [comment]
@kkaefer Is there any performance delta on iPad mini?

**Comment by kkaefer** [comment]
| name | before | after |
| --- | --- | --- |
| paris      | 58.8 fps | 59.4 fps |
| paris2     | 59.8 fps | 59.6 fps |
| alps       | 27.4 fps | 27.2 fps |
| us east    | 60.0 fps | 60.0 fps |
| greater la | 51.2 fps | 51.1 fps |
| sf         | 60.1 fps | 60.2 fps |
| oakland    | 60.1 fps | 60.0 fps |
| germany    | 32.0 fps | 32.1 fps |

looks largely identical

**Pull request merged**
