### PR TITLE
Use std::chrono

### PR DESCRIPTION
**Pull request by ljbade**
Fixes https://github.com/mapbox/mapbox-gl-native/issues/784
Fixes https://github.com/mapbox/mapbox-gl-native/issues/783
Fixes https://github.com/mapbox/mapbox-gl-native/issues/801

@jfirebaugh Can you give this a review?

@ansis You may also want to test this to make sure all animations & transitions are working correctly.

### CODE REVIEW

**Comment by ljbade** [comment]
@springmeyer Looks like I am hitting https://github.com/mapbox/mapbox-gl-native/issues/802

**Comment by mikemorris** [comment]
Trying to figure out why [the OS X build is failing here](https://travis-ci.org/mapbox/mapbox-gl-native/jobs/49312596).

**Comment by jfirebaugh** [comment]
:+1: Nice work, code changes look good.

**Comment by ljbade** [comment]
@mikemorris, on @kkaefer's advice I removed all the global `-Wno-error` flags. I need to dive into the iOS code and fixup a few unused references.

**Pull request merged**
