### PR TITLE
[android] add support for mapzen terrarium raster-dem encoding

### PR DESCRIPTION
**Pull request by mollymerp**
remaining tail work from #11224 

basically just guessed here, so if there's more to be done please let me know @tobrun

### CODE REVIEW

**Comment by jfirebaugh** [comment]
If this is intended to be included in boba, please retarget it at `release-boba`. 🙏

**Comment by tobrun** [comment]
Thank you for this @mollymerp, to review I will write a small test around this.

**Comment by LukasPaczos** [comment]
To validate this PR I used [Amazon's tile server](https://aws.amazon.com/public-datasets/terrain/): `https://s3.amazonaws.com/elevation-tiles-prod/terrarium/{z}/{x}/{y}.png`. Results below.

With `mapbox` encoding:
device-2018-03-01-151319

With `terrarium` encoding:
device-2018-03-01-151217

Looks like we are good here @tobrun.

**Comment by mollymerp** [comment]
thank you @LukasPaczos @tobrun !

**Pull request merged**
