### PR TITLE
Fix dialog fragment setup, add regression test

### PR DESCRIPTION
**Pull request by tobrun**
Closes https://github.com/mapbox/mapbox-gl-native/issues/14025, next to fixing the sample code, I added a test to catch regressions.

### CODE REVIEW

**Comment by androideveloper** [comment]
Isn't this PR solving just sample usage case inside Activity? My case was a bit different. I'm using SupportMapFragment inside DialogFragment as a child fragment. I've attached demo project in the issue description.

**Comment by tobrun** [comment]
> Isn't this PR solving just sample usage case inside Activity? My case was a bit different. I'm using SupportMapFragment inside DialogFragment as a child fragment. I've attached demo project in the issue description.

This PR is solving an issue with our DialogFragment sample. Adding a map to a dialogfragment is as shown in the code a bit of a hack. DialogFragment doesn't follow the lifecycle in a same way as normal fragment and that is why we have to override the dismiss callback to do our cleanup. See [here](https://github.com/mapbox/mapbox-gl-native/blob/ba1d5b8b41cc7082cde60d5f3fa4b4d36427ff2a/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/maplayout/MapInDialogActivity.java#L73). Adding such a setup might work for this inner child fragment setup but again, it's more of a hack as a solution.

**Comment by androideveloper** [comment]
I have tried to implement hacky logic, but still the same. Even if I call of lifecycle methods of map inside my parent dialog fragment onDismiss, still the same freeze. What is causing freeze actually? It's somewhere inside native C++ code as I guess.

**Comment by tobrun** [comment]
@androideveloper found the root cause, added code similar to your setup as regression test in https://github.com/mapbox/mapbox-gl-native/pull/14127

**Comment by androideveloper** [comment]
@tobrun Great! Thanks for the update! When are you planning to release it?

**Pull request merged**
