### PR TITLE
fix background-pattern rendering in perspective view

### LINKED ISSUE #3488: switch u_patternmatrix to u_patternscale in pattern shader
the same way it was done here: https://github.com/mapbox/mapbox-gl-js/pull/1886

### LINKED ISSUE #3801: port background rendering from -js
https://github.com/mapbox/mapbox-gl-js/blob/master/js/render/draw_background.js

This is needed to make background patterns work correctly in perspective view.

### PR DESCRIPTION
**Pull request by ansis**
fix #3801
fix #3488
:eyes: @jfirebaugh

### CODE REVIEW

**Comment by jfirebaugh** [comment]
Does this fix #3488 too?

**Comment by ansis** [comment]
Yeah, this fixes #3488

**Comment by jfirebaugh** [comment]
:+1:

**Comment by mb12** [comment]
@ansis Is plainshader needed for cases when the background is not a pattern? glClearColor is already set to background color.

**Comment by ansis** [comment]
@mb12 there is an uncommon but possible case where there are multiple background layers

**Pull request merged**
