### PR TITLE
Migrate iOS and OS X targets to checked-in Xcode projects

### LINKED ISSUE #3275: Migrate iOS targets to checked-in Xcode projects
Currently, on OS X, all libraries and executables are built by Xcode projects generated by gyp. This system is ill-suited for iOS and OS X development: for instance, to add a file to the iOS SDK, you need to move the file to the right folder, `git add` the file, and finally edit the appropriate .gypi file to include it. The process gets even more involved when adding a new target, such as a test bundle: you need to essentially reverse-engineer Xcode’s template for that target to ensure that all the required build settings are persisted across invocations of `make iproj`.

We should migrate the platform-ios and iosapp targets to a checked-in Xcode project, similar to the [ios-tests.xcodeproj](https://github.com/mapbox/mapbox-gl-native/tree/master/test/ios/ios-tests.xcodeproj) that’s already checked in. Adding a new file thus becomes a matter of adding it in Xcode (which handles git and any required build phase updates automatically). If folks are uncomfortable with the idea of maintaining build settings in a .pbxproj file, we can put those settings in .xcconfig files ([example](https://github.com/realm/realm-cocoa/blob/master/Configuration/Realm/Realm.xcconfig)), which are less prone to conflicts.

The new Xcode project would continue to depend on the output of gyp-generated core projects. We’d probably check in a workspace that ties together all the projects to ensure that they get built together. With these changes, we’ll also be able to remove much of the shell scripting that forms the final part of the iOS SDK build process.

/cc @mapbox/gl

### LINKED ISSUE #4191: Allow C99 extensions in iOS and OS X SDK targets
C99 extensions are currently disallowed throughout the project due to pedantic warnings being enabled. This makes no sense in Objective-C code, since we’ve been able to depend on C99 support for years. At the least, the iOS and OS X SDK targets should get a `-Wno-c99-extensions` flag. This will enable us to remove a fair amount of redundant code in MGLMapView.

If any non-SDK Objective-C code needs to use C99-specific features like designated initializers or the Elvis operator, we can selectively turn off the Clang warning via `#pragma clang diagnostic ignored "-Wc99-extensions"` on a case-by-case basis.

/cc @jfirebaugh @boundsj

### LINKED ISSUE #4264: Project warnings in Xcode 7.3b5 — ALWAYS_SEARCH_USER_PATHS
I get several of these warnings building the iOS or OS X SDK in Xcode 7.3b5:

```
warning: using 'ALWAYS_SEARCH_USER_PATHS = YES' while building targets which define modules ('DEFINES_MODULE = YES') may fail. Please migrate to using 'ALWAYS_SEARCH_USER_PATHS = NO'.
```

/cc @kkaefer

### LINKED ISSUE #4481: iOS SDK resource bundle includes SVGs
The iOS SDK’s resource bundle is pulling in platform/default/resources/ for the .der files, but it’s inadvertently pulling in SVG files as well. The iOS SDK has no use for these SVG files; it uses PNGs rasterized from them.

@bleege, does the Android SDK need the SVG files? If not, we should move them to common/.

/cc @boundsj

### LINKED ISSUE #4495: Run “darwin” test suite on iOS
The XCTest-based test suite in platform/darwin/test/ currently runs on OS X. We should get it to run on iOS too. The tests don’t currently take long and we should be able to reuse the OS X SDK tests’ gyp file.

/cc @kkaefer @jfirebaugh

### LINKED ISSUE #4704: Drop support for armv7s?
We should consider dropping support for the `armv7s` architecture and measuring the impact on iPhone 5 devices. Based on what I’m seeing in #4641, I believe omitting support for this architecture (by setting `ARCHS=$(ARCHS_STANDARD)`) will contribute to a significant reduction in the built framework’s size and shave a bit of time off the build.

Major iOS frameworks have already dropped support for `armv7s`. As noted in [this PSPDFKit knowledge base topic](https://pspdfkit.com/guides/ios/current/usage-issues/about-armv7s-support/), Apple no longer requires or encourages building for that architecture, which is only applicable to iPhone 5 and 5c. Those models will fall back to the `armv7` slice, which may be slower with floating-point-heavy operations.

/cc @mapbox/mobile

### PR DESCRIPTION
**Pull request by 1ec5**
This PR replaces the various iOS-specific targets in ios.xcodeproj and OS X–specific targets in osx.xcodeproj with checked-in targets created within Xcode. The core targets remain in the GYP-generated platform.xcodeproj projects. New Xcode workspaces bind ios.xcodeproj to platform.xcodeproj and manages dependencies between the two; likewise for osx.xcodeproj. The ios.xcworkspace also contains ios-test.xcodeproj and KIF.xcodeproj for convenience. (Although we really should be pulling in KIF via a package manager like CocoaPods: #1522.)

You still set up your development environment with `make iproj` and `make xproj`, but now those make rules open the workspace. Other workflows have been streamlined:

* When you add or remove an SDK file, you can do so inside Xcode. No more build failures because you forgot to also update platform.gypi and rerun `make iproj`.
* You can leave the workspace open in Xcode while performing Git operations that add and remove SDK files. You can also run `make iproj` or `make xproj` with the workspace still open.
* You can debug the iOS SDK and core code while running KIF-based integration tests.
* Derived data locations are shared between the Xcode GUI and `xcodebuild` command line tool, so you no longer have to rebuild from scratch when switching between the two. Cleaning in one environment automatically affects the other environment.
* Incremental builds of the SDK are much faster.
* `make clean` is more thorough, wiping away Xcode’s index and module cache along with the intermediate files.
* You can add additional test bundles or demo applications inside Xcode without having to reverse-engineer undocumented GYP features.

libmbgl-platform-ios.a has been reduced to a very small library that contains just the iOS-specific code needed by core code. (The same was done for libmbgl-platform-osx.a in #4608.) The iOS SDK dynamic framework and iOS SDK static library link the core static libraries directly, making it possible for the two to have differing content should the need ever arise. To significantly reduce binary sizes and build times, the iOS SDK no longer builds the `armv7s` slice; iPhone 5 and iPhone 5c will fall back to the `armv7` slice automatically without a noticeable performance hit.

`make test-ios` additionally runs the same “Darwin” unit tests that we’ve been running against the OS X SDK. It’d be trivial to add functional tests (whether the existing KIF tests or future XCUITest tests) to this make rule.

The workspaces come with disabled Objective-C exception breakpoints by default. They also include schemes that exactly replicate what gets built on Bitrise and what gets built by package.sh for distribution.

Project upgrade warnings in GYP targets have been fixed. The default warnings that come with Xcode’s target templates exposed some additional warnings for issues that have been lurking silently in GYP-generated targets; those issues have been fixed. Conversely, the iOS and OS X targets no longer pull in pedantic warnings (treated as errors) from the core targets, so now we can use modern Objective-C syntax, including designated initializers.

The new iOS SDK static library target comes with `OTHER_LDFLAGS=-ObjC` by default, so the various workarounds we’ve been using to avoid `-ObjC` have been removed. The size decrease from removing the `armv7s` slice and from switching to `-Os` optimization in #3183 more than makes up for the addition of `-ObjC`. Developers who manually install the static framework no longer need to set `-ObjC` in their own application targets, so the net effect is a potentially drastic decrease in application size.

Numerous images used by iosapp and the iOS benchmarking application have been placed inside asset catalogs. Storyboards are now localizable. Unused SVG files have been removed from the SDK’s resource bundle.

* [x] Create iosapp.xcodeproj and iosapp target that depends on ios.xcodeproj
* [x] Create ios.xcworkspace
* [x] Bring osxtest over to iOS
* [x] Add ios-tests.xcodeproj to ios.xcworkspace
* [ ] ~~Fold ios-tests.xcodeproj into ios.xcodeproj~~
 * Now planning to replace this test suite with one based on XCUITest after #1496 lands.
* [x] Define dependencies in .xcconfig files
* [x] Move dynamic framework from GYP-generated project to ios.xcodeproj
* [x] Move static library from GYP-generated project to ios.xcodeproj
* [x] Ensure derived data ends up in build/
* [x] Simplify package.sh
* [x] Fix up make rules (ref #4608)
* [x] Do the same for OS X targets
* [x] Update documentation
* [x] Squash uninteresting commits

Fixes #3275, fixes #4481, fixes #4191, fixes #4264, fixes #4704, and fixes #4495.

/cc @boundsj @friedbunny @jfirebaugh @kkaefer

### CODE REVIEW

**Comment by jfirebaugh** [comment]
Is there an advantage to having multiple .xcodeproj files and a workspace, versus a monolithic .xcodeproj with multiple targets?

**Comment by 1ec5** [comment]
Ultimately, I'd like for there to be a workspace with two projects: one that pulls in mbgl, as generated by gyp, and the other that includes targets for iossdk, iosapp, etc.

**Comment by jfirebaugh** [comment]
To adjust from the changes in #4608, you'll need to:

* Change the location of the core .xcodeproj referenced by the workspace. It's now at `build/ios-all/platform/ios/platform.xcodeproj`.
* Remove the targets you want to moving to the checked in .xcodeproj from platform/ios/platform.xcodeproj (`iossdk`, `iosapp`, `ios-bench`, I assume).

I think that's it.

**Comment by jfirebaugh** [comment]
Another change that I recommend making as part of this is to move [all the Objective C sources](https://github.com/mapbox/mapbox-gl-native/blob/f964e40e7e9220d08751d8607af61ac5a7c0794c/platform/ios/platform.gyp#L72-L118) from the `platform-lib` target to the `iossdk` target. 

I did this for the osx platform in #4608 but held off for ios because I'm not familiar with the packaging requirements.

**Comment by 1ec5** [comment]
Thanks for trying to minimize conflicts – much appreciated.

The OS X SDK project is a little simpler because it only produces a dynamic framework. The iOS project produces an intermediate static framework that we actually ship. I think it'll be possible to move them out of the platform-lib target though.

**Comment by 1ec5** [comment]
After moving the SDK classes into the dynamic framework proper, the fat framework sees a 40% size reduction (25 MB), a 66% size reduction after stripping out simulator content (12 MB), and that’s before the extra `strip` invocation in package.sh.

**Comment by 1ec5** [comment]
The size savings are due in part to setting `ARCHS=$(ARCHS_STANDARD)` in build settings for the dynamic and static SDK products. Apparently `$(ARCHS_STANDARD)` omits `armv7s`, which we still include for all gyp-managed targets. I filed #4704 to discuss removing support for this architecture.

**Comment by 1ec5** [comment]
iOS builds continue to fail on Bitrise but not locally with:

```
Application path /Users/vagrant/git/build/ios-all/Debug-iphonesimulator/ios-test.app doesn't exist!
make: *** [test-ios] Error 1
```

**Comment by jfirebaugh** [comment]
I don't know why it would be different on Bitrise than locally for you, but the gyp-generated projects use [this hack](https://github.com/mapbox/mapbox-gl-native/blob/3af3e72bb3cb3f05b33be304d59e66cc244ef4d9/platform/ios/platform.gyp#L6-L10) to force xcodebuild output to `build/ios-all`. Do you have something equivalent in place for the checked in projects / workspace?

**Comment by 1ec5** [comment]
ios.xcodeproj and ios-test.xcodeproj [set the `SYMROOT` as a project-relative path](https://github.com/mapbox/mapbox-gl-native/blob/fc49c17595fab37917c5ac2eac99fdf4d2bd8edc/platform/ios/ios.xcodeproj/project.pbxproj#L1162). However, Xcode workspaces ignore this setting by default, instead placing derived data under ~/Library/. A developer can configure the derived data location for the workspace, but that configuration is normally per-user, in a directory that’s ignored by git. In fc49c17595fab37917c5ac2eac99fdf4d2bd8edc, I moved the workspace configuration into a shared folder, so `SYMROOT` will be honored.

**Comment by 1ec5** [comment]
Turns out that isn’t enough. So instead of bothering with the legacy-style build roots that gyp prefers, I’ve gone ahead and set the `-derivedDataPath` argument to `xcodebuild`, which puts a modern DerivedData directory next to the gyp-generated project.

**Comment by 1ec5** [comment]
This PR has been squashed so that each of the remaining commits should build and be notable in its own right. I’ve updated the PR description to describe in detail all that’s changed.

**Comment by jfirebaugh** [comment]
👏

**Comment by boundsj** [comment]
🎉

**Comment by Gerz-inc** [comment]
Starting with version 3.3 alpha-1 is not possible to connect a static framework. Perhaps additional settings are needed? Version 3.2 connects without problems.

`Ld /Users/MacBook/Library/Developer/Xcode/DerivedData/Taxi-erbmhgfrlvababhfavyiqjkewgeq/Build/Products/Debug-iphoneos/Taxovichkof.app/Taxovichkof normal armv7
    cd "/Users/MacBook/Google Диск/iOS/TaxiApp"
    export IPHONEOS_DEPLOYMENT_TARGET=7.0
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch armv7 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.3.sdk -L/Users/MacBook/Library/Developer/Xcode/DerivedData/Taxi-erbmhgfrlvababhfavyiqjkewgeq/Build/Products/Debug-iphoneos -L/Users/MacBook/Library/Developer/Xcode/DerivedData/Taxi-erbmhgfrlvababhfavyiqjkewgeq/Build/Products/Debug-iphoneos/AFNetworking -L/Users/MacBook/Library/Developer/Xcode/DerivedData/Taxi-erbmhgfrlvababhfavyiqjkewgeq/Build/Products/Debug-iphoneos/Bolts -L/Users/MacBook/Library/Developer/Xcode/DerivedData/Taxi-erbmhgfrlvababhfavyiqjkewgeq/Build/Products/Debug-iphoneos/Facebook-iOS-SDK -L/Users/MacBook/Library/Developer/Xcode/DerivedData/Taxi-erbmhgfrlvababhfavyiqjkewgeq/Build/Products/Debug-iphoneos/Google-API-Client -L/Users/MacBook/Library/Developer/Xcode/DerivedData/Taxi-erbmhgfrlvababhfavyiqjkewgeq/Build/Products/Debug-iphoneos/OpenInChrome -L/Users/MacBook/Library/Developer/Xcode/DerivedData/Taxi-erbmhgfrlvababhfavyiqjkewgeq/Build/Products/Debug-iphoneos/PKMultipartInputStream -L/Users/MacBook/Library/Developer/Xcode/DerivedData/Taxi-erbmhgfrlvababhfavyiqjkewgeq/Build/Products/Debug-iphoneos/SAMTextView -L/Users/MacBook/Library/Developer/Xcode/DerivedData/Taxi-erbmhgfrlvababhfavyiqjkewgeq/Build/Products/Debug-iphoneos/SDWebImage -L/Users/MacBook/Library/Developer/Xcode/DerivedData/Taxi-erbmhgfrlvababhfavyiqjkewgeq/Build/Products/Debug-iphoneos/SSKeychain -L/Users/MacBook/Library/Developer/Xcode/DerivedData/Taxi-erbmhgfrlvababhfavyiqjkewgeq/Build/Products/Debug-iphoneos/ShareKit -L/Users/MacBook/Library/Developer/Xcode/DerivedData/Taxi-erbmhgfrlvababhfavyiqjkewgeq/Build/Products/Debug-iphoneos/UIActivityIndicator-for-SDWebImage -L/Users/MacBook/Library/Developer/Xcode/DerivedData/Taxi-erbmhgfrlvababhfavyiqjkewgeq/Build/Products/Debug-iphoneos/gtm-http-fetcher -L/Users/MacBook/Library/Developer/Xcode/DerivedData/Taxi-erbmhgfrlvababhfavyiqjkewgeq/Build/Products/Debug-iphoneos/gtm-logger -L/Users/MacBook/Library/Developer/Xcode/DerivedData/Taxi-erbmhgfrlvababhfavyiqjkewgeq/Build/Products/Debug-iphoneos/gtm-oauth2 -L/Users/MacBook/Google\ Диск/iOS/TaxiApp/Pods/GoogleAnalytics/Libraries -L/Users/MacBook/Google\ Диск/iOS/TaxiApp/Pods/GoogleConversionTracking/Libraries -L/Users/MacBook/Google\ Диск/iOS/TaxiApp/Pods/GoogleIDFASupport/Libraries -L/Users/MacBook/Google\ Диск/iOS/TaxiApp/Libraries/metrica-sdk-ios-master -L/Users/MacBook/Google\ Диск/iOS/TaxiApp/Libraries/ShareKit-master/Submodules/buffer-ios-sdk/BufferSDK -F/Users/MacBook/Library/Developer/Xcode/DerivedData/Taxi-erbmhgfrlvababhfavyiqjkewgeq/Build/Products/Debug-iphoneos -F/Users/MacBook/Google\ Диск/iOS/TaxiApp/Pods/GoogleMaps/Frameworks -F/Users/MacBook/Google\ Диск/iOS/TaxiApp/Pods/ShareKit/Frameworks -F/Users/MacBook/Google\ Диск/iOS/TaxiApp/Pods/YandexMobileMetrica -F/Users/MacBook/Google\ Диск/iOS/TaxiApp -F/Users/MacBook/Google\ Диск/iOS/TaxiApp/Libraries -F/Users/MacBook/Google\ Диск/iOS/TaxiApp/Libraries/mapbox-ios-sdk-3/static -F/Users/MacBook/Google\ Диск/iOS/TaxiApp/Libraries/ShareKit-master/Frameworks -F/Users/MacBook/Google\ Диск/iOS/TaxiApp/Libraries/ShareKit-master/Frameworks/Pinterest.embeddedframework -F/Users/MacBook/Google\ Диск/iOS/TaxiApp/Libraries/QuincyKit-develop/client/iOS -F/Users/MacBook/Google\ Диск/iOS/TaxiApp/Libraries/FacebookSDKs-iOS-20150910 -filelist /Users/MacBook/Library/Developer/Xcode/DerivedData/Taxi-erbmhgfrlvababhfavyiqjkewgeq/Build/Intermediates/Taxi.build/Debug-iphoneos/Taxovichkof.build/Objects-normal/armv7/Taxovichkof.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -miphoneos-version-min=7.0 -dead_strip -Xlinker -no_deduplicate -lxml2 -ObjC -lAFNetworking -lAdIdAccessLibrary -lBolts -lFacebook-iOS-SDK -lGoogle-API-Client -lGoogleAnalytics -lGoogleConversionTracking -lOpenInChrome -lPKMultipartInputStream -lSAMTextView -lSDWebImage -lSSKeychain -lShareKit -lUIActivityIndicator-for-SDWebImage -lc++ -lgtm-http-fetcher -lgtm-logger -lgtm-oauth2 -licucore -lsqlite3 -lz -framework AVFoundation -framework Accelerate -framework AdSupport -framework AddressBook -framework AssetsLibrary -framework CoreBluetooth -framework CoreData -framework CoreGraphics -framework CoreLocation -framework CoreMedia -framework CoreMotion -framework CoreTelephony -framework CoreText -framework Foundation -framework GLKit -framework GoogleMaps -framework GooglePlus -framework ImageIO -framework MediaPlayer -framework MessageUI -framework MobileCoreServices -framework OpenGLES -framework QuartzCore -framework Security -framework Social -framework SystemConfiguration -framework Twitter -framework UIKit -framework YandexMobileMetrica -weak_framework Accounts -weak_framework AudioToolbox -weak_framework CoreGraphics -weak_framework CoreLocation -weak_framework Foundation -weak_framework QuartzCore -weak_framework SafariServices -weak_framework Security -weak_framework Social -weak_framework UIKit -fobjc-arc -fobjc-link-runtime -lz -lsqlite3 -lc++ -framework QuartzCore -framework ImageIO -framework GLKit -framework AdSupport -framework AudioToolbox -framework CrashReporter -framework MobileCoreServices -framework Security -framework Mapbox -framework SystemConfiguration -framework CoreMotion -framework UIKit -framework MessageUI -framework SafariServices -framework CoreMedia -framework CoreFoundation -framework Foundation -framework AVFoundation -framework AssetsLibrary -framework Accounts -framework MediaPlayer -framework Social -framework CoreData -framework OpenGLES -framework CoreText -framework MapKit -framework LiveSDK -lPods-Taxovichkof -Xlinker -dependency_info -Xlinker /Users/MacBook/Library/Developer/Xcode/DerivedData/Taxi-erbmhgfrlvababhfavyiqjkewgeq/Build/Intermediates/Taxi.build/Debug-iphoneos/Taxovichkof.build/Objects-normal/armv7/Taxovichkof_dependency_info.dat -o /Users/MacBook/Library/Developer/Xcode/DerivedData/Taxi-erbmhgfrlvababhfavyiqjkewgeq/Build/Products/Debug-iphoneos/Taxovichkof.app/Taxovichkof

Undefined symbols for architecture armv7:
  "_OBJC_METACLASS_$_MGLPointAnnotation", referenced from:
      _OBJC_METACLASS_$_TAXMapLocation in TAXMapLocation.o
  "_OBJC_CLASS_$_MGLPointAnnotation", referenced from:
      _OBJC_CLASS_$_TAXMapLocation in TAXMapLocation.o
  "_OBJC_CLASS_$_MGLAnnotationImage", referenced from:
      objc-class-ref in TAXOrderViewController.o
      objc-class-ref in TAXCarsAnimation.o
      objc-class-ref in TAXRadarViewController.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

**Pull request merged**
