### PR TITLE
Fix outline rendering

### LINKED ISSUE #8751: Bugs in fill_outline shader
The fragment shader does `smoothstep(1.0, 0.0, dist)`. But [`smoothstep`'s behavior is undefined](https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/smoothstep.xhtml) when its first argument is >= its second argument. On macOS, it appears that the result is always 0.

Changing it to `smoothstep(0.0, 1.0, dist)` also doesn't work -- except for a band across the middle of the screen, the result value is always 1.0.

Using the following shader modification, you can see it's calculating the distance from the a horizontal line through the center of the viewport, rather than the desired value:

```
    float alpha = dist / 100.0;
    gl_FragColor = vec4(alpha, alpha, alpha, 1.0);
```

image

cc @kkaefer @ansis

### PR DESCRIPTION
**Pull request by kkaefer**
@jfirebaugh discovered in https://github.com/mapbox/mapbox-gl-native/issues/8751 that we are using undefined behavior in the `fill_outline` shader: https://github.com/mapbox/mapbox-gl-js/blob/c0dcee76ed5c7d0559bf271ed85692b1b81c654c/src/shaders/fill_outline.fragment.glsl#L11

It seems that some implementations correctly interpolate between 1.0 and 0.0 based on the `t` value, but per the [spec](https://www.khronos.org/registry/OpenGL-Refpages/es3/html/smoothstep.xhtml), it's undefined behavior.

It also fixes outline rendering, which has regressed at some point.

Current behavior when drawing an outline with a color different from the fill color:

actual

New (and correct) behavior:

expected

We are drawing outlines as antialiased `GL_LINES` around the polygon. When the color is identical to the fill color, we are clipping the outline at the polygon bounds (see first image), but we can't do that when the color is different. Therefore, we either render the fill below or above the line. At some point, this regressed into rendering it always below (and in this case, it's clipped/covered by the fill).

### CODE REVIEW

**Comment by friedbunny** [comment]
This fix looks significant enough to warrant changelog entries (at least, for iOS). 🙇

**Comment by jfirebaugh** [comment]
Working on the failing query test in https://github.com/mapbox/mapbox-gl-js/pull/4604.

**Comment by jfirebaugh** [comment]
@kkaefer Even with these changes, macosapp still isn't rendering correctly for me locally.

image

**Comment by kkaefer** [comment]
@jfirebaugh What GPU are you using locally? What's the maximum line width in your OpenGL implementation?

**Comment by jfirebaugh** [comment]
Intel Iris Graphics 6100, GL_ALIASED_LINE_WIDTH_RANGE = [1, 7], GL_SMOOTH_LINE_WIDTH_RANGE = [0, 7]

**Comment by kkaefer** [comment]
Fixed in https://github.com/mapbox/mapbox-gl-native/pull/9699

**Pull request closed without merging**
