### PR TITLE
iOS Customize Callout Content

### PR DESCRIPTION
**Pull request by mappy-mobile**
Add the ability to customize callout views content via the mapView:calloutViewForAnnotation: callback of MGLMapViewDelegate.

### CODE REVIEW

**Comment by friedbunny** [comment]
This would fix #2211.

**Comment by mappy-mobile** [comment]
I didn't mention issue #2211 because it seems to me that was about totally replacing the callout view.
Maybe both systems can be implemented : 
 - either the user provides a full view ( as requested in #2211)
 - either the user provides only the content as implemented by this pull request

My callback could be renamed to 'calloutContentViewForAnnotation' and we could add a 'calloutViewForAnnotation' for the first use case ?

**Comment by friedbunny** [comment]
@mappy-mobile Ah yes, you're totally right —`calloutViewForAnnotation` threw me, at first glance.

I think our intention should still be to allow complete replacement of the callout view (#2211), but `calloutContentViewForAnnotation`/`centerCalloutContentView` (this PR) may also be useful.

/cc @incanus @1ec5

**Comment by 1ec5** [comment]
Thank you for the pull request! We’re overhauling the callout API in #4948 to remove the SMCalloutView dependency. I’m not sure if we want to allow a halfway-custom callout view in the new API, but let’s see whether the implementation lends itself to something like that.

**Pull request closed without merging**
