### PR TITLE
[android] #4326 - using the camera API vs getCameraPosition 

### LINKED ISSUE #4326: OnCameraChangeListener vs getCameraPosition
A user reported this:

I'm a bit confused about this listener. I'm setting new position (of course just once):

```
 mMapboxMap.moveCamera(CameraUpdateFactory.newLatLngZoom(latLng, zoom)); 
```

That works fine but the problem is with returned value, this is my basic code:

```
private void onCameraChangeListener(CameraPosition cameraPosition) {
        Timber.e("cameraPosition.zoom: " + cameraPosition.zoom + " mMapboxMap.getCameraPosition().zoom: " + mMapboxMap.getCameraPosition().zoom);
}
```

and here is the related log:

```
03-14 16:25:29.785 MapObserver: cameraPosition.zoom: 13.791596412658691 mMapboxMap.getCameraPosition().zoom: 13.791596412658691
03-14 16:25:29.801 MapObserver: cameraPosition.zoom: 14.0 mMapboxMap.getCameraPosition().zoom: 14.0
03-14 16:25:29.802 MapObserver: cameraPosition.zoom: 13.791596412658691 mMapboxMap.getCameraPosition().zoom: 14.0
```

The values coming from `OnCameraChangeListener` and `getCameraPosition` are slightly different.

### PR DESCRIPTION
**Pull request by tobrun**
closes #4326

cc @bleege @zugaldia

### CODE REVIEW

**Comment by tobrun** [comment]
Unit tests don't approve my changes, I now remember why I initially saved the `CameraPosition`, this was for being able to unit test the Camera API. Going to revisit this before this is able to be reviewed.

**Comment by tobrun** [comment]
All right success, got both logic and unit tests aligned correctly:

```
03-21 19:57:33.429 13992-13992/com.mapbox.mapboxsdk.testapp V/MainActivity: OnCameraChange : Target: LatLng [longitude=9.9320668330013, latitude=20.114912700070548, altitude=0.0], Zoom:10.0, Bearing:63.7888069152832, Tilt:0.0
03-21 19:57:33.429 13992-13992/com.mapbox.mapboxsdk.testapp V/MainActivity: OnCameraChange : Target: LatLng [longitude=9.9320668330013, latitude=20.114912700070548, altitude=0.0], Zoom:10.0, Bearing:63.7888069152832, Tilt:0.0
03-21 19:57:33.432 13992-13992/com.mapbox.mapboxsdk.testapp V/MainActivity: OnCameraChange : Target: LatLng [longitude=9.9320668330013, latitude=20.114912700070548, altitude=0.0], Zoom:10.0, Bearing:63.7888069152832, Tilt:0.0
03-21 19:57:33.432 13992-13992/com.mapbox.mapboxsdk.testapp V/MainActivity: OnCameraChange : Target: LatLng [longitude=9.9320668330013, latitude=20.114912700070548, altitude=0.0], Zoom:10.0, Bearing:63.7888069152832, Tilt:0.0
03-21 19:57:33.710 13992-13992/com.mapbox.mapboxsdk.testapp V/MainActivity: OnCameraChange : Target: LatLng [longitude=9.891000463401042, latitude=20.205262308280385, altitude=0.0], Zoom:10.0, Bearing:63.7888069152832, Tilt:0.0
03-21 19:57:33.710 13992-13992/com.mapbox.mapboxsdk.testapp V/MainActivity: OnCameraChange : Target: LatLng [longitude=9.891000463401042, latitude=20.205262308280385, altitude=0.0], Zoom:10.0, Bearing:63.7888069152832, Tilt:0.0
03-21 19:57:33.734 13992-13992/com.mapbox.mapboxsdk.testapp V/MainActivity: OnCameraChange : Target: LatLng [longitude=9.880894384375665, latitude=20.225012231557038, altitude=0.0], Zoom:10.0, Bearing:63.7888069152832, Tilt:0.0
03-21 19:57:33.734 13992-13992/com.mapbox.mapboxsdk.testapp V/MainActivity: OnCameraChange : Target: LatLng [longitude=9.880894384375665, latitude=20.225012231557038, altitude=0.0], Zoom:10.0, Bearing:63.7888069152832, Tilt:0.0
03-21 19:57:33.737 13992-13992/com.mapbox.mapboxsdk.testapp V/MainActivity: OnCameraChange : Target: LatLng [longitude=9.880894384375665, latitude=20.225012231557038, altitude=0.0], Zoom:10.0, Bearing:63.7888069152832, Tilt:0.0
03-21 19:57:33.737 13992-13992/com.mapbox.mapboxsdk.testapp V/MainActivity: OnCameraChange : Target: LatLng [longitude=9.880894384375665, latitude=20.225012231557038, altitude=0.0], Zoom:10.0, Bearing:63.7888069152832, Tilt:0.0
03-21 19:57:34.072 13992-13992/com.mapbox.mapboxsdk.testapp V/MainActivity: OnCameraChange : Target: LatLng [longitude=9.790998149366374, latitude=20.376255914907386, altitude=0.0], Zoom:10.0, Bearing:63.7888069152832, Tilt:0.0
03-21 19:57:34.072 13992-13992/com.mapbox.mapboxsdk.testapp V/MainActivity: OnCameraChange : Target: LatLng [longitude=9.790998149366374, latitude=20.376255914907386, altitude=0.0], Zoom:10.0, Bearing:63.7888069152832, Tilt:0.0
03-21 19:57:34.075 13992-13992/com.mapbox.mapboxsdk.testapp V/MainActivity: OnCameraChange : Target: LatLng [longitude=9.790998149366374, latitude=20.376255914907386, altitude=0.0], Zoom:10.0, Bearing:63.7888069152832, Tilt:0.0
03-21 19:57:34.075 13992-13992/com.mapbox.mapboxsdk.testapp V/MainActivity: OnCameraChange : Target: LatLng [longitude=9.790998149366374, latitude=20.376255914907386, altitude=0.0], Zoom:10.0, Bearing:63.7888069152832, Tilt:0.0
03-21 19:57:34.116 13992-13992/com.mapbox.mapboxsdk.testapp V/MainActivity: OnCameraChange : Target: LatLng [longitude=9.787638240666126, latitude=20.384724312215813, altitude=0.0], Zoom:10.0, Bearing:63.7888069152832, Tilt:0.0
03-21 19:57:34.116 13992-13992/com.mapbox.mapboxsdk.testapp V/MainActivity: OnCameraChange : Target: LatLng [longitude=9.787638240666126, latitude=20.384724312215813, altitude=0.0], Zoom:10.0, Bearing:63.7888069152832, Tilt:0.0
03-21 19:57:34.436 13992-13992/com.mapbox.mapboxsdk.testapp V/MainActivity: OnCameraChange : Target: LatLng [longitude=9.709293933607825, latitude=20.52882995031878, altitude=0.0], Zoom:10.0, Bearing:63.7888069152832, Tilt:0.0
03-21 19:57:34.436 13992-13992/com.mapbox.mapboxsdk.testapp V/MainActivity: OnCameraChange : Target: LatLng [longitude=9.709293933607825, latitude=20.52882995031878, altitude=0.0], Zoom:10.0, Bearing:63.7888069152832, Tilt:0.0
03-21 19:57:34.440 13992-13992/com.mapbox.mapboxsdk.testapp V/MainActivity: OnCameraChange : Target: LatLng [longitude=9.709293933607825, latitude=20.52882995031878, altitude=0.0], Zoom:10.0, Bearing:63.7888069152832, Tilt:0.0
03-21 19:57:34.440 13992-13992/com.mapbox.mapboxsdk.testapp V/MainActivity: OnCameraChange : Target: LatLng [longitude=9.709293933607825, latitude=20.52882995031878, altitude=0.0], Zoom:10.0, Bearing:63.7888069152832, Tilt:0.0
03-21 19:57:34.522 13992-13992/com.mapbox.mapboxsdk.testapp V/MainActivity: OnCameraChange : Target: LatLng [longitude=9.704257805200257, latitude=20.54460684149224, altitude=0.0], Zoom:10.0, Bearing:63.7888069152832, Tilt:0.0
03-21 19:57:34.522 13992-13992/com.mapbox.mapboxsdk.testapp V/MainActivity: OnCameraChange : Target: LatLng [longitude=9.704257805200257, latitude=20.54460684149224, altitude=0.0], Zoom:10.0, Bearing:63.7888069152832, Tilt:0.0
03-21 19:57:34.928 13992-13992/com.mapbox.mapboxsdk.testapp V/MainActivity: OnCameraChange : Target: LatLng [longitude=9.691795204013573, latitude=20.58364195499003, altitude=0.0], Zoom:10.0, Bearing:63.7888069152832, Tilt:0.0
03-21 19:57:34.928 13992-13992/com.mapbox.mapboxsdk.testapp V/MainActivity: OnCameraChange : Target: LatLng [longitude=9.691795204013573, latitude=20.58364195499003, altitude=0.0], Zoom:10.0, Bearing:63.7888069152832, Tilt:0.0
03-21 19:57:35.334 13992-13992/com.mapbox.mapboxsdk.testapp V/MainActivity: OnCameraChange : Target: LatLng [longitude=9.687696918031946, latitude=20.5964763445874, altitude=0.0], Zoom:10.0, Bearing:63.7888069152832, Tilt:0.0
03-21 19:57:35.334 13992-13992/com.mapbox.mapboxsdk.testapp V/MainActivity: OnCameraChange : Target: LatLng [longitude=9.687696918031946, latitude=20.5964763445874, altitude=0.0], Zoom:10.0, Bearing:63.7888069152832, Tilt:0.0
03-21 19:57:36.739 13992-13992/com.mapbox.mapboxsdk.testapp V/MainActivity: OnCameraChange : Target: LatLng [longitude=9.687457819771595, latitude=20.597225082858536, altitude=0.0], Zoom:10.0, Bearing:63.7888069152832, Tilt:0.0
03-21 19:57:36.739 13992-13992/com.mapbox.mapboxsdk.testapp V/MainActivity: OnCameraChange : Target: LatLng [longitude=9.687457819771595, latitude=20.597225082858536, altitude=0.0], Zoom:10.0, Bearing:63.7888069152832, Tilt:0.0
03-21 19:57:36.739 13992-13992/com.mapbox.mapboxsdk.testapp V/MainActivity: OnCameraChange : Target: LatLng [longitude=9.687457819771595, latitude=20.597225082858536, altitude=0.0], Zoom:10.0, Bearing:63.7888069152832, Tilt:0.0
03-21 19:57:36.739 13992-13992/com.mapbox.mapboxsdk.testapp V/MainActivity: OnCameraChange : Target: LatLng [longitude=9.687457819771595, latitude=20.597225082858536, altitude=0.0], Zoom:10.0, Bearing:63.7888069152832, Tilt:0.0
03-21 19:57:37.041 13992-13992/com.mapbox.mapboxsdk.testapp V/MainActivity: OnCameraChange : Target: LatLng [longitude=9.687457819771595, latitude=20.597225082858536, altitude=0.0], Zoom:10.0, Bearing:63.7888069152832, Tilt:0.0
03-21 19:57:37.041 13992-13992/com.mapbox.mapboxsdk.testapp V/MainActivity: OnCameraChange : Target: LatLng [longitude=10.000200000000007, latitude=19.99999999999999, altitude=0.0], Zoom:10.0, Bearing:63.7888069152832, Tilt:0.0
03-21 19:57:37.041 13992-13992/com.mapbox.mapboxsdk.testapp V/MainActivity: OnCameraChange : Target: LatLng [longitude=10.000200000000007, latitude=19.99999999999999, altitude=0.0], Zoom:10.0, Bearing:63.7888069152832, Tilt:0.0
03-21 19:57:37.041 13992-13992/com.mapbox.mapboxsdk.testapp V/MainActivity: OnCameraChange : Target: LatLng [longitude=10.000200000000007, latitude=19.99999999999999, altitude=0.0], Zoom:10.0, Bearing:63.7888069152832, Tilt:0.0
03-21 19:57:37.041 13992-13992/com.mapbox.mapboxsdk.testapp V/MainActivity: OnCameraChange : Target: LatLng [longitude=10.000200000000007, latitude=19.99999999999999, altitude=0.0], Zoom:10.0, Bearing:63.7888069152832, Tilt:0.0
03-21 19:57:37.041 13992-13992/com.mapbox.mapboxsdk.testapp V/MainActivity: OnCameraChange : Target: LatLng [longitude=10.000200000000007, latitude=19.99999999999999, altitude=0.0], Zoom:10.0, Bearing:63.7888069152832, Tilt:0.0
```

Above you can see one line the update to onCameraChangeListener.
Second line is the one from getCameraPosition.

**Comment by bleege** [comment]
Looking at this now.  Build fails on device due to #4175 being fixed after this branch.  Will rebase and try again.

**Comment by bleege** [comment]
I tested it out by adding an extra Log statement to the MainActivity.java locally that prints out the `MapboxMap.getCameraPosition()` below the `CameraPostition` object that comes via  `onCameraChange()` (see screenshot below).  I then double tapped on the map (specifically around Germany) and the logs below show that things are working as expected.

screen shot 2016-03-21 at 4 47 07 pm
_Double Logs_

```java
03-21 16:50:07.156 5875-5875/com.mapbox.mapboxsdk.testapp I/ScaleGestureDetector: TwScaleGestureDetector
03-21 16:50:07.206 5875-5875/com.mapbox.mapboxsdk.testapp I/MainActivity: OnCameraChange : Target: LatLng [longitude=8.58682048174606, latitude=6.799765818497882, altitude=0.0], Zoom:1.126704454421997, Bearing:-0.0, Tilt:0.0
03-21 16:50:07.206 5875-5875/com.mapbox.mapboxsdk.testapp I/MainActivity: OnCameraChange (Map) : Target: LatLng [longitude=8.58682048174606, latitude=6.799765818497882, altitude=0.0], Zoom:1.126704454421997, Bearing:-0.0, Tilt:0.0
03-21 16:50:07.516 5875-5875/com.mapbox.mapboxsdk.testapp I/MainActivity: OnCameraChange : Target: LatLng [longitude=11.747702808721641, latitude=30.420113153936104, altitude=0.0], Zoom:2.126704454421997, Bearing:-0.0, Tilt:0.0
03-21 16:50:07.516 5875-5875/com.mapbox.mapboxsdk.testapp I/MainActivity: OnCameraChange (Map) : Target: LatLng [longitude=11.747702808721641, latitude=30.420113153936104, altitude=0.0], Zoom:2.126704454421997, Bearing:-0.0, Tilt:0.0
```

Next step is to merge into `release-ios-3.2.0-android-4.0.0`.

**Comment by bleege** [comment]
Rebased and merged on to `release-ios-3.2.0-android-4.0.0`.  Since this PR was against the release branch will rely on the post release merge back into `master` to bring this functionality back inline.

screen shot 2016-03-21 at 4 59 52 pm

/cc @jfirebaugh

**Pull request closed without merging**
