### PR TITLE
[Android] fix Czech translations for telemetry dialog

### PR DESCRIPTION
**Pull request by hrach**

### CODE REVIEW

**Comment by LukasPaczos** [comment]
Sorry, I thought those could go in separately. Here's the link @hrach, if you'd like to contribute there as well - https://www.transifex.com/mapbox/mapbox-gl-native/.

**Comment by hrach** [comment]
Well, sorry to wrongly contribute. I've tried to setup a transifex account, but it seems to require an approval for joining the team - knowing that before registration I would say feel free to copy the texts over there :)

**Comment by LukasPaczos** [comment]
Alright, I'll do that, thanks again @hrach!

**Comment by hrach** [comment]
Thanks :)

**Pull request closed without merging**
