### PR TITLE
[ios] Add MGLMapView.showsScale to control scale bar visibility

### LINKED ISSUE #11302: scaleBar remains hidden until the map's visible region changes
**Platform: iOS**
**Mapbox SDK version: 3.7.5**

### Steps to trigger behavior

- Create an MGLMapView and immediately set `mapView.scaleBar.isHidden = false`.

I'm creating the MGLMapView, and adding it to the view hierarchy, programmatically rather than using a storyboard — not sure if that matters for reproducing this.

### Expected behavior

I expected the scale bar to be visible as soon as the view appears. (This is what I'm trying to achieve in my app: a scale bar that's visible 100% of the time.)

### Actual behavior

The scale bar remains hidden initially. But as soon as the user pans or zooms the map, the scale bar does become.

### PR DESCRIPTION
**Pull request by friedbunny**
- Adds `MGLMapView.showsScale` as the recommended way to show the scale bar.
- Adds `IBInspectable` for scale bar visibility.
- Fixes #11302, where the scale bar was not visible until a camera change event. _See note about `scaleBar.hidden` below._
- Includes _two_ changelog entries, because I couldn’t see a concise way to combine the new property with the bug fix.

This isn’t technically breaking — setting `MGLMapView.scaleBar.hidden = NO` will still work, but is no longer the recommended approach.

Setting the scale bar view’s `hidden` property at initialization will now properly show that view when the map loads (because of the new `updateScaleBar` call in `cameraDidChangeAnimated:`), but setting this property later will still cause it not to be visible until a camera event occurs. The new `showsScale` property avoids this issue by calling `updateScaleBar` itself.

/cc @frederoni @1ec5 @fabian-guerra

### CODE REVIEW

**Comment by friedbunny** [comment]
Thanks for the review, @fabian-guerra. These changes would be easy to retarget at `release-agua`, but I didn’t do that initially because a “soft deprecation” (i.e., changing the recommended way of showing the scale bar without breaking the old way) feels more appropriate for a semver minor or major release.

I’m not obstinately in that camp, though, so if folks feel like we should put this in the next v3.7.x patch release I can go ahead and retarget this PR.

**Comment by 1ec5** [comment]
Per https://github.com/mapbox/mapbox-gl-native/issues/11302#issuecomment-369189897, I’m wondering if we aren’t papering over a subtle bug with this change.

**Comment by friedbunny** [comment]
@1ec5 There may be an issue there, but I believe it’s incidental to the problems solved here:

- The initial visibility of the scale bar should not be tied to any camera change event. Making sure the map gets `cameraIsChanging` on its first load would not fix the case where a developer enables the scale bar after map initialization.
- We need to update the scale bar both on `cameraIsChanging` and `cameraDidChange`, as the final value may be different than the last reported intermediate value.

**Comment by friedbunny** [comment]
Added tests to verify that the scale bar is appearing when it should.

**Pull request merged**
