### PR TITLE
Saving/restoring MyLocationViewSettings

### LINKED ISSUE #10628: Location marker disappear when orientation changes
**Platform:** Android 8.0.0
**Mapbox SDK version:** 5.2.0

### Steps to trigger behavior

 1. Open activity with locationview in portrait mode
 2. Rotate device to landscape
 3. LocationView marker dissapear

### Expected behavior
Location marker should be there as activity recreated

### Actual behavior

Location marker disappears

PS: I checked Location Layer plugin.Its not in state to completely replace LocationView, So sticking with LocationView for now and facing this issue.

### PR DESCRIPTION
**Pull request by LukasPaczos**
Fixes #10628.

location-view-settings

### CODE REVIEW

**Comment by LukasPaczos** [comment]
Good catch @tobrun. Can you :eyes: now?

**Comment by mdakram** [comment]
@LukasPaczos @tobrun Thanks for the [fix,](https://github.com/mapbox/mapbox-gl-native/issues/10628) But there is another bug popped up.

Step to reproduce.
Run Any activity with location marker on it.->Take app in background.->Bring app in foreground

Location marker is splitting in two parts attached is screenshot.(Device is OnePlus 3T running Oreo)

whatsapp image 2017-12-20 at 16 12 45

**Comment by LukasPaczos** [comment]
@mdakram Unfortunately, I wasn't able to reproduce the issue following the presented steps. Is there a possibility that you could try using a different device? Is this 100% reproducible on 3T?

**Comment by mdakram** [comment]
Hi @LukasPaczos yes its 100% reproducible. I have tried it on nexus 5x simulator as well, its there.

**Comment by LukasPaczos** [comment]
@mdakram let's continue this in https://github.com/mapbox/mapbox-gl-native/issues/10761.

**Pull request merged**
