### PR TITLE
Merge Android 4.1.0 Release Branch Into Master

### PR DESCRIPTION
**Pull request by bleege**
Now that Mapbox Android 4.1.0 has been released ( #5510 ) it's time to merge the release branch back into `master` and update the automated nightly SNAPSHOT build process to build from `master` again.

/cc @jfirebaugh @zugaldia @ivovandongen @tobrun @cammace

### CODE REVIEW

**Comment by jfirebaugh** [comment]
Conflicts here:

```
CONFLICT (content): Merge conflict in test/api/annotations.cpp
CONFLICT (modify/delete): src/mbgl/tile/vector_tile_data.hpp deleted in HEAD and modified in origin/release-android-v4.1.0. Version origin/release-android-v4.1.0 of src/mbgl/tile/vector_tile_data.hpp left in tree.
CONFLICT (modify/delete): src/mbgl/tile/vector_tile_data.cpp deleted in HEAD and modified in origin/release-android-v4.1.0. Version origin/release-android-v4.1.0 of src/mbgl/tile/vector_tile_data.cpp left in tree.
CONFLICT (content): Merge conflict in src/mbgl/tile/tile_worker.hpp
CONFLICT (content): Merge conflict in src/mbgl/tile/tile_worker.cpp
CONFLICT (content): Merge conflict in src/mbgl/style/style.hpp
CONFLICT (content): Merge conflict in src/mbgl/style/style.cpp
CONFLICT (content): Merge conflict in src/mbgl/map/map.cpp
CONFLICT (content): Merge conflict in src/mbgl/annotation/annotation_manager.hpp
CONFLICT (content): Merge conflict in src/mbgl/annotation/annotation_manager.cpp
CONFLICT (rename/delete): platform/macos/INSTALL.md deleted in HEAD and renamed in origin/release-android-v4.1.0. Version origin/release-android-v4.1.0 of platform/macos/INSTALL.md left in tree.
CONFLICT (rename/delete): platform/macos/CHANGELOG.md deleted in HEAD and renamed in origin/release-android-v4.1.0. Version origin/release-android-v4.1.0 of platform/macos/CHANGELOG.md left in tree.
CONFLICT (content): Merge conflict in README.md
CONFLICT (content): Merge conflict in Makefile
```

Let me look at these in more detail later today.

**Comment by bleege** [comment]
@jfirebaugh Sounds good.  I'll list you as the Assignee on this to bring it home.  Thanks!

**Comment by jfirebaugh** [comment]
Does 03f30f52078262c1dfaf60ffb35a287a63ff9a59 look good?

The conflicts were due to 11dd4afc5b271c4efb0e900320bdca4d137cd049, where I hand-ported changes that were already in master, and 2893f39249650bac8c5c4c4edf6600018e811642, cherry picking the macOS rename. So in all cases I resolved simply by accepting `master`'s version of the file.

**Comment by bleege** [comment]
@jfirebaugh Yep, accepting the changes from `master` in the case of the conflicted C++ files is the right call.  Thank you for working through this and getting us all back on `master` now.

To finish things off I'll going to reset the nightly SNAPSHOT process to work from `master` and then delete the `release-android-v4.1.0` release branch now.

**Pull request merged**
