### PR TITLE
[android]  #3251 - add offline directions example to test app

### LINKED ISSUE #3251: Directions Example In TestApp
To help people better self serve let's build a simple Directions activity in the TestApp.  All it needs to do is draw markers for the starting and stopping points and a polyline for the route.  The data can be cached JSON from an actual request to [Mapbox Directions](https://www.mapbox.com/developers/api/directions/).

/cc @zugaldia @tobrun @mapbox/support

### PR DESCRIPTION
**Pull request by tobrun**
Closes #3251

### CODE REVIEW

**Comment by tobrun** [comment]
Need to merge and test #3350 before merging this

**Comment by mb12** [comment]
@tobrun why is this called "offline" direction? Route computation is not happening on the client or is it?

**Comment by tobrun** [comment]
@mb12 Maybe `mocked` instead of `offline` would have been a better choice of words.

**Comment by tobrun** [comment]
@mb12 see this [directions.json](https://raw.githubusercontent.com/mapbox/mapbox-gl-native/3251-add-Directions-sample-app/platform/android/MapboxGLAndroidSDKTestApp/src/main/assets/directions.json) in the assets folder.

**Comment by zugaldia** [comment]
@tobrun I have adapted your sample to use the new Directions SDK here: https://github.com/mapbox/mapbox-gl-native/compare/3484-directions-sdk

Let's just use that branch instead of this one?

**Comment by tobrun** [comment]
@zugaldia, let's close and delete this one, great job!

**Pull request closed without merging**
