### PR TITLE
Run full test suite on CI

### PR DESCRIPTION
**Pull request by tobrun**
This PR tests if we are able to run all instrumentation tests in a timely fashion. We were recently able to speed up the tests with https://github.com/mapbox/mapbox-gl-native/commit/c9c2e96240b17ce4bd32729a66cdd3ff213aa313.

### CODE REVIEW

**Comment by tobrun** [comment]
screen shot 2017-10-31 at 13 33 27

**Comment by tobrun** [comment]
Note that full firebase step on Circle CI took 10 minutes:
 - uploading apks to firebase
 - waiting for an available device
 - running the tests
 - downloading the results

screen shot 2017-10-31 at 13 37 42

**Comment by tobrun** [comment]
Adding here that the total build time is something between 16 <-> 20 minutes. 
Atm the node build is running for 25 minutes, so I feel this is justifiable.

**Comment by friedbunny** [comment]
@tobrun This is now always the longest build on CircleCI, especially for cached rebuilds. For instance, [this build](https://circleci.com/gh/mapbox/mapbox-gl-native/45863) took 22:47, while the next-longest was [`clang-tidy`](https://circleci.com/gh/mapbox/mapbox-gl-native/45854) at 11:43.

Can we revisit when and how often we run these tests? 🙇

**Pull request merged**
