### PR TITLE
Explicit Opt Out Checking

### PR DESCRIPTION
**Pull request by bleege**
For #1516

### CODE REVIEW

**Comment by jfirebaugh** [comment]
@bleege What's up with the commits in this PR? Did you branch off `ios-b1` and then make a pull request against `master`?

**Comment by bleege** [comment]
@jfirebaugh good catch.  this is supposed to be off of `ios-beta1`.  i'll fix this.

**Comment by incanus** [comment]
We should be dev'ing off of `master`, committing critical b1-related changes, and then cherry-picking to `ios-b1`.

**Comment by bleege** [comment]
Reopening as @incanus is correct that we should be going `dev_branch` --> `master` --> `ios-1` with code.

**Comment by bleege** [comment]
@1ec5 suggestions have been implemented, tested locally, and now Travis approved.  Time to merge to `master`.

**Comment by jfirebaugh** [comment]
@bleege You branched off of `ios-b1`, but then you merged to `master`. This had the effect of merging `ios-b1` to master. We were probably going to do that anyway, but I would have rather have done it as an explicit decision rather than as a byproduct of an unrelated change.

**Comment by bleege** [comment]
@jfirebaugh Yep, looks like my troubles branching last night carried over to this morning.  Sorry about that.

**Comment by bleege** [comment]
@1ec5 The getter is now added!  Created #1528 to bring it into master.  I'll let you merge this time!  :-)

**Comment by incanus** [comment]
Love it.

**Pull request merged**
