### PR TITLE
[android] - Add touch velocity effects on scale and rotation gesture.

### PR DESCRIPTION
**Pull request by rooholam**
Track fingers velocity for scale and rotation gesture.

ezgif com-optimize 1

### CODE REVIEW

**Comment by tobrun** [comment]
@rooholam thank you for this contribution, putting on my radar to review, this is definitely an UX that we are considering to add (similar for rotation and other gestures).

**Comment by rooholam** [comment]
@tobrun I committed codes for rotating gesture too.
Hope you find it useful.

**Comment by tobrun** [comment]
@rooholam tested this out and this is a great start! We might need to fine-tune a couple of things  before we will merge this (eg. the focal point used when the velocity animation starts) but thank you for this contribution! Note we might bring this functionality at the same time as we replace the animations with Android SDK animators.

**Comment by tobrun** [comment]
I've pulled in the changesd in #10202 and work further from there to integrate these changes in the SDK. Thanks again for the contribution.

**Pull request closed without merging**
