### PR TITLE
Filtering compass changes in Android

### PR DESCRIPTION
**Pull request by erf**
I've added a low pass filter for averaging compass directional changes, i also use time and angle to limit these updates. Used in the MapboxGLAndroidSDKTestApp.

Improvement for issue  #1676

### CODE REVIEW

**Comment by ljbade** [comment]
Tried testing it on my Sony Z3 but unfortunately today the compass sensor does not want to co-operate - was point in every direction but the right one (was doing the same thing in Google Maps)

Looking at the code, can you make a few tweaks:
- use camelCase for the variable names
- remove the commented out lines

**Comment by erf** [comment]
I also had compass problems on S3, but it's much better on nexus 7. Maybe the algorithm can be improved upon.

I'll fix those issues, BTW, i am quite new to pull requests - do i add a new commit to the current branch or create a new?

**Comment by bleege** [comment]
Thanks @erf!  Moving to `0.2.0` for now though.

**Comment by tobrun** [comment]
@erf 
I wanted to thank you for this contribution, I have been playing around with your suggestion. Your code has helped me a lot on setting this up but I must mention I have removed it again. Instead I'm rate limiting the sensor input and I'm seeing great improvements on lowering memory churn.

**Comment by erf** [comment]
@tobrun No worries! I'm glad you are doing progress.

**Pull request closed without merging**
