### PR TITLE
[core] Blocking the Map Thread when destroying TileData objects

### PR DESCRIPTION
**Pull request by tmpsantos**
We create and destroy TileData objects constantly, specially when zooming in/out fast, and we might block and destroying them. This issue is noticeable on iOS (tested on a iPad Mini 2 Retina) and can be reproduced two ways:

- Pinch the map fast, zooming in and out and you will see the map hanging sometimes.
- Move the map to a place somewhat far from the current location and click on the top right button to trigger a "fly to" animation, that should hang a few times (can be made worse with the map on full tilt).

While the first scenario is hardly a real life use case, the second is. The root cause is that we cannot cancel worker tasks once they are started (see #2644).

### CODE REVIEW

**Comment by tmpsantos** [comment]
:eyes: @jfirebaugh @kkaefer

**Comment by tmpsantos** [comment]
Also easy to see using the "Start World Tour" option on the iOS app.

**Comment by jfirebaugh** [comment]
This adds additional complexity to an area where reasoning about threading behavior and object lifetimes is already difficult. I would much prefer we continue to investigate and eliminate the direct causes of blocking, rather than delaying TileData destructors.

**Comment by tmpsantos** [comment]
> This adds additional complexity to an area where reasoning about threading behavior and object lifetimes is already difficult. I would much prefer we continue to investigate and eliminate the direct causes of blocking, rather than delaying TileData destructors.

The alternative I see would be change how we use workers. We would always transfer the ownership of what is pass on the parameters to the worker, so cancellation would still need a mutex for flipping a flag, but executing the task on the worker would not acquire that mutex. The worker would only acquire the mutex for posting back the callback to the Map Thread or not if it was cancelled.

Canceling an ongoing task would be a matter of let the task go on and self destruct at the end. Only destroying the worker itself would block.

Good thing is these objects momentarily owned by the worker would be destroyed on the worker thread in this case, offloading the destruction job from the Map Thread, but I don't think this will make a difference. The advantage I see is cancelling a task can be considered effectively non-blocking (not truly because the cancellation flag mutex).

Bad thing is we need to enforce a safe design pattern that I don't think it can be done programmatically like it is today. We would only pass as arguments to the worker `std::unique_ptr` or `std::shared_ptr`. The later only to immutable objects.

**Comment by 1ec5** [comment]
Pulling off the 3.1.0 milestone given #3731.

**Comment by kkaefer** [comment]
Thinking some more about this, I think we should actually implement what @tmpsantos is suggesting in https://github.com/mapbox/mapbox-gl-native/pull/3724#issuecomment-176742934. Having a custom deleter will add unnecessary complexity and essentially add a custom deferred shared pointer destruction that could be very complicated to debug.

This is what our workers currently use: 

- layers from the stylesheet (these are already copied ✓)
- actual tile data (they are moved ✓)
- placement configuration (already copied ✓)
- tile ID, source ID, map mode (already copied ✓)
- **SpriteStore, GlyphAtlas, GlyphStore**, these are currently references and shared among all workers and the main thread. In JS, these live on the main thread, and web workers get a copy when initializing and communicate with the main thread to mutate them. We should do this in native as well, and make it easier to communicate across thread boundaries.

**Comment by jfirebaugh** [comment]
Agreed @kkaefer; that's been our long term goal since #667.

**Comment by jfirebaugh** [comment]
Closing; I think we should investigate alternative solutions here per above comments.

**Pull request closed without merging**
