### PR TITLE
Configuration for limiting resource visibility

### PR DESCRIPTION
**Pull request by tobrun**
See issue #2223

### CODE REVIEW

**Comment by ljbade** [comment]
Looks good, to me, I'll merge it.

**Comment by ljbade** [comment]
Oh, wait the commit branch is not in `mapbox-gl-native` repo?

**Comment by ljbade** [comment]
@tobrun Can you move it into `mapbox-gl-native` - easiest way is to [change the git remote URL](https://help.github.com/articles/changing-a-remote-s-url/) for the branch to point to `mapbox/mapbox-gl-native` and do a `git push`

**Comment by tobrun** [comment]
Done, result at #2442, closing..

**Pull request closed without merging**
