### PR TITLE
Centralize tile cache size

### LINKED ISSUE #8039: Core and iOS bindings fight over in memory tile cache size
[This code](https://github.com/mapbox/mapbox-gl-native/blob/e8065cfc1084343e10a63c3dec589f99e8be49a8/src/mbgl/style/source_impl.cpp#L142-L149) in source_impl.cpp sets the tile size based on the viewport size, zoom range, and source tile size. It will be executed whenever `updateTiles` is called, i.e. whenever the camera changes. This calculation was recently tuned (#7739) to produce better results.

[This code](https://github.com/mapbox/mapbox-gl-native/blob/272dc3f6a91ee1f0734c6642d610366f4396ec93/platform/ios/src/MGLMapView.mm#L759-L767) in the iOS bindings includes several other factors, but it does not include the tuning factors introduced in #7739. [macOS](https://github.com/mapbox/mapbox-gl-native/blob/fe3f63dbffbf890781a4e75cc29d3f08a5c213b2/platform/macos/src/MGLMapView.mm#L793-L800) and [Android](https://github.com/mapbox/mapbox-gl-native/blob/f1c06f8d837b57c1b10677fb5317f0bf20987cf6/platform/android/src/native_map_view.cpp#L81-L88) have similar code.

We need to have a single source of truth for calculating tile size. Since this is an internal implementation detail of the core implementation, it's best handled there. If environment specific factors like total memory size need to be taken into account -- and it's not clear to me that they do -- then that should be done by having core make calls out to a platform-provided API, like we do for timers, image IO, etc.

### PR DESCRIPTION
**Pull request by ivovandongen**
Fixes #8039

### CODE REVIEW

**Comment by jfirebaugh** [comment]
Let's get an idea of what the net effect is -- on typical devices, and assuming that the SDK sizing would have won the fight, is this going to increase or decrease the cache size?

**Comment by ivovandongen** [comment]
The cache size will decrease in all cases:

Low-end (IPhone 5S: dual core, 1GB, 320 × 568 points screen):
- Old calculation: 14
- New calculation: 11

High-End (IPhone 7+: quad core, 3GB, 414 × 736 points screen):
- Old calculation: 147
- New calculation: 14

Memory (1 vs 3) and cpu (2 vs 4) changes the outcome significantly.

**Comment by ivovandongen** [comment]
Turns out that the core cache size already won out on iOS, macOS and Android. So in reality, the cache size will be the same. Good to merge @1ec5 ?

**Comment by 1ec5** [comment]
:shipit:

**Pull request merged**
