### PR TITLE
Do not pass uv_loop_t around

### PR DESCRIPTION
**Pull request by tmpsantos**
Use util::RunLoop::getLoop() instead when it is needed. This will
simplify a bit our interfaces.

### CODE REVIEW

**Comment by tmpsantos** [comment]
@jfirebaugh review?

**Comment by jfirebaugh** [comment]
I think I'm :-1: on this change -- it introduces more reliance on what is effectively a global variable, which hides these classes dependency on an active run loop, and can make things more difficult to test (I recall some tests passing `uv_default_loop()` rather than creating a `RunLoop`).

**Comment by tmpsantos** [comment]
> I think I'm  on this change -- it introduces more reliance on what is effectively a global variable, which hides these classes dependency on an active run loop, and can make things more difficult to test (I recall some tests passing uv_default_loop() rather than creating a RunLoop).

That is true indeed, but I think it used to be the case before mbgl::Thread. Now I think it is very safe to assume that you always have a main loop per thread (exception being the Main thread that we don't assume any main loop at all).

What I tried to solve here is instead of receiving a loop reference that you don't know if it belongs to your current thread, you now say: reply to my thread, so use my current main loop.

And regarding the tests, we have to run them on a mbgl::Thread anyway because we have assertions like `currentlyOn(Map)` everywhere. That was the case for all the style tests I wrote.

**Comment by jfirebaugh** [comment]
How about a compromise: remove the argument from the places where a `RunLoop`/`uv_loop_t*` dependency is "expected" (the `::Impl`s and `MapContext`), but leave it in `Style` and `GlyphStore` -- which are domain objects that shouldn't really have this dependency -- as a reminder that it's awkward and we'd like to properly remove it.

**Comment by tmpsantos** [comment]
> How about a compromise: remove the argument from the places where a RunLoop/uv_loop_t* dependency is "expected" (the ::Impls and MapContext), but leave it in Style and GlyphStore -- which are domain objects that shouldn't really have this dependency -- as a reminder that it's awkward and we'd like to properly remove it.

Sounds great! :+1:

**Pull request merged**
