### PR TITLE
[android] Replace libuv with Looper

### PR DESCRIPTION
**Pull request by tmpsantos**
Looper ships with Android and can provide the same functionality.

### CODE REVIEW

**Comment by tmpsantos** [comment]
:eyes: @jfirebaugh @tobrun @zugaldia @bleege 

This is a step towards https://github.com/mapbox/mapbox-gl-native/pull/2909

**Comment by tmpsantos** [comment]
Marking as `DO NOT MERGE` because although it is apparently working just fine, I would feel more comfortable after getting the utests running on Android.

**Comment by zugaldia** [comment]
@tmpsantos thank you!

@tobrun let's schedule a new battery of tests on Monday?

**Comment by zugaldia** [comment]
Related: https://github.com/mapbox/mapbox-gl-native/issues/3440

**Comment by tobrun** [comment]
@zugaldia I will look into those performance tests

**Comment by jfirebaugh** [comment]
Also noting that we want to hold off merging this until after we branch for the 4.0.0 release.

**Comment by bleege** [comment]
Discussed with @tmpsantos in chat and will pick this up now.  I'll build it locally to make sure the TestApp works as expected.  From there I'll rebase and make sure CI is happy.

**Comment by bleege** [comment]
Local tests worked great!  I'm going to rebase now and push back to the branch so that we can run the CI on it before merging back to master.

**Comment by bleege** [comment]
Rebased, but the only way to push to GitHub required a `git pull` first from the remote branch which created a merge commit.  Everything appears to be as expected.  Will wait for CI to playout before merging to `master`.

**Comment by bleege** [comment]
All CI save the Android build passed.  Will explore.

**Comment by bleege** [comment]
Error turned out to be the following.  Will try to resolve locally and push again for CI.

```
[1m[32m* Recreating project...[0m
gyp: Undefined variable libuv_cflags in gyp/mbgl.gyp
make[1]: Leaving directory `/bitrise/src'
make[1]: *** [Makefile/__project__] Error 1
make: *** [android-lib] Error 2
```

**Comment by bleege** [comment]
As best I can tell some other C++ configs shifted between when @tmpsantos first wrote his 3 commits and now.  To rule out a possible messed up rebase and merge, I created a new branch based off `master` today (commit 81261cafaba781293d8359fa609373afab3c6337) and then tried cherrypicking @tmpsantos's original 3 commits from this PR on to it.  I did this in a time sequential manor to mirror @tmpsantos original work and then ran `make android` after each cherrypick.  The first two (Introduce and Attach RunLoop) both cherrypicked cleanly and executed `make android` just fine.  However when the third commit (Replace libuv with Looper) was cherrypicked the `make android` command ended with the same error as above.  Based on what I can see (see attached screenshot), but it appears that the build script is still trying to build with libuv as indicated by the `loop=uv` print out.

* Introduce RunLoop ( a610d145974f7ce76499720681b0a6e8f0f6e7c9 )
* Attach thread on RunLoop ( 9b15e6ee899353807cd509793ae76a6bc20faf9b )
* Replace libuv With Looper ( ea699ec050e9142273364887d7775dd60e295517 )

screen shot 2016-04-05 at 4 25 40 pm
_Is `loop=uv` Still Being Used?_

**Comment by jfirebaugh** [comment]
Give me a second and I'll be available to fix this up.

**Comment by bleege** [comment]
Forgot to mention that my test branch is called `3440-replace-libuv` and is available for :eyes: at:

https://github.com/mapbox/mapbox-gl-native/commits/3440-replace-libuv

**Comment by tmpsantos** [comment]
Got is fixed and merged!

**Comment by bleege** [comment]
Ah ha!  Libuv had to also be [turned off in `defaults.mk`](https://github.com/mapbox/mapbox-gl-native/pull/4280/files#diff-ae9095196f14c099381fb3ecb7796739R5)  Thanks again for making this happen @tmpsantos!

**Pull request merged**
