### PR TITLE
Update libuv to 1.7.5

### PR DESCRIPTION
**Pull request by mikemorris**
Update from ancient v0.10.28 across all platforms, but retain support for older versions.

/cc @kkaefer

### CODE REVIEW

**Comment by kkaefer** [comment]
Looks great! Thanks for rolling this PR!

**Comment by mikemorris** [comment]
Screwed up the `-ff-only` merge by pushing `master` first, then force-pushing `update-libuv`.
This pull request contained the following commits:
- https://github.com/mapbox/mapbox-gl-native/commit/62595a9b394547bffb8c2965b103bd87dd397e15
- https://github.com/mapbox/mapbox-gl-native/commit/071dbcf44cc394a95a15ba172c4ed3ed018c5eca

**Comment by picciano** [comment]
Is this update to address some of the crashing we are seeing? Such as https://github.com/mapbox/mapbox-gl-native/issues/2417 ?

**Comment by mikemorris** [comment]
Motivated more by simply wanting to move off of an ancient version of libuv, I'd be curious to know if this does anything to address #2417. If not, the bug is likely in `mbgl::HTTPNSURLRequest::handleResult()` as @1ec5 [mentioned](https://github.com/mapbox/mapbox-gl-native/issues/2417#issuecomment-146713260).

**Pull request closed without merging**
