### PR TITLE
Reorganize documentation

### PR DESCRIPTION
**Pull request by 1ec5**
Rewrote some copy to provide more context and link to more GL-related repos, including GL JS. Put the various SDKs in a table so we can show all three Bitrise bots’ status.

/cc @jfirebaugh @friedbunny

### CODE REVIEW

**Comment by jfirebaugh** [comment]
Looks good.

Should we merge the "Targets" list into the table?

**Comment by 1ec5** [comment]
I ended up reorganizing all the Markdown documentation in this repository. Previously, even though all the documentation was in one folder, it was a maze to navigate to the right documentation. I tried interlinking the documents, but there ended up being quite a lot of duplication. So instead, all the SDK documentation lives right alongside the SDKs, in platform/, in keeping with #899 #2146. One benefit is that directories like [platform/android/](https://github.com/mapbox/mapbox-gl-native/tree/master/platform/android/) show an introduction in addition to the file listing.

The documents now distinguish between the two primary use cases of integrating an SDK into an application and building an SDK for SDK development. INSTALL.md is still a bit of a bottleneck, but I’m happy with how things ended up.

**Comment by jfirebaugh** [comment]
This is fantastic.

**Comment by friedbunny** [comment]
Very nice, this feels more natural and self-contained.

One thing that may still trip folks up is `/ios` in the base of the repo, which seems like a logical place to look (if I'm not in to reading and just like clicking the first reasonableish link). Maybe we stick a brief readme there that redirects to `/platform/ios`?

**Comment by 1ec5** [comment]
Everything passes. Merging.

**Comment by jfirebaugh** [comment]
@friedbunny `/ios` will be merged into `/platform/ios`. I've been waiting for some of @1ec5's PRs to land (#3183 for example) before doing so, to minimize potential conflicts.

**Comment by 1ec5** [comment]
I added a soft redirect anyways. We can toss it when ios/ gets merged.

**Pull request merged**
