### PR TITLE
[core] Simplify asset:// implementation

### PR DESCRIPTION
**Pull request by jfirebaugh**
Followup to #3490.

* Move asset:// URL handling to `DefaultFileSource`.
* `AssetFileSource` implements `FileSource` interface and follows familiar implementation patterns.
* Move default implementation to `platform/default`, zip implementation to `platform/android`.
* Don't bother with modified / expires / etag -- assets are not cached so it doesn't matter.
* Don't bother with interleaving individual IO calls on the implementation thread. That adds a lot of complexity for very little benefit.
* Eliminate `platform::assetRoot()`.

cc @kkaefer @tmpsantos

### CODE REVIEW

**Comment by mb12** [comment]
@jfirebaugh  without platform specific assetRoot, how do you figure out if assets have to be loaded from main bundle or MapboxGL.bundle? This is for iOS.

**Comment by jfirebaugh** [comment]
There's still a platform specific root, it's merely passed as a normal parameter rather than looked up via a platform-specific implementation of `platform::assetRoot()`.

**Comment by mb12** [comment]
Thanks for the clarification @jfirebaugh .

**Comment by jfirebaugh** [comment]
Merged.

**Pull request closed without merging**
