### PR TITLE
forward declare GLX typedefs to limit conflicts from glx.h

### PR DESCRIPTION
**Pull request by mikemorris**

### CODE REVIEW

**Comment by jfirebaugh** [comment]
IMHO it would be better to use the [pimpl idiom](http://herbsutter.com/gotw/_100/) here.

**Comment by mikemorris** [comment]
@jfirebaugh that really feels like unnecessary complexity in this case to me, and the compilation benefits would be negligible for such a narrowly-used header file.

**Comment by jfirebaugh** [comment]
The point would be to not have to do all that forward declaration of GLX stuff, which could change between versions or platforms.

**Comment by jfirebaugh** [comment]
I see the forward declarations are more minimal now, so I don't have strong objections though.

**Pull request merged**
