### PR TITLE
[android] rotated map returns incorrect bounds when going over date line

### PR DESCRIPTION
**Pull request by osana**

### CODE REVIEW

**Comment by tobrun** [comment]
@osana could you retarget this branch to release-boba? Capturing from chat that we should avoid cherry-picking every commit, treat release-boba as the master branch for now.

**Comment by osana** [comment]
@tobrun I tested it interactively  using a test program but I am not sure how to write a unit test for it.

**Comment by tobrun** [comment]
@osana the best way to test this is through an Android instrumentation test. 

some pseudo code:

```java
@RunWith(AndroidJUnit4.class)
public class SomeTest extends BaseActivityTest {

  @Override
  protected Class getActivityClass() {
    return EspressoTestActivity.class;
  }

  @Test
  public void test() {
    validateTestSetup();
    invoke(mapboxMap, (uiController, mapboxMap) -> {
      // set camera bearing with CameraUpdateFactory.bearingTo
      // if needed use waitloop() to wait for a render
      // get bounds from the map and assert
    });
  }
}
```

**Comment by osana** [comment]
@tobrun I might be just hitting some other bugs. Yesterday I sort of when the same route you are suggesting. Added a test to MapboxMapTest.java 

```  @Test
  public void testVisibleRegionBounds() {
    ViewUtils.checkViewIsDisplayed(R.id.mapView);
    onView(withId(R.id.mapView)).perform(new MapboxMapAction((uiController, view) -> {

      CameraUpdate cameraUpdate = CameraUpdateFactory.newLatLngBounds(
        LatLngBounds.from(10, -170, -10, 170), 0);
      mapboxMap.moveCamera(cameraUpdate, new MapboxMap.CancelableCallback() {
        @Override
        public void onCancel() {
        }

        @Override
        public void onFinish() {
          VisibleRegion visibleRegion = mapboxMap.getProjection().getVisibleRegion();
          Log.d(">>>>>>>>>>>", " VisRect= " +visibleRegion.toString());
        }
      });
    }));
  }
```
The output that I was getting was not taking dateline into account. I suspect that CameraUpdate might be interpreting LatLngBounds incorrectly - I still need to confirm that though.  Also I need to figure out what is the reasonable error as bounds will be different when rotated.

**Pull request merged**
