### PR TITLE
Optimise icon management

### LINKED ISSUE #7343: Update Marker Icon doesn't result in AnnotationManager::removeAnnotationIcon
Platform:Android
Mapbox SDK version:android-v4.2.0-beta.4

### Steps to trigger behavior

 1. Create many markers on map by using  MapboxMap.addMarkers(List<? extends BaseMarkerOptions> markerOptionsList); - for example 200 markers;
 2. Change all markers position and  icon  every second (icon - new bitmap)
### Expected behavior
Markers change icon and  position
### Actual behavior
Memory leak - used memory grows on every icon change.

When i use  mapboxMap.addMarker(new MarkerViewOptions().position(position))  for each marker    add - everything works well.  

For my project i need to draw many markers (about 200 - 300) and periodicaly change its position and icon. 
With  mapboxMap.addMarker(new MarkerViewOptions().position(position)) func adding  i has memory leak. May be  not using addMarkers  method?

Example with memory leak i've make base on mapbox demo // AnimatedIconActivity:

package com.mapbox.mapboxandroiddemo.examples.annotations;

import android.animation.ObjectAnimator;
import android.animation.TypeEvaluator;
import android.animation.ValueAnimator;
import android.graphics.Bitmap;
import android.graphics.BitmapFactory;
import android.graphics.Canvas;
import android.graphics.Color;
import android.graphics.Paint;
import android.graphics.Rect;
import android.os.Bundle;
import android.os.Handler;
import android.support.annotation.NonNull;
import android.support.v7.app.AppCompatActivity;

import com.mapbox.mapboxandroiddemo.R;
import com.mapbox.mapboxsdk.MapboxAccountManager;
import com.mapbox.mapboxsdk.annotations.Icon;
import com.mapbox.mapboxsdk.annotations.IconFactory;
import com.mapbox.mapboxsdk.annotations.Marker;
import com.mapbox.mapboxsdk.annotations.MarkerOptions;
import com.mapbox.mapboxsdk.annotations.MarkerViewOptions;
import com.mapbox.mapboxsdk.geometry.LatLng;
import com.mapbox.mapboxsdk.maps.MapView;
import com.mapbox.mapboxsdk.maps.MapboxMap;
import com.mapbox.mapboxsdk.maps.OnMapReadyCallback;

import java.util.ArrayList;
import java.util.List;

public class AnimatedMarkerActivity extends AppCompatActivity {

  private MapView mapView;
  Handler handler = new Handler();
  List<MarkerOptions> mlist = new ArrayList<>();
  Paint paint;
  static  int i=0;
  Runnable runnable;
  MapboxMap mmapboxMap;

  @Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);

    runnable = new Runnable() {
      @Override
      public void run() {
        i++;

        for (Marker marker: mmapboxMap.getMarkers()) {

          marker.setIcon(getIcon(i, paint));

          LatLng position = marker.getPosition();
          position.setLatitude(position.getLatitude() + 0.001);
          position.setLongitude(position.getLongitude() + 0.001);
          marker.setPosition(position);
        }

        handler.postDelayed(runnable, 2000);

      }
    };

    // Mapbox access token is configured here. This needs to be called either in your application
    // object or in the same activity which contains the mapview.
    MapboxAccountManager.start(this, getString(R.string.access_token));

    // This contains the MapView in XML and needs to be called after the account manager
    setContentView(R.layout.activity_annotation_animated_marker);

    mapView = (MapView) findViewById(R.id.mapView);
    mapView.onCreate(savedInstanceState);

    paint = new Paint(Paint.ANTI_ALIAS_FLAG);
    paint.setColor(Color.WHITE);
    paint.setTextAlign(Paint.Align.LEFT);
    paint.setTextSize(10 * getResources().getDisplayMetrics().density);

    mapView.getMapAsync(new OnMapReadyCallback() {
      @Override
      public void onMapReady(MapboxMap mapboxMap) {
        mmapboxMap = mapboxMap;

        final ArrayList<MarkerOptions> buffer = new ArrayList<>();

        for (int i=0;i< 200; i++) {
          LatLng position = new LatLng(64.900932, -18.167040);
          position.setLatitude(position.getLatitude() - 0.2 * i);
          position.setLongitude(position.getLongitude() + 0.2 * i);

          MarkerOptions marker = new MarkerOptions()
                  .title("")
                  .position(position);

          buffer.add(marker);

        }

        mapboxMap.addMarkers(buffer);
        handler.postDelayed(runnable, 3000);
      }
    });
  }

  @Override
  public void onResume() {
    super.onResume();
    mapView.onResume();
  }

  @Override
  public void onPause() {
    super.onPause();
    mapView.onPause();
  }

  @Override
  public void onLowMemory() {
    super.onLowMemory();
    mapView.onLowMemory();
  }

  @Override
  protected void onDestroy() {
    super.onDestroy();
    mapView.onDestroy();
  }

  @Override
  protected void onSaveInstanceState(Bundle outState) {
    super.onSaveInstanceState(outState);
    mapView.onSaveInstanceState(outState);
  }

  private static class LatLngEvaluator implements TypeEvaluator<LatLng> {
    // Method is used to interpolate the marker animation.

    private LatLng latLng = new LatLng();

    @Override
    public LatLng evaluate(float fraction, LatLng startValue, LatLng endValue) {
      latLng.setLatitude(startValue.getLatitude()
        + ((endValue.getLatitude() - startValue.getLatitude()) * fraction));
      latLng.setLongitude(startValue.getLongitude()
        + ((endValue.getLongitude() - startValue.getLongitude()) * fraction));
      return latLng;
    }
  }

  private Icon getIcon(int i, Paint paint){
    Bitmap bitmap;

      bitmap = BitmapFactory.decodeResource(
              getResources(),R.drawable.green_marker);
    Icon icon = IconFactory.getInstance(this).fromBitmap(drawTextOnBitmap(String.valueOf(i), paint, bitmap));
    return icon;
  }

  public static Bitmap drawTextOnBitmap(String text, Paint paint, Bitmap source) {
    Bitmap mutableBitmap = source.copy(Bitmap.Config.ARGB_8888, true);
    Canvas canvas = new Canvas(mutableBitmap);

    // draw text to the Canvas center
    Rect boundsText = new Rect();
    paint.getTextBounds(text, 0, text.length(), boundsText);
    int x = (mutableBitmap.getWidth() - boundsText.width()) / 2;
    int y = (mutableBitmap.getHeight() + boundsText.height()) / 2;
    canvas.drawText(text, x, y, paint);
    return Bitmap.createBitmap(mutableBitmap, 0, 0, mutableBitmap.getWidth(), mutableBitmap.getHeight());
  }
}

### LINKED ISSUE #7374: Fragment - Map is blank
Hi,

Please I don't understand why the map is blank
I have an Activity with ViewPager. One of the fragment of the ViewPager contains the MapView
I don't understand why but the map fragment it's blank!!! No Map !!!!
Here are my code

```java
public class PlacesFragment extends Fragment {

    private MapView mapView;


    @Override
    public void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        // MapboxAccountManager.start(getActivity(), getString(R.string.mapbox_access_token));
    }

    @Nullable
    @Override
    public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        View view = inflater.inflate(R.layout.fragment_places, container, false);

        mapView = (MapView) view.findViewById(R.id.mapView);
        // mapView.setStyle(Style.MAPBOX_STREETS);
        mapView.setStyleUrl(Style.MAPBOX_STREETS);
        mapView.getMapAsync(new OnMapReadyCallback() {
            @Override
            public void onMapReady(MapboxMap mapboxMap) {

            }
        });
        mapView.onCreate(savedInstanceState);


        return super.onCreateView(inflater, container, savedInstanceState);
    }

    @Override
    public void onResume() {
        super.onResume();
        mapView.onResume();
    }

    @Override
    public void onPause() {
        super.onPause();
        mapView.onPause();
    }

    @Override
    public void onSaveInstanceState(Bundle outState) {
        super.onSaveInstanceState(outState);
        mapView.onSaveInstanceState(outState);
    }

    @Override
    public void onLowMemory() {
        super.onLowMemory();
        mapView.onLowMemory();
    }

    @Override
    public void onDestroy() {
        super.onDestroy();
        mapView.onDestroy();
    }
}
```

```xml
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:mapbox="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context=".fragment.PlacesFragment">

    <!-- Set the starting camera position and map style using xml-->
    <com.mapbox.mapboxsdk.maps.MapView
        android:id="@+id/mapView"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        mapbox:center_latitude="40.73581"
        mapbox:center_longitude="-73.99155"
        mapbox:zoom="11"/>

</RelativeLayout>
```

```java
public class MFApplication extends Application {

    public static final String TAG = MFApplication.class.getSimpleName();

    @Override
    public void onCreate() {
        super.onCreate();

        MapboxAccountManager.start(getBaseContext(), getString(R.string.mapbox_access_token));
    }
}
```

### PR DESCRIPTION
**Pull request by tobrun**
closes #7343

### CODE REVIEW

**Comment by tobrun** [comment]
been adding tests to potentially cherry pick this PR to release branch, been hitting some compability issues with android OS versions. KitKat and below suffer from a bitmap recycling issue. For now I'm going to turn off recycling for these OS versions.

FYI:

This is memory consumption with Bitmap recycling:

screenshot at 2017-07-31 14 03 22


This is consumption without recycling:

screenshot at 2017-07-31 14 02 11

**Comment by zugaldia** [comment]
Great improvement.

> This is memory consumption with Bitmap recycling:

What was the scenario in this case (how many icons, size...). Wondering if we could estimate an approximate percentage of memory saved by this change for a typical scenario.

**Comment by tobrun** [comment]
> What was the scenario in this case (how many icons, size...). 

Shown graph is after having executed all the tests from `IconTest.java` (at that time it was 5 or 6 tests). This means we have created 5-6 different Activities with each Activity having it's own map and icons. The lowering of memory = recycling of bitmaps.

> Wondering if we could estimate an approximate percentage of memory saved by this change for a typical scenario.

Memory saved is the same as the memory footprint of the bitmap released.

**Comment by tobrun** [comment]
@zugaldia could you review this? Would love get this in master so we can kick the tires on it.

**Pull request merged**
