### PR TITLE
[android] Bring back OkHTTP

### LINKED ISSUE #2856: Try OkHTTP on Android again
Time to try https://github.com/mapbox/mapbox-gl-native/pull/2033 again and use OkHTTP instead of curl for Android.

Previous blocker for this was https://github.com/mapbox/mapbox-gl-native/issues/2400 which has not been looked at for a while.

Things that might have fixed that crash:
- updating libuv - https://github.com/mapbox/mapbox-gl-native/pull/2609
- refactor in the core GL HTTP code - https://github.com/mapbox/mapbox-gl-native/pull/2617

OkHTTP will be an enabler for offline support.

/cc @bleege @tobrun

### PR DESCRIPTION
**Pull request by ljbade**
Fixes #2856

### CODE REVIEW

**Comment by ljbade** [comment]
@bleege @tobrun Can you give this branch a good stress test. Specifically looking to reproduce #2400

**Comment by tobrun** [comment]
I was able to crash it with:
>pid: 6260, tid: 8632, name: OkHttp https://  >>> com.mapbox.mapboxgl.testapp <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x3c

Full stacktrace:

> 29 15:46:11.072 6260-8632/? A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x3c in tid 8632 (OkHttp https://)
10-29 15:46:11.099 204-788/? D/AudioFlinger: mixer(0xb4140000) throttle end: throttle time(7)
10-29 15:46:11.183 201-201/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
10-29 15:46:11.183 201-201/? A/DEBUG: Build fingerprint: 'google/hammerhead/hammerhead:6.0/MPA44I/2172151:user/release-keys'
10-29 15:46:11.183 201-201/? A/DEBUG: Revision: '0'
10-29 15:46:11.183 201-201/? A/DEBUG: ABI: 'arm'
10-29 15:46:11.183 201-201/? A/DEBUG: pid: 6260, tid: 8632, name: OkHttp https://  >>> com.mapbox.mapboxgl.testapp <<<
10-29 15:46:11.183 201-201/? A/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x3c
10-29 15:46:11.214 201-201/? A/DEBUG:     r0 00000000  r1 00000000  r2 00000008  r3 00000043
10-29 15:46:11.214 201-201/? A/DEBUG:     r4 94460e60  r5 9560c000  r6 94460e6c  r7 9b0523d4
10-29 15:46:11.214 201-201/? A/DEBUG:     r8 9d3c3c20  r9 fffff424  sl 00000130  fp 9b0523c8
10-29 15:46:11.214 201-201/? A/DEBUG:     ip a0978a0c  sp 9b052318  lr a06f981c  pc a0854ca8  cpsr 800e0010
10-29 15:46:11.257 201-201/? A/DEBUG:     #00 pc 0036cca8  /data/app/com.mapbox.mapboxgl.testapp-1/lib/arm/libmapbox-gl.so (uv_async_send+8)
10-29 15:46:11.257 201-201/? A/DEBUG:     #01 pc 00211818  /data/app/com.mapbox.mapboxgl.testapp-1/lib/arm/libmapbox-gl.so (mbgl::HTTPAndroidRequest::onResponse(int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::_
10-29 15:46:11.258 201-201/? A/DEBUG:     #02 pc 0020f390  /data/app/com.mapbox.mapboxgl.testapp-1/lib/arm/libmapbox-gl.so (mbgl::nativeOnResponse(_JNIEnv*, _jobject*, long long, int, _jstring*, _jstring*, _jstring*, _jstring*, _jstring*, _jbyteArray*)+1620)
10-29 15:46:11.258 201-201/? A/DEBUG:     #03 pc 00867a4f  /data/app/com.mapbox.mapboxgl.testapp-1/oat/arm/base.odex (void com.mapbox.mapboxsdk.http.HTTPContext$HTTPRequest.nativeOnResponse(long, int, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, byte[])+258)
10-29 15:46:11.258 201-201/? A/DEBUG:     #04 pc 00868047  /data/app/com.mapbox.mapboxgl.testapp-1/oat/arm/base.odex (void com.mapbox.mapboxsdk.http.HTTPContext$HTTPRequest.onResponse(com.squareup.okhttp.Response)+594)
10-29 15:46:11.258 201-201/? A/DEBUG:     #05 pc 0086f1e5  /data/app/com.mapbox.mapboxgl.testapp-1/oat/arm/base.odex (void com.squareup.okhttp.Call$AsyncCall.execute()+488)
10-29 15:46:11.258 201-201/? A/DEBUG:     #06 pc 00683d83  /data/app/com.mapbox.mapboxgl.testapp-1/oat/arm/base.odex (void com.squareup.okhttp.internal.NamedRunnable.run()+254)
10-29 15:46:11.258 201-201/? A/DEBUG:     #07 pc 72bebc67  /data/dalvik-cache/arm/system@framework@boot.oat
10-29 15:46:12.489 201-201/? E/DEBUG: AM write failed: Broken pipe
10-

**Comment by tobrun** [comment]
Another crash:
> Fatal signal 11 (SIGSEGV), code 1, fault addr 0x3c in tid 9178 (nJ_UO_MMZKFEaiA)

Full stacktrace: 
10-29 15:49:18.014 9103-9103/com.mapbox.mapboxgl.testapp E/Surface: getSlotFromBufferLocked: unknown buffer: 0x9ae7a510
10-29 15:49:18.124 9103-9178/com.mapbox.mapboxgl.testapp A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x3c in tid 9178 (nJ_UO_MMZKFEaiA)
10-29 15:49:18.226 201-201/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
10-29 15:49:18.226 201-201/? A/DEBUG: Build fingerprint: 'google/hammerhead/hammerhead:6.0/MPA44I/2172151:user/release-keys'
10-29 15:49:18.226 201-201/? A/DEBUG: Revision: '0'
10-29 15:49:18.227 201-201/? A/DEBUG: ABI: 'arm'
10-29 15:49:18.227 201-201/? A/DEBUG: pid: 9103, tid: 9178, name: nJ_UO_MMZKFEaiA  >>> com.mapbox.mapboxgl.testapp <<<
10-29 15:49:18.227 201-201/? A/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x3c
10-29 15:49:18.253 201-201/? A/DEBUG:     r0 00000000  r1 00000000  r2 00000000  r3 00000000
10-29 15:49:18.253 201-201/? A/DEBUG:     r4 999fa3a4  r5 9ae2e840  r6 999fa398  r7 999fa3d4
10-29 15:49:18.253 201-201/? A/DEBUG:     r8 9d719bc0  r9 fffff424  sl 000000c8  fp 999fa3c8
10-29 15:49:18.254 201-201/? A/DEBUG:     ip a07fba0c  sp 999fa318  lr a057c81c  pc a06d7ca8  cpsr 600e0010
10-29 15:49:18.296 201-201/? A/DEBUG:     #00 pc 0036cca8  /data/app/com.mapbox.mapboxgl.testapp-1/lib/arm/libmapbox-gl.so (uv_async_send+8)
10-29 15:49:18.296 201-201/? A/DEBUG:     #01 pc 00211818  /data/app/com.mapbox.mapboxgl.testapp-1/lib/arm/libmapbox-gl.so (mbgl::HTTPAndroidRequest::onResponse(int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::_
10-29 15:49:18.297 201-201/? A/DEBUG:     #02 pc 0020f390  /data/app/com.mapbox.mapboxgl.testapp-1/lib/arm/libmapbox-gl.so (mbgl::nativeOnResponse(_JNIEnv*, _jobject*, long long, int, _jstring*, _jstring*, _jstring*, _jstring*, _jstring*, _jbyteArray*)+1620)
10-29 15:49:18.297 201-201/? A/DEBUG:     #03 pc 00867a4f  /data/app/com.mapbox.mapboxgl.testapp-1/oat/arm/base.odex (void com.mapbox.mapboxsdk.http.HTTPContext$HTTPRequest.nativeOnResponse(long, int, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, byte[])+258)
10-29 15:49:18.297 201-201/? A/DEBUG:     #04 pc 00868047  /data/app/com.mapbox.mapboxgl.testapp-1/oat/arm/base.odex (void com.mapbox.mapboxsdk.http.HTTPContext$HTTPRequest.onResponse(com.squareup.okhttp.Response)+594)
10-29 15:49:18.297 201-201/? A/DEBUG:     #05 pc 0086f1e5  /data/app/com.mapbox.mapboxgl.testapp-1/oat/arm/base.odex (void com.squareup.okhttp.Call$AsyncCall.execute()+488)
10-29 15:49:18.297 201-201/? A/DEBUG:     #06 pc 00683d83  /data/app/com.mapbox.mapboxgl.testapp-1/oat/arm/base.odex (void com.squareup.okhttp.internal.NamedRunnable.run()+254)
10-29 15:49:18.297 201-201/? A/DEBUG:     #07 pc 72bebc67  /data/dalvik-cache/arm/system@framework@boot.oat

**Comment by ljbade** [comment]
Thanks @tobrun was able to repro it easily.

Here is the `ndk-stack` log:
```
********** Crash dump: **********
Build fingerprint: 'samsung/zerofltedv/zeroflte:5.1.1/LMY47X/G920IDVU3DOJ6:user/release-keys'
pid: 14778, tid: 15013, name: OkHttp https://  >>> com.mapbox.mapboxgl.testapp <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x3c
Stack frame #00 pc 00360cf8  /data/app/com.mapbox.mapboxgl.testapp-2/lib/arm/libmapbox-gl.so (uv_async_send+8): Routine uv_async_send at /home/travis/build/mapbox/mason/mason_packages/.build/libuv-1.7.5/src/unix/async.c:62
Stack frame #01 pc 00205868  /data/app/com.mapbox.mapboxgl.testapp-2/lib/arm/libmapbox-gl.so (mbgl::HTTPAndroidRequest::onResponse(int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::_: Routine uv::async::send() at /home/leith/mb/mapbox-gl-native/build/android-arm-v7/../../src/mbgl/util/uv_detail.hpp:124
Stack frame #02 pc 002033e0  /data/app/com.mapbox.mapboxgl.testapp-2/lib/arm/libmapbox-gl.so (mbgl::nativeOnResponse(_JNIEnv*, _jobject*, long long, int, _jstring*, _jstring*, _jstring*, _jstring*, _jstring*, _jbyteArray*)+1620): Routine mbgl::nativeOnResponse(_JNIEnv*, _jobject*, long long, int, _jstring*, _jstring*, _jstring*, _jstring*, _jstring*, _jbyteArray*) at /home/leith/mb/mapbox-gl-native/build/android-arm-v7/../../platform/android/http_request_android.cpp:359 (discriminator 6)
Stack frame #03 pc 002798b7  /data/dalvik-cache/arm/data@app@com.mapbox.mapboxgl.testapp-2@base.apk@classes.dex
```

**Comment by ljbade** [comment]
Looks like we still have #2400

**Comment by zugaldia** [comment]
I can still reproduce the crash as @tobrun describes here: https://github.com/mapbox/mapbox-gl-native/pull/2857#issuecomment-152203596

Anecdotally, `monkey` fails to create a crash no matter how many times I try (`adb shell monkey -p com.mapbox.mapboxgl.testapp -v 1000`)

**Comment by tobrun** [comment]
@zugaldia is monkey able to scroll/zoom/pan?
To make it easier to crash: Maybe start with an already zoomed in map? The problem occurs with fetching data, if you are on highest zoomlevel and pan you won't fetch any data.

**Comment by ljbade** [comment]
Hmm `monkey`, going to have to look that one up.

@zugaldia did you see the PR https://github.com/mapbox/mapbox-gl-native/pull/2905

**Comment by zugaldia** [comment]
@tobrun I believe so. It's what `monkey` calls a "motion event" (motion events consist of a down event somewhere on the screen, a series of pseudo-random movements, and an up event). You can add more with the `--pct-motion <percent>` flag.

@ljbade On it. Also, you can just start with a plain `adb shell monkey -p com.mapbox.mapboxgl.testapp -v 1000`.

**Comment by ljbade** [comment]
Closing as this was replaced by https://github.com/mapbox/mapbox-gl-native/blob/c66aec9cfa47bc7590856c8734dee0bd5e1b6256/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/http/HTTPContext.java#L99

**Pull request closed without merging**
