### PR TITLE
[android] Add support for data driven styling

### PR DESCRIPTION
**Pull request by ivovandongen**
Adds support for data driven styling to the Android SDK.

TODO:

Functions
- [X] Camera (Zoom)
  - [X] Exponential
  - [X] Interval
  - [X] Unit tests
- [x] Source (Property)
  - [x] Categorical
  - [x] Exponential
  - [x] Identity
  - [x] Interval
  - [x] Unit tests
- [x] Composite (ZoomAndProperty)
  - [x] Categorical
  - [x] Exponential
  - [x] Interval
  - [x] Unit tests

Other:
- [x] Merge `Property` and `PropertyValue`
- [x] Test activity/examples
- [x] JavaDoc

### CODE REVIEW

**Comment by ivovandongen** [comment]
@mapbox/android I've restored support for exponential zoom functions on this branch and set up the basis for the property / zoom-and-property functions. For this I adhered to the naming in the [style spec](https://www.mapbox.com/mapbox-gl-style-spec/#types-function) and not the core naming. So, for example, `ZoomFunction` and not `CameraFunction`.

**Comment by ivovandongen** [comment]
After the discussion yesterday I've re-implemented the functions and stops with typed stops in https://github.com/mapbox/mapbox-gl-native/pull/7752/commits/8d08c610090fc17fb6e50a58f78c8a3233d4bce8. Overall, I think it looks good. 

We now have:

Functions:
- `CameraFunction`
- `SourceFunction` - Contains the referenced property
- `CompositeFunction` (not implemented yet)

Stops:
- `CategoricalStops` (not implemented yet)
- `ExponentialStops` - Contains base, stops (and soon colorSpace)
- `IntervalStops` - Contains stops
- `IntervalStops` - Empty, marker class

The DSL is spread out in `Function`, `Stop` and `Stops` and looks like this for `CameraFunctions` (exponential):

```
    //Set
    layer.setProperties(
      fillOpacity(
        zoom(
          exponential(
            0.5f,
            stop(2, fillOpacity(0.3f))
          )
        )
      )
    );

    //Get
    float base = ((ExponentialStops) layer.getFillOpacity().getFunction().getStops()).getBase();
    Stop[] stops = ((ExponentialStops) layer.getFillOpacity().getFunction().getStops()).stops;
```

And like this for `SourceFunctions` (identity):

```
    //Set
    layer.setProperties(
      fillOpacity(property("FeaturePropertyA", Stops.<Float>identity()))
    );

    //Get
    String property = ((SourceFunction) layer.getFillOpacity().getFunction()).getProperty();
```


The typing is a little uncomfortable when interrogating the style. Suggestions are welcome.

**Comment by tobrun** [comment]
API looks great, can't think of a simpler construction as the proposed DSL.

**Comment by ivovandongen** [comment]
I've implemented the composite functions (unit test generation forthcoming). The DSL for composite functions looks similar to the [style spec](https://www.mapbox.com/mapbox-gl-style-spec/#types-function) format for Zoom-And-Property functions:

```
      fillOpacity(
        composite(
          "FeaturePropertyA",
          exponential(
            0.5f,
            stop(0, 0.3f, fillOpacity(1f)),
            stop(0, 0.5f, fillOpacity(0.3f)),
            stop(1, 0.3f, fillOpacity(1f)),
            stop(1, 0.5f, fillOpacity(0.3f))
          )
        )
      )
```

Where there is only one stops implementation for all zoom levels.

An alternative which is closer to the representation in the core implementation and the [proposal for function revision](https://github.com/mapbox/mapbox-gl-style-spec/issues/613):

```
    layer.setProperties(
      fillOpacity(
        composite(
          "FeaturePropertyA",
          stop(0,
            exponential(
              0.5f,
              stop(0.3f, fillOpacity(1f)),
              stop(0.5f, fillOpacity(0.3f))
            )
          ),
          stop(1,
            exponential(
              0.5f,
              stop(0.3f, fillOpacity(1f)),
              stop(0.5f, fillOpacity(0.3f))
            )
          )
        )
      )
```

This offers more flexibility, but is also more verbose.

In addition, I made some changes to the `Stops` classes and added a [IterableStops](https://github.com/mapbox/mapbox-gl-native/blob/213e6a58aeae0e4c69e15c42e62b187c7f1e637f/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/functions/stops/IterableStops.java) abstract base class so it is easier to access the actual stops collections without code like `getStops().getStops().length` (now `getStops().size()`). This does involve some generics acrobatics:

```
CompositeStops<Float, Float, Float, ExponentialStops<Float, Float>> stops = (CompositeStops<Float, Float, Float, ExponentialStops<Float, Float>>) layer.getFillOpacity().getFunction().getStops();
```

**Comment by ivovandongen** [comment]
@jfirebaugh Finished up on this. After reviews, shall I merge it back into the `dds-wip` branch?

**Pull request merged**
