### PR TITLE
[android] Reorganize dependencies

### PR DESCRIPTION
**Pull request by zugaldia**
This PR moves some dependencies out of the SDK that are only necessary for the Test App.

### CODE REVIEW

**Comment by tobrun** [comment]
@zugaldia lint is complaining about incompatible gradle version for the SDK. This is because the lost dependency and telem are bringing in a couple of support libs. I optimised the dependencies to not include redundant dependencies. eg. fragment + support annoation code is pulled in with supportv7.

**Comment by zugaldia** [comment]
Thanks @tobrun for the pass. Lint is still complaining, I need to figure out what the actual error is:

image

**Comment by tobrun** [comment]
@zugaldia:

```
All com.android.support libraries must use the exact same version specification (mixing versions can lead to runtime crashes). Found versions 25.4.0, 25.1.0. Examples include com.android.support:support-compat:25.4.0 and com.android.support:animated-vector-drawable:25.1.0
```

we need to look into excluding modules from dependencies that rely on 25.1.0

**Comment by zugaldia** [comment]
Thanks @tobrun for the extra push, looks like we're now good to go (pending CI changes from https://github.com/mapbox/mapbox-gl-native/pull/10289).

**Pull request merged**
