### PR TITLE
[core] Bring more stability to the symbol placement

### PR DESCRIPTION
**Pull request by pozdnyakov**
This pull request improves the labels stability and performance for the tilted view. The following changes are done:
- place already visible symbols first and hidden symbols last
- stop squeezing the placement period (add 300ms delay) on new symbols appearance
- the already placed variable labels stick to their latest-used anchor
- collision index uses doubled padding with the tilted view

Fixes https://github.com/mapbox/mapbox-gl-native-team/issues/132

### CODE REVIEW

**Comment by ansis** [comment]
Overall this looks good!

This looks like it prioritizes previously placed symbols within each sortkeyrange/layer but layer priority will still be respected? This seems like a great compromise to me.

> the already placed variable labels stick to their latest-used anchor

It looks like they are allowed to be *only* their last used anchor. Did this make a large change for stability?

Overall this looks good to me! I think it's worth considering making this the default behavior instead of just for tilted views to keep things simpler

**Comment by pozdnyakov** [comment]
>>the already placed variable labels stick to their latest-used anchor
>
>It looks like they are allowed to be only their last used anchor. Did this make a large change for stability?

Yeah, the symbol once placed does not change its anchor - otherwise symbols are "jumping" while camera is moving

**Comment by pozdnyakov** [comment]
>Overall this looks good to me! I think it's worth considering making this the default behavior instead of just for tilted views to keep things simpler

the first change "place already visible symbols first and hidden symbols last" could be a default behavior indeed, however the other changes IMO are more navigation mode specific.

**Comment by chloekraw** [comment]
@pozdnyakov this is great, thank you! Before you merge, may I suggest a small modification to the changelog:
> Improve stability of symbol placement when the map is tilted

**Pull request merged**
