### PR TITLE
Fix font rendering at the top of the viewport

### PR DESCRIPTION
**Pull request by kkaefer**
When the map is tilted, glyphs at the top of the viewport are shaded incorrectly:

screen shot 2015-11-17 at 19 32 41

### CODE REVIEW

**Comment by 1ec5** [comment]
Since #3135 landed, the new osxapp obscures the problematic labels by default with a translucent toolbar. You can still see the issue if you hide the toolbar though.

I see that this PR has a “do not merge” label on it – what’s left to do?

**Comment by jfirebaugh** [comment]
@kkaefer What's left here? Can this be merged?

**Comment by jfirebaugh** [comment]
It looks like one of the two commits was merged in 2700ea87a4e6abb9c8ea8520fe92b067be022935. @kkaefer, if you want the other commit ("only write shaders if the file content changed"), please rebase and merge in a new PR.

**Comment by kkaefer** [comment]
@jfirebaugh 2700ea87a4e6abb9c8ea8520fe92b067be022935 is no longer necessary, since we're now generating the shaders individually with gyp rules, rather than always writing them.

**Pull request closed without merging**
