### PR TITLE
[all] Upgrade to boost 1.62.0

### PR DESCRIPTION
**Pull request by jfirebaugh**

### CODE REVIEW

**Comment by jfirebaugh** [comment]
@springmeyer Can you look at the CI failure here? The error is:

```
/usr/bin/ld: cannot find -lprogram_options
```

It seem like this probably stems from a change in mason.ini for boost_libprogram_options. The contents for 1.62.0 includes:

```
ldflags=-L{prefix}/lib -lprogram_options
```

This line is not present in the mason.ini for 1.60.0.

**Comment by springmeyer** [comment]
@jfirebaugh taking a look now.

**Comment by springmeyer** [comment]
Working on upstream fix at https://github.com/mapbox/mason/pull/297

**Comment by springmeyer** [comment]
This is now fixed after upstream mason fixes and clearing the build cache.

**Pull request merged**
