### PR TITLE
[ios, osx] Replace libuv with native implementations

### PR DESCRIPTION
**Pull request by jfirebaugh**
Progress toward #2909.

:eyes: @1ec5 @tmpsantos

### CODE REVIEW

**Comment by tmpsantos** [comment]
:+1: This ended up cleaner than I was expecting.

**Comment by jfirebaugh** [comment]
This is passing Node OS X builds on Bitrise while failing locally. I believe it should be failing on Bitrise -- with this implementation as it stands, the Node bindings on OS X are using a mix of libuv and Cocoa APIs, which may produce unpredictable results. Instead,  the Node bindings on OS X should continue to use libuv as the loop implementation. I'm investigating.

**Comment by jfirebaugh** [comment]
#4560

**Comment by 1ec5** [comment]
:+1:

**Pull request merged**
