### PR TITLE
[ios] Generate iOS code coverage for metrics

### PR DESCRIPTION
**Pull request by jmkiley**
This tracks generating an iOS code coverage percentage that can be uploaded to Mode. It partially addresses #7609, but does not add CodeCov. 

CodeCov is a little more detailed than we need for metrics purposes, and a lot more complicated to implement in gl-native

This PR also enables code coverage generation for `dynamic` when `CI` tests are run locally. Line coverage percentage is generated for the `dynamic` target, which covers the iOS Maps SDK and `mbgl`, but should exclude tests and demo apps. 

To do:
- [x] Upload percentage to AWS
- [x] Move report generation to nightly build

There are a few new `xccov` features in [Xcode 10.2 beta 3](https://developer.apple.com/documentation/xcode_release_notes/xcode_10_2_beta_3_release_notes) that will be helpful for us. Being able to merge coverage reports and more easily calculate the coverage diff will be 💯 , but that is tail work.

### CODE REVIEW

**Comment by jmkiley** [comment]
Keeping the coverage script in `ios-debug` for now while I get things working. Not seeing the report show up in the data warehouse right now, so will continue to troubleshoot. Thank you to @captainbarbosa for all the help so far.

**Comment by jmkiley** [comment]
I think this is ready to review. @langsmith - let me know if there are any data formatting changes that you would like to see.

**Comment by jmkiley** [comment]
:wave: I think this is ready for re-review. I have separated the steps for uploading to S3 so that they can be used by Android as well.

**Comment by captainbarbosa** [comment]
Nice work! 🌟

**Pull request merged**
