### PR TITLE
break out setup.sh from run.sh

### PR DESCRIPTION
**Pull request by mikemorris**
Needed to avoid code duplication in node-mapbox-gl-native travis scripts, refs https://github.com/mapbox/mapbox-gl-native/pull/1339, https://github.com/mapbox/node-mapbox-gl-native/pull/119.

### CODE REVIEW

**Comment by jfirebaugh** [comment]
This regressed headless tests. They are no longer using the version of mesa installed via mason, because loading that version depends on [setting `LD_LIBRARY_PATH`](https://github.com/mapbox/mapbox-gl-native/blob/8e15732954dfc5635490d42fff7142e793a5208c/scripts/linux/setup.sh#L24) and this moved the export from `run.sh` to a separate `setup.sh` shell file whose exports aren't available from `run.sh`.

**Comment by jfirebaugh** [comment]
Oops, sorry, I misdiagnosed the cause. It's still this change, but it's because the `mason prefix` call within the `export LD_LIBRARY_PATH` command happens before `mason install` is run.

**Comment by jfirebaugh** [comment]
I've reverted this for the time being so we have passing builds going into the final hours of the iOS b1 release.

**Comment by mikemorris** [comment]
That seems odd, `setup.sh` is still sourced before `run.sh` is called, and Mesa should be installed in `install.sh`, call before `setup.sh`.

- https://github.com/mapbox/mapbox-gl-native/blob/8e15732954dfc5635490d42fff7142e793a5208c/.travis.yml#L88-L92
- https://github.com/mapbox/mapbox-gl-native/blob/8e15732954dfc5635490d42fff7142e793a5208c/scripts/linux/install.sh#L10-L11

**Comment by mikemorris** [comment]
-> https://github.com/mapbox/mapbox-gl-native/pull/1527

**Pull request merged**
