### PR TITLE
Fix for flaky CI test

### PR DESCRIPTION
**Pull request by frederoni**
Just want to run this a few times and try to reproduce -> https://www.bitrise.io/build/4a53af4219ae7884

### CODE REVIEW

**Comment by 1ec5** [comment]
This will hopefully fix #6385. While you’re at it, can you cherry-pick 61043b5ac67123bd0674808cf6d6133ef6d2a285? That change addresses a race condition and failure that occurs if you run another offline map test before this one.

**Comment by kkaefer** [comment]
https://github.com/mapbox/mapbox-gl-native/pull/6397/commits/ad7057595008f15018279b5007e1e18fc941994d is missing the `[ios, macos]` prefix; can you merge https://github.com/mapbox/mapbox-gl-native/pull/6397/commits/ad7057595008f15018279b5007e1e18fc941994d and https://github.com/mapbox/mapbox-gl-native/pull/6397/commits/85efa10024d9edb72e80de0fff8538a7c0b96e18 into one commit?

**Comment by frederoni** [comment]
Merged ad70575 and 85efa10 into one commit.
iOS and macOS have finished 5 successful checks consecutively so far.

**Comment by 1ec5** [comment]
This change introduced a subtler bug that consistently fails iOS unit tests on the branch for #5999, as detailed in https://github.com/mapbox/mapbox-gl-native/pull/5999#issuecomment-263678869. A fix is in #7228.

**Pull request merged**
