### PR TITLE
upgrade gyp

### PR DESCRIPTION
**Pull request by mikemorris**
Refs #3178

Not seeing any git tags or releases in https://chromium.googlesource.com/external/gyp, so this is just copied from `HEAD` (commit `6fb8bd829f0ca8fd432fd85ede788b6881c4f09f`).

First error I'm hitting, when running `make osx`, is mismatched arguments to a function that changed, haven't been able to track down where this is happening yet.

```
* Building target osxapp...
  MACTOOL copy-bundle-resource ../../macosx/Icon.icns
Traceback (most recent call last):
  File "./gyp-mac-tool", line 611, in <module>
    sys.exit(main(sys.argv[1:]))
  File "./gyp-mac-tool", line 28, in main
    exit_code = executor.Dispatch(args)
  File "./gyp-mac-tool", line 43, in Dispatch
    return getattr(self, method)(*args[1:])
TypeError: ExecCopyBundleResource() takes exactly 4 arguments (3 given)
make[2]: *** [Release/Mapbox GL.app/Contents/Resources/Icon.icns] Error 1
make[1]: *** [Makefile/osxapp] Error 2
make: *** [osx] Error 2
```

/cc @1ec5

### CODE REVIEW

**Comment by 1ec5** [comment]
I’m able to run `make xosx` and `make osx` without any problems on this branch. Did you `make clean && make distclean` first?

**Comment by mikemorris** [comment]
@1ec5 I definitely ran `make distclean && make osx`, looks like this is originating from https://github.com/mapbox/mapbox-gl-native/blob/master/macosx/mapboxgl-app.gypi#L12?

**Comment by 1ec5** [comment]
What version of Xcode and OS X are you using? I tried in Xcode 7.1 and 7.2 on OS X 10.11.

**Comment by 1ec5** [comment]
You should also try deleting build/gyp/. `make clean && make distclean` don’t take care of that folder. I rolled a fix for that into #3135.

**Comment by mikemorris** [comment]
Ah, `build/gyp` could've been the cuprit (possibly related to https://github.com/mapbox/mapbox-gl-native/commit/dfb36d62317d99482e6a16b772e8d370464d1cce). `Version 7.1.1 (7B1005)` on OS X 10.11 fwiw.

**Comment by 1ec5** [comment]
I was mistaken: I get the same error as you. I wasn’t seeing it before because `git checkout gyp` doesn’t check out the gyp branch; rather, it tries to checkout the latest version of the gyp/ folder in the project root.

**Comment by 1ec5** [comment]
Fixed `make osx` in d6099fbbd32f2c9c75d315f649c05fa05844a161.

**Comment by 1ec5** [comment]
I’ve reapplied 36cd65e1ab232c3a876d7c10a366143a9546e2e7 and b32748b42f6c9ec8d336f4571f6278a2eeeebae0 in an attempt to fix Linux g++ builds. baa684eb9861d83c350a4acbc58d00568817b0cd and 13c698fa26eaa91cc9310aac52ee5c45cf3f60f5 don’t appear to be needed: some of these flags are already set in gyp master, while the rest are either set in the iOS gyp files or explicitly unset in the OS X gyp files in #3135.

**Comment by mikemorris** [comment]
> `git checkout gyp` doesn’t check out the gyp branch

**Comment by mikemorris** [comment]
Hrm, last remaining Travis error is something I've never seen before (but doesn't look like it should be hard to fix?)

```
/usr/bin/ld: /home/travis/build/mapbox/mapbox-gl-native/mason_packages/linux-x86_64/sqlite/3.9.1/lib/libsqlite3.a(sqlite3.o): undefined reference to symbol 'dlclose@@GLIBC_2.2.5'
/usr/bin/ld: note: 'dlclose@@GLIBC_2.2.5' is defined in DSO /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/libdl.so so try adding it to the linker command line
/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/libdl.so: could not read symbols: Invalid operation
collect2: error: ld returned 1 exit status
make[2]: *** [Release/mbgl-render] Error 1
rm gyp_mbgl_gyp_shaders_target_Build_Shaders.intermediate
make[2]: Leaving directory `/home/travis/build/mapbox/mapbox-gl-native/build/linux-x86_64'
make[1]: *** [Makefile/mbgl-render] Error 2
make[1]: Leaving directory `/home/travis/build/mapbox/mapbox-gl-native'
make: *** [render] Error 2
```

**Comment by mikemorris** [comment]
Rebased and cleaned up, this looks good for merge to me once Travis passes @1ec5

**Comment by 1ec5** [comment]
@springmeyer, now that this branch has landed, can we delete https://github.com/mapbox/mapbox-gl-native/tree/update-gyp?

**Pull request merged**
