### PR TITLE
Update Mason submodule pin

### LINKED ISSUE #1707: Lots of linker warnings in Xcode 7 / iOS 9 SDK — built for newer iOS version (9.0) than being linked (8.2)
I get 28 of these warnings when building the iosapp scheme in Xcode 7 for the iPhone 6 (9.0) simulator:

```
ld: warning: object file (/path/to/mapbox-gl-native/mason_packages/ios-8.3/libuv/0.10.28/lib/libuv.a(async.o)) was built for newer iOS version (8.3) than being linked (7.0)
```

### LINKED ISSUE #1957: Adopt Bitcode
iosapp fails to build for iOS 9 devices in Xcode 7 with the following linker error:

```
ld: '/Users/mxn/hub/mapbox-gl-native/mason_packages/ios-9.0/libuv/0.10.28/lib/libuv.a(async.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64
```

We’ll need to patch upstream and update the mason submodule pin.

/cc @kkaefer @incanus

### PR DESCRIPTION
**Pull request by 1ec5**
This PR pulls in mapbox/mason@41d8b2eb28b3cd942d9f15583467b27c549675ea for mapbox/mason#106, as well as plenty of other changes. @kkaefer @ljbade, is it safe to pull in all the Mason changes since mapbox/mason@abdc131273c3e50e42f245b1166c27de4c34c582?

Fixes #1957; fixes #1707.

### CODE REVIEW

**Comment by ljbade** [comment]
@1ec5 It looks OK. But only way to know for sure is on Travis.

**Comment by 1ec5** [comment]
Not looking good on the Android side, @ljbade. Looks like toolchain.sh just stalls out.

**Comment by ljbade** [comment]
Hmm, OK I'll have to try it locally.

**Comment by ljbade** [comment]
Strange it doesn't hand locally but I get a bunch of weird messages:
```
leith@leith-xps:~/mb/mapbox-gl-native$ make android
git submodule update --init src/mbgl/util/geojsonvt
/home/leith/mb/mapbox-gl-native/.mason/mason: fork: retry: No child processes
/home/leith/mb/mapbox-gl-native/.mason/mason: fork: retry: No child processes
/home/leith/mb/mapbox-gl-native/.mason/mason: fork: retry: No child processes
/home/leith/mb/mapbox-gl-native/.mason/mason: fork: retry: No child processes
/home/leith/mb/mapbox-gl-native/.mason/mason: fork: retry: No child processes
/home/leith/mb/mapbox-gl-native/.mason/mason: fork: retry: No child processes
/home/leith/mb/mapbox-gl-native/.mason/mason: fork: retry: No child processes
/home/leith/mb/mapbox-gl-native/.mason/mason: fork: retry: No child processes
/home/leith/mb/mapbox-gl-native/.mason/mason: fork: retry: No child processes
/home/leith/mb/mapbox-gl-native/.mason/mason: fork: retry: No child processes
/home/leith/mb/mapbox-gl-native/.mason/mason: fork: Resource temporarily unavailable
./scripts/android/toolchain.sh: line 15: mason: No such file or directory
./scripts/android/toolchain.sh: line 15: which: No such file or directory
./scripts/android/toolchain.sh: line 16: mason: No such file or directory
./scripts/android/toolchain.sh: line 16: which: No such file or directory
./scripts/android/toolchain.sh: line 17: mason: No such file or directory
./scripts/android/toolchain.sh: line 17: which: No such file or directory
./scripts/android/toolchain.sh: line 18: mason: No such file or directory
./scripts/android/toolchain.sh: line 18: which: No such file or directory
./scripts/android/toolchain.sh: line 19: mason: No such file or directory
./scripts/android/toolchain.sh: line 19: which: No such file or directory
./scripts/android/toolchain.sh: line 20: mason: No such file or directory
./scripts/android/toolchain.sh: line 20: which: No such file or directory
./scripts/android/toolchain.sh: line 21: mason: No such file or directory
./scripts/android/toolchain.sh: line 21: which: No such file or directory
./scripts/android/toolchain.sh: line 22: mason: No such file or directory
./scripts/android/toolchain.sh: line 23: mason: No such file or directory
./scripts/android/toolchain.sh: line 24: mason: No such file or directory
./scripts/android/toolchain.sh: line 25: mason: No such file or directory
./scripts/android/toolchain.sh: line 26: mason: No such file or directory
deps/run_gyp android/mapboxgl-app.gyp -Dhost=android -Iconfig/android-arm-v7.gypi -Dheadless_lib=none -Dplatform_lib=android -Dasset_lib=zip -Dhttp_lib=curl -Dcache_lib=sqlite --depth=. -Goutput_dir=. --generator-output=./build/android-arm-v7 -f make-android
/home/leith/mb/mapbox-gl-native/.mason/mason: fork: retry: No child processes
/home/leith/mb/mapbox-gl-native/.mason/mason: fork: retry: No child processes
/home/leith/mb/mapbox-gl-native/.mason/mason: fork: retry: No child processes
/home/leith/mb/mapbox-gl-native/.mason/mason: fork: retry: No child processes
/home/leith/mb/mapbox-gl-native/.mason/mason: fork: retry: No child processes
/home/leith/mb/mapbox-gl-native/.mason/mason: fork: retry: No child processes
/home/leith/mb/mapbox-gl-native/.mason/mason: fork: Resource temporarily unavailable
./scripts/android/toolchain.sh: line 15: mason: No such file or directory
./scripts/android/toolchain.sh: line 15: which: No such file or directory
./scripts/android/toolchain.sh: line 16: mason: No such file or directory
./scripts/android/toolchain.sh: line 16: which: No such file or directory
./scripts/android/toolchain.sh: line 17: mason: No such file or directory
./scripts/android/toolchain.sh: line 17: which: No such file or directory
./scripts/android/toolchain.sh: line 18: mason: No such file or directory
./scripts/android/toolchain.sh: line 18: which: No such file or directory
./scripts/android/toolchain.sh: line 19: mason: No such file or directory
./scripts/android/toolchain.sh: line 19: which: No such file or directory
./scripts/android/toolchain.sh: line 20: mason: No such file or directory
./scripts/android/toolchain.sh: line 20: which: No such file or directory
./scripts/android/toolchain.sh: line 21: mason: No such file or directory
./scripts/android/toolchain.sh: line 21: which: No such file or directory
./scripts/android/toolchain.sh: line 22: mason: No such file or directory
./scripts/android/toolchain.sh: line 23: mason: No such file or directory
./scripts/android/toolchain.sh: line 24: mason: No such file or directory
./scripts/android/toolchain.sh: line 25: mason: No such file or directory
./scripts/android/toolchain.sh: line 26: mason: No such file or directory
make -C build/android-arm-v7 BUILDTYPE=Release androidapp
make[1]: Entering directory '/home/leith/mb/mapbox-gl-native/build/android-arm-v7'
  ACTION mbgl_gyp_version_target_Build_Version_Header Release/obj/gen/include/mbgl/util/version.hpp
  CXX(target) Release/obj.target/core/src/clipper/clipper.o
make[1]: -DNDEBUG: Command not found
core.target.mk:240: recipe for target 'Release/obj.target/core/src/clipper/clipper.o' failed
make[1]: *** [Release/obj.target/core/src/clipper/clipper.o] Error 127
make[1]: Leaving directory '/home/leith/mb/mapbox-gl-native/build/android-arm-v7'
Makefile:187: recipe for target 'android-lib-arm-v7' failed
make: *** [android-lib-arm-v7] Error 2
```

**Comment by ljbade** [comment]
OK got a compare link https://github.com/mapbox/mason/compare/abdc131...41d8b2e

**Comment by ljbade** [comment]
Only change that looks interesting is https://github.com/mapbox/mason/compare/abdc131...41d8b2e#diff-cc7a13abf233cbd4fc6762059aee5946R207

I think I need to clone mason on this computer to the right place.

**Comment by ljbade** [comment]
Hrm still does it.

@springmeyer What do you think has broken?

**Comment by springmeyer** [comment]
@ljbade - I don't know. I've not being working on mason master so I presume it is some change @kkaefer made. I'm also on vacation for a week starting today, so lean on @kkaefer ideally for help.

**Comment by 1ec5** [comment]
Per scrum, we’d like to feature iOS 9 SDK compatibility in the next release of GL for iOS. If we don’t figure the Android build failures by then, we’ll cut a branch based on the current submodule pin and cherry-pick just mapbox/mason@41d8b2eb28b3cd942d9f15583467b27c549675ea.

**Comment by ljbade** [comment]
@1ec5 Yeah I'd do that while we figure this out.

**Comment by kkaefer** [comment]
Is this fixed in current master?

**Comment by 1ec5** [comment]
@kkaefer, yes, that fixed it – thanks. I’ve also pulled in mason/mason@d8597d9 for mapbox/mason#110 to fix #1707.

**Pull request merged**
