### PR TITLE
[core] Bump standard library to libstdc++5-dev and clang version to 3.8.

### PR DESCRIPTION
**Pull request by ChrisLoer**

### CODE REVIEW

**Comment by jfirebaugh** [comment]
This proved to be a prerequisite for portions of #6984, namely using `<codecvt>` for UTF transcoding.

@kkaefer @brunoabinader @springmeyer See any downsides to upgrading? This basically brings mapbox-gl-js in line with the recommendations of https://github.com/mapbox/cpp.

**Comment by springmeyer** [comment]
:+1 This feels like the right way forward. https://github.com/mapbox/mapbox-gl-native/issues/309 tracks when we hit this before and decided to work around without upgrading libstdc++. I think it is a good time to require at least libstdc++-5-dev.

> See any downsides to upgrading?

I think the upsides outweight the downsides. And the downside is not a blocker, but I'll detail it for the record. It is that requiring libstdc++-5 instead of 4.9 will trigger a GLIBCXX symbol dependency will jump to GLIBCXX_3.4.21. This means that binaries built of mbgl-native will work out of the box on systems >= ubuntu xenial, but will not work on ubuntu trusty or ubuntu precise without upgrading libstdc++. Because we were targeting libstdc++-4.9 before, mbgl binaries (including node-mbgl) would run on ubuntu trusty by default. However, for Mapbox this has no impact, since we've already upgraded our systems to support GLIBCXX_3.4.21 as per the upgrade methods described in https://github.com/mapbox/cpp.

**Comment by kkaefer** [comment]
As an alternative to using `codecvt`, we could also make this a system-specific API and backfill with Nunicode on platforms where no platform-native alternative is available.

**Comment by jfirebaugh** [comment]
`codecvt` is a standard C++11 feature -- it makes more sense to me to use it rather than platform-specific equivalents.

**Pull request merged**
