### PR TITLE
{ios,osx} ⇢ platform

### LINKED ISSUE #3702: move include/mbgl/{darwin,ios,osx} to platform/{darwin,ios,osx}/include
Followup to #3324, #3328, etc.

### PR DESCRIPTION
**Pull request by jfirebaugh**
Fixes #3702.

:eyes: @1ec5

### CODE REVIEW

**Comment by 1ec5** [comment]
Looks good at a cursory glance. Make sure to test both the static framework and dynamic framework on iOS, and test launching osxapp from Finder.

**Comment by jfirebaugh** [comment]
> test both the static framework and dynamic framework on iOS

Is this something that we can have CI do?

**Comment by jfirebaugh** [comment]
I tried replacing Mapbox.framework in the "Mapbox GL Tests" target of ios-tests.xcproject with the static framework using the steps described in INSTALL.md, but when running it I get the following error:

```
dyld: Library not loaded: @rpath/Mapbox.framework/Mapbox
  Referenced from: /Users/john/Library/Developer/CoreSimulator/Devices/5EF1C722-105D-43FF-9F03-34E0D9E39944/data/Containers/Bundle/Application/92733C1C-DBB8-4A62-9D63-5517C875F8BF/Mapbox GL Tests.app/Mapbox GL Tests
  Reason: no suitable image found.  Did find:
	/Users/john/Library/Developer/CoreSimulator/Devices/5EF1C722-105D-43FF-9F03-34E0D9E39944/data/Containers/Bundle/Application/92733C1C-DBB8-4A62-9D63-5517C875F8BF/Mapbox GL Tests.app/Frameworks/Mapbox.framework/Mapbox: unknown file type, first eight bytes: 0x21 0x3C 0x61 0x72 0x63 0x68 0x3E 0x0A
```

**Comment by 1ec5** [comment]
We only build (and test) the dynamic framework on Bitrise to keep the build times low. We could add a scheduled nightly build on Bitrise that builds both, however. I can't find the ticket tracking that right now.

**Comment by jfirebaugh** [comment]
I was able to hand-edit `pkg/dynamic` ⇢ `pkg/static` in ios-tests.xcodeproj, make the other necessary changes (adding frameworks and libraries and `-ObjC`), and build and run the tests. Going to merge.

**Pull request merged**
