### PR TITLE
undef GLX constants and chmod +x Python scripts

### PR DESCRIPTION
**Pull request by mikemorris**
Warning from @kkaefer:
> @mikemorris I think the reason we avoided [dropping the `python` gyp var] is that Xcode may not necessarily have the python executable in its PATH

### CODE REVIEW

**Comment by kkaefer** [comment]
@mikemorris can you please look at what it takes to remove the GLX headers from the headless_view.hpp and only include it in the CPP file? We might be able to just add a few forward definitions rather than including the whole GLX header file, which would restrict the overly broadly named definitions to just the CPP file.

**Comment by mikemorris** [comment]
@kkaefer Good thinking, I'll see if I can hit that today.

**Comment by mikemorris** [comment]
@kkaefer Broke the GLX cleanup out into a separate PR at https://github.com/mapbox/mapbox-gl-native/pull/840

**Comment by mikemorris** [comment]
-> new PR into `master` at https://github.com/mapbox/mapbox-gl-native/pull/842

**Pull request closed without merging**
