### PR TITLE
[core] don't hide icons if text is an empty string

### PR DESCRIPTION
**Pull request by ansis**
port of https://github.com/mapbox/mapbox-gl-js/pull/6164

### CODE REVIEW

**Comment by ChrisLoer** [comment]
I think there's actually a very subtle difference from the GL JS logic here.

GL JS says "if you have a collision box, try to place it", and in `symbol_layout.js` it only adds a collision box if the shaping is non-empty:

https://github.com/mapbox/mapbox-gl-js/blob/692ee23a301210a4a98c56e88c7e77c6ffbe4324/src/symbol/symbol_layout.js#L341-L344

But on gl-native, this new logic says "if you have a non-empty shaping, try to place your `CollisionFeature`". I think in gl-native we'll actually create a `CollisionFeature` (and accompanying box, potentially with non-zero size due to padding) even if the shaping is empty:

https://github.com/mapbox/mapbox-gl-native/blob/8a283b030629abb00367929d047731c3974bc3d6/src/mbgl/layout/symbol_layout.cpp#L254-L257

https://github.com/mapbox/mapbox-gl-native/blob/8a283b030629abb00367929d047731c3974bc3d6/src/mbgl/layout/symbol_instance.cpp#L33-L35

Did the new test fail before you made these changes? It seems to me like they may not be necessary (although we should rationalize the behavior between JS and native, I'm starting to think the current native behavior _may_ be more correct?)

**Comment by ansis** [comment]
@ChrisLoer good point. I need to dig into this more

> Did the new test fail before you made these changes?

Yep, the test fails without these changes

**Comment by ChrisLoer** [comment]
I just added a native ignore for this for https://github.com/mapbox/mapbox-gl-native/pull/11156, let's remember to take that out when we merge the fix here.

**Comment by ansis** [comment]
Ok, so, there are three cases we care about: no text, empty string of text, text. 

native master creates:
- zero-sized shapings and collision features for no text
- zero-plus-padding-sized shapings and collision features for empty strings of text

However, they never get used because [this](https://github.com/mapbox/mapbox-gl-native/blob/c2d9d6a4235d5bce5c10b40b3f8cfaeb331d7878/src/mbgl/text/placement.cpp#L115) is only true when the text is a non-empty string. So while there are internal differences between native master and old -js, they had the same behaviour.

---

I think it might be fine to continue treating an empty string of text the same as undefined text. Both would never be tested for collisions. Do you see any good reason to start treating empty strings differently?

I pushed a fix that is equivalent to the previous fix but simpler. It just changes the per-bucket data presence check to a per-feature check. If this looks good, I'll change -js to match this approach (which shouldn't change -js behaviour).

**Pull request merged**
