### PR TITLE
[core] Wireframe debug mode

### PR DESCRIPTION
**Pull request by brunoabinader**
Together with `MapDebugOptions::Collision`, provides _wireframe_ rendering output so all drawn objects are visible. This mode ignores the line width, background and fill colors for better visualization.

/cc @mapbox/gl

### CODE REVIEW

**Comment by brunoabinader** [comment]
Example output:

wireframe

:eyes: @kkaefer @jfirebaugh @tmpsantos

**Comment by 1ec5** [comment]
Awesome – this is the mode @kkaefer requested in #4669, right? It’ll be pretty easy to hook this up to the iOS and OS X SDKs now that there’s a `MapDebugOptions` option for it.

**Comment by brunoabinader** [comment]
@1ec5 I think this is what @kkaefer mentioned - https://github.com/mapbox/mapbox-gl-native/blob/master/platform/default/glfw_view.cpp#L483-L520 - which provides a different output - but can be added as a new `MapDebugOptions` as such.

**Comment by 1ec5** [comment]
22ef615f360bb5e0ea58491620f0fc59da8f491b exposes this new mode in the iOS and OS X SDKs and their demo applications.

**Comment by brunoabinader** [comment]
Thank you @1ec5!

**Comment by kkaefer** [comment]
@brunoabinader stencil mask mode is different from the wireframe mode; the stencil mode shows the checkerboard-style pattern that we're using to clip tiles.

**Comment by brunoabinader** [comment]
@kkaefer yes, that's exactly what I mentioned to @1ec5 in the last comment :) We should move the stencil mask code to core and add a new enum for it in `MapDebugOptions`.

**Pull request merged**
