### PR TITLE
Support GL face culling

### PR DESCRIPTION
**Pull request by brunoabinader**
This is a common OpenGL optimization technique that skips rendering e.g. back-facing triangles. For that, we need to apply a common winding order (either clockwise or counter-clockwise) when ordering the triangle vertices we use when drawing.

When enabling face culling, GL culls back-facing triangles and assumes front-facing triangles being ones ordered counter-clockwise by default. This required some changes in our winding order when populating our buckets.

We enable face culling by default. We apply counter-clockwise winding order for culling back-facing triangles when rendering in the main buffer, and clockwise winding order for culling front-facing triangles when rendering offscreen (heatmaps, hillshade and fill extrusions). We disable face culling when rendering custom layers.

Depends on https://github.com/mapbox/mapbox-gl-js/pull/7178.

### CODE REVIEW

**Comment by brunoabinader** [comment]
CI failures are caused due to recent unrelated GL JS changes - will solve those once https://github.com/mapbox/mapbox-gl-js/pull/7178 is merged.

**Comment by brunoabinader** [comment]
Mapbox GL JS benchmark results for reference: https://github.com/mapbox/mapbox-gl-js/pull/7178#issuecomment-415741498

**Comment by mollymerp** [comment]
@brunoabinader sorry about that! hoping to merge #12284 asap and that should resolve failures.

**Comment by brunoabinader** [comment]
Thank you @mollymerp :bowing_man:  @nagineni is going to push this forward while I'm on vacations.

**Comment by anderco** [comment]
I started to implement the same feedback given to the JS version to this PR. See https://github.com/mapbox/mapbox-gl-native/tree/anderco-face-culling

**Comment by anderco** [comment]
I updated this PR to match what was done in mapbox/mapbox-gl-js#7178, so face culling is only enabled for fill extrusion layers by adding a face culling mode parameter to Program::draw().

/cc @ansis

**Pull request merged**
