### PR TITLE
[Android][WIP] Refactor my location view

### PR DESCRIPTION
**Pull request by cammace**
The user location has been suffering from a few bugs since it is a view placed on top of map. 

Closes: https://github.com/mapbox/mapbox-gl-native/issues/6084
Closes: https://github.com/mapbox/mapbox-gl-native/issues/4799
Closes: https://github.com/mapbox/mapbox-gl-native/issues/2564?
Closes: https://github.com/mapbox/mapbox-gl-native/issues/7086
Closes: https://github.com/mapbox/mapbox-gl-native/issues/7349?
Closes: https://github.com/mapbox/mapbox-gl-native/issues/6768?
Closes: https://github.com/mapbox/mapbox-gl-native/issues/6765?
Closes: https://github.com/mapbox/mapbox-gl-native/issues/6167
Closes: https://github.com/mapbox/mapbox-gl-native/issues/6138

This PR attempts to refactor mainly the locationView to instead use runtime styling on the map. 

ezgif com-video-to-gif 3

A few things are left to bring this implementation up to par with what the current my location view offers, mainly tracking, animation between new user location positions, and customization of the colors.

### CODE REVIEW

**Comment by cammace** [comment]
Customization of user location icon:
ezgif com-video-to-gif 2

User location compass (Not sure what is causing the flickering): 
ezgif com-video-to-gif 1

Stale user location:
ezgif com-video-to-gif

**Comment by zugaldia** [comment]
@cammace Looking fantastic.

**Comment by cammace** [comment]
This implementation is currently blocked after discovering that consistently calling turf.circle while animating the user location to a new position produces major lagging on the map. The ideal fix for this will be once `circle-pitch-alignment` is implemented in the style spec (currently being tracked in https://github.com/mapbox/mapbox-gl-style-spec/issues/459).

**Comment by zugaldia** [comment]
@cammace Looking at the list of tickets this PR could potentially close, though I understand https://github.com/mapbox/mapbox-gl-style-spec/issues/459 is a blocker for full implementation, would it be possible to land partial progress with this PR (closing those tickets that don't depend on `circle-pitch-alignment`) and leave the rest for a separate PR?

**Comment by cammace** [comment]
I'll look into this beginning of next week, I think some issues have already been resolved such as this flickering issue:

https://cloud.githubusercontent.com/assets/5652865/21627666/61722fb0-d1e7-11e6-89cf-fa8ceb98909e.gif

which was fixed recently with https://github.com/mapbox/mapbox-gl-native/issues/7615

**Comment by cammace** [comment]
Closing in favor of https://github.com/mapbox/mapbox-plugins-android/pull/22

**Pull request closed without merging**
