### PR TITLE
Delay render thread creation for TextureView impl

### PR DESCRIPTION
**Pull request by tobrun**
Possible solution to https://github.com/mapbox/mapbox-gl-native/issues/13601. Working on creating a reproducible testcase and needs to be refactored in a cleaner setup conform to GLSurfaceView attach/detach setup.

### CODE REVIEW

**Comment by tobrun** [comment]
>  Working on creating a reproducible testcase 

So far no luck with this. Been trying to reproduce on older android handsets as it seems this condition can mostly occur on devices with limited hardware.

**Comment by tobrun** [comment]
Did some benchmarking on `init` to `OnMapReady`:

### Master:
2019-07-31 14:51:01.913 24525-24525/com.mapbox.mapboxsdk.testapp E/TVN: Execution time is 378
2019-07-31 14:51:14.201 24525-24525/com.mapbox.mapboxsdk.testapp E/TVN: Execution time is 130
2019-07-31 14:51:19.746 24525-24525/com.mapbox.mapboxsdk.testapp E/TVN: Execution time is 140
2019-07-31 14:51:23.028 24525-24525/com.mapbox.mapboxsdk.testapp E/TVN: Execution time is 123
2019-07-31 14:51:26.275 24525-24525/com.mapbox.mapboxsdk.testapp E/TVN: Execution time is 137
2019-07-31 14:51:29.849 24525-24525/com.mapbox.mapboxsdk.testapp E/TVN: Execution time is 128
2019-07-31 14:51:33.703 24525-24525/com.mapbox.mapboxsdk.testapp E/TVN: Execution time is 127
2019-07-31 14:51:37.312 24525-24525/com.mapbox.mapboxsdk.testapp E/TVN: Execution time is 107

-> which averages to 158,75 ms

### This branch:
2019-07-31 14:55:51.608 24541-24541/com.mapbox.mapboxsdk.testapp E/TVN: Execution time is 364
2019-07-31 14:55:58.875 24541-24541/com.mapbox.mapboxsdk.testapp E/TVN: Execution time is 164
2019-07-31 14:56:02.387 24541-24541/com.mapbox.mapboxsdk.testapp E/TVN: Execution time is 113
2019-07-31 14:56:06.966 24541-24541/com.mapbox.mapboxsdk.testapp E/TVN: Execution time is 130
2019-07-31 14:56:11.307 24541-24541/com.mapbox.mapboxsdk.testapp E/TVN: Execution time is 151
2019-07-31 14:56:25.909 24541-24541/com.mapbox.mapboxsdk.testapp E/TVN: Execution time is 138
2019-07-31 14:56:30.533 24541-24541/com.mapbox.mapboxsdk.testapp E/TVN: Execution time is 119
2019-07-31 15:00:06.591 24541-24541/com.mapbox.mapboxsdk.testapp E/TVN: Execution time is 136

-> which averages to 164,375 ms

**Comment by tobrun** [comment]
> So far no luck with this. Been trying to reproduce on older android handsets as it seems this condition can mostly occur on devices with limited hardware.

still no luck but a customer that was hitting this issue. Confirmed that after a long test run using a snapshot build from this branch, they aren't seeing this issue anymore.

**Comment by LukasPaczos** [comment]
Can we run into a situation where an activity is stopped/paused, or the surface is created and the renderer requested, before the view is attached to the window? Those cases would cause an NPE.

**Comment by tobrun** [comment]
> Can we run into a situation where an activity is stopped/paused, or the surface is created and the renderer requested, before the view is attached to the window? Those cases would cause an NPE.

So far my tests haven't show this:
 - instrumentation tests
 - monkey tests (using only textureview activities)
 - manual testing

The monkey tests were to validate the `activity is stopped/paused` part. For the latter situation of `surface is created and the renderer requested, before the view is attached to the window`. The render thread, that is responsible for requesting the render eg. [here](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/renderer/textureview/TextureViewRenderThread.java#L75), isn't created yet. It's created as part of the attach view callback.

Lmk if you are able to find an issue with this setup. A customer testing this branch, hasn't hit suggested issues yet.

**Comment by LukasPaczos** [comment]
I gave this another round and spotted a possible cause of the issue. Proposed fix in https://github.com/mapbox/mapbox-gl-native/pull/15355.

**Comment by tobrun** [comment]
Moving forward with https://github.com/mapbox/mapbox-gl-native/pull/15355#pullrequestreview-276494331 instead

**Pull request closed without merging**
