### PR TITLE
CP [core] Variable label placement

### PR DESCRIPTION
**Pull request by pozdnyakov**
Port of mapbox/mapbox-gl-js#7596

Cherry-pick of https://github.com/mapbox/mapbox-gl-native/pull/14184

### CODE REVIEW

**Comment by julianrex** [comment]
Should this be merged to master, and then cherry-picked?

**Comment by pozdnyakov** [comment]
@julianrex Sorry, for being unclear, it was merged to master already https://github.com/mapbox/mapbox-gl-native/pull/14184.  I'll update the PR description.

**Comment by julianrex** [comment]
Would you mind updating the change logs and we can PR that too

**Comment by pozdnyakov** [comment]
> Would you mind updating the change logs and we can PR that too

Change logs are updated in the latest commit, pls tell if I did this properly :-)

**Pull request merged**
