### PR TITLE
5282 locationpicker

### PR DESCRIPTION
**Pull request by ivovandongen**
Still need to squash the commits

### CODE REVIEW

**Comment by zugaldia** [comment]
Found a merge conflict while rebasing with `platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerViewManager.java`. Resolving now.

**Comment by zugaldia** [comment]
CI is complaining in the javadoc phase.

```
:MapboxGLAndroidSDK:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
/bitrise/src/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerViewManager.java:435: error: cannot find symbol
        marker.setDuration(duration);
              ^
  symbol:   method setDuration(long)
  location: variable marker of type MarkerView
/bitrise/src/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerViewManager.java:436: error: cannot find symbol
        marker.setStartTime(AnimationUtils.currentAnimationTimeMillis());
                            ^
  symbol:   variable AnimationUtils
  location: class MarkerViewManager
/bitrise/src/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerViewManager.java:437: error: cannot find symbol
        marker.setShouldAnimate(true);
              ^
  symbol:   method setShouldAnimate(boolean)
  location: variable marker of type MarkerView
/bitrise/src/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerViewManager.java:443: error: cannot find symbol
            marker.setAnimating(true);
                  ^
  symbol:   method setAnimating(boolean)
  location: variable marker of type MarkerView
/bitrise/src/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerViewManager.java:444: error: cannot find symbol
            PointF screenLocation = mapboxMap.getProjection().toScreenLocation(marker.getTargetPosition());
                                                                                     ^
  symbol:   method getTargetPosition()
  location: variable marker of type MarkerView
/bitrise/src/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerViewManager.java:448: error: cannot find symbol
            ObjectAnimator animatorX = ObjectAnimator.ofFloat(convertView, "x", screenLocation.x - marker.getOffsetX());
            ^
  symbol:   class ObjectAnimator
  location: class MarkerViewManager
/bitrise/src/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerViewManager.java:448: error: cannot find symbol
            ObjectAnimator animatorX = ObjectAnimator.ofFloat(convertView, "x", screenLocation.x - marker.getOffsetX());
                                       ^
  symbol:   variable ObjectAnimator
  location: class MarkerViewManager
/bitrise/src/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerViewManager.java:449: error: cannot find symbol
            ObjectAnimator animatorY = ObjectAnimator.ofFloat(convertView, "y", screenLocation.y - marker.getOffsetY());
            ^
  symbol:   class ObjectAnimator
  location: class MarkerViewManager
/bitrise/src/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerViewManager.java:449: error: cannot find symbol
            ObjectAnimator animatorY = ObjectAnimator.ofFloat(convertView, "y", screenLocation.y - marker.getOffsetY());
                                       ^
  symbol:   variable ObjectAnimator
  location: class MarkerViewManager
/bitrise/src/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerViewManager.java:450: error: cannot find symbol
            AnimatorSet set = new AnimatorSet();
            ^
  symbol:   class AnimatorSet
  location: class MarkerViewManager
/bitrise/src/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerViewManager.java:450: error: cannot find symbol
            AnimatorSet set = new AnimatorSet();
                                  ^
  symbol:   class AnimatorSet
  location: class MarkerViewManager
/bitrise/src/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerViewManager.java:453: error: cannot find symbol
            set.setDuration(marker.getRemainingTime());
                                  ^
  symbol:   method getRemainingTime()
  location: variable marker of type MarkerView
/bitrise/src/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerViewManager.java:454: error: cannot find symbol
            set.addListener(new AnimatorListenerAdapter() {
                                ^
  symbol:   class AnimatorListenerAdapter
  location: class MarkerViewManager
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /bitrise/src/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerViewManager.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
13 errors
:MapboxGLAndroidSDK:compileReleaseJavaWithJavac FAILED
```

@cammace could I have your 👀 here?

**Comment by ivovandongen** [comment]
@zugaldia Started over with local state. Squashed into 2 commits now, one for #5282 and one for #5384

**Comment by zugaldia** [comment]
@ivovandongen Merged. Thanks for sorting this up.

**Pull request merged**
