### PR TITLE
[iOS] Add tests for map region change events

### PR DESCRIPTION
**Pull request by lloydsheng**
The PR contains following main changes:
1.  Added a UI testing bundle `Integration UI Tests`
2. Added a simple map view page in the bundle for testing 
3. Added a test for verifying map region events triggered as expected

### CODE REVIEW

**Comment by julianrex** [comment]
Since this uses some code from `ios-sdk-examples` let's discuss with @friedbunny if we can lift the shared code out into a separate dependency, or whether this is now the time to think about further integrating these two projects.

**Comment by julianrex** [comment]
UI tests are fragile - I wonder if there's a more appropriate way to test this?

**Comment by friedbunny** [comment]
> UI tests are fragile - I wonder if there's a more appropriate way to test this?

We’ve had iOS UI tests in `gl-native` previously and were forced to abandon them — the cost of an unreliable test is too high (given the number of disparate contributors and platforms here) and maintaining reliability for UI tests that run on CI is not a productive use of limited developer resources.

I think that I’d be in favor of directly integrating `ios-sdk-examples` into `gl-native`, but that’s a bigger discussion.

**Comment by lloydsheng** [comment]
>  UI tests are fragile - I wonder if there's a more appropriate way to test this?

That's most appropriate way I can find.

@julianrex @friedbunny Thanks for your suggestions. To make a long story short, we currently should not pay any efforts on UI testing?

**Comment by julianrex** [comment]
> @julianrex @friedbunny Thanks for your suggestions. To make a long story short, we currently should not pay any efforts on UI testing?

We should absolutely be looking at UI testing - but I think the consensus is that `ios-sdk-examples` is a better home for these. UI tests are great for user testing - and the examples are perfect candidates.

**Comment by lloydsheng** [comment]
Close this PR, will move the test to `ios-sdk-examples`.

**Pull request closed without merging**
