### PR TITLE
Add location related tests

### LINKED ISSUE #7159: Dynamically grant permissions in UI tests
There are some tests excluded from being generated and/or ignored because a way to grant permissions dynamically in tests wasn't implemented.

There are some workarounds to grant permissions dynamically in tests.
Including:
* `adb install -g`
* [PermissionGranter](https://gist.github.com/rocboronat/65b1187a9fca9eabfebb5121d818a3c4)
* [Grant permissions before tests](https://github.com/googlesamples/android-testing/blob/ed62c450e43f859333b3113d44dd59f75971b529/ui/espresso/IntentsBasicSample/app/src/androidTest/java/com/example/android/testing/espresso/BasicSample/DialerActivityTest.java#L94)

I think the latter would be the best approach.

Below all the activities that request Location permissions:
`MyLocationTrackingModeActivity`, `MyLocationToggleActivity`, `MyLocationTintActivity`, `MyLocationDrawableActivity`, `LocationPickerActivity` and `MyLocationViewTest`.

Cc/ @tobrun @zugaldia

### PR DESCRIPTION
**Pull request by Guardiola31337**
Fixes #7159.

* Added location permission granter.
* Removed location related activities (except `MyLocationDrawableActivity` because of #7174) from being excluded.
* Removed @Ignore annotation of `testEnabled()` (`MyLocationViewTest`).

Note: Still ignoring `testTracking()` (`MyLocationViewTest`).

Cc/ @tobrun @zugaldia

### CODE REVIEW

**Comment by Guardiola31337** [comment]
There is an issue with the permission dialog popup. It is still appearing even granting permissions (`PermissionGranter. grantLocation()`) beforehand. Maybe, the second option defined here #7177 is better. The problem is that [UIAutomator](https://developer.android.com/topic/libraries/testing-support-library/index.html#UIAutomator) requires API level 18 or higher and changing the `minSdkVersion` of testapp should be discussed.

We should discuss as well how to test activities which require permissions because if you get rid of the permission dialog (e.g. denying it forever) tests pass (because we aren't testing anything that involves permissions) and `PermissionGranter. grantLocation()` isn't doing anything, which means tests aren't giving any value in the permissions aspect.

What do you think @tobrun @zugaldia @cammace?

**Comment by tobrun** [comment]
I will look into resolving conflicts and the remarks mentioned in OP.

**Comment by Guardiola31337** [comment]
I managed to solve the problem with the popup dialog. The problem was that @Before is executed after the activity is launched and obviously before the test. Which means the activity is launched first and shows the dialog.
So, in this particular case @BeforeClass solves the issue.

**Comment by Guardiola31337** [comment]
`testEnabled()` from `MyLocationViewTest` is not working. It's related with the order between asking for `LocationServices.getLocationServices(view.getContext()).getLastLocation()` (called in `ToggleLocationAction`) and when permissions are actually granted.

**Comment by Guardiola31337** [comment]
@tobrun
I run `MyLocationTintActivityTest` locally and it's working. What error did you get?
I don't know what happened with the last Bitrise check. Could you tell me?

**Comment by Guardiola31337** [comment]
Remember to remove from being excluded when #7181 is merged.

**Comment by tobrun** [comment]
I saw the same thing here @Guardiola31337, but also noticed that CI was failing over a strange native crash of updateMarker (which isn't anywhere found in the code executed). Now disabling that test shows that another location related test is failing on the same updateMarker function. Need to make some time to dig into this..

**Comment by zugaldia** [comment]
@Guardiola31337 @tobrun Any progress here? Do you need my 👀 ?

**Comment by 1ec5** [comment]
Since this PR is scheduled for Android SDK v5.0.0, it needs to be rebased and retargeted at the release-ios-v3.5.0-android-v5.0.0 branch.

**Comment by tobrun** [comment]
Since this PR is related to testing already existing features, moving it from the 5.0.0 milestone.

**Comment by tobrun** [comment]
Initial issue this PR was closing was made obsolete, closing this PR as well.

**Pull request closed without merging**
