### PR TITLE
Merge release-android-2.0.0-redo-working Back Into Master

### PR DESCRIPTION
**Pull request by bleege**
For #2515 

/cc @incanus @jfirebaugh

### CODE REVIEW

**Comment by incanus** [comment]
Cool. The ultimate test here will be not whether this goes cleanly, but whether it unblocks future merges as well. Was having trouble ironing this out on Friday, so I will take a look at this as it was on my roadmap anyway.

**Comment by bleege** [comment]
Woo hoo!  Travis CI has just signed off.  Let the fun begin!

**Comment by bleege** [comment]
Results of Step 1 for Command Line Merge:

```
Brads-MacBook-Pro:mapbox-gl-android brad$ git status
On branch release-android-v2.0.0-redo-working
Your branch is up-to-date with 'origin/release-android-v2.0.0-redo-working'.
nothing to commit, working directory clean
Brads-MacBook-Pro:mapbox-gl-android brad$ git fetch origin
Brads-MacBook-Pro:mapbox-gl-android brad$ git merge master
Removing src/rapidjson/writer.h
Removing src/rapidjson/stringbuffer.h
Removing src/rapidjson/reader.h
Removing src/rapidjson/rapidjson.h
Removing src/rapidjson/prettywriter.h
Removing src/rapidjson/internal/strfunc.h
Removing src/rapidjson/internal/stack.h
Removing src/rapidjson/internal/pow10.h
Removing src/rapidjson/filestream.h
Removing src/rapidjson/document.h
Removing src/mbgl/map/annotation.hpp
Auto-merging src/mbgl/annotation/annotation_manager.cpp
Removing platform/ios/MGLFileCache.mm
Removing platform/ios/MGLFileCache.h
Removing ios/benchmark/fo/benchmark-ios.gypi
Removing ios/benchmark/fo/MBXBenchViewController.mm
Removing ios/benchmark/assets/tiles/mapbox.mapbox-terrain-v2.json
Removing ios/benchmark/assets/tiles/mapbox.mapbox-streets-v6.json
Removing ios/benchmark/assets/styles/mapbox-streets-v7.json
Removing include/mbgl/util/variant_io.hpp
Removing include/mbgl/util/variant.hpp
Removing include/mbgl/util/recursive_wrapper.hpp
Removing include/mbgl/util/optional.hpp
Removing deps/gtest/gtest/gtest.h
Removing deps/gtest/gtest.gyp
Removing deps/gtest/gtest-all.cc
Auto-merging android/java/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/MainActivity.java
Auto-merging android/java/MapboxGLAndroidSDKTestApp/src/main/AndroidManifest.xml
Auto-merging android/java/MapboxGLAndroidSDKTestApp/build.gradle
Auto-merging android/java/MapboxGLAndroidSDK/src/main/res/layout/infowindow.xml
CONFLICT (content): Merge conflict in android/java/MapboxGLAndroidSDK/src/main/res/layout/infowindow.xml
Auto-merging android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/NativeMapView.java
Auto-merging android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/MapView.java
Auto-merging android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/geometry/CoordinateSpan.java
Auto-merging android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/geometry/BoundingBox.java
Auto-merging android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerOptions.java
CONFLICT (content): Merge conflict in android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerOptions.java
Auto-merging android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/Marker.java
CONFLICT (content): Merge conflict in android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/Marker.java
CONFLICT (rename/rename): Rename "android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxgl/annotations/InfoWindowTipView.java"->"android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/InfoWindowTipView.java" in branch "HEAD" rename "android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxgl/annotations/InfoWindowTipView.java"->"android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/InfoWindowTipView.java" in "master"
CONFLICT (rename/rename): Rename "android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxgl/annotations/InfoWindow.java"->"android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/InfoWindow.java" in branch "HEAD" rename "android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxgl/annotations/InfoWindow.java"->"android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/InfoWindow.java" in "master"
Auto-merging android/java/MapboxGLAndroidSDK/gradle.properties
CONFLICT (content): Merge conflict in android/java/MapboxGLAndroidSDK/gradle.properties
Auto-merging android/cpp/jni.cpp
CONFLICT (content): Merge conflict in android/cpp/jni.cpp
Automatic merge failed; fix conflicts and then commit the result.
Brads-MacBook-Pro:mapbox-gl-android brad$ 
```

**Comment by bleege** [comment]
The files that show up in Android Studio "Resolve Conflict" dialog.  Seems to be 2 more than the command line.

screen shot 2015-10-05 at 11 23 30 am

**Comment by bleege** [comment]
Ok... just finished merging `master` on to `release-android-v2.0.0-redo-working`.  Realized that the "2 extra" files were due to InfoWindow and InfoWindowTipView being moved from one package to another so this is correct.  I took the approach of "when in doubt accept the changes from master" while doing the merge.  I'm going to test things out locally and if life is good then will finish this process by doing Step 2 and merge back into `master`.

**Comment by incanus** [comment]
>  just finished merging `master` on to `release-android-v2.0.0-redo-working`

Not sure I follow here — we are only cherry-picking from `master` into the release branch, right? `v2.0.0` is the same as `v0.1.0`.

**Comment by bleege** [comment]
> Not sure I follow here — we are only cherry-picking from master into the release branch, right? v2.0.0 is the same as v0.1.0. 

@incanus That was the route that [you and I tried on Friday](https://github.com/mapbox/mapbox-gl-native/issues/2515#issuecomment-145138869) (2-Oct-2015) but it failed miserably due to massive underlying git disconnects that we discovered.  The strategy [was to redo the 5 commits](https://github.com/mapbox/mapbox-gl-native/issues/2515#issuecomment-145190609) in `release-android-v2.0.0-redo-working` and then merge back in.

**Comment by incanus** [comment]
My point is that redoing the commits, despite bringing over the code changes, leaves Git without knowledge that the old commits on `master` and the new, redone ones on the branch are the same thing, leading to future merge conflicts because of duplicate code and inability to determine commit order. Cherry-picking updates the index properly to help with this. So I don't think simply redoing the commits is enough to solve this problem. I'm still not sure what is yet.

**Comment by bleege** [comment]
Discussed with @jfirebaugh @incanus and due to the recreated commits already being in `master` there's no need to remerge this branch back into `master`.  Will use the [`android-2.0.0`](https://github.com/mapbox/mapbox-gl-native/commits/android-v2.0.0) tag for future point releases at `2.0.x`.

**Pull request closed without merging**
