### PR TITLE
Add Crashlytics NDK to Android

### LINKED ISSUE #2107: Use Crashlytics NDK support
It seems that Crashlytics has NDK support: http://docs.fabric.io/android/crashlytics/ndk.html

### PR DESCRIPTION
**Pull request by bleege**
Closes #2107

### CODE REVIEW

**Comment by bleege** [comment]
Hrmmm... the build on Travis works except for the Android builds.  The common issue is that it can't find an .apk to upload to S3.  Other than that things are murky as to what's actually causing this issue.

Will pause this merge until @ljbade can look at things in order to prevent all mapbox-gl-native builds from failing on Travis due to Android.

screen shot 2015-09-22 at 9 51 58 am
_Build Matrix_

screen shot 2015-09-22 at 9 51 12 am
_Can't Find .apk_

/cc @jfirebaugh

**Comment by ljbade** [comment]
Interesting maybe Crashlytics causes the filename there to change.

Do we need S3 APK upload now that we have maven and Crashlytics to archive the debug symbols?

**Comment by ljbade** [comment]
Ah APK split change I made causes it to name files with the ABI:
```
MapboxGLAndroidSDKTestApp-armeabi-release-unsigned.apk
MapboxGLAndroidSDKTestApp-armeabi-v7a-release-unsigned.apk
MapboxGLAndroidSDKTestApp-mips-release-unsigned.apk
MapboxGLAndroidSDKTestApp-universal-release-unsigned.apk
MapboxGLAndroidSDKTestApp-x86-release-unsigned.apk
```
I assume we want the universal one.

**Comment by ljbade** [comment]
Looks like the universal APK includes the 64bit Crashlytics JNI libs which is going to be a problem we will have to keep in mind when we integrate this into Sirius.

However this won't affect Travis builds and only the test app so I think we still OK to merge after fixing this error.

**Comment by ljbade** [comment]
Pushed a fix, waiting to see if this works.

**Comment by bleege** [comment]
Yep, working good.  Just saw [our first C++ error](https://fabric.io/mapbox4/android/apps/com.mapbox.mapboxgl.testapp/issues/56029491f5d3a7f76b414051) come in via Crashlytics NDK from this morning.

Thanks @ljbade!

**Pull request merged**
