### PR TITLE
port sprite atlas pollution fix

### LINKED ISSUE #1398: port sprite leaking fix
port https://github.com/mapbox/mapbox-gl-js/pull/1195

Fixes this test issue:

out

Diff:

image

### PR DESCRIPTION
**Pull request by ansis**
ports https://github.com/mapbox/mapbox-gl-js/pull/1195 to fix #1398

### CODE REVIEW

**Comment by ansis** [comment]
@kkaefer want to take a quick look? this should be ready to merge

**Comment by kkaefer** [comment]
Will review and adjust and re-enable test cases.

**Comment by jfirebaugh** [comment]
This improves some test cases but degrades others. In particular, some of the icons appear to be shifted one full pixel to the right compared to the reference rendering. See `icon-size/default` for example:

http://mapbox.s3.amazonaws.com/mapbox-gl-native/tests/4313.1/index.html

**Comment by ansis** [comment]
> some of the icons appear to be shifted one full pixel to the right compared to the reference rendering

I can't reproduce this locally. Can you?

The changes in this pr should affect all instances of an icon the same way so it's surprising that only some instances of the same icon are shifted. The only thing I can think of is that since the extrudes changed some precision issues caused the icons to snap (nearest neighbour filtering) in a different direction. This would be surprising though because it would be an unrelated issue that we haven't seen before.

**Comment by kkaefer** [comment]
I couldn't reproduce the regressed tests either.  @jfirebaugh, do you have an image?

**Comment by jfirebaugh** [comment]
I made some test suite adjustments so that things pass again. As always, "it's probably multiple issues".

**Pull request merged**
