### PR TITLE
Dispense Telemetry Events If Offline

### LINKED ISSUE #4629: Telemetry events buffer should be capped
We've started noticing `OutOfMemoryError` with the following stack trace:

screen shot 2016-04-07 at 14 07 59

It seems that it happens when device is offline for too long and have collected too much events. Even if it succeedeed, I'm not sure that Mapbox servers would be happy with parsing enormous JSONs. 

I see a couple of options:

 - use capped buffer for events (maybe some flavour of ring buffer); there is a chance to drop some events, but if we crash we drop all of them anyway;
 - send events in chunks; it would solve serialization problem, but  `OutOfMemoryError` could still happen because of excessive buffer growth;
 - flush some part of events to flash, while offline.

**Platform:** Android (but probably applies to iOS as well)
**Mapbox SDK version:** 4.0.0

### PR DESCRIPTION
**Pull request by bleege**
Closes #4629

### CODE REVIEW

**Comment by vkurchatkin** [comment]
@bleege maybe it makes sense also to call `events.removeAllElements()` in case of failed requests?

**Comment by bleege** [comment]
@vkurchatkin That should still happen regardless of the HTTP response.

**Comment by vkurchatkin** [comment]
@bleege what about `IOException`?

**Comment by bleege** [comment]
@vkurchatkin Ah... I see what you mean.  I just moved it to a `finally` block so that we can be super sure that it gets cleaned up.

**Comment by bleege** [comment]
Rebased and Merged!

**Pull request closed without merging**
