### PR TITLE
Reduce coupling of SourceInfo

### PR DESCRIPTION
**Pull request by kkaefer**
The SourceInfo object is too much integrated; it should become less dependent on other parts.

### CODE REVIEW

**Comment by kkaefer** [comment]
This pulls a lot of the preparatory code out of https://github.com/mapbox/mapbox-gl-native/pull/2721. All commits in this PR can be reviewed on their own.

/cc @jfirebaugh @tmpsantos

**Comment by jfirebaugh** [comment]
:+1: on `SourceInfo` becoming a simple data object solely responsible for holding TileJSON properties.

**Comment by kkaefer** [comment]
@jfirebaugh I think I addressed all of your notes with this set of commits. Can you please give it a cursory look, in particular https://github.com/mapbox/mapbox-gl-native/commit/389886e734bff14681bbd525278860b8894f3bd7?

I fixed based on your comments in 
https://github.com/mapbox/mapbox-gl-native/commit/dbbd4a7b04fa1f7f7ffb13260002695129a278c4#commitcomment-15376615 and https://github.com/mapbox/mapbox-gl-native/commit/72db4707e3748fb71ad5505fd6778faec8a09828#commitcomment-15377095.

**Comment by jfirebaugh** [comment]
Looks good!

**Pull request merged**
