### PR TITLE
Cherry-pick master changes into release-boba (mid-February edition)

### PR DESCRIPTION
**Pull request by friedbunny**
Cherry-picks some recent changes from `master` to `release-boba`:

- #11196 — iOS testing compatibility improvements.
- #11229 — Fix for location permission loop (from `ios-v3.7.5`).
- #11227 — Tile prefetching fixes.

/cc @asheemmamoowala @fabian-guerra

### CODE REVIEW

**Comment by friedbunny** [comment]
@ChrisLoer should we bring #11156 into `release-boba`, too?

**Comment by ChrisLoer** [comment]
> @ChrisLoer should we bring #11156 into release-boba, too?

I don't think #11156 (expression serialization) should be very high-risk/destabilizing, so I'd be inclined to pull it in. But I also don't know how much it will unblock on it's own vs. what we hope to get once iOS and Android have built wrappers around it? /cc @lilykaiser

**Comment by friedbunny** [comment]
Thanks, @asheemmamoowala — since these changes are being included in future `agua` patch releases (#11248), we’ll want to do the changelogging there.

**Comment by friedbunny** [comment]
@ChrisLoer we didn’t end up cherry-picking #11156 in _this_ PR, just so you’re aware. 🙇

**Pull request merged**
