### PR TITLE
[ios] Move image resources to an asset catalog & switch to PDFs

### LINKED ISSUE #5688: Optimize image assets
Noticed that there are room for improvements in terms of image assets:
- `Compass.png` is incorrect scale (2x = 1,8x, 3x = 2,81) (3x downscaling should be handled automatically) which results in half pixels when loading from resources.
- Logo is positioned on half pixels which prevents pixel perfect rendering.
- App Thinning cannot slice resources unless they're in an asset catalog. (would save ~12KB on 2x devices) (Cocoapods supports asset catalogs as of version 1.0)

### LINKED ISSUE #8703: Switch Mapbox logo to a universal PDF
Currently the Mapbox logo is included as pngs at 1x, 2x, and 3x. Let's switch this to a vector PDF like our macOS implementation.

/cc @friedbunny

### PR DESCRIPTION
**Pull request by friedbunny**
- Fixes #5688 by moving our bundled image resources into an [asset catalog](https://developer.apple.com/library/content/documentation/Xcode/Reference/xcode_ref-Asset_Catalog_Format/).

- Fixes #8703 by converting the logo and marker from raster PNGs to vector PDFs. The marker PDF is copied from the macOS SDK, while I reexported the logo PDF from the SVG in order to match the old dimensions.

~~I’ve left the compass as PNGs — we will need to recreate this resource in a vector format, which may be a good opportunity for redesign.~~ See https://github.com/mapbox/mapbox-gl-native/pull/9060#issuecomment-303315484 for the compass.

/cc @1ec5 @frederoni @ericrwolfe

### CODE REVIEW

**Comment by 1ec5** [comment]
The iOS build is failing, starting with:

```
MGLAnnotationViewTests
    ✗ testAnnotationView, failed: caught "Resource not found", "The resource named “mapbox.png” could not be found in the Mapbox framework bundle."
```

**Comment by friedbunny** [comment]
T’was afraid there would be problems with that — [`resourceImageNamed:`](https://github.com/mapbox/mapbox-gl-native/blob/5b21d2d70a04f30637d52167ef4be6083d372052/platform/ios/src/MGLMapView.mm#L5292) has PNG hardcoded. This works unmodified in iosapp (presumably because PDFs are converted to PNG at compile time). I'll look at why tests are failing.

**Comment by friedbunny** [comment]
Had to clean my local build before this test would fail locally. 😬 

Our old way of creating a bundle path and then using `+[UIImage imageWithContentsOfFile:]` will not work with asset catalogs, so eeb0ab426d5c61cf3f15faf8def46748f74ab65d switches to [`+[UIImage imageNamed:inBundle:compatibleWithTraitCollection:]`](https://developer.apple.com/reference/uikit/uiimage/1624154-imagenamed).

This new method has the distinct advantage of checking the system cache first, something `imageWithContentsOfFile:` did not do.

One thing for us to consider: if a developer is loading these resources manually, this switch to an asset catalog may break that (depending on which method they’re using). Broken images are typically silent errors that don’t typically crash apps (hence our exception in `resourceImageNamed:`).

**Comment by friedbunny** [comment]
This PR adds 48KB to the raw bundle, but switching to an asset catalog enables [App Thinning](https://developer.apple.com/library/content/documentation/IDEs/Conceptual/AppDistributionGuide/AppThinning/AppThinning.html#//apple_ref/doc/uid/TP40012582-CH35)/Slicing, which should ultimately reduce the number of bits delivered to an enduser.

**Comment by friedbunny** [comment]
This is broken for static builds because of https://github.com/mapbox/mapbox-gl-native/issues/9072 — `+[UIImage imageNamed:inBundle:compatibleWithTraitCollection:]` requires the correct bundle, but `+[NSBundle mgl_frameworkBundle]` does not return Mapbox.bundle.

**Comment by friedbunny** [comment]
On hold until #9074 lands.

**Comment by friedbunny** [comment]
Went ahead and vectorized the compass in https://github.com/mapbox/mapbox-gl-native/pull/9060/commits/815d7086c35c108db5432382dd35b027bbb9c13c:

newcompass

The new compass is slightly larger — the difference `@1x` is +2px (38px vs 40px), but `@2x` and `@3x` raster resources weren’t properly scaled, so they gained 11px and 16px. It’s a nicer touch target, though not terribly noticeable, even at 3x:

diff

**Pull request merged**
