### PR TITLE
[android] - get firebase test lab results with gsutil

### LINKED ISSUE #6218: Get results/logs from Firebase Test Lab
Capturing from conversation with @brunoabinader and request from @jfirebaugh:

Since https://github.com/mapbox/mapbox-gl-native/pull/6073 we are running instrumentation tests on the Android platform to prevent regressions. While the basic configuration is there to run the tests, we are not receiving any immediate feedback in our CI when a tests fails. The only way to get that information right now is to log into the Google service account. This is not ideal for an opensource project or for a team that is continually scaling.

I see two possible solutions:
 - download result files and make them part of the artefacts Bitrise produces during a build
 - configure Firebase test lab to show testresults without authentication

At this point the former seems to be more feasible than the latter. Reading up on the docs related to Firebase, it seems this should be possible using `gsutil`:

> You can also add a gsutil command to the shell command shown above to copy the test results data to your local computer.

The problem is that this is the only documentation Google offers on this so I need to figure a couple if things out first.

### PR DESCRIPTION
**Pull request by tobrun**
Closes #6218: adds the test results from Firebase test lab as an artefact to the Android Bitrise job.

### CODE REVIEW

**Comment by jfirebaugh** [comment]
Bump. @bleege and I are jumping through all kinds of hoops this morning trying to get access to this.

**Comment by tobrun** [comment]
Been working on publishing the test results as a build artefact. 

When the build finishes, you should be able to see the following on Bitrise:

screen shot 2016-09-02 at 15 39 45

Within that `.zip` the following files are located in `apk20160902-8744-1z09e1f/2016-09-02_12/46/39.767198_oKGA/shamu-22-en-portrait/`

screen shot 2016-09-02 at 15 41 16

**Comment by tobrun** [comment]
I'm punting on current progress to unblock people needing to look into the logcat output.
I will create a follow up ticket to improve current artefact and script.

**Comment by tobrun** [comment]
If CI approves we are good to merge for now. I validated that the logcat output is correctly added in both success/failing cases. We create follow up ticket to improve this in following days.

**Comment by tobrun** [comment]
It seems this didn't get merged yet, looking into this now

**Comment by zugaldia** [comment]
@tobrun 👍

**Comment by tobrun** [comment]
cc @mapbox/android

**Pull request merged**
