### PR TITLE
fixes #6688: assert remaining map view notification responses are main thread

### LINKED ISSUE #6688: -[MGLMapView didReceiveMemoryWarning] should MGLAssertIsMainThread()
`-[MGLMapView didReceiveMemoryWarning]` should `MGLAssertIsMainThread()`, as do other selectors observing `[NSNotificationCenter defaultCenter]`,  such as `sleepGL` and `wakeGL`. Or alternatively, it should dispatch itself back to the main thread.

`UIApplicationDidReceiveMemoryWarningNotification` is not specifically documented as being posted on the main thread, and if `_mbglMap->onLowMemory()` were called from a thread that's not the main thread, that would be bad.

### PR DESCRIPTION
**Pull request by incanus**
sign-colors

### CODE REVIEW

**Comment by incanus** [comment]
Can't get Android tests to pass, but they should not be impacted by this change.

**Comment by 1ec5** [comment]
```
Download https://jcenter.bintray.com/com/android/tools/annotations/25.2.2/annotations-25.2.2.jar
File /root/.android/repositories.cfg could not be loaded.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':MapboxGLAndroidSDK'.
> Failed to notify project evaluation listener.
   > You have not accepted the license agreements of the following SDK components:
     [Android SDK Build-Tools 25].
     Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.
     Alternatively, to learn how to transfer the license agreements from one workstation to another, go to http://d.android.com/r/studio-ui/export-licenses.html
   > You have not accepted the license agreements of the following SDK components:
     [Android SDK Build-Tools 25].
     Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.
     Alternatively, to learn how to transfer the license agreements from one workstation to another, go to http://d.android.com/r/studio-ui/export-licenses.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

**Comment by tobrun** [comment]
@incanus @1ec5 haven't pinpointed concretely where `ios-memory-thread` branches away from master but was able to scroll back over a month. Rebasing will solve this issue as it would include the fix in #7729.

**Comment by 1ec5** [comment]
Apparently @incanus branched off aeba7cce84bc066d19e8e695be29ce301d06b9c0. That’s pretty ancient.

**Comment by incanus** [comment]
Oh weird! I thought I branched off of `release-ios-v3.4.0`. Let me adjust the PR.

**Comment by incanus** [comment]
Ok, now the base is the release branch and I based atop it just for good measure. 🤞 for tests again.

**Pull request merged**
