### PR TITLE
[build] Introduce optional FORCE_LIBUV for OS X

### PR DESCRIPTION
**Pull request by brunoabinader**
Following up https://github.com/mapbox/mapbox-gl-native/pull/4608#issuecomment-207162791 - GLFW test app using CoreFoundation's `CFRunLoop` is currently broken (see https://github.com/mapbox/mapbox-gl-native/issues/4578 for details). Our current working fallback is the `libuv` implementation. This patch re-enables it when passing an optional `FORCE_LIBUV=1` envvar.

Example usage in OS X:
```$ FORCE_LIBUV=1 make glfw-app```

/cc @jfirebaugh @kkaefer @tmpsantos

### CODE REVIEW

**Comment by mikemorris** [comment]
Can this just be `LOOP=uv` (like https://github.com/mapbox/mapbox-gl-native/commit/d46f24cdf8ccc577beec0f1a75e64f6599f25875) instead of a significantly different syntax?

**Comment by brunoabinader** [comment]
> Can this just be LOOP=uv (like d46f24c) instead of a significantly different syntax?

It can be done, I avoided it because cases like e.g. `LOOP=darwin` would have no effect. I'm happy to change it to the previous syntax otherwise.

**Comment by jfirebaugh** [comment]
How about we just fix #4578?

**Comment by brunoabinader** [comment]
> How about we just fix #4578?

Agreed - this is meant only as a workaround until we figure out #4578 👍

**Comment by kkaefer** [comment]
Fixing #4578 is important, but I'd love to see a patch like this as well because it makes debugging libuv issues way easier.

**Comment by jfirebaugh** [comment]
When would you need to debug libuv issues nowadays? The node bindings are the only real platform where it's used now, and those always built with libuv, even on OS X. So you can debug normally without any special flags.

**Comment by jfirebaugh** [comment]
Closing; merged #4666 instead.

**Pull request closed without merging**
