### PR TITLE
Use stale styles

### PR DESCRIPTION
**Pull request by kkaefer**
With #2617 in place, we now get stale data from the cache. Currently, stale styles aren't used, but we should change this. This could be trivially implemented by regular style update (= treat it like setting a new style). Currently, this means that we have to reparse everything, and will see a short flicker. However, as soon as we implement style transitions (https://github.com/mapbox/mapbox-gl-native/issues/2445), we'll get a flicker-free update.

### CODE REVIEW

**Comment by kkaefer** [comment]
:eyes: @jfirebaugh @tmpsantos

**Comment by kkaefer** [comment]
For reference, this patch incorporates #2720, #2722 and #2724 as well.

**Comment by jfirebaugh** [comment]
This PR has a lot of changes and is hard to review comprehensively. Is it possible to split it up into smaller units?

**Comment by kkaefer** [comment]
Will roll this again after https://github.com/mapbox/mapbox-gl-native/pull/3480 is in.

**Comment by kkaefer** [comment]
@jfirebaugh pls :eyes: (minus the first two commits)

**Pull request merged**
