### PR TITLE
[ios]Add errors reporting

### PR DESCRIPTION
**Pull request by m-stephen**
close: #15011 
For this case, only report errors for improving user experience. 
We don't report any network related errors from this PR.

### CODE REVIEW

**Comment by m-stephen** [comment]
@julianrex Could u help to review this PR?

**Comment by julianrex** [comment]
Apologies for the delay - I think it would be good to also report exceptions that are raised. 

@m-stephen @friedbunny how about we create a convenience class method to replace `raise:format:`? Something like 

`-[NSException mgl_raise:format:]` that internally calls `-[MMEEventsManager reportException:]`?

**Comment by m-stephen** [comment]
> Apologies for the delay - I think it would be good to also report exceptions that are raised.
> 
> @m-stephen @friedbunny how about we create a convenience class method to replace `raise:format:`? Something like
> 
> `-[NSException mgl_raise:format:]` that internally calls `-[MMEEventsManager reportException:]`?

Since I already want to report exceptions previously by this comment: https://github.com/mapbox/mapbox-gl-native/issues/15011#issuecomment-516685819
but it seems our telemetry SDK cannot do it right now:

According to @alfwatt's comment:
> we don't have a way to flag an event as 'real time' or 'send immediately' right no, and I don't think we should start throwing exceptions unless there's a real programmer error. Better to use NSError objects and reportError:

@julianrex

**Comment by m-stephen** [comment]
For more clear explanation, `[MMEEventsManager reportException]` add an exception event into an event queue but does not report this event immediately. It means when the app throw an exception this event will not report to server bcoz the event is still in the memory.  @julianrex

**Comment by julianrex** [comment]
Good point. I think we'll need to wait for deferred telemetry for this.

**Comment by julianrex** [comment]
@m-stephen added a PR to this branch: https://github.com/mapbox/mapbox-gl-native/pull/15633

**Comment by julianrex** [comment]
@m-stephen can you rebase please?

**Comment by julianrex** [comment]
@alfwatt would you mind taking a look at this PR to see if this matches your intentions with `reportError` please?

**Comment by julianrex** [comment]
For tail work: can we please move the `#if` checks in lines like this into `reportError`?

```
#if TARGET_OS_IPHONE || TARGET_OS_SIMULATOR
             [[MMEEventsManager sharedManager] reportError:error]; 
#endif
```

cc @alfwatt

**Comment by m-stephen** [comment]
> For tail work: can we please move the `#if` checks in lines like this into `reportError`?
> 
> ```
> #if TARGET_OS_IPHONE || TARGET_OS_SIMULATOR
>              [[MMEEventsManager sharedManager] reportError:error]; 
> #endif
> ```
> 
> cc @alfwatt

Yes, it's better to move this into telemetry SDK.
But just in case, is `reportError` will also be used in macOS or carPlay devices? @alfwatt  If so, we have to keep this or need to package a new function.

**Comment by julianrex** [comment]
@m-stephen I believe you need to rebase on master, since Circle CI checks have changed.

**Comment by julianrex** [comment]
Thanks for landing this. A few things please:

- Can you list the types of errors, so that we can fine-tune the rules about what & why we report an error, so we know how and when to do so.
- Can you confirm that these errors contain no PII?

**Comment by julianrex** [comment]
@m-stephen ping!

**Pull request merged**
