### PR TITLE
Type of Response::{modified,expired} should be optional<SystemTimePoint>

### PR DESCRIPTION
**Pull request by jfirebaugh**

### CODE REVIEW

**Comment by jfirebaugh** [comment]
`nativeOnResponse` / `HTTPAndroidRequest::onResponse` do not properly distinguish between no modified/expires/etag and zero modified/zero expires/empty etag. I'll fix that next.

**Comment by kkaefer** [comment]
Looks like libstdc++ doesn't have full `optional` support?

**Comment by jfirebaugh** [comment]
The only incompatibility I've found so far is that whatever implementation Android uses appears to be missing `optional::operator!=` (workaround is to use `!(a == b)` instead).

The build errors here are legit and I'm working on them.

**Comment by jfirebaugh** [comment]
:eyes: @kkaefer @brunoabinader @tobrun

**Comment by kkaefer** [comment]
:+1:

**Pull request merged**
