### PR TITLE
Refactor Storage and HTTP interface

### PR DESCRIPTION
**Pull request by kkaefer**
This changes the FileSource/FileCache interface so that it can be swapped out more easily and replaced altogether, e.g. in situations where you don't want to rely on CURL/OpenSSL/SQLite but have an outside method of obtaining files and caching them.

### CODE REVIEW

**Comment by mikemorris** [comment]
Some change here seems to be breaking `make install` (at least on OS X)
```
deps/run_gyp mbgl.gyp -Iconfig.gypi -Dhost=osx -Dheadless_lib=cgl -Dplatform_lib=osx -Dasset_lib=fs -Dhttp_lib=nsurl -Dcache_lib=sqlite --depth=. -Goutput_dir=.. --generator-output=./build/mbgl -f make
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C build/mbgl BUILDTYPE=Release install
make[1]: *** No rule to make target `install'.  Stop.
make: *** [install] Error 2
```

**Comment by kkaefer** [comment]
Yeah, make install doesn't quite work yet. I'll figure it out tomorrow.

**Comment by mikemorris** [comment]
@kkaefer Fixed by setting `-Dinstall_prefix=$(PREFIX)` in `CONFIG_STRING`

**Comment by mikemorris** [comment]
Looks like a new failure resolving `headless_lib` gyp dependencies now.

**OSX**
```
deps/run_gyp macosx/mapboxgl-app.gyp -Iconfig.gypi -Dhost=osx -Dheadless_lib=cgl -Dplatform_lib=osx -Dasset_lib=fs -Dhttp_lib=nsurl -Dcache_lib=sqlite -Dinstall_prefix=/usr/local --depth=. -Goutput_dir=.. --generator-output=./build/macosx -f make
Traceback (most recent call last):
  File "deps/run_gyp", line 8, in <module>
    sys.exit(gyp.script_main())
  File "deps/gyp/pylib/gyp/__init__.py", line 534, in script_main
    return main(sys.argv[1:])
  File "deps/gyp/pylib/gyp/__init__.py", line 527, in main
    return gyp_main(args)
  File "deps/gyp/pylib/gyp/__init__.py", line 503, in gyp_main
    options.circular_check)
  File "deps/gyp/pylib/gyp/__init__.py", line 129, in Load
    params['parallel'], params['root_targets'])
  File "deps/gyp/pylib/gyp/input.py", line 2759, in Load
    RemoveLinkDependenciesFromNoneTargets(targets)
  File "deps/gyp/pylib/gyp/input.py", line 1483, in RemoveLinkDependenciesFromNoneTargets
    if targets[t].get('variables', {}).get('link_dependency', 0):
KeyError: 'mbgl.gyp:cgl#target'
make: *** [__osx__/osx] Error 1
```

**Linux**
```
deps/run_gyp linux/mapboxgl-app.gyp -Iconfig.gypi -Dhost=linux -Dheadless_lib=glx -Dplatform_lib=linux -Dasset_lib=fs -Dhttp_lib=curl -Dcache_lib=sqlite -Dinstall_prefix=/usr/local --depth=. -Goutput_dir=.. --generator-output=./build/linux -f make
Traceback (most recent call last):
  File "deps/run_gyp", line 8, in <module>
    sys.exit(gyp.script_main())
  File "deps/gyp/pylib/gyp/__init__.py", line 534, in script_main
    return main(sys.argv[1:])
  File "deps/gyp/pylib/gyp/__init__.py", line 527, in main
    return gyp_main(args)
  File "deps/gyp/pylib/gyp/__init__.py", line 503, in gyp_main
    options.circular_check)
  File "deps/gyp/pylib/gyp/__init__.py", line 129, in Load
    params['parallel'], params['root_targets'])
  File "deps/gyp/pylib/gyp/input.py", line 2759, in Load
    RemoveLinkDependenciesFromNoneTargets(targets)
  File "deps/gyp/pylib/gyp/input.py", line 1483, in RemoveLinkDependenciesFromNoneTargets
    if targets[t].get('variables', {}).get('link_dependency', 0):
KeyError: 'mbgl.gyp:glx#target'
make: *** [__linux__/linux] Error 1
```

**Comment by mikemorris** [comment]
Fixed that, was just a deps naming issue. New bug is zlib linking (mason is pointing to a folder that doesn't exist?). This line in the mason `zlib-system` script looks problematic https://github.com/mapbox/mason/blob/zlib-system/script.sh#L43

```
  LINK(target) ../Release/libmbgl.a
ld: warning: directory not found for option '-L/Users/mikemorris/Projects/mapbox-gl-native/mason_packages/osx-10.10/zlib/system/lib'
Undefined symbols for architecture x86_64:
  "_main", referenced from:
     implicit entry/start for main executable
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [../Release/libmbgl.a] Error 1
make: *** [install] Error 2
```

**Comment by springmeyer** [comment]
zlib is my fault - I'll take a look at fixing up: however it is just a warning. The error looks like a library is being built as an executable rather than a library.

**Comment by kkaefer** [comment]
> The error looks like a library is being built as an executable rather than a library.

Sort of, we're using a [fake linker script](https://github.com/mapbox/mapbox-gl-native/blob/a1fb3f314ee1066eecdc7c67e84bcc0c58c5823d/gyp/link.py) and link as an executable (to gyp), but instead of producing an executable, we're extracting the linker flags and merge the static library, and extract the linker flags. This allows us to use gyp's regular link flags inheriting, so we know exactly what sort of flags we need for linking a particular configuration.

In related news, we can now produce custom configurations of the library and tests by swapping out parts: `make test HTTP=curl` forces CURL on OS X, rather than defaulting to the NSURL* HTTP implementation. You can swap other parts of the library by setting `HTTP=...`, `ASSET=...`, `CACHE=...`, `PLATFORM=...` etc.

**Comment by mikemorris** [comment]
@kkaefer Working on updating Node.js bindings to build against this branch, and I'm hitting some linker errors:
```
/usr/bin/ld: cannot find -ljpeg
/usr/bin/ld: cannot find -lnu
```
I'm not quite sure how your "fake linker" is working, but my output from `mbgl-config --libs` yields
```
/usr/local/lib/libmbgl.a -lm -ljpeg -lnu -lcurl -lrt -ldl -lpthread -lz
```
...which looks like it's dropping the preceding `-L/dirpath` flags from some `mason` packages.

```
./.mason/mason ldflags nunicode 1.5.1
-L/home/mikemorris/mapbox-gl-native/mason_packages/linux-x86_64/nunicode/1.5.1/lib -lnu
./.mason/mason ldflags jpeg v9a
-L/home/mikemorris/mapbox-gl-native/mason_packages/linux-x86_64/jpeg/v8d/lib -ljpeg
```

**Comment by ljbade** [comment]
@kkaefer make changed look good but:
- in android/script/copy-files.sh I added a symbol strip step, can you add that to the new gyp
- once done remove copy-files.sh
- update readme to document new single ABI (default arm-v7) vs build all
- expand list of all abis to:
 - arm-v8
 - arm-v7
 - arm-v5
 - x86
 - x86-64
 - mips
 - mips-64

Now we have a build all you may want to reduce the travis android matrix to just a make all release, and a make all debug

**Comment by mikemorris** [comment]
@kkaefer was dropping the `PREFIX` default from `Makefile` intentional?

**Comment by mikemorris** [comment]
Okay so the "fake linker" looks to currently be missing a handful of libs that should get passed on to `mbgl-config`, notably the GLFW deps.

**master**
```
-L/usr/local/lib -Wl,--start-group -lmbgl-core -lmbgl-linux -Wl,--end-group -lmbgl-headless /home/mikemorris/mapbox-gl-native/mason_packages/linux-x86_64/sqlite/3.8.8.1/lib/libsqlite3.a -ldl -lpthread -lcurl -lz -lm /home/mikemorris/mapbox-gl-native/mason_packages/linux-x86_64/nunicode/1.5.1/lib/libnu.a /home/mikemorris/mapbox-gl-native/mason_packages/linux-x86_64/libpng/1.6.16/lib/libpng.a /home/mikemorris/mapbox-gl-native/mason_packages/linux-x86_64/jpeg/v8d/lib/libjpeg.a /home/mikemorris/mapbox-gl-native/mason_packages/linux-x86_64/glfw/e1ae9af5/lib/libglfw3.a -lrt -lXrandr -lXinerama -lXi -lXcursor -lGL -lm -ldl -lXrender -ldrm -lXdamage -lX11-xcb -lxcb-glx -lxcb-dri2 -lxcb-dri3 -lxcb-present -lxcb-sync -lxshmfence -lXxf86vm -lXfixes -lXext -lX11 -lpthread -lxcb -lXau -lXdmcp
```

**storage**
```
/usr/local/lib/libmbgl.a -lm -L/home/mikemorris/mapbox-gl-native/mason_packages/linux-x86_64/jpeg/v8d/lib -ljpeg -L/home/mikemorris/mapbox-gl-native/mason_packages/linux-x86_64/nunicode/1.5.1/lib -lnu -lcurl -lrt -ldl -lpthread -lz
```

**Comment by kkaefer** [comment]
> /usr/bin/ld: cannot find -ljpeg
> /usr/bin/ld: cannot find -lnu

This is an error in the mason packages. The libraries we're building are static libraries, which work correctly and are linked into the main .a file. However, the mason ldflags command doesn't strip the dynamic linking, which is why they are passed on into the mbgl-config. In short, the `-L.. -l..` for these files shouldn't be there because these libs are already statically linked into the main archive.

> in android/script/copy-files.sh I added a symbol strip step, can you add that to the new gyp

Missed that, thanks. However, a better solution is to switch the Release builds to skip debug symbols altogether, so we don't have to strip them to begin with. I added the debug symbols to Release builds to aid debugging (especially on Travis) a while ago, but for actual releases, they should be gone.

> @kkaefer was dropping the PREFIX default from Makefile intentional?

Yes, but it's a bad solution. The reason I did this is because the presence of a `PREFIX` generates a `install` target, which copies folders, which breaks on Xcode builds. However, this is not a good solution; instead, we should make a separate gyp file for installs and only load it in a make context.

> Okay so the "fake linker" looks to currently be missing a handful of libs that should get passed on to mbgl-config, notably the GLFW deps.

GLFW isn't part of the library, so we shouldn't pass on the linker flags from GLFW. This means that consuming implementations have to manually add the correct linker flags for linking to the platform's GL library. We can't really do that for them. Us passing on the GLFW flags in the past was more of a hack that we should get rid of.

**Comment by ljbade** [comment]
@kkaefer the idea behind having debug symbols for release is so they can be archived for use when investigating stack traces of crashes for released versions. Otherwise it is near impossible to fix rare crashes.

**Comment by mikemorris** [comment]
Thanks for the clarifications @kkaefer, hitting this again today to get flags all fixed up.

**Comment by mikemorris** [comment]
Looks like some OS X frameworks are now being passed along as flags [without knowing the actual path to the framework](https://discussions.apple.com/thread/3754858).

**master**
```
-L/usr/local/lib -lmbgl-core -lmbgl-osx -lmbgl-headless /Users/mikemorris/Projects/mapbox-gl-native/mason_packages/osx-10.10/sqlite/3.8.8.1/lib/libsqlite3.a -L/Users/mikemorris/Projects/mapbox-gl-native/mason_packages/osx-10.10/libcurl/system/lib -lcurl -lz
```

**storage**
```
/usr/local/lib/libmbgl.a -framework ImageIO -framework Foundation -lpthread -ldl -framework CoreFoundation -framework CoreServices -L/Users/mikemorris/Projects/mapbox-gl-native/mason_packages/osx-10.10/zlib/system/lib -lz -L./Release
```

This is leading to the following errors compiling Node.js bindings
```
clang: error: no such file or directory: 'Foundation'
clang: error: no such file or directory: 'CoreFoundation'
clang: error: no such file or directory: 'CoreServices'
```

**Comment by incanus** [comment]
I'm a little lost here. This PR also *starts* to restructure the iOS subproject by adding a duplicate `gl-cocoa` submodule (https://github.com/mapbox/mapbox-gl-native/pull/772/files#diff-8903239df476d7401cf9e76af0252622). It also pins against the not-yet-merged `storage` branch of `gl-cocoa`, which itself starts to refactor the iOS project structure.

**Comment by mikemorris** [comment]
@incanus Ultimately, both submodules should be removed. This PR did a bit of restructuring work, if the `storage` branch of `gl-cocoa` is working, it should be merged into master, then go from there.

**Comment by incanus** [comment]
Yeah, but the restructure wasn't properly exposing all of the Cocoa headers, including all of the resources, and a few other things. I brought over just the code changes in https://github.com/mapbox/mapbox-gl-cocoa/pull/82.

**Pull request merged**
