### PR TITLE
[ios] Update events submodule to include RN override

### PR DESCRIPTION
**Pull request by rclee**
React native user agent override for internal use.

### CODE REVIEW

**Comment by rclee** [comment]
ref: https://github.com/mapbox/mapbox-events-ios/pull/51

**Comment by friedbunny** [comment]
Looks like this is the first PR targeting `release-drink` — I had to adjust the required CI builds, as they didn’t match this branch’s config.

**Comment by jfirebaugh** [comment]
Is this not something that should be committed to master first and then cherry picked?

**Comment by friedbunny** [comment]
> Is this not something that should be committed to master first and then cherry picked?

Now that you mention it: yes. 😁

@rclee Let’s retarget this PR against `master` and open another PR that cherry-picks that commit into `release-drink`.

**Comment by julianrex** [comment]
Good catch! I totally missed this wasn't targeted at `master`

**Pull request merged**
