### PR TITLE
Improve transitions in iOS 9 multitasking

### PR DESCRIPTION
**Pull request by bwhtmn**
Leave GLview rendering on when app is inactive, to get nice smooth transitions between sizes  when using multitasking on iPad (iOS 9).

### CODE REVIEW

**Comment by 1ec5** [comment]
At the very least, the GL view needs to be inactive in the background on iOS 8.x and below, to avoid regressing #1050, #1186, #1203, #1243, and #1460. (It’s been quite a journey…) Can you verify that those crashes don’t occur in iOS 9?

**Comment by 1ec5** [comment]
Ah, I misread the change: you’re only removing the case where the application becomes inactive, not the case where it goes entirely into the background. That’s probably considerably safer.

**Comment by bwhtmn** [comment]
Yup, this should apply to situations where the app is temporarily interrupted (e.g. multitasking or a system alert).

According to [Apple's docs](https://developer.apple.com/library/prerelease/ios/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/StrategiesforHandlingAppStateTransitions/StrategiesforHandlingAppStateTransitions.html#//apple_ref/doc/uid/TP40007072-CH8-SW10), you'd ideally want to throttle down the OpenGL frame rate when the app is inactive but I didn't see an easy way to do that.

**Comment by incanus** [comment]
>  you'd ideally want to throttle down the OpenGL frame rate when the app is inactive but I didn't see an easy way to do that.

Yeah, this is most commonly done in `GLKView` with a corresponding `GLKViewController` (`preferredFramesPerSecond`), which we don't use because we want to be a standalone view like `MKMapView`. Not seeing a shortcut way to do this.

**Comment by 1ec5** [comment]
Thanks for this PR. An updated version is now being tracked as #2988.

**Pull request closed without merging**
