### PR TITLE
[android] UserLocationView improves (and BearingTracking)

### PR DESCRIPTION
**Pull request by mayardb**
Related to #4136.

If you have any question or remarks, we will be happy to answer.

Best regards.

### CODE REVIEW

**Comment by tobrun** [comment]
@mayardb this is awesome. I'm going to take a look at this now. I will first pull this into our repo so our CI tests can be run. Afterwards I'm going to add a feature activity to see the new feature in action.

**Comment by tobrun** [comment]
CI is being run here:

screen shot 2016-03-02 at 13 07 25

**Comment by tobrun** [comment]
I have setup a test using the following code in `MyLocationTrackingModeActivity`:

```java
Drawable shadowDrawable = ContextCompat.getDrawable(context,R.drawable.ic_locationview_custom_shadow);
mapboxMap.setUserLocationDrawable(ContextCompat.getDrawable(context, R.drawable.ic_locationview_custom_normal), shadowDrawable);
mapboxMap.setUserLocationStaleDrawable(ContextCompat.getDrawable(context, R.drawable.ic_locationview_custom_stale), shadowDrawable);
mapboxMap.setUserLocationBearingDrawable(ContextCompat.getDrawable(context, R.drawable.ic_locationview_custom_bearing), shadowDrawable);```
```

The referenced drawables above are these:

screen shot 2016-03-02 at 13 44 25

This results in following clips:
 - UserlocationTracking with GPS Bearing:
   - https://www.dropbox.com/s/ue9z9qs79lgd13n/device-2016-03-02-134737.mp4?dl=0
 - Going from active to stale drawable:
   - https://www.dropbox.com/s/vxqup8dtg4y7wqv/device-2016-03-02-134946.mp4?dl=0

**Comment by tobrun** [comment]
Here is also an example with shadow:

```java
mapboxMap.setUserLocationShadowOffset(10,10);
```

as

**Comment by tobrun** [comment]
Remarks @mayardb:
 - Are you exposing an API to change the colour of GPS accuracy? (change the blue circle)

    device-2016-03-02-135925

 - I will probably change the way the API is accessed at this time. I feel it deserves a separate class instead of calling methods on MapboxMap. I will pick this up after feedback on above.

Thanks again for the contribution! this is amazing!

**Comment by mayardb** [comment]
@tobrun:

it is a good point. I just missed it.
I can add it to the MapboxMap if you want, unless you want to manage it while refactoring to another class ? (I think, you are talking using a class like UISettings or TrakckingSettings)

**Comment by mayardb** [comment]
Just issued some rotation problems:

- [x] the map cannot rotate with gesture.
- [x] the shadow rotates around the `UserLocationView`.
- [ ] the UserLocationView is rotating while the map is rotating thanks to gesture.

The first two issues are resolved with the last commit I have just did.
But I think that the last one is hiding a more serious problem with the current version of the sdk.

**Comment by mayardb** [comment]
Just added an API to change the color of GPS accuracy.

**Comment by mayardb** [comment]
Just created an issue to talk about the UserLocationView orientation bug (+ found one crash) : #4186 so this PullRequest won't fix it.

**Comment by tobrun** [comment]
@mayardb I just wanted to reach out and indicate we are loving this PR but we are bit hesitant in adding this for the `4.0.0` release since there are some know issues and bugs with it. After the dust settles for `4.0.0` we will take this up again.

**Comment by mayardb** [comment]
The bugs are not really related to this PR.

They exist without theses functionality but they are more hidden.
Anyway there is no problem to wait before including this.

**Comment by tobrun** [comment]
@mayardb I'm going to take a look at refactoring UserLocationView in #4396. 
* Could you rebase this PR? 

I would love to start my work from this branch to include your work.

**Comment by mayardb** [comment]
@tobrun:
I have just done it in PR #4626. (never find the way to rebase properly a pushed branch with git)

**Comment by tobrun** [comment]
@mayardb you need to force push the branch after rebasing ;)

**Comment by mayardb** [comment]
@tobrun: thanks, I will try the next time. :)

**Pull request closed without merging**
