### PR TITLE
[android] Checkstyle fixes round 1

### PR DESCRIPTION
**Pull request by cammace**
removes a lot of the Hungarian notation and fixes other checkstyle issues. @bleege can you review?

### CODE REVIEW

**Comment by bleege** [comment]
Looks good overall @cammace.  The only trouble I ran into when running the TestApp was with

1. ManualZoomActivity not rendering a style
1. ViewPagerActivity crashing

Once those are addressed this should be good to go.

**Comment by cammace** [comment]
What's the crash your getting? For ViewPagerActivity, I was getting a crash also but it was related to https://github.com/mapbox/mapbox-gl-native/issues/6193. clearing the apps data fixed it for me.

**Comment by cammace** [comment]
For the the ManualZoomActivity not rendering a style, this can be reproduced in master and has to do with setting the style using the MapView object. Ticketed in #6242. Looking into the ViewPagerActivity issue now.

**Comment by cammace** [comment]
`ViewPagerActivity` issue is also reproducible in master, this PR just removed unused imports from that class.

**Comment by cammace** [comment]
@bleege has given the 👍 merging now

cc: @mapbox/android

**Pull request merged**
