### PR TITLE
[node] Drop node 4.x support, add 6.x and 10.x support

### LINKED ISSUE #10343: [node] Node.js 8 support
Node.js 8 Moves into Long-Term Support, with a big improvement both in syntax and performance. Would you consider upgrade node-mapbox-gl-native with Node.js 8 support?

### PR DESCRIPTION
**Pull request by jfirebaugh**
Related to https://github.com/mapbox/mapbox-gl-js/issues/6563.
Fixes #10343, enabled by #11913.

Does `node-pre-gyp publish` do the right thing when the lib dir contains modules for multiple ABIs?

Note that this still only tests the v6 ABI (48). If we want to run complete tests for all ABIs, we should fan out CI jobs after building libmbgl-core, one per ABI, and have each build and test the respective ABI. The libmbgl-core build result can be shared with the fan out via a [workspace](https://circleci.com/docs/2.0/workflows/#using-workspaces-to-share-data-among-jobs).

cc @springmeyer

### CODE REVIEW

**Comment by jfirebaugh** [comment]
> Does `node-pre-gyp publish` do the right thing when the lib dir contains modules for multiple ABIs?

A cursory read of the code and a test of `./node_modules/.bin/node-pre-gyp package` on this PR seems to indicate that the answer is "no".

```
~/Development/mapbox-gl-native $ ./node_modules/.bin/node-pre-gyp package
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.6.39
node-pre-gyp info using node@8.11.1 | darwin | x64
node-pre-gyp ERR! package error 
node-pre-gyp ERR! stack Error: Cannot package because /Users/john/Development/mapbox-gl-native/lib/mapbox_gl_native.node missing: run `node-pre-gyp rebuild` first
node-pre-gyp ERR! stack     at /Users/john/Development/mapbox-gl-native/node_modules/node-pre-gyp/lib/package.js:23:29
node-pre-gyp ERR! stack     at FSReqWrap.cb [as oncomplete] (fs.js:312:19)
node-pre-gyp ERR! System Darwin 17.6.0
node-pre-gyp ERR! command "/usr/local/Cellar/node@8/8.11.1/bin/node" "/Users/john/Development/mapbox-gl-native/node_modules/.bin/node-pre-gyp" "package"
node-pre-gyp ERR! cwd /Users/john/Development/mapbox-gl-native
node-pre-gyp ERR! node -v v8.11.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok 
Cannot package because /Users/john/Development/mapbox-gl-native/lib/mapbox_gl_native.node missing: run `node-pre-gyp rebuild` first
```

The `lib` directory contains files named like `mbgl-node.abi-48.node`, not `mapbox_gl_native.node`.

@kkaefer, @springmeyer -- thoughts on how we should handle this?

**Comment by springmeyer** [comment]
node-pre-gyp's versioning is configurable and can likely be convinced the package the right thing if you modify the `package_name` and `module_name` properties in https://github.com/mapbox/mapbox-gl-native/blob/bf28fd6c7a39da31c18131919f523585b2eb0b20/package.json#L54 to adapt to #11913. If not let me know and I can look closer (not all of the properties can be templated in node-pre-gyp but I *think* `module_name` and `package_name` can be....).

**Comment by springmeyer** [comment]
>  It does not appear that module_name supports {node_abi}:

Okay. That is an easy addition to node-pre-gyp. Please ticket and cc me and @mapsam if you need this.

> Also, correct me if I'm wrong, but don't the package and publish commands work only with the ABI version for the currently installed version of node?

node-pre-gyp can be told what ABI you want to target by passing command line arguments to select specific node versions.

But, I'm starting to gather your problem. You are trying to package multiple binaries and node-pre-gyp has no support for that - it expects a single binary.

> What we would like is to publish each ABI version that's present in the lib directory.

node-pre-gyp is designed to only support a single binary, since it has a tool to validate that binary upon install. So it is starting to sound like what you are trying to do is in conflict with the design of node-pre-gyp.

**Comment by springmeyer** [comment]
> But, I'm starting to gather your problem. You are trying to package multiple binaries and node-pre-gyp has no support for that - it expects a single binary.

However https://github.com/mapbox/node-pre-gyp/issues/171 seems to indicate that node-pre-gyp might actually package everything inside the `./lib/binding` folder, so perhaps my memory is wrong.

**Comment by jfirebaugh** [comment]
👍 Opened https://github.com/mapbox/node-pre-gyp/issues/395.

> You are trying to package multiple binaries and node-pre-gyp has no support for that - it expects a single binary.

Yes and no -- we do want to package binaries for multiple versions of node, as we've been doing for some time. The change with #11913 is that we are able to cross compile ABIs, so we don't necessarily need a separate row in the CI matrix for each desired ABI. So we don't need any one individual node-pre-gyp tarball to contain more than a single binary, but we do need to have node-pre-gyp generate multiple tarballs.

> node-pre-gyp can be told what ABI you want to target by passing command line arguments to select specific node versions.

This sounds like it ought to work for us -- we can loop over the ABIs in the publishing script and make multiple calls to `node-pre-gyp`. I'll try it out.

**Comment by jfirebaugh** [comment]
I opened a fresh ticket for the publishing issue, since it isn't caused by this PR. This PR I'm putting on hold, since we may simply need to back out #11913 for now in order to get publishing working in the short term.

**Comment by kkaefer** [comment]
I opened https://github.com/mapbox/node-pre-gyp/issues/401 since it currently doesn't seem possible to pass a Node ABI version to `node-pre-gyp`. Let's use 6.0.0, 8.0.0 and 10.0.0 for now to match the ABIs we build.

**Comment by jfirebaugh** [comment]
Updated and got it working. You can see a successful test publish [here](https://circleci.com/workflow-run/94027a54-bb2e-428a-abfd-18ebae3450c8).

**Pull request merged**
