### PR TITLE
Merge Android 4.1.0-beta.2 Release Branch Into master

### LINKED ISSUE #5284: Release Android 4.1.0 Beta 2
Mapbox Android 4.1.0 builds off our ambitious 4.0.0 version with 3 major new features being released.  These new features are part of our ongoing efforts focused on providing a premiere navigation experience in-car, on-dash, and on the street for Android.  To help us produce the highest quality SDK possible we're releasing a second official Beta release first so that everyone has time to explore it and help hardened it before the official 4.1.0 Final Release.  The first `4.1.0-beta.1` was released on 26-May-2016 in #5160.  

#### Highlights

* [View Based Annotations](https://github.com/mapbox/mapbox-gl-native/issues/3276)
* [UserLocationView Refactor](https://github.com/mapbox/mapbox-gl-native/issues/4396)
* [MapboxAccountManager](https://github.com/mapbox/mapbox-gl-native/issues/5004)

Full Change Log: https://github.com/mapbox/mapbox-gl-native/issues?q=milestone%3Aandroid-v4.1.0

Release Branch: https://github.com/mapbox/mapbox-gl-native/commits/release-android-v4.1.0

#### Improvements Since Beta 1

* [Dynamically Update InfoWindow](https://github.com/mapbox/mapbox-gl-native/issues/5237)
* [armeabi ABI Work On armv7 Devices](https://github.com/mapbox/mapbox-gl-native/issues/3985)
* [Remove Adapter Requirement For MarkerView](https://github.com/mapbox/mapbox-gl-native/issues/5214)
* [Always Current Version Style URL Constants](https://github.com/mapbox/mapbox-gl-native/issues/5193)
* [Random NullPointerException On Telemetry](https://github.com/mapbox/mapbox-gl-native/issues/5186)

#### The TODO list for making this happen:

- [x] Change Version Name to `4.1.0-beta.2` in [`gradle.properties`](https://github.com/mapbox/mapbox-gl-native/blob/925687ab06892528f25fd4a79d27a55560634d96/platform/android/MapboxGLAndroidSDK/gradle.properties#L2)
- [x] Update version info in [Twitter Fabric metadata file](https://github.com/mapbox/mapbox-gl-native/blob/925687ab06892528f25fd4a79d27a55560634d96/platform/android/MapboxGLAndroidSDK/src/main/resources/fabric/com.mapbox.mapboxsdk.mapbox-android-sdk.properties#L2)
- [ ] ~~Move open issues to `android-v4.0.0-final` Milestone in GitHub~~
- [x] Publish `4.1.0-beta.2` artifact to Maven Central
- [x] Updating Mapbox.com JavaDoc Documentation
- [x] Update [CHANGELOG.md](https://github.com/mapbox/mapbox-gl-native/blob/master/CHANGELOG.md)
- [x] Tag `android-v4.1.0-beta.2` in GitHub
- [ ] ~~Close Milestone `android-v4.0.0` in GitHub~~
- [ ] ~~Blog Post on https://www.mapbox.com/blog/~~
- [ ] ~~Alert Twitter Fabric team of new release~~
- [x] Tweet Release Announcement from `@mapbox`
- [ ]  Merge `release-android-v4.1.0` back into `master` but leave open for continued development
- [x] Change Version Name _BACK to SNAPSHOT after release and release branch merge_ to support daily development.  In this case set to  `4.1.0-SNAPSHOT` in [`gradle.properties`](https://github.com/mapbox/mapbox-gl-native/blob/925687ab06892528f25fd4a79d27a55560634d96/platform/android/MapboxGLAndroidSDK/gradle.properties#L2)
- [x] Update [Mapbox Demo App](https://github.com/mapbox/mapbox-android-demo) to use `4.1.0-beta.2` and release on Google Play

/cc @mapbox/mobile @mapbox/support @gundersen @lxbarth @yhahn @Lndsay @pveugen

### PR DESCRIPTION
**Pull request by bleege**
Closes #5284 

/cc @mapbox/mobile

### CODE REVIEW

**Comment by bleege** [comment]
There were the following conflicts during the initial merge that I'm working on resolving.  For the Java classes (except for `NativeMapView`) I've accepted the version from `release-android-v4.1.0` as the "correct version" as it's the branch that has been primary for Android development since the `beta.1` was released on 26-May-2016 in #5160.  The JNI and CPP classes however I'm going through line by line as there's been some work in both branches.  My default instinct will be to go with the JNI / CPP classes from `master` however as that'll be more up to date with the project as a whole.

After I finish merging the conflicts, I'm going to rebuild and test locally in the TestApp to confirm that everything runs as expected.  If it does, as expected, I'll ask @jfirebaugh to review the changes to make sure that something hasn't accidentally been overwritten and then merge back into `master`.

As an internal reminder to the team, we'll continue to use `release-android-v4.1.0` as the primary Android development branch until 4.1.0 Final ships.  We will NOT be merging `master` into `release-android-v4.1.0` however to keep the Android release as isolated and in a more known state.

screen shot 2016-06-08 at 6 39 05 pm

**Comment by bleege** [comment]
I've finished the merge and while using the TestApp to verify I ran into the following error in PolygonActivity.  Will investigate.

```java
06-09 14:31:56.391 3879-3879/? I/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
06-09 14:31:56.391 3879-3879/? I/DEBUG: Build fingerprint: 'samsung/klteuc/klteatt:5.0/LRX21T/G900AUCU3BOC4:user/release-keys'
06-09 14:31:56.391 3879-3879/? I/DEBUG: Revision: '14'
06-09 14:31:56.391 3879-3879/? I/DEBUG: ABI: 'arm'
06-09 14:31:56.401 3879-3879/? I/DEBUG: pid: 1669, tid: 1669, name: pboxsdk.testapp  >>> com.mapbox.mapboxsdk.testapp <<<
06-09 14:31:56.401 3879-3879/? I/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
06-09 14:31:56.431 3879-3879/? I/DEBUG:     r0 00000000  r1 fffffff0  r2 00000001  r3 00000000
06-09 14:31:56.431 3879-3879/? I/DEBUG:     r4 be861228  r5 be861224  r6 be861220  r7 00000000
06-09 14:31:56.431 3879-3879/? I/DEBUG:     r8 be861214  r9 551bea2f  sl b6c5b305  fp be861250
06-09 14:31:56.431 3879-3879/? I/DEBUG:     ip 9ee00ff4  sp be861044  lr 9e87c860  pc 9e87cda4  cpsr 600b0010
06-09 14:31:56.431 3879-3879/? I/DEBUG: backtrace:
06-09 14:31:56.431 3879-3879/? I/DEBUG:     #00 pc 0044bda4  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so (bool mapbox::geometry::operator!=<double>(mapbox::geometry::point<double> const&, mapbox::geometry::point<double> const&)+20)
06-09 14:31:56.431 3879-3879/? I/DEBUG:     #01 pc 0044b85c  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so (mbgl::ToGeoJSONVT::convertPoints(mapbox::geojsonvt::ProjectedFeatureType, std::__1::vector<mapbox::geometry::point<double>, std::__1::allocator<mapbox::geometry::point<double> > > const&) const+936)
06-09 14:31:56.431 3879-3879/? I/DEBUG:     #02 pc 0044a674  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so (mbgl::ToGeoJSONVT::operator()(mapbox::geometry::polygon<double, std::__1::vector> const&) const+444)
06-09 14:31:56.431 3879-3879/? I/DEBUG:     #03 pc 0044a468  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so (_ZN6mapbox4util6detail10dispatcherIN4mbgl11ToGeoJSONVTENS0_7variantIJNS_8geometry11line_stringIdNSt3__16vectorEEENS6_7polygonIdS9_EENS6_17multi_line_stringIdS9_EENS6_13multi_polygonIdS9_EEEEENS_9geojsonvt16ProjectedFeatureEJSC_SE_SG_EE11apply_constERKSH_OS4_+84)
06-09 14:31:56.431 3879-3879/? I/DEBUG:     #04 pc 0044a05c  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so (_ZN6mapbox4util6detail10dispatcherIN4mbgl11ToGeoJSONVTENS0_7variantIJNS_8geometry11line_stringIdNSt3__16vectorEEENS6_7polygonIdS9_EENS6_17multi_line_stringIdS9_EENS6_13multi_polygonIdS9_EEEEENS_9geojsonvt16ProjectedFeatureEJSA_SC_SE_SG_EE11apply_constERKSH_OS4_+112)
06-09 14:31:56.431 3879-3879/? I/DEBUG:     #05 pc 0043ff58  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so (_ZN6mapbox4util7variantIJNS_8geometry11line_stringIdNSt3__16vectorEEENS2_7polygonIdS5_EENS2_17multi_line_stringIdS5_EENS2_13multi_polygonIdS5_EEEE5visitIN4mbgl11ToGeoJSONVTESD_NS_9geojsonvt16ProjectedFeatureEEEDTclsr6detail10dispatcherIT_T0_T1_S6_S8_SA_SC_EE11apply_constfp_clsr3stdE7forwardISJ_Efp0_EEERKSK_OSJ_+36)
06-09 14:31:56.431 3879-3879/? I/DEBUG:     #06 pc 0043ece4  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so (mbgl::ShapeAnnotationImpl::updateTile(mbgl::CanonicalTileID const&, mbgl::AnnotationTile&)+256)
06-09 14:31:56.431 3879-3879/? I/DEBUG:     #07 pc 003ef5b8  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so (mbgl::AnnotationManager::getTile(mbgl::CanonicalTileID const&)+1420)
06-09 14:31:56.431 3879-3879/? I/DEBUG:     #08 pc 003f1468  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so (mbgl::AnnotationManager::updateStyle(mbgl::style::Style&)+5464)
06-09 14:31:56.431 3879-3879/? I/DEBUG:     #09 pc 00484db0  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so (mbgl::Map::Impl::update()+360)
06-09 14:31:56.431 3879-3879/? I/DEBUG:     #10 pc 0048edf8  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
06-09 14:31:56.431 3879-3879/? I/DEBUG:     #11 pc 0048ed24  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
06-09 14:31:56.431 3879-3879/? I/DEBUG:     #12 pc 00495db4  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so (std::__1::function<void ()>::operator()() const+164)
06-09 14:31:56.431 3879-3879/? I/DEBUG:     #13 pc 006ca1d8  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so (mbgl::util::AsyncTask::Impl::runTask()+204)
06-09 14:31:56.431 3879-3879/? I/DEBUG:     #14 pc 006cbb24  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so (mbgl::util::RunLoop::Impl::processRunnables()+788)
06-09 14:31:56.431 3879-3879/? I/DEBUG:     #15 pc 006cd0b8  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so (mbgl::util::RunLoop::runOnce()+240)
06-09 14:31:56.431 3879-3879/? I/DEBUG:     #16 pc 006ca9c8  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
06-09 14:31:56.431 3879-3879/? I/DEBUG:     #17 pc 0001030f  /system/lib/libutils.so (android::SimpleLooperCallback::handleEvent(int, int, void*)+10)
06-09 14:31:56.431 3879-3879/? I/DEBUG:     #18 pc 00010f6f  /system/lib/libutils.so (android::Looper::pollInner(int)+482)
06-09 14:31:56.431 3879-3879/? I/DEBUG:     #19 pc 00011019  /system/lib/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+92)
06-09 14:31:56.431 3879-3879/? I/DEBUG:     #20 pc 00082ff9  /system/lib/libandroid_runtime.so (android::NativeMessageQueue::pollOnce(_JNIEnv*, int)+22)
06-09 14:31:56.431 3879-3879/? I/DEBUG:     #21 pc 000b22df  /system/framework/arm/boot.oat
06-09 14:31:56.511 902-1038/? W/ActivityManager: mDVFSHelper.release()
06-09 14:31:56.511 902-1038/? I/Timeline: Timeline: Activity_windows_visible id: ActivityRecord{1844711b u0 com.mapbox.mapboxsdk.testapp/.activity.annotation.PolygonActivity t1026} time:782403934
06-09 14:31:57.591 3879-3879/? I/DEBUG: Tombstone written to: /data/tombstones/tombstone_00
                                        
                                        
                                        [ 06-09 14:31:57.591  3879: 3879 E/         ]
                                        !@dumpstate -k -t -z -d -o /data/log/dumpstate_app_native -m 1669
```

**Comment by jfirebaugh** [comment]
That's #5259.

**Comment by bleege** [comment]
@jfirebaugh Great!  I wasn't sure if there was something that I had missed in the Core GL code, so this helps me not have to go down that rabbit hole for now.  I'll go back to checking the rest of the examples in the TestApp then.  Thanks!

**Comment by bleege** [comment]
Yep, also got a similar error for Polyline too.  Looks like it's something with GeoJSONVT.

```java
06-09 14:44:50.641 8749-8749/com.mapbox.mapboxsdk.testapp A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x10 in tid 8749 (pboxsdk.testapp)
06-09 14:44:50.691 3879-3879/? I/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
06-09 14:44:50.691 3879-3879/? I/DEBUG: Build fingerprint: 'samsung/klteuc/klteatt:5.0/LRX21T/G900AUCU3BOC4:user/release-keys'
06-09 14:44:50.691 3879-3879/? I/DEBUG: Revision: '14'
06-09 14:44:50.691 3879-3879/? I/DEBUG: ABI: 'arm'
06-09 14:44:50.691 3879-3879/? I/DEBUG: pid: 8749, tid: 8749, name: pboxsdk.testapp  >>> com.mapbox.mapboxsdk.testapp <<<
06-09 14:44:50.691 3879-3879/? I/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x10
06-09 14:44:50.711 3879-3879/? I/DEBUG:     r0 be8613c0  r1 00000000  r2 00000000  r3 3df00000
06-09 14:44:50.711 3879-3879/? I/DEBUG:     r4 00000000  r5 00000000  r6 00000000  r7 aaaaaaab
06-09 14:44:50.711 3879-3879/? I/DEBUG:     r8 00000000  r9 3ff00000  sl be8613c0  fp be8612f0
06-09 14:44:50.711 3879-3879/? I/DEBUG:     ip 9ee88cec  sp be860fd0  lr 9ed7f03c  pc 9ed7fd14  cpsr 600b0010
06-09 14:44:50.711 3879-3879/? I/DEBUG: backtrace:
06-09 14:44:50.711 3879-3879/? I/DEBUG:     #00 pc 008ced14  /data/app/com.mapbox.mapboxsdk.testapp-2/lib/arm/libmapbox-gl.so (mapbox::geojsonvt::Simplify::simplify(std::__1::vector<mapbox::geojsonvt::ProjectedPoint, std::__1::allocator<mapbox::geojsonvt::ProjectedPoint> >&, double)+108)
06-09 14:44:50.711 3879-3879/? I/DEBUG:     #01 pc 008ce038  /data/app/com.mapbox.mapboxsdk.testapp-2/lib/arm/libmapbox-gl.so (mapbox::geojsonvt::Convert::projectRing(std::__1::vector<mapbox::geojsonvt::LonLat, std::__1::allocator<mapbox::geojsonvt::LonLat> > const&, double)+344)
06-09 14:44:50.711 3879-3879/? I/DEBUG:     #02 pc 0044b9f0  /data/app/com.mapbox.mapboxsdk.testapp-2/lib/arm/libmapbox-gl.so (mbgl::ToGeoJSONVT::convertPoints(mapbox::geojsonvt::ProjectedFeatureType, std::__1::vector<mapbox::geometry::point<double>, std::__1::allocator<mapbox::geometry::point<double> > > const&) const+1340)
06-09 14:44:50.711 3879-3879/? I/DEBUG:     #03 pc 0044a14c  /data/app/com.mapbox.mapboxsdk.testapp-2/lib/arm/libmapbox-gl.so (mbgl::ToGeoJSONVT::operator()(mapbox::geometry::line_string<double, std::__1::vector> const&) const+188)
06-09 14:44:50.711 3879-3879/? I/DEBUG:     #04 pc 0044a040  /data/app/com.mapbox.mapboxsdk.testapp-2/lib/arm/libmapbox-gl.so (_ZN6mapbox4util6detail10dispatcherIN4mbgl11ToGeoJSONVTENS0_7variantIJNS_8geometry11line_stringIdNSt3__16vectorEEENS6_7polygonIdS9_EENS6_17multi_line_stringIdS9_EENS6_13multi_polygonIdS9_EEEEENS_9geojsonvt16ProjectedFeatureEJSA_SC_SE_SG_EE11apply_constERKSH_OS4_+84)
06-09 14:44:50.711 3879-3879/? I/DEBUG:     #05 pc 0043ff58  /data/app/com.mapbox.mapboxsdk.testapp-2/lib/arm/libmapbox-gl.so (_ZN6mapbox4util7variantIJNS_8geometry11line_stringIdNSt3__16vectorEEENS2_7polygonIdS5_EENS2_17multi_line_stringIdS5_EENS2_13multi_polygonIdS5_EEEE5visitIN4mbgl11ToGeoJSONVTESD_NS_9geojsonvt16ProjectedFeatureEEEDTclsr6detail10dispatcherIT_T0_T1_S6_S8_SA_SC_EE11apply_constfp_clsr3stdE7forwardISJ_Efp0_EEERKSK_OSJ_+36)
06-09 14:44:50.711 3879-3879/? I/DEBUG:     #06 pc 0043ece4  /data/app/com.mapbox.mapboxsdk.testapp-2/lib/arm/libmapbox-gl.so (mbgl::ShapeAnnotationImpl::updateTile(mbgl::CanonicalTileID const&, mbgl::AnnotationTile&)+256)
06-09 14:44:50.711 3879-3879/? I/DEBUG:     #07 pc 003ef5b8  /data/app/com.mapbox.mapboxsdk.testapp-2/lib/arm/libmapbox-gl.so (mbgl::AnnotationManager::getTile(mbgl::CanonicalTileID const&)+1420)
06-09 14:44:50.711 3879-3879/? I/DEBUG:     #08 pc 003f1468  /data/app/com.mapbox.mapboxsdk.testapp-2/lib/arm/libmapbox-gl.so (mbgl::AnnotationManager::updateStyle(mbgl::style::Style&)+5464)
06-09 14:44:50.711 3879-3879/? I/DEBUG:     #09 pc 00484db0  /data/app/com.mapbox.mapboxsdk.testapp-2/lib/arm/libmapbox-gl.so (mbgl::Map::Impl::update()+360)
06-09 14:44:50.711 3879-3879/? I/DEBUG:     #10 pc 0048edf8  /data/app/com.mapbox.mapboxsdk.testapp-2/lib/arm/libmapbox-gl.so
06-09 14:44:50.711 3879-3879/? I/DEBUG:     #11 pc 0048ed24  /data/app/com.mapbox.mapboxsdk.testapp-2/lib/arm/libmapbox-gl.so
06-09 14:44:50.711 3879-3879/? I/DEBUG:     #12 pc 00495db4  /data/app/com.mapbox.mapboxsdk.testapp-2/lib/arm/libmapbox-gl.so (std::__1::function<void ()>::operator()() const+164)
06-09 14:44:50.711 3879-3879/? I/DEBUG:     #13 pc 006ca1d8  /data/app/com.mapbox.mapboxsdk.testapp-2/lib/arm/libmapbox-gl.so (mbgl::util::AsyncTask::Impl::runTask()+204)
06-09 14:44:50.711 3879-3879/? I/DEBUG:     #14 pc 006cbb24  /data/app/com.mapbox.mapboxsdk.testapp-2/lib/arm/libmapbox-gl.so (mbgl::util::RunLoop::Impl::processRunnables()+788)
06-09 14:44:50.711 3879-3879/? I/DEBUG:     #15 pc 006cd0b8  /data/app/com.mapbox.mapboxsdk.testapp-2/lib/arm/libmapbox-gl.so (mbgl::util::RunLoop::runOnce()+240)
06-09 14:44:50.711 3879-3879/? I/DEBUG:     #16 pc 006ca9c8  /data/app/com.mapbox.mapboxsdk.testapp-2/lib/arm/libmapbox-gl.so
06-09 14:44:50.711 3879-3879/? I/DEBUG:     #17 pc 0001030f  /system/lib/libutils.so (android::SimpleLooperCallback::handleEvent(int, int, void*)+10)
06-09 14:44:50.711 3879-3879/? I/DEBUG:     #18 pc 00010f6f  /system/lib/libutils.so (android::Looper::pollInner(int)+482)
06-09 14:44:50.711 3879-3879/? I/DEBUG:     #19 pc 00011019  /system/lib/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+92)
06-09 14:44:50.711 3879-3879/? I/DEBUG:     #20 pc 00082ff9  /system/lib/libandroid_runtime.so (android::NativeMessageQueue::pollOnce(_JNIEnv*, int)+22)
06-09 14:44:50.711 3879-3879/? I/DEBUG:     #21 pc 000b22df  /system/framework/arm/boot.oat
06-09 14:44:50.951 902-1038/? W/ActivityManager: mDVFSHelper.release()
06-09 14:44:50.951 902-1038/? I/Timeline: Timeline: Activity_windows_visible id: ActivityRecord{308545c3 u0 com.mapbox.mapboxsdk.testapp/.activity.annotation.PolylineActivity t1028} time:783178372
06-09 14:44:51.591 3879-3879/? I/DEBUG: Tombstone written to: /data/tombstones/tombstone_02
                                        
                                        
                                        [ 06-09 14:44:51.591  3879: 3879 E/         ]
                                        !@dumpstate -k -t -z -d -o /data/log/dumpstate_app_native -m 8749
```

**Comment by bleege** [comment]
Crash (as expected) on Directions Activity too again due to GeoJSONVT issue.  Continuing test.

```java
06-09 14:49:50.121 9479-9479/com.mapbox.mapboxsdk.testapp A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x10 in tid 9479 (pboxsdk.testapp)
06-09 14:49:50.211 286-286/? E/SMD: DCD ON
06-09 14:49:50.221 3879-3879/? I/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
06-09 14:49:50.221 3879-3879/? I/DEBUG: Build fingerprint: 'samsung/klteuc/klteatt:5.0/LRX21T/G900AUCU3BOC4:user/release-keys'
06-09 14:49:50.221 3879-3879/? I/DEBUG: Revision: '14'
06-09 14:49:50.221 3879-3879/? I/DEBUG: ABI: 'arm'
06-09 14:49:50.221 3879-3879/? I/DEBUG: pid: 9479, tid: 9479, name: pboxsdk.testapp  >>> com.mapbox.mapboxsdk.testapp <<<
06-09 14:49:50.221 3879-3879/? I/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x10
06-09 14:49:50.251 3879-3879/? I/DEBUG:     r0 be8613c0  r1 00000000  r2 00000000  r3 3df00000
06-09 14:49:50.251 3879-3879/? I/DEBUG:     r4 00000000  r5 00000000  r6 00000000  r7 aaaaaaab
06-09 14:49:50.251 3879-3879/? I/DEBUG:     r8 00000000  r9 3ff00000  sl be8613c0  fp be8612f0
06-09 14:49:50.251 3879-3879/? I/DEBUG:     ip 9ecfdcec  sp be860fd0  lr 9ebf403c  pc 9ebf4d14  cpsr 600d0010
06-09 14:49:50.251 3879-3879/? I/DEBUG: backtrace:
06-09 14:49:50.251 3879-3879/? I/DEBUG:     #00 pc 008ced14  /data/app/com.mapbox.mapboxsdk.testapp-2/lib/arm/libmapbox-gl.so (mapbox::geojsonvt::Simplify::simplify(std::__1::vector<mapbox::geojsonvt::ProjectedPoint, std::__1::allocator<mapbox::geojsonvt::ProjectedPoint> >&, double)+108)
06-09 14:49:50.251 3879-3879/? I/DEBUG:     #01 pc 008ce038  /data/app/com.mapbox.mapboxsdk.testapp-2/lib/arm/libmapbox-gl.so (mapbox::geojsonvt::Convert::projectRing(std::__1::vector<mapbox::geojsonvt::LonLat, std::__1::allocator<mapbox::geojsonvt::LonLat> > const&, double)+344)
06-09 14:49:50.251 3879-3879/? I/DEBUG:     #02 pc 0044b9f0  /data/app/com.mapbox.mapboxsdk.testapp-2/lib/arm/libmapbox-gl.so (mbgl::ToGeoJSONVT::convertPoints(mapbox::geojsonvt::ProjectedFeatureType, std::__1::vector<mapbox::geometry::point<double>, std::__1::allocator<mapbox::geometry::point<double> > > const&) const+1340)
06-09 14:49:50.251 3879-3879/? I/DEBUG:     #03 pc 0044a14c  /data/app/com.mapbox.mapboxsdk.testapp-2/lib/arm/libmapbox-gl.so (mbgl::ToGeoJSONVT::operator()(mapbox::geometry::line_string<double, std::__1::vector> const&) const+188)
06-09 14:49:50.251 3879-3879/? I/DEBUG:     #04 pc 0044a040  /data/app/com.mapbox.mapboxsdk.testapp-2/lib/arm/libmapbox-gl.so (_ZN6mapbox4util6detail10dispatcherIN4mbgl11ToGeoJSONVTENS0_7variantIJNS_8geometry11line_stringIdNSt3__16vectorEEENS6_7polygonIdS9_EENS6_17multi_line_stringIdS9_EENS6_13multi_polygonIdS9_EEEEENS_9geojsonvt16ProjectedFeatureEJSA_SC_SE_SG_EE11apply_constERKSH_OS4_+84)
06-09 14:49:50.251 3879-3879/? I/DEBUG:     #05 pc 0043ff58  /data/app/com.mapbox.mapboxsdk.testapp-2/lib/arm/libmapbox-gl.so (_ZN6mapbox4util7variantIJNS_8geometry11line_stringIdNSt3__16vectorEEENS2_7polygonIdS5_EENS2_17multi_line_stringIdS5_EENS2_13multi_polygonIdS5_EEEE5visitIN4mbgl11ToGeoJSONVTESD_NS_9geojsonvt16ProjectedFeatureEEEDTclsr6detail10dispatcherIT_T0_T1_S6_S8_SA_SC_EE11apply_constfp_clsr3stdE7forwardISJ_Efp0_EEERKSK_OSJ_+36)
06-09 14:49:50.251 3879-3879/? I/DEBUG:     #06 pc 0043ece4  /data/app/com.mapbox.mapboxsdk.testapp-2/lib/arm/libmapbox-gl.so (mbgl::ShapeAnnotationImpl::updateTile(mbgl::CanonicalTileID const&, mbgl::AnnotationTile&)+256)
06-09 14:49:50.251 3879-3879/? I/DEBUG:     #07 pc 003ef5b8  /data/app/com.mapbox.mapboxsdk.testapp-2/lib/arm/libmapbox-gl.so (mbgl::AnnotationManager::getTile(mbgl::CanonicalTileID const&)+1420)
06-09 14:49:50.251 3879-3879/? I/DEBUG:     #08 pc 003f1468  /data/app/com.mapbox.mapboxsdk.testapp-2/lib/arm/libmapbox-gl.so (mbgl::AnnotationManager::updateStyle(mbgl::style::Style&)+5464)
06-09 14:49:50.251 3879-3879/? I/DEBUG:     #09 pc 00484db0  /data/app/com.mapbox.mapboxsdk.testapp-2/lib/arm/libmapbox-gl.so (mbgl::Map::Impl::update()+360)
06-09 14:49:50.251 3879-3879/? I/DEBUG:     #10 pc 0048edf8  /data/app/com.mapbox.mapboxsdk.testapp-2/lib/arm/libmapbox-gl.so
06-09 14:49:50.251 3879-3879/? I/DEBUG:     #11 pc 0048ed24  /data/app/com.mapbox.mapboxsdk.testapp-2/lib/arm/libmapbox-gl.so
06-09 14:49:50.251 3879-3879/? I/DEBUG:     #12 pc 00495db4  /data/app/com.mapbox.mapboxsdk.testapp-2/lib/arm/libmapbox-gl.so (std::__1::function<void ()>::operator()() const+164)
06-09 14:49:50.251 3879-3879/? I/DEBUG:     #13 pc 006ca1d8  /data/app/com.mapbox.mapboxsdk.testapp-2/lib/arm/libmapbox-gl.so (mbgl::util::AsyncTask::Impl::runTask()+204)
06-09 14:49:50.251 3879-3879/? I/DEBUG:     #14 pc 006cbb24  /data/app/com.mapbox.mapboxsdk.testapp-2/lib/arm/libmapbox-gl.so (mbgl::util::RunLoop::Impl::processRunnables()+788)
06-09 14:49:50.251 3879-3879/? I/DEBUG:     #15 pc 006cd0b8  /data/app/com.mapbox.mapboxsdk.testapp-2/lib/arm/libmapbox-gl.so (mbgl::util::RunLoop::runOnce()+240)
06-09 14:49:50.251 3879-3879/? I/DEBUG:     #16 pc 006ca9c8  /data/app/com.mapbox.mapboxsdk.testapp-2/lib/arm/libmapbox-gl.so
06-09 14:49:50.251 3879-3879/? I/DEBUG:     #17 pc 0001030f  /system/lib/libutils.so (android::SimpleLooperCallback::handleEvent(int, int, void*)+10)
06-09 14:49:50.251 3879-3879/? I/DEBUG:     #18 pc 00010f6f  /system/lib/libutils.so (android::Looper::pollInner(int)+482)
06-09 14:49:50.251 3879-3879/? I/DEBUG:     #19 pc 00011019  /system/lib/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+92)
06-09 14:49:50.251 3879-3879/? I/DEBUG:     #20 pc 00082ff9  /system/lib/libandroid_runtime.so (android::NativeMessageQueue::pollOnce(_JNIEnv*, int)+22)
06-09 14:49:50.251 3879-3879/? I/DEBUG:     #21 pc 000b22df  /system/framework/arm/boot.oat
06-09 14:49:51.521 902-12119/? W/ActivityManager:   Force finishing activity com.mapbox.mapboxsdk.testapp/.activity.directions.DirectionsActivity
06-09 14:49:51.521 902-12120/? W/DropBoxManagerService: Dropping: data_app_native_crash (10 > 0 bytes)
06-09 14:49:51.531 3879-3879/? I/DEBUG: Tombstone written to: /data/tombstones/tombstone_03
                                        
                                        
                                        [ 06-09 14:49:51.531  3879: 3879 E/         ]
                                        !@dumpstate -k -t -z -d -o /data/log/dumpstate_app_native -m 9479
06-09 14:49:51.531 902-1033/? I/BootReceiver: Copying /data/tombstones/tombstone_03 to DropBox (SYSTEM_TOMBSTONE)
```

**Comment by bleege** [comment]
Finished testing the rest of the TestApp examples and everything is in order.  Next up is to get this into `master`.

**Pull request merged**
