### PR TITLE
[ios] Calculate size of a MGLMapViewOpenGLImpl renderable from MGLMapView bounds

### PR DESCRIPTION
**Pull request by alexshalamov**
When `MGLMapViewOpenGLImpl` initializes it's `GLKView`, Renderable size is set to `GLKView`'s framebuffer size. Unfortunately, `GLKView`'s framebuffer size is unknown until it is ready, i.e., when `GLKViewDelegate`'s draw method is called.

This PR adds `virtual void layoutChanged()` method to `MGLMapViewImpl`  that should be called when map's UIView is laid out, so that `Renderable` size can be calculated from the `UIView` bounds.

Fixes: #14807

- [x] Update changelog
- [x] Add integration test
- [ ] Cherry pick PR

### CODE REVIEW

**Comment by kkaefer** [comment]
Good catch! Does this also fix the issue when you initialize a map view with a given size, then resize it (e.g. by rotating the device), then add a heatmap layer?

**Comment by alexshalamov** [comment]
@kkaefer thanks, checking right now.

**Comment by alexshalamov** [comment]
@kkaefer @astojilj I changed PR, so that we calculate `MGLMapViewOpenGLImpl`'s size when map's UIView is laid out. This sets correct initial `Renderable` size as well as size updates due to the screen rotation.

**Comment by julianrex** [comment]
Discussed this PR with @alexshalamov - @captainbarbosa and l will run some tests locally, just to be sure. Please hold off on merging until then.

**Comment by alexshalamov** [comment]
@julianrex sure, I'm waiting for your's and @captainbarbosa's :+1:

**Comment by friedbunny** [comment]
@alexshalamov @kkaefer @astojilj have you considered how this functionality might be unit tested?

**Comment by alexshalamov** [comment]
@friedbunny I think that unit tests wouldn't be useful for such change, I will check tomorrow if I can add ios integration test.

**Comment by julianrex** [comment]
Perhaps we can convert @astojilj's `iosapp` "test" into an integration test - that seems the most straightforward option here.

**Comment by friedbunny** [comment]
Indeed, `iosapp`’s role as a catch-all landing place for manual regression/integration tests is ending with the ongoing refactoring of that app. If something needs integration tests, @julianrex’s suggestion to add it to the Integration Tests target is probably the way to go (though those aren’t run on CI because of poor stability).

**Comment by alexshalamov** [comment]
@julianrex could you please check commit with integration test https://github.com/mapbox/mapbox-gl-native/pull/14810/commits/4a822207e2035425fa1259d3cb84c1b4e2917be7

I couldn't figure out how to access `MGLMapView` implementation ([needed here](https://github.com/mapbox/mapbox-gl-native/pull/14810/commits/4a822207e2035425fa1259d3cb84c1b4e2917be7#diff-09f3aca061b84b9d2d4619a0ac7d45b1R213)), so I added one method to the `MGLMapView_Private.h`

**Pull request merged**
