### PR TITLE
Verbose commenting on getSegmentGlyphs

### PR DESCRIPTION
**Pull request by ChrisLoer**
@anandthakker and I paired on trying to understand how getSegmentGlyphs works, since we couldn't pick @ansis 's brain. Our goal was (1) make sure we understand how the function is supposed to work, and then (2) use the comments as guidelines to refactor the function so that some of the magic parts are less mysterious.

### CODE REVIEW

**Comment by ChrisLoer** [comment]
OK @anandthakker , over to you. :)

I took a stab at refactoring based on the understanding we developed during the commenting. If you did a round of improvements on variable names, function inlining, control flow, and commenting, I bet it would start to look pretty good.

**Comment by anandthakker** [comment]
@ChrisLoer your first pass was a huge improvement / most of the work.  Just took a pass to add some more comments, over to @jfirebaugh to 👀

**Comment by ChrisLoer** [comment]
Awesome ASCII art! But unless I'm misunderstanding the diagram, I don't think it represents the "virtual anchor" concept correctly. Instead of:

                    B <-- beginning of current segment
                    .*-----
                  .  |
                .    /
              .     /
            .      /
    ------.*------`
        .  A
      .    anchor
     *
    VA <- "virtual" anchor

I think it's more like:


                      B <-- beginning of current segment
    * . . . . . . . *--------* E <-- end of current segment
    VA              |      
                    /        VA = "virtual segment anchor"
                   /
         ---*-----`
            A = label anchor

**Comment by anandthakker** [comment]
@ChrisLoer oh yeah, you are totally right.  I misread the vector math!

**Comment by anandthakker** [comment]
@jfirebaugh okay, this should be ready for 👀 now

**Comment by ChrisLoer** [comment]
🎉

**Pull request merged**
