### PR TITLE
[android] Make the android release all build batched

### PR DESCRIPTION
**Pull request by Guardiola31337**
- Makes the `android-release-all` build batched

👀 @ivovandongen @brunoabinader @tmpsantos

### CODE REVIEW

**Comment by tmpsantos** [comment]
If that is the case, you will need to create a new target on the `Makefile`, maybe name it `apackage-batch`, where different archs will depend on each other.

**Comment by Guardiola31337** [comment]
I run it locally and it only generates one `.aar`. I unzipped it and all the architectures are included in the `jni` folder.

Apparently, it gets overwritten on each architecture build but because we're not removing the `intermediates` folders it seems previous `.so` files generated are taken into account and are included in the last build.

So, if I'm not missing anything, it's working as it was.

cc/ @ivovandongen @tmpsantos

**Comment by ivovandongen** [comment]
@Guardiola31337 

Interesting, but that also means that the archive is being created redundantly for each architecture. Reducing the change to something like:

```
diff --git a/Makefile b/Makefile
index ab0b36658..52ad0b41d 100644
--- a/Makefile
+++ b/Makefile
@@ -594,6 +594,7 @@ run-android-ui-test-aws: platform/android/configuration.gradle
 # Builds a release package of the Android SDK
 .PHONY: apackage
 apackage: platform/android/configuration.gradle
+       make android-lib-arm-v5 && make android-lib-arm-v7 && make android-lib-arm-v8 && make android-lib-x86 && make android-lib-x86-64 && make android-lib-mips
        cd platform/android && $(MBGL_ANDROID_GRADLE) -Pmapbox.abis=all assemble$(BUILDTYPE)
 
 # Uploads the compiled Android SDK to Maven
```

Ensures the shared libraries are built separately, but the resulting archive and the test app are built only once.

As a side-effect, it also ensures that any missing architectures in that list will still be built instead of silently ignored.

**Comment by Guardiola31337** [comment]
@ivovandongen 
> Ensures the shared libraries are built separately,

Correct.

> but the resulting archive [...] built only once.

This is not true because `make android-lib-$1` executes `:MapboxGLAndroidSDK:assemble$(BUILDTYPE)` which creates a new archive each time is executed.

> the test app are built only once.

This is true 👍 

> As a side-effect, it also ensures that any missing architectures in that list will still be built instead of silently ignored.

You're right, good catch!

**Comment by Guardiola31337** [comment]
@ivovandongen https://github.com/mapbox/mapbox-gl-native/pull/9907/commits/9622ae04186e9f7274d7cc5bda633aeebd4fbe10 addressed your comments.

**Pull request merged**
