### PR TITLE
Add make task for building node bindings via Xcode

### PR DESCRIPTION
**Pull request by mikemorris**
Think this should do it @kkaefer.

### CODE REVIEW

**Comment by mikemorris** [comment]
Looks like this is grabbing the wrong libuv/node headers, I hit this before testing a pre-release Node version for https://github.com/mapbox/mapbox-gl-native/issues/2597, workaround was adding the node headers path to [`include_dirs`](https://github.com/mapbox/mapbox-gl-native/blob/00a1c2343abcdcfc222d26c9a579fc081fffff6a/binding.gyp#L13) in `binding.gyp`.

**Comment by kkaefer** [comment]
on node v0.10, it's failing with `AttributeError: 'PBXAggregateTarget' object has no attribute ‘FrameworksPhase'`. Looks like `node-gyp` includes `-undefined dynamic_lookup` in the `libraries, which isn't something Xcode likes. Instead, that should be in `LDFLAGS`.

**Comment by tmcw** [comment]
@mikemorris for the sake of documentation, why would someone want to run this instead of `make node`?

**Comment by kkaefer** [comment]
@tmcw You want to run `make xnode` so that you have an Xcode project that you can open in Xcode. This helps when debugging code, since you'll get a GUI debugger in the case of a crash.

**Pull request merged**
