### PR TITLE
[ios] Fix typo

### PR DESCRIPTION
**Pull request by tmpsantos**
s/Reponse/Response

### CODE REVIEW

**Comment by frederoni** [comment]
Should be done in the dependency but this is correct since it's copied/checked in.
(https://github.com/AliSoftware/OHHTTPStubs)

👍

**Comment by tmpsantos** [comment]
> Should be done in the dependency but this is correct since it's copied/checked in.
> (https://github.com/AliSoftware/OHHTTPStubs)

Thanks for pointing out. I will make a PR there too.

**Comment by tmpsantos** [comment]
The API was fixed upstream already, just the docs were left.

https://github.com/AliSoftware/OHHTTPStubs/pull/198

**Comment by friedbunny** [comment]
Do you recall why OHHTTPStubs isn’t a git submodule, @1ec5? Submodules can be a headache, but we’re probably always going to be reliant on them in this project.

**Comment by 1ec5** [comment]
I don't think there's a good reason it's checked in. We could certainly turn it into a submodule.

**Pull request merged**
