### PR TITLE
[meta] update INSTALL dependencies

### PR DESCRIPTION
**Pull request by friedbunny**
Updates `INSTALL.md` with libuv version recommendation and new project URL. This would be a good opportunity to check that the rest of our listed dependencies are up-to-date @mapbox/gl.

Refs #2609

### CODE REVIEW

**Comment by jfirebaugh** [comment]
I think we should actually remove the packages that will be installed by mason from this list entirely (boost, libuv, zlib, libpng, glfw). The relevant question for people coming to this page is "What do I need to manually install to be able to run the mapbox-gl-native build?", not "What package versions will the build itself install?"

**Comment by friedbunny** [comment]
That'd be fine, too. Variant and rapidjson are two dependencies that mason installs that aren't on this list, while libtool and automake are both occasionally required if mason doesn't have a prebuilt binary.

**Comment by ljbade** [comment]
Yeah it should just list stuff that our build system doesn't install/download for you.

Did we remove the references to manually installing the Android NDK (not the SDK)

**Comment by mikemorris** [comment]
Gonna revisit this after https://github.com/mapbox/mapbox-gl-native/pull/2800 lands.

**Comment by mikemorris** [comment]
Revised this to drop mason-installed packages Boost, zlib, libpng, libuv and glfw. Added libtool and automake, which may be needed on platforms where mason binaries are not available.

:eyes: @friedbunny

**Comment by friedbunny** [comment]
Thanks @mikemorris, changes looks good. 

@mourner @jfirebaugh Do we need ImageMagick? It's [still installed](https://github.com/mapbox/mapbox-gl-native/blob/aaf090b87dbc96f7a09e783833c10d0b88a16d39/docker/linux/Dockerfile#L5) on Travis, anyway.

**Comment by jfirebaugh** [comment]
ImageMagick is no longer required. Hooray!

**Comment by friedbunny** [comment]
I clobbered @mikemorris' 8cc78b58909dda58b7d0a4b9b310d64aa50f0b7c removal of ImageMagick with a rebased version of the same. Apologies — luckily the result this time was effectively the same as rebasing/squashing. I think we're ready to merge here, @mikemorris?

**Pull request merged**
