### PR TITLE
-fsanitize=integer issues in glyph_set.cpp

### PR DESCRIPTION
**Pull request by brunoabinader**
Running with `-fsanitize=integer` shows warnings from glyph_set.cpp indicating overflows:

```
../src/mbgl/text/glyph_set.cpp:165:34: runtime error: unsigned integer overflow: 4294967282 + 28 cannot be represented in type 'unsigned int'
../src/mbgl/text/glyph_set.cpp:167:34: runtime error: unsigned integer overflow: 4294967208 + 176 cannot be represented in type 'unsigned int'
../src/mbgl/text/glyph_set.cpp:167:34: runtime error: unsigned integer overflow: 4294967251 + 90 cannot be represented in type 'unsigned int'
```

Replicable with:

```sh
SANITIZER="integer"
export CFLAGS="-fsanitize=${SANITIZER}"
export CXXFLAGS="-fsanitize=${SANITIZER}"
export LDFLAGS="-fsanitize=${SANITIZER}"
make test-node
```

### CODE REVIEW

**Comment by brunoabinader** [comment]
@springmeyer @mikemorris sorry folks, used wrong issue number :fearful:

**Comment by brunoabinader** [comment]
Oh dang - removing the path did more damage than the conversion - I'll add a stub patch to keep the issue (now PR) open :sob:

**Comment by jfirebaugh** [comment]
This PR seems to be in a weird state. We've got a tracking issue for asan/tsan in #5379. Let's close here.

**Comment by springmeyer** [comment]
@jfirebaugh - there was never a PR here - it only looked like it. But nevertheless this warning will arise again once we get #5379 going, so all good to handle there.

**Pull request closed without merging**
