### PR TITLE
[styles] Update to styles release v1.1.4

### PR DESCRIPTION
**Pull request by ljbade**
Fixes https://github.com/mapbox/mapbox-gl-native/issues/2585

### CODE REVIEW

**Comment by ljbade** [comment]
@bsudekum Is this the right styles release to use?

Will the new Satellite hybrid style become an "offical" style? If so we should add it to the list of bundles styles on Android and iOS and in the SDKs/Test Apps/Siriuses.

@mapbox/mobile Everyone should test the latest styles to check for any rendering errors since native has been using old style for quite some time.

**Comment by jfirebaugh** [comment]
I don't think there's any reason not to use the latest version, 1.1.4.

Yes, satellite hybrid is "official". The full official list is in the README for https://github.com/mapbox/mapbox-gl-styles.

**Comment by jfirebaugh** [comment]
Also note that we want to remove this submodule entirely: #2239.

**Comment by ljbade** [comment]
@jfirebaugh there is no 1.1.4 tag in the styles repo.

**Comment by jfirebaugh** [comment]
cc @edenh ^ are we missing some tags?

**Comment by edenh** [comment]
Sorry, just pushed the tags: https://github.com/mapbox/mapbox-gl-styles/releases

**Comment by ljbade** [comment]
@jfirebaugh Updated to 1.1.4

Will wait for Travis then merge.

**Comment by ljbade** [comment]
Only iOS test failed. Merging.

**Comment by ljbade** [comment]
Merged.

**Pull request closed without merging**
