### PR TITLE
[android] #6077 - keep rules for Signature and Annotation

### LINKED ISSUE #6077: Update Proguard rules
Discovered an issue when using Proguard and the SDK that might be because of MAS becoming a dependency or the new styles. Current work around's to keep everything:

```pro
-keep class com.mapbox.mapboxsdk.** { *; }
```

cc: @mapbox/android

### PR DESCRIPTION
**Pull request by tobrun**
Closes #6077 

I was able to proguard the testapp with this configuration. Would love some 👀 . 

You can retest this with adding the following in our build.gradle of the testapp:

```
    buildTypes {
        debug {
            // run code coverage reports
            testCoverageEnabled = true
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
```

Review @cammace, @bleege

### CODE REVIEW

**Comment by cammace** [comment]
Looks good to merge @tobrun, Once in master and the next SNAPSHOT's built, i'll test in the app 😉

**Comment by tobrun** [comment]
I try to revisiting proposed PR by keeping generic innerclasses specificaly. This would remove the need for keep Attributes, Signature but couldn't get it to work for the generic constructor of `MarkerViewAdapter<T>`. I'm going to point on this for now but revisit later.

**Comment by tobrun** [comment]
After rebasing in i'm also noticing issues with mapbox-java depedency. Going to keep that package that for now and created a follow  ticket in https://github.com/mapbox/mapbox-java/issues/178. Will push my commit and merge.

**Comment by tobrun** [comment]
CI approved, going to merge cc @mapbox/android.

**Comment by zugaldia** [comment]
@tobrun @cammace Why are we doing `com.mapbox.mapboxsdk.<package>.*` for each package in the SDK, instead of doing `com.mapbox.mapboxsdk.*` to cover them all and keep the rules shorter. Any particular advantages?

**Pull request merged**
