### PR TITLE
Update compile flags for iOS

### PR DESCRIPTION
**Pull request by kkaefer**
We should do these changes to iOS compilation settings:

- [x] [Only build active architecture when building Debug builds to speed up compile time](https://github.com/mapbox/mapbox-gl-native/pull/7388)
- [x] Remove bitcode from Debug builds
- [x] [Add `-fvisibility=hidden`](https://github.com/mapbox/mapbox-gl-native/pull/7604)
- [x] Strip non-global symbols for Release static/dynamic library
- [x] Enable monolithic LTO

/cc @1ec5

### CODE REVIEW

**Comment by kkaefer** [comment]
> This means we won't catch any differences between 32-bit and 64-bit. We have unit tests for regressions around the size of an NSInteger, for example.

Okay; can we force `ONLY_ACTIVE_ARCH=NO` on CI, but use `YES` (first commit in this PR) for regular builds that you do when developing?

**Comment by kkaefer** [comment]
> We already conditionally do this in the packaging script (just not in the Xcode project)

Any reason why we wouldn't do this as part of the Xcode build and only do it in an external packaging script?

**Comment by kkaefer** [comment]
With all of the above optimizations, arm64 shrinks from 3,351 KB to 2,925 KB.

**Comment by 1ec5** [comment]
I’m all for performing the stripping in the Xcode project instead of the packaging script. The more of the packaging script we can put in proper Xcode build steps, the better.

>> This means we won't catch any differences between 32-bit and 64-bit. We have unit tests for regressions around the size of an NSInteger, for example.

> Okay; can we force ONLY_ACTIVE_ARCH=NO on CI, but use YES (first commit in this PR) for regular builds that you do when developing?

I’d prefer not to trim the CI build matrix at the expense of local incremental build times. We already make this compromise when it comes to static builds, which is why #6194 went undetected for awhile.

**Comment by kkaefer** [comment]
> I’d prefer not to trim the CI build matrix at the expense of local incremental build times.

It's the other way around: Local build times would be faster, since we are only building the active architecture for Debug builds (typically arm64 with most modern devices). On CI, we'd explicitly set `ONLY_ACTIVE_ARCH=NO` on the Debug build to have it build both architectures. Release builds will still build both architectures local and on CI.

**Comment by friedbunny** [comment]
> Any reason why we wouldn't do this as part of the Xcode build and only do it in an external packaging script?

We can do it in the Xcode project, but the implementation of conditionally stripped symbols will have to be updated in the packaging script and all of the possible packages will need to be re-validated.

**Comment by kkaefer** [comment]
> all of the possible packages will need to be re-validated.
 
What does that mean? Are you referring to code signing?

**Comment by friedbunny** [comment]
I mean that we’ll need to confirm that every built package still works as expected.

**Comment by kkaefer** [comment]
@friedbunny what's the process here? Do we have a list of all the packages that need to build, and how to validate them?

**Comment by friedbunny** [comment]
[Here’s the list of packages we publish](https://github.com/mapbox/mapbox-gl-native/blob/4577c56745d90cfa00837d00e5e5605260a54879/platform/ios/scripts/deploy-packages.sh#L111-L115) — static and dynamic w/symbols, static and dynamic w/o symbols, and one Fabric build that’s static w/o symbols.

The process for verifying that a build is usable is mostly manual. You’ll need at least two test iOS projects that integrate Mapbox.framework — one for static and one for dynamic.

Steps to confirm that a build works:
- Test it in an iOS project.
  - With and without storyboards.
  - ObjC and Swift.
- Submit that app to TestFlight/App Store.
- Confirm that that dSYM and framework UUIDs match. ([automatic](https://github.com/mapbox/mapbox-gl-native/blob/4577c56745d90cfa00837d00e5e5605260a54879/platform/ios/scripts/package.sh#L194-L203))

These steps should be repeated for every packaged build.

I’m also unsure where we stand on Xcode 8 vs 7.3.1 (https://github.com/mapbox/mapbox-gl-native/issues/7029) — it may be necessary to test builds from both. /cc @boundsj

**Comment by kkaefer** [comment]
> The process for verifying that a build is usable is mostly manual.

Is there a way to automate it? It seems that I can't run `deploy-packages.sh` when that version has already been published.

What is the advantage of building with symbols? I thought we have external symbols in the .dSYM file anyway?

> You’ll need at least two test iOS projects that integrate Mapbox.framework — one for static and one for dynamic.

Where do I get those from? Just create a new sample app that embeds those frameworks? Can we automate this?

**Comment by friedbunny** [comment]
I looked at implementing LTO today and wasn’t able to see any noticeable change in the bench app FPS on my iPhone 5 — plain master and various LTO combinations averaged ~40.5 FPS. After watching the WWDC session on it, this was underwhelming.

### Notes
- ThinLTO seems like the way to go (rather than Monolithic) — compile times are supposed to be much better, while performance is supposed to be more or less the same.
- It seemed compatible with ccache (surprisingly).
- Problematic: missing core symbol warnings from dsymutil when building the dynamic framework.

### Links
- [ThinLTO: Scalable and Incremental LTO - LLVM Blog](http://blog.llvm.org/2016/06/thinlto-scalable-and-incremental-lto.html)
- [ThinLTO - Clang docs](https://clang.llvm.org/docs/ThinLTO.html)
- [WWDC 2016 - What’s New in LLVM](https://developer.apple.com/videos/play/wwdc2016/405/) ([transcript](http://asciiwwdc.com/2016/sessions/405))

**Comment by kkaefer** [comment]
LTO optimizes the CPU code, but it looks like rendering is GPU bound on your phone. This would explain the lack of FPS increase. Did LTO have any effect on binary size?

**Comment by friedbunny** [comment]
#12502 takes on LTO, the final unmerged piece of this PR — closing.

**Pull request closed without merging**
