### PR TITLE
[core] Introduce dedicated filter types for $type and $id special cases

### PR DESCRIPTION
**Pull request by jfirebaugh**
Refs #7552

### CODE REVIEW

**Comment by 1ec5** [comment]
iOS and macOS tests are failing because `FilterEvaluator` in NSPredicate+MGLAdditions.mm has no operator `()` for the new type filter types:

```
▸ Compiling NSPredicate+MGLAdditions.mm

❌  /Users/vagrant/git/mason_packages/headers/variant/1.1.4/include/mapbox/variant.hpp:312:20: no matching function for call to object of type 'FilterEvaluator'

            return f(unwrapper<T>::apply(v.template get_unchecked<T>()));
                   ^



❌  /Users/vagrant/git/mason_packages/headers/variant/1.1.4/include/mapbox/variant.hpp:312:20: no matching function for call to object of type 'FilterEvaluator'

            return f(unwrapper<T>::apply(v.template get_unchecked<T>()));
                 ^


make: *** [run-test-*] Error 65
```

For now, let’s have the conversion match [the existing documentation](https://www.mapbox.com/ios-sdk/api/3.4.1/Classes/MGLVectorStyleLayer.html#/c:objc%28cs%29MGLVectorStyleLayer%28py%29predicate) to avoid backwards compatibility concerns. For example:

```objc
[NSPredicate predicateWithFormatString:@"%@ = 'LineString'", @"$type"]
[NSPredicate predicateWithFormatString:@"%@ IN { 'LineString', 'Polygon' }", @"$type"]
```

If we’re considering cherry-picking this change into iOS SDK v3.4.2, then I’d recommend aliasing 1, 2, 3 to `Point`, `LineString`, and `Polyline`, respectively, when setting a layer’s predicate (but always producing the strings when getting a predicate). Otherwise, I think we should chalk the current behavior up to buggy behavior that isn’t worth preserving.

**Comment by jfirebaugh** [comment]
Feel free to push SDK changes to this PR.

@ivovandongen, can you comment on whether the Android SDK has a similar issue to #7552 and how this change would affect it?

**Comment by 1ec5** [comment]
The style validator allows the `has` and `!has` operators with `$type`, right?

**Comment by ivovandongen** [comment]
@jfirebaugh The `$type` filter works correctly with string values on this branch, thanks. There is no accessor yet on Android, added https://github.com/mapbox/mapbox-gl-native/issues/7978 for this.

**Comment by 1ec5** [comment]
@ivovandongen, so if you set `eq("$type", "Point")` on Android, will you get a `TypeEqualsFilter` under the hood? Or will mbgl be smart enough to convert it from an `EqualsFilter` to a `TypeEqualsFilter` even when specified via runtime styling?

**Comment by jfirebaugh** [comment]
> The style validator allows the `has` and `!has` operators with `$id`, right?

The validator allows them but they don't work as expected: https://github.com/mapbox/mapbox-gl-js/issues/4235.

**Comment by 1ec5** [comment]
b7fa2c0cf54f25249c1d24eb0df59c3a265536ec takes care of the changes needed for iOS and macOS.

**Comment by jfirebaugh** [comment]
Updated with `["has"/"!has", "$id"]` support.

**Comment by 1ec5** [comment]
8efe3b97102d753ca4c6015c4071c99ab88193b7 also takes care of `$id = nil` and `$id != nil` on iOS and macOS and adds more unit tests.

**Comment by 1ec5** [comment]
```
failed regressions mapbox-gl-js#4235
```

**Comment by boundsj** [comment]
The iOS and macOS changes look good to me.

**Comment by 1ec5** [comment]
Thanks! I think all that’s left is:

* [ ] Core regression test failure: https://github.com/mapbox/mapbox-gl-native/pull/7971#issuecomment-278760879 @jfirebaugh
* [ ] Does the `eq()` syntax produce the expected results on Android? https://github.com/mapbox/mapbox-gl-native/pull/7971#issuecomment-278397228 @ivovandongen

**Comment by ivovandongen** [comment]
> Does the eq() syntax produce the expected results on Android

@1ec5 Yes (https://github.com/mapbox/mapbox-gl-native/pull/7971#issuecomment-278327256)

> ... Android, will you get a TypeEqualsFilter under the hood

Yes, we use the conversion templates for filter conversion (and the rest of the style conversions) which will produce the `TypeEqualsFilter` in this case [here](https://github.com/mapbox/mapbox-gl-native/blob/master/include/mbgl/style/conversion/filter.hpp#L137).

Thanks for the heads up.

**Pull request merged**
