### PR TITLE
Return none for invalid colors

### LINKED ISSUE #8075: [core] Return NONE for invalid color strings in `Color::parse()`
[Color::parse](https://github.com/mapbox/mapbox-gl-native/blob/master/src/mbgl/util/color.cpp#L9) (via [CSSColorParser::parse()](https://github.com/mapbox/mapbox-gl-native/blob/master/src/csscolorparser/csscolorparser.cpp#L226)) defaults to black for invalid / unparseable color strings.  This prevents us from correctly evaluating property functions for color values in the case where the property value is an invalid color string -- see https://github.com/mapbox/mapbox-gl-js/issues/4150

### PR DESCRIPTION
**Pull request by ivovandongen**
Fixes #8075

### CODE REVIEW

**Comment by jfirebaugh** [comment]
Changes look good. Check that https://github.com/mapbox/mapbox-gl-js/blob/abdd41a90f8d9f6985bcadf0d363d84149f6fa47/test/integration/render-tests/regressions/mapbox-gl-js%234150/style.json#L8-L8 now passes, and remove the ignore.

@kkaefer Are you ok with changing this copy or do you want to update https://github.com/mapbox/css-color-parser-cpp, publish to mason, and remove the vendored copy here?

**Comment by kkaefer** [comment]
I'm not planning to release this on Mason since we'd have to do releases for multiple C++ ABIs. Instead, I'll update https://github.com/mapbox/css-color-parser-cpp and we'll continue to use the copy.

**Comment by ivovandongen** [comment]
Tests succeeds now, enabled in https://github.com/mapbox/mapbox-gl-js/pull/4538. Needs review/merge and then update this pr with the commit hash.

**Comment by ivovandongen** [comment]
Tests merged and pr updated. @anandthakker care to review?

**Comment by kkaefer** [comment]
Added in https://github.com/mapbox/css-color-parser-cpp/commit/4262ac80ae0919f81b5a2504bb6596114a5db618, and also found this bug: https://github.com/mapbox/css-color-parser-cpp/commit/4262ac80ae0919f81b5a2504bb6596114a5db618#diff-6f54320f4777f289e3bf3d6bfe95c9c8L44

Can you please update from the source?

**Comment by ivovandongen** [comment]
Oopsy... Time for a spell check plugin in vi. Fixed

**Pull request merged**
