### PR TITLE
Add Mapbox Jazzy theme

### PR DESCRIPTION
**Pull request by friedbunny**
Based on Jazzy's [`fullwidth` theme](https://github.com/realm/jazzy/tree/master/lib/jazzy/themes/fullwidth).

### To-do

This is a good start, but there are more improvements to be made:
- [x] Truncate long method names in the nav and lists, when necessary.
- [x] Update the screenshot triptych with new shots and frames.
- [x] Bring in Open Sans as the font, like Mapbox.com.
- [x] Hide empty/broken “Other Type Definitions” section. https://github.com/mapbox/mapbox-gl-native/issues/3957
- [x] Report broken Swift method parsing upstream. https://github.com/realm/jazzy/issues/536
- [x] Force minimum navigation bar width (Chrome is misbehaving).
- [x] Better wrap~~/truncate~~ long methods on class pages.
- [x] Add theme to macOS jazzy docs, too.

### Going forward
Jazzy allows for arbitrary prose sections written in Markdown that include the same code highlighting, so we could even consider moving the examples or guides into here, too. This could be a good opportunity to write specific feature sections that focus on complex features such as offline or annotations.

## Main page
mapbox ios sdk reference 20160622
_[First draft.](https://cloud.githubusercontent.com/assets/1198851/15951188/184ad082-2e6b-11e6-8459-53a3b5861df5.jpg)_

## `MGLMapView`
mglmapview class reference 20160622
_[First draft.](https://cloud.githubusercontent.com/assets/1198851/15951225/5d0bb132-2e6b-11e6-896c-00734413d609.jpg)_

/cc @danswick @1ec5 @cammace @boundsj @frederoni

### CODE REVIEW

**Comment by 1ec5** [comment]
> Hide empty/broken “Other Type Definitions” section.

#3957

**Comment by 1ec5** [comment]
> Jazzy allows for arbitrary prose sections written in Markdown that include the same code highlighting, so we could even consider moving the examples or guides into here, too.

That’s realm/jazzy#435, released just a few hours ago in jazzy 0.6.3 (upgrade now!). I’m strongly in favor of doing this, because it makes our examples that much more discoverable to Dash users. Also, it would allow us to eventually replace the entire /ios-sdk site with the jazzy documentation (with an online-specific readme, perhaps), streamlining navigation considerably.

**Comment by friedbunny** [comment]
Elided extra-long navigation items, though I believe @1ec5 disapproves of my methods. 😁

screen shot 2016-06-10 at 2 57 28 pm

**Comment by friedbunny** [comment]
https://github.com/realm/jazzy/commit/f70493df5d99933637b7edc656151d8fc34a0f9f may fix #3957.

**Comment by friedbunny** [comment]
Going to give this Jazzy theme another look after evaluating the [new Apple documentation style](https://developer.apple.com/reference/messages), see if there’s anything to borrow.

**Comment by friedbunny** [comment]
SourceKit is the cause of `UnsafeMutablePointer` swallowing the rest of the method signature, per https://github.com/realm/jazzy/issues/536. No up-upstream issue exists yet.

This is where the problem manifests for us: when we use a pointer to a struct, such as [`-[MGLMapView setVisibleCoordinates:count:edgePadding:animated:]`](https://www.mapbox.com/ios-sdk/api/3.2.3/Classes/MGLMapView.html#/c:objc(cs)MGLMapView(im)setVisibleCoordinates:count:edgePadding:animated:) with `CLLocationCoordinate2D`:

```objc
- (void)setVisibleCoordinates:(CLLocationCoordinate2D *)coordinates count:(NSUInteger)count edgePadding:(UIEdgeInsets)insets animated:(BOOL)animated;
```

**Comment by friedbunny** [comment]
Made this more Mapboxy by using Open Sans for the text — screencaps have been updated.

**Comment by friedbunny** [comment]
Rebased and squashed this down to the essential commits. The iOS screenshot is still a placeholder, pending me actually coming up with something that decently illustrates polylines.

Also added macOS support:

screen shot 2016-06-28 at 4 24 22 pm

_... had to fake a `macos` tag in order for it to build._

**Comment by cammace** [comment]
Wow this looks great @friedbunny, can't wait to see it live!

**Comment by 1ec5** [comment]
Don’t forget to note the new design in the changelog for both SDKs!

**Comment by friedbunny** [comment]
screen shot 2016-07-01 at 5 52 55 pm

**Comment by friedbunny** [comment]
For anyone wanting to update the iOS screenshots, there’s a new Sketch file at [`platform/ios/originals/screenshots.sketch`](https://github.com/mapbox/mapbox-gl-native/tree/388fdd2ff7bfc652d0bd40a614a31e6a235e1328/platform/ios/originals) that includes the frame and images.

**Pull request merged**
