### PR TITLE
[android] Add a method to make map snapshots

### PR DESCRIPTION
**Pull request by vkurchatkin**
Fixes: https://github.com/mapbox/mapbox-gl-native/issues/3466

/cc @tobrun 

TODO list:

 - [ ] - add tests (need some guidance);
 - [x] - maybe move API to `MapboxMap` instead;
 - [ ] - docs.

### CODE REVIEW

**Comment by tobrun** [comment]
@vkurchatkin this is really awesome, will review soon!

**Comment by tobrun** [comment]
> maybe move the API to `MaboxMap` instead

I haven't reviewed the code or compiled the PR, but here already some feedback:

This would improve our parity with [Google](https://developers.google.com/android/reference/com/google/android/gms/maps/GoogleMap#public-methods) so having that in MapboxMap would make more sense.

> add support for reusing a bitmap

Google maps supports 2 methods for taking a snapshot:
 - public final void snapshot (GoogleMap.SnapshotReadyCallback callback)
 - public final void snapshot (GoogleMap.SnapshotReadyCallback callback, Bitmap bitmap)

Ideally we also support both where the latter can reuse bitmaps for performance reasons.

> add tests (need some guidance);

Hit me up with any questions you have on this. Related to this feature, it will be hard to write proper unit tests for this but we should be able to come up with some integration/ui tests.

**Comment by vkurchatkin** [comment]
> Google maps supports 2 methods for taking a snapshot

Somehow missed it, makes sense

**Comment by tobrun** [comment]
I'm going to pull this in to our repo to run the CI tests, this will also allow me to rebase the commits.
Thanks again for the contribution!

**Comment by vkurchatkin** [comment]
@tobrun Thanks!

**Pull request closed without merging**
