### PR TITLE
Remove blocking on future in Thread constructor

### PR DESCRIPTION
**Pull request by jfirebaugh**
The `Thread` constructor has [this line](https://github.com/mapbox/mapbox-gl-native/blob/8112ac3371230d0d99733c4b71fb2fac3d610404/src/mbgl/util/thread.hpp#L109-L109), which blocks the launching thread until construction of the `Object` template parameter has completed on the launched thread. This is not necessary, and should be removed so as to avoid potentially blocking the main thread for an indeterminate amount of time.

It isn't necessary because there's no way that launching thread can access `object` directly. It can only ask the `Thread` to `invoke` methods, and execution of the invocation is guaranteed to happen, on the launched thread, only after `object` is constructed.

This was a factor in #4501.

### CODE REVIEW

**Comment by jfirebaugh** [comment]
Turns out the `running` promise/future _is_ necessary, because the launching thread needs to at least wait for the launched thread's `RunLoop` to be constructed, and `RunLoop` doesn't currently support cross-thread ownership transfer. But fulfillment of the promise can happen before constructing `Object`.

cc @tmpsantos

**Comment by tmpsantos** [comment]
:+1: 

> doesn't currently support cross-thread ownership transfer.

This is probably not worth doing because some main loops implementations backing the `RunLoop` make assumptions of which thread they get initialized.

**Comment by jfirebaugh** [comment]
Never got this to pass tests. Abandoning.

**Comment by jfirebaugh** [comment]
Never got this to pass tests. Abandoning.

**Pull request closed without merging**
