### PR TITLE
Color class

### PR DESCRIPTION
**Pull request by yhahn**
Per https://github.com/mapbox/mapbox-gl-native/pull/5334#discussion_r66891882.

### CODE REVIEW

**Comment by brunoabinader** [comment]
LGTM 👍

**Comment by yhahn** [comment]
@jfirebaugh want to give this a quick :eyes: when you have the chance?

**Comment by jfirebaugh** [comment]
👌

**Comment by friedbunny** [comment]
@yhahn Total nit unrelated to your code, but we’ve been adding platform prefix(es) to commits — makes the enormous monorepo a tiny bit easier to navigate. In this case, the prefix would have been `[core]`.

> Prefix your commit messages with the platform(s) your changes affect: `[core]`, `[android]`, `[ios]`, `[macos]`, `[node]`, or `[qt]`.

**Pull request merged**
