### PR TITLE
Android SDK renaming

### PR DESCRIPTION
**Pull request by langsmith**
This pr renames Android content that needs to be renamed, to `Mapbox Maps SDK for Android` . 

This is a part of https://github.com/mapbox/mapbox-gl-native/issues/10385, which is the effort to rename various Mapbox Maps SDKs.

### CODE REVIEW

**Comment by langsmith** [comment]
@tobrun & @zugaldia , I believe this pr is good to go. It adjusts everything in this repo that I think is worth adjusting. Two things to be aware of:

1. I didn't change mentions of the `Android SDK` in the javadocs of various classes within the SDK. Figured that it was self-explanatory and that we didn't need naming continuity down to that deep of a level.

2. Should [the `attribution title` string resource](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDK/src/main/res/values/strings.xml#L7) be adjusted? 🤔   As of this writing, I've haven't pushed the change to this pr.  Here's what the attribution dialog looks like with the longer title 👇

device-2017-11-30-142810

**Comment by 1ec5** [comment]
> I didn't change mentions of the `Android SDK` in the javadocs of various classes within the SDK. Figured that it was self-explanatory and that we didn't need naming continuity down to that deep of a level.

Can we refer to it as “the Android map SDK” in that case, to avoid confusion with the Android navigation SDK?

**Comment by zugaldia** [comment]
> Can we refer to it as “the Android map SDK” in that case,

Wouldn't it be “the Android maps SDK”?

> Should the attribution title string resource be adjusted?

I vote adjusting it to the new longer name ("Mapbox Maps SDK for Android").

**Comment by 1ec5** [comment]
>> Can we refer to it as “the Android map SDK” in that case,
> 
> Wouldn't it be “the Android maps SDK”?

Ugh, yeah, I keep forgetting we long ago standardized on excessive pluralization around here. 😉 Maps SDK it is.

**Comment by langsmith** [comment]
Ok, so green javadocs will have `Android Maps SDK` and attribution title will be `Mapbox Maps SDK for Android`

**Comment by langsmith** [comment]
good to go here @zugaldia

**Pull request merged**
