### PR TITLE
Refactor MapView code to be more maintainable. Implement JavaDocs up to rotation.

### PR DESCRIPTION
**Pull request by ljbade**
This is the first of several MapView JavaDoc commits for #2002

### CODE REVIEW

**Comment by ljbade** [comment]
I'm going to keep the branch alive

**Comment by bleege** [comment]
@ljbade Can you clarify why moving the Annotation classes to the `views` package was necessary?

**Comment by ljbade** [comment]
@bleege This was so some public functions in MapView that are only mean for internal use by InfoWindow could be made package private.

**Comment by bleege** [comment]
@ljbade Ah... thanks for the background info.  That said, it still seems to make more sense to have all the Annotations stuff in one package.  I could see a developer using the SDK being confused as to why things were split up.  I also know that MapView and Annotations have a tight working relationship but keeping them separate has the additional benefit of helping us build stronger APIs and codebase.

**Comment by ljbade** [comment]
@bleege In https://github.com/mapbox/mapbox-gl-native/issues/2538 I am proposing merging the annotations and views packages, perhaps just putting them under the base package. Google Maps API seems to happily keep everything in one package.

**Comment by ljbade** [comment]
Actually I figure out how to fix this properly, top offset pixels should be a member of Marker that we pass in addMarker.

**Pull request merged**
