### PR TITLE
expose annotation styling

### LINKED ISSUE #1734: expose more style properties for annotations
Shape annotations need to support more features in the exposed API. 

Definite: 

- line join
- line cap
- line dash

Maybe: 

- line/fill image
- translate (for putting lines next to roads? e.g. multiple transit line colors)
- antialias off? 

@friedbunny

### PR DESCRIPTION
**Pull request by incanus**
Fixes #1734 and allows a workaround for https://github.com/mapbox/mapbox-gl-native/issues/1814 by exposing the full set of line & fill layout and paint properties to map clients. 

Todo: 

- [ ] Safely query what's set in the passed style (i.e. no `.at()` directly). 
- [ ] Render more values. 
- [ ] Set sane defaults in core for the properties (not necessarily the same as the defaults in `LineProperties`/`FillProperties`; for example, shapes shouldn't be black or default to miter line join). 
- [ ] Test dead code removal from https://github.com/mapbox/mapbox-gl-native/commit/174fb6be7c07d9a177dda05fe8d6738526f86239. 
- [ ] Find a better way to determine fill/line distinction now that the use of the `StyleProperties` variant is gone (i.e. not [this](https://github.com/mapbox/mapbox-gl-native/blob/1734-expose-annotation-styling/src/mbgl/map/map_context.cpp#L169)).

### CODE REVIEW

**Comment by jfirebaugh** [comment]
Is there a dependency chain pulling in `class_properties.hpp` and `property_transition.hpp`? Those looks like they might be unnecessary. I'm ok with the other includes being "semi-public", in that they are used by iOS but not considered part of the public core GL. These interfaces will probably change a lot with mutable style API and data driven styles.

**Comment by jfirebaugh** [comment]
@incanus What's the status of this PR?

**Comment by jfirebaugh** [comment]
Going in the direction of #837 instead.

**Comment by incanus** [comment]
:+1:

**Pull request closed without merging**
