### PR TITLE
fixes #5238: Android marker view z-ordering

### LINKED ISSUE #5238: Add View Annotations Z ordering
We have been hearing about the need to be able to order Markers. For View based Markers an end developer should be able to indicate to a marker to be placed on top of another marker.  This system must integrate with other already shown View elements as CompasView, MyLocationView etc. This could be made part or based on current implementation of MarkerViewAdapter, as a separate ViewOverlay implementation or exposed in Marker itself.

This should solve the issues we have been seeing related to overlapping views.
This issue doesn't cover z-ordering or layering from core in https://github.com/mapbox/mapbox-gl-native/issues/991

### PR DESCRIPTION
**Pull request by incanus**
First phase of #5238, allowing addition of marker views meant to always be above another, named marker view. 

I'll squash etc. once this looks good to go. 

@tobrun @zugaldia

### CODE REVIEW

**Comment by incanus** [comment]
Something that occurred to me here is my relative inexperience with memory management in Java, so I would welcome thoughts on any sort of issues with `aboveMarkerView` references as a result of this.

**Comment by tobrun** [comment]
@incanus this is great! just one remark is that the builder creating the MarkerView must comply to the Parceable interface. The Parceable interface is used to restore the builder and its variables after a configuration change (eg. orientation change). At this point the MarkerView itself does not implement the Parceable interface and we won't be able to recreate this interaction correctly (the set MarkerView will be null). 

There are a couple of ways to workaround this:
 - expose the functionality only on MarkerView (it's the user responsibility to restore correctly)
 - expose a method on `MarkerViewManager` that takes in 2 MarkerViews
 - only save the id of the MarkerView and lookup the concrete MarkerView when needed through MarkerViewManager

**Comment by incanus** [comment]
> only save the id of the MarkerView and lookup the concrete MarkerView when needed through MarkerViewManager

I'm not used to objects having this, what sounds like a global id, that can be used. I'll look into this.

**Comment by tobrun** [comment]
> only save the id of the MarkerView and lookup the concrete MarkerView when needed through MarkerViewManager

Now thinking of this, this won't be an option since the id will only be available after we have added the marker to the map (this id would be equal to the core gl marker id).

**Comment by incanus** [comment]
Backing this up a moment @tobrun, I am seeing things ordered ok after device orientation change. Is this truly a problem?

**Comment by incanus** [comment]
@tobrun and I voiced on this at length yesterday and worked through some consideration of both an API design like I've proposed as well as a callback-based sort comparator. The short is that it probably makes sense to skip right to the comparator as fetching it from a callback is a lesser consideration on performance than the actual sorting. Additionally, we could add `Parcelable` to `Marker` in order to make the proposed solution work, but the API is still limiting in referring to only one other marker, when marker add order needs to remain flexible. 

I will start on this soon, but it's not as high priority right now.

**Comment by incanus** [comment]
Closing this PR per https://github.com/mapbox/mapbox-gl-native/pull/5862#issuecomment-239164783 since we're go the comparator route instead.

**Pull request closed without merging**
