### PR TITLE
functions for everything

### PR DESCRIPTION
**Pull request by ansis**
Implements:
- transitioned functions for patterns and dasharrays
- functions for all paint and all layout properties
- switches array properties like fill-translate from arrays of functions to functions of arrays (https://github.com/mapbox/mapbox-gl-style-spec/issues/237)
- separates raster-brightness into two properties

js version: https://github.com/mapbox/mapbox-gl-js/pull/976
style migration prs: https://github.com/mapbox/mapbox-gl-js/pull/976#issuecomment-73110776

### CODE REVIEW

**Comment by kkaefer** [comment]
Great! Can we have some tests here?

**Comment by ansis** [comment]
Added a test for successfully parsing string, enum, bool functions in 177f441. Is that enough?

**Comment by jfirebaugh** [comment]
A few warnings from the test suite:

```
- ["INFO", "General", "test fixture line-dasharray"]
- ["WARNING", "ParseStyle", "dasharray value must be an array of numbers"]
- ["WARNING", "ParseStyle", "dasharray value must be an array of numbers"]
- ["WARNING", "ParseStyle", "dasharray value must be an array of numbers"]
- ["WARNING", "ParseStyle", "dasharray value must be an array of numbers"]
- ["WARNING", "ParseStyle", "dasharray value must be an array of numbers"]
```

And a few unexpected failures:

* background-image (no image is rendered)
* fill-image (same)
* line-dasharray (rendering differences -- maybe not a regression)
* linear-filter-opacity-edge/literal (not sure if regression)
* raster-brightness
* text-rotate/function (not sure if regression)

**Comment by ansis** [comment]
Dasharray warnings and raster-brightness are fixed.

- The fill-image and background-image failures are also present in master. https://github.com/mapbox/mapbox-gl-native/issues/835
- Same with text-rotate/function and linear-filter-opacity-edge/literal
- line-dasharray/literal difference is also in master. It looks nearly identical visually so it might just be a tolerance issue.

**Pull request merged**
