### PR TITLE
[ios]Fix an issue where annotation view not fully cleanup before enqueue

### PR DESCRIPTION
**Pull request by lloydsheng**
Just a copy of PR https://github.com/mapbox/mapbox-gl-native/pull/11366

### CODE REVIEW

**Comment by friedbunny** [comment]
Like @julianrex mentioned in https://github.com/mapbox/mapbox-gl-native/pull/11366#issuecomment-371917685, we should quantify the performance impact of this change. As it stands, the performance of view annotations is only borderline acceptable and we should be careful not to regress if we don’t have to.

**Comment by lloydsheng** [comment]
@friedbunny Thank you for your reminding.

@1ec5  @julianrex I'd like to listen to your ideas about view annotations performance test. How did we do this test in the past, any related document?

**Comment by julianrex** [comment]
@lloydsheng I was chatting with @friedbunny about this, and we think some kind of reproducible test could be added to `iosapp` (or should it be in `bench` @friedbunny ?). 

For example, the camera could fly on a path (circle?) through a number of annotations, with a set number of laps. This would allow annotations to move on and off-screen. We could then analyze the performance in Instruments.

**Comment by lloydsheng** [comment]
I performed the annotation views profiling with Instrument.
## Sample code
Add 200 annotation views in the mapview after it finished rendering. here is the code:
https://gist.github.com/lloydsheng/63be39a2c5b560668458afcdd52a4cab

## Manual Steps
## Pan
manual_steps
## Zoom
ezgif-4-d617ac496a

## Performace result

### Pan
|  | release-boba  | llooyd |
 | -------------  | ------------- | ------------- |
|  Chart |  image |  image |
|  Details | [boba.trace.zip](https://github.com/mapbox/mapbox-gl-native/files/1832678/boba.trace.zip) |  [llooyd.trace.zip](https://github.com/mapbox/mapbox-gl-native/files/1832677/llooyd.trace.zip) |

### Zoom
|  | release-boba  | llooyd |
 | -------------  | ------------- | ------------- |
|  Chart | image  |  image |
|  Details |  [zoom_boba.trace.zip](https://github.com/mapbox/mapbox-gl-native/files/1832918/zoom_boba.trace.zip) | [zoom_llooyd.trace.zip](https://github.com/mapbox/mapbox-gl-native/files/1832919/zoom_llooyd.trace.zip) |  

## Conclusion
As you can see, It seems the FPS almost hasn't been impacted after the change. can we accept the change?
Please tell me your thoughts about this performance test. @1ec5 @julianrex @friedbunny

**Comment by friedbunny** [comment]
> why is dwarf-with-dsym not the default for Debug?

To improve Debug build times, AFAIK — check out https://github.com/mapbox/mapbox-gl-native/pull/6529 for background.

**Comment by lloydsheng** [comment]
@julianrex @friedbunny thank you, these comments really helped a lot,I will improve the test and post the update result.

**Comment by lloydsheng** [comment]
I've improved the performance test:

- Increase annotation views' count to 1000
- Build and run performance with `Release` configuration.
- Programmatically control mapview's camera
- Find my long time no use iPhone SE and use it for testing

Here is the PFS table data (because of [ Instrument can't exporting the table directly](https://forums.developer.apple.com/thread/51680), I had to take a screenshoot and recognize numbers with OCR tools 😂)

| # Second | Llooyd | Release-boba |
-- | -- | --
1 | 1 | 26
2 | 38 | 32
3 | 41 | 42
4 | 38 | 45
5 | 41 | 40
6 | 43 | 40
7 | 41 | 40
8 | 41 | 42
9 | 40 | 43
10 | 41 | 41
11 | 42 | 40
12 | 40 | 39
13 | 39 | 41
14 | 39 | 42
15 | 42 | 42
16 | 41 | 38
17 | 40 | 41
18 | 39 | 40
19 | 42 | 42
20 | 41 | 41
21 | 40 | 38
22 | 39 | 40
23 | 41 | 40
24 | 42 | 41
25 | 40 | 38
26 | 39 | 39
27 | 41 | 42
28 | 41 | 40
29 | 40 | 41
30 | 39 | 39
31 | 41 | 40
32 | 41 | 42
33 | 40 | 41
34 | 39 | 38
35 | 41 | 40
36 | 41 | 42
37 | 40 | 40
38 | 39 | 39
39 | 41 | 41
40 | 40 | 41
41 | 40 | 41
42 | 40 | 40
43 | 39 | 38
44 | 40 | 40
45 | 40 | 41
46 | 41 | 41
47 | 40 | 40
48 | 38 | 38
49 | 40 | 38
50 | 40 | 41
51 | 41 | 42
52 | 40 | 40
53 | 38 | 37
54 | 40 | 40
55 | 39 | 42
56 | 41 | 40
57 | 41 | 38
58 | 37 | 40
59 | 40 | 42
60 | 41 | 41
61 | 41 | 40
62 | 38 | 38
63 | 38 | 38
64 | 40 | 42
65 | 41 | 41
66 | 40 | 40
67 | 38 | 38
68 | 41 | 40
69 | 42 | 41
70 | 41 | 41
71 | 38 | 38
72 | 40 | 39
73 | 41 | 40
74 | 41 | 41
75 | 41 | 40
76 | 37 | 39
77 | 40 | 41
78 | 41 | 41
79 | 41 | 40
80 | 40 | 37
81 | 37 | 40
82 | 37 | 40
83 | 40 | 40
84 | 41 | 40
85 | 40 | 40
86 | 38 | 39
87 | 38 | 41
88 | 41 | 40
89 | 40 | 40
90 | 40 | 40
91 | 40 | 39
92 | 38 | 39
93 | 41 | 40
94 | 41 | 41
95 | 40 | 39
96 | 39 | 38
97 | 40 | 39
98 | 40 | 41
99 | 40 | 40
100 | 39 | 40
101 | 40 | 38
102 | 40 | 40
103 | 40 | 41
104 | 40 | 41
105 | 40 | 40
106 | 41 | 39
107 | 40 | 39
108 | 39 | 41
109 | 42 | 40
110 | 40 | 39
111 | 41 | 38
112 | 37 | 40
113 | 40 | 40
114 | 40 | 40
115 | 40 | 40
116 | 41 | 40
117 | 40 | 40
118 | 39 | 41
119 | 40 | 39
Average (3 - 118) | 40.02 | 40.08
  |   | 0.15%

Test code:
https://gist.github.com/lloydsheng/63be39a2c5b560668458afcdd52a4cab
Test Data:
https://gist.github.com/lloydsheng/aa1ef548c79bf8a2096cd01a58068f56
Trace detail:
[llooyd(2m).trace.zip](https://github.com/mapbox/mapbox-gl-native/files/1855667/llooyd.2m.trace.zip)
[release-boba(2m).trace.zip](https://github.com/mapbox/mapbox-gl-native/files/1855668/release-boba.2m.trace.zip)

The release-boba's build average FPS is about 0.15% greater than the llooyd's build.
@friedbunny @julianrex What's your thoughts about the result? Is this an acceptable result? Feel free to tell me if there are anything mistakes.

**Comment by julianrex** [comment]
Thanks for pulling this together @lloydsheng and apologies for the delay in responding. Is this PR blocking you?

I pulled down your sample test and profiled on an iPhone 6+. To me - it appears to be ever so slightly slower (matching your result). This might be down to the nature of the test (which in this case makes some sense as `-addSubview:` and `-removeFromSuperview` are repeatedly called). 

However, personally I would like to see the `UIView`s being cleaned up correctly.

So, a few thoughts (from discussion with @friedbunny):

- How important is it to get this into `boba`? I vote we don't delay the release
- If we need to get it in, is it possible to restrict to just adding `[self.annotationContainerView.annotationViews removeObject:annotationView];`?
- Let's spend some time evaluating how we manage the lifetimes of our annotation views.
- Get some real timing measurements in the code to help us make our decisions - it's very hard to get this info out of Instruments.
- Can we make use of some of the existing examples to get more real-world use cases? Maybe the world tour might be a good start?

These last 3 will need some discussion and their own tickets. 🙂

**Comment by lloydsheng** [comment]
@julianrex Thanks for your comments.
> Is this PR blocking you?

No, This issue just caused a potential crash. Currently only one customer report this type of crash. I also vote we don't delay the release.

I'm agree with you that give a fully assessment to this change before it take affected. about the last 3 item. where should i create those issues? I don't quite know what to do next step.

**Pull request closed without merging**
