### PR TITLE
[node] Do not throw if raster image does not load

### PR DESCRIPTION
**Pull request by bsudekum**
Currently, if a vector tile does not load, we still render the map. This is not true for raster tiles; if a raster tile does not load, we throw an error.

For example, imagine a map that has imagery for a given city. When the user is zoomed in on the city and the tiles are in view, all is well. The moment they pan out side the imagery limits, tiles begin to `404` (as intended) but we should still render the given map.

This change allows raster tiles which `404` to pass by.

/cc @jfirebaugh @mikemorris

### CODE REVIEW

**Comment by jfirebaugh** [comment]
This doesn't look the correct fix. We need to distinguish "no data" from "bad data" (== `*image` is false). Also this change removes error checking for `bucket->setImage()`.

**Comment by mikemorris** [comment]
Possibly refs https://github.com/mapbox/mapbox-gl-native/issues/1837#issuecomment-121212673?

/cc @tmpsantos

**Comment by jfirebaugh** [comment]
> Currently, if a vector tile does not load, we still render the map.

@bsudekum Are you sure this is true? It looks to me like a vector tile 404 will produce the same behavior as a raster tile 404.

**Comment by bsudekum** [comment]
> It looks to me like a vector tile 404 will produce the same behavior as a raster tile 404.

@jfirebaugh No, if a raster tile 404's the the process fails with `error parsing raster image` (https://github.com/mapbox/mapbox-gl-native/blob/bc92c2de3988a39d6def34617ade4afb5b82e214/src/mbgl/util/worker.cpp#L22). This is not the case with a vector tile.

Looking at how this is handled in vector land:

```c++
void parseVectorTile(TileWorker* worker, std::string data, std::function<void (TileParseResult)> callback) {
    try {
        pbf tilePBF(reinterpret_cast<const unsigned char *>(data.data()), data.size());
        callback(worker->parse(VectorTile(tilePBF)));
    } catch (const std::exception& ex) {
        callback(TileParseResult(ex.what()));
    }
}
```

Changing the `pbf` function call to have a `data.size()` of 0, the map still renders but there is no vector layer:
`pbf tilePBF(reinterpret_cast<const unsigned char *>(data.data()), 0);`

This makes me think that the `pbf` can accept a empty data input. This is currently not the case with raster however. An image is created from a raster tile that 404's, causing `!image` to be true. 

```c++
std::unique_ptr<util::Image> image(new util::Image(data));
if (!(*image)) {
    callback(TileParseResult("error parsing raster image"));
}
```

**Comment by jfirebaugh** [comment]
Yeah, you are right. I think this happens mostly by accident -- I don't think we were counting on `pbf` accepting an empty input (and we probably shouldn't).

I want to take a deeper look at this today and make 404 handling more consistent between vector and raster, node and other platforms, and unblock a clean fix for #1724.

**Comment by bsudekum** [comment]
Closing, working on this https://github.com/mapbox/mapbox-gl-native/pull/2458

**Pull request closed without merging**
