### PR TITLE
Add simple non-semantic version support to build script

### PR DESCRIPTION
**Pull request by friedbunny**
With version string ` ios-beta-preview-sirius-1.0v2` I was getting the following Xcode build error:

```
Traceback (most recent call last):
  File "/Users/jason/Documents/Mapbox/mapbox-gl-native/scripts/build-version.py", line 56, in <module>
    patch = tag[2],
IndexError: list index out of range
Command /bin/sh failed with exit code 1
```

My fixes would result in version `1.0.2` in this case, which is wrongish but builds.

### CODE REVIEW

**Comment by 1ec5** [comment]
I think the use of a “v” here was an oversight, and the x.y.z format is probably the only one we need for the time being. But maybe this change will be useful if we ever decide to have things like 1.2.3b7.

**Comment by incanus** [comment]
Yeah, I was just trying to stay similar to an internal project tag. Let's leave this open and take a peek when some dust settles. Thanks @friedbunny!

**Comment by friedbunny** [comment]
Hah, the tag renaming had me confused — I didn't see a `ios-beta-preview-sirius-1.0v2` tag in git but I couldn't get my copy to build. Eventually did a tactical-nuking of my local repo. :boom:

**Comment by jfirebaugh** [comment]
We're going to stick with x.y.z version numbers, so this shouldn't be necessary.

**Pull request closed without merging**
