### PR TITLE
Remove support v7

### PR DESCRIPTION
**Pull request by Chaoba**
Remove support v7 library. Tested on Redmi2(Android 4.4), no issue found for compassView and attribution.

### CODE REVIEW

**Comment by tobrun** [comment]
This PR results in: 
```
releaseRuntimeClasspath - Runtime classpath of compilation 'release' (target  (androidJvm)).
+--- com.mapbox.mapboxsdk:mapbox-android-telemetry:4.3.0
|    +--- com.squareup.okhttp3:okhttp:3.10.0 -> 3.12.0
|    |    \--- com.squareup.okio:okio:1.15.0
|    +--- com.google.code.gson:gson:2.8.2 -> 2.8.5
|    +--- com.android.support:support-annotations:27.1.1
|    +--- com.mapbox.mapboxsdk:mapbox-android-core:1.2.0
|    \--- com.android.support:support-core-utils:27.1.1
|         +--- com.android.support:support-annotations:27.1.1
|         \--- com.android.support:support-compat:27.1.1
|              +--- com.android.support:support-annotations:27.1.1
|              \--- android.arch.lifecycle:runtime:1.1.0
|                   +--- android.arch.lifecycle:common:1.1.0
|                   \--- android.arch.core:common:1.1.0
+--- com.mapbox.mapboxsdk:mapbox-sdk-geojson:4.3.0
|    \--- com.google.code.gson:gson:2.8.5
+--- com.mapbox.mapboxsdk:mapbox-android-gestures:0.4.0
|    \--- com.android.support:support-compat:27.1.1 (*)
+--- com.mapbox.mapboxsdk:mapbox-sdk-turf:4.3.0
|    +--- com.mapbox.mapboxsdk:mapbox-sdk-core:4.3.0
|    |    +--- com.google.code.gson:gson:2.8.5
|    |    +--- com.squareup.retrofit2:retrofit:2.4.0
|    |    |    \--- com.squareup.okhttp3:okhttp:3.10.0 -> 3.12.0 (*)
|    |    +--- com.squareup.retrofit2:converter-gson:2.4.0
|    |    |    +--- com.squareup.retrofit2:retrofit:2.4.0 (*)
|    |    |    \--- com.google.code.gson:gson:2.8.2 -> 2.8.5
|    |    \--- com.squareup.okhttp3:logging-interceptor:3.11.0
|    |         \--- com.squareup.okhttp3:okhttp:3.11.0 -> 3.12.0 (*)
|    \--- com.mapbox.mapboxsdk:mapbox-sdk-geojson:4.3.0 (*)
+--- com.android.support:support-annotations:27.1.1
+--- com.android.support:support-fragment:27.1.1
|    +--- com.android.support:support-compat:27.1.1 (*)
|    +--- com.android.support:support-core-ui:27.1.1
|    |    +--- com.android.support:support-annotations:27.1.1
|    |    +--- com.android.support:support-compat:27.1.1 (*)
|    |    \--- com.android.support:support-core-utils:27.1.1 (*)
|    +--- com.android.support:support-core-utils:27.1.1 (*)
|    +--- com.android.support:support-annotations:27.1.1
|    +--- android.arch.lifecycle:livedata-core:1.1.0
|    |    +--- android.arch.lifecycle:common:1.1.0
|    |    +--- android.arch.core:common:1.1.0
|    |    \--- android.arch.core:runtime:1.1.0
|    |         \--- android.arch.core:common:1.1.0
|    \--- android.arch.lifecycle:viewmodel:1.1.0
+--- com.squareup.okhttp3:okhttp:3.12.0 (*)
\--- com.getkeepsafe.relinker:relinker:1.3.1
```

**Comment by Chaoba** [comment]
@tobrun @LukasPaczos Thanks for your confirmation.

**Comment by friedbunny** [comment]
Please be sure to prefix commit messages with the platform(s) they change — e.g., `[android]`.

**Comment by Chaoba** [comment]
> @Chaoba Please be sure to prefix commit messages with the platform(s) they change — e.g., `[android]`.

@friedbunny Sorry for that, will do.

**Pull request merged**
