### PR TITLE
Convert point annotations to RTree instead of pre-creating tiles for all zoom levels

### PR DESCRIPTION
**Pull request by kkaefer**
depends on #1695

### CODE REVIEW

**Comment by kkaefer** [comment]
@incanus, is there any reason we're using integer IDs rather than wrapping a shared_ptr to track annotations for later removal?

**Comment by incanus** [comment]
> is there any reason we're using integer IDs rather than wrapping a shared_ptr to track annotations for later removal?

If annotation adds/removes are synchronous, why bother with the complexity? basically

See also how we map them Cocoa-side, which I suppose could be adapted to live pointers: 

https://github.com/mapbox/mapbox-gl-native/blob/cfee5aa8ef73b5bd2050bd68d584846192ebf0a2/platform/ios/MGLMapView.mm#L79

**Comment by kkaefer** [comment]
>  why bother with the complexity? basically

We need to maintain a separate mapping of ID to Annotation so we can remove the correct elements from the RTree.

**Comment by kkaefer** [comment]
@incanus can you review please?

**Comment by incanus** [comment]
We're not hitting this as part of b3.

**Comment by jfirebaugh** [comment]
⇢ #2673

**Pull request closed without merging**
