### PR TITLE
[core] Refcount the view activations

### LINKED ISSUE #5721: MapView: eglSwapBuffers Error
When chaining some operations on the MapView the map, applications [crash](https://github.com/mapbox/mapbox-gl-native/issues/5610#issuecomment-233123509) due to an error while rendering. Specifically:

```
07-16 11:25:32.255 7133-7133/com.mapbox.mapboxsdk.testapp E/libEGL: call to OpenGL ES API with no current context (logged once per thread)
07-16 11:25:32.258 7133-7133/com.mapbox.mapboxsdk.testapp D/mbgl: {unknown}[Android]: NativeMapView::notifyMapChange()
07-16 11:25:32.259 7133-7133/com.mapbox.mapboxsdk.testapp E/mbgl: {unknown}[OpenGL]: eglSwapBuffers() returned error 12301
07-16 11:25:32.259 7133-7133/com.mapbox.mapboxsdk.testapp D/AndroidRuntime: Shutting down VM
07-16 11:25:32.260 7133-7133/com.mapbox.mapboxsdk.testapp E/AndroidRuntime: FATAL EXCEPTION: main
                                                                            Process: com.mapbox.mapboxsdk.testapp, PID: 7133
                                                                            java.lang.Error: eglSwapBuffers() failed
                                                                                at com.mapbox.mapboxsdk.maps.NativeMapView.nativeRender(Native Method)
                                                                                at com.mapbox.mapboxsdk.maps.NativeMapView.render(NativeMapView.java:131)
                                                                                at com.mapbox.mapboxsdk.maps.MapView.onDraw(MapView.java:1302)
                                                                                at android.view.View.draw(View.java:16184)
                                                                                at android.view.View.updateDisplayListIfDirty(View.java:15180)
```

As @jfirebaugh [suggests](https://github.com/mapbox/mapbox-gl-native/issues/5610#issuecomment-233480297), it might be that the the MapView doesn't reactivate the GL Context properly. We need to check that the the context is deactivated and re-activated properly. Atm, it's easily re-produced by removing a layer within a camera animation finish callback.

It might be a good idea to isolate from issues like this by placing callbacks on the main looper. This ensures that the callbacks always happen on the main thread as well. A similar solution is also used on the QT bindings I believe (cc @tmpsantos).

cc @tobrun @zugaldia @bleege

### LINKED ISSUE #5836: Chained animations lead to StackOverFlowException
In creating an activity to reproduce the error in #5721 I ran into a situation where the test app crashes due to a StackOverflowException. The relevant code in question:

```
    private void animateToNextPosition(final int iterations) {
        //Setup the target camera position
        final CameraPosition cameraPosition = new CameraPosition.Builder()
                .target(getNextLatLng())
                .bearing(270)
                .tilt(20)
                .build();

        //Create a callback
        final MapboxMap.CancelableCallback callback = new MapboxMap.CancelableCallback() {
            @Override
            public void onCancel() {
                Log.i(TAG, String.format("Duration onCancel Callback called on Thread id: %s, name %s", Thread.currentThread().getId(), Thread.currentThread().getName()));
                //Toast.makeText(CameraAnimationChainingActivity.this, "Duration onCancel Callback called.", Toast.LENGTH_SHORT).show();
            }

            @Override
            public void onFinish() {
                Log.i(TAG, String.format("Duration onFinish Callback called on Thread id: %s, name %s", Thread.currentThread().getId(), Thread.currentThread().getName()));
                //Toast.makeText(CameraAnimationChainingActivity.this, "Duration onFinish Callback called.", Toast.LENGTH_SHORT).show();
                if (iterations > 0) {
                    animateToNextPosition(iterations - 1);
                }
            }
        };

        mapView.getMapAsync(new OnMapReadyCallback() {
            @Override
            public void onMapReady(MapboxMap mapboxMap) {
                mapboxMap.animateCamera(CameraUpdateFactory.newCameraPosition(cameraPosition), 7500, callback);
            }
        });
    }
```

Resulting in:

```
...
07-30 16:03:34.426  4707  4707 I CameraAnimationChainingActivity: Duration onFinish Callback called on Thread id: 1, name main
07-30 16:03:34.427  4707  4707 I CameraAnimationChainingActivity: Duration onFinish Callback called on Thread id: 1, name main
07-30 16:03:34.427  4707  4707 I CameraAnimationChainingActivity: Duration onFinish Callback called on Thread id: 1, name main
07-30 16:03:34.595  4707  4707 W art     : JNI WARNING: java.lang.StackOverflowError thrown while calling printStackTrace
07-30 16:03:34.625  4707  4707 W System.err: java.lang.StackOverflowError: stack size 8MB
```

The actual issue is caused when cancelTransitions() is called in [MapView#flyto()](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java#L1252), which eventually reaches [Transform::cancelTransition()](https://github.com/mapbox/mapbox-gl-native/blob/master/src/mbgl/map/transform.cpp#L638) in core where the previous `transitionFinishFn` is still set:

```
    if (transitionFinishFn) {
        transitionFinishFn();
    }

    transitionFrameFn = nullptr;
    transitionFinishFn = nullptr;
```

Might be solved by clearing the `transitionFn` and then calling it. A similar situation exists in [startTransition()](https://github.com/mapbox/mapbox-gl-native/blob/master/src/mbgl/map/transform.cpp#L602) which might instigate the loop.

Possibly related: #5833

cc @tmpsantos @zugaldia

### PR DESCRIPTION
**Pull request by tmpsantos**
Fixes #5836
Fixes #5721

### CODE REVIEW

**Comment by tmpsantos** [comment]
:eyes: @kkaefer @ivovandongen @mikemorris

**Comment by tmpsantos** [comment]
On android we still have to activate/deactivate the context because on some phones you have multiple contexts around.

But it is now "refcounted" so it supports nested invocations.

**Comment by tmpsantos** [comment]
Reducing the scope just for android, gonna be one week out and this could potentially have some unwanted side effects.

**Comment by kkaefer** [comment]
Why are you refcounting? Shouldn't it be something like "activate when not activated" and "deactivate when still active" and make all other operations no-ops? Rather than count the number of activations, is there a way to fix the underlying issue so that they aren't activated/deactivated in the first place?

**Comment by tmpsantos** [comment]
> Why are you refcounting? Shouldn't it be something like "activate when not activated" and "deactivate when still active" and make all other operations no-ops? Rather than count the number of activations, is there a way to fix the underlying issue so that they aren't activated/deactivated in the first place?

That would not work. The buggy code was:

```
Render
    Activate
        Signal (mapped to OnLoaded on Android)
            Client calls AddLayer
                Activate
                Do some GL
                Deactivate
    Do some more GL
    Deactivate
```

So the `Do some more GL` would have a deactivated context. Another way of fixing I tried was not calling activate/deactivate at all and assume the context is always valid inside mbgl-core. We would transfer this responsibility to client/platform. What do you think?

**Comment by kkaefer** [comment]
Well, we could only call Activate/Deactivate after AddLayer when the context is not active?

**Pull request merged**
