### PR TITLE
[WIP] [android] #3231 - tinting colors 

### LINKED ISSUE #3231: Add support for tinting UserLocationView and Attribution icon
iOS currently exposes a feature that allows tinting the UserLocationView and the Attribution Icon.

On Android we can support automatic tinting by using:
```xml
<resources>
  <!-- inherit from the material theme -->
  <style name="AppTheme" parent="android:Theme.Material">
    <!-- Main theme colors -->
    <!--   your app branding color for the app bar -->
    <item name="android:colorPrimary">@color/primary</item>
    <!--   darker variant for the status bar and contextual app bars -->
    <item name="android:colorPrimaryDark">@color/primary_dark</item>
    <!--   theme UI controls like checkboxes and text fields -->
    <item name="android:colorAccent">@color/accent</item>
  </style>
</resources>
```

cc @bleege @zugaldia

### PR DESCRIPTION
**Pull request by tobrun**
Closes #3231

### CODE REVIEW

**Comment by bleege** [comment]
@tobrun Is this still ready to be merged?

**Comment by tobrun** [comment]
@bleege yeah, this was a work in progress that was neglected a bit. The blocker here was related to UserLocationView and that should land with #4396. Picking up this PR is part of the ticket in #4396.

**Comment by bleege** [comment]
Thanks for clarifying @tobrun.  So if I understand correctly we need #4396 to land first and then we can merge this PR?

**Comment by tobrun** [comment]
@bleege this PR is from before MapboxMap refactor, better to pick this up in a separate branch/PR

**Comment by tobrun** [comment]
closes in favour of #4843

**Pull request closed without merging**
