### PR TITLE
Refactor constructors MapView

### PR DESCRIPTION
**Pull request by tobrun**
Constructor targeted at Lollipop and higher, 
Using defStyle and defStyleRes to obtain attributes, 
Android annotations for constructor arguments

### CODE REVIEW

**Comment by ljbade** [comment]
Hmm we decided to avoid `@TargetApi` in https://github.com/mapbox/mapbox-gl-native/issues/934

@tobrunvannuland Is it neccessary to support the new Lollipop constructor? What happens if you don't use `defStyle` and `defStyleRes`?

/cc @bleege

**Comment by bleege** [comment]
> Hmm we decided to avoid @TargetApi in #934

Agreed.  Unless there's a backport available that supports the entire supported API range (currently 15+) we want to avoid `@TargetAPI` as it inevitably leads to hidden API range incompatibilities.

**Comment by tobrun** [comment]
About the @TargetApi:
Sorry, I wasn't aware of that discussion and I completely agree with the decision made!

About Lollipop constructor:
The main gist behind it is that the users would have an extra way of customising the map.

From the Android docs:
> defStyleAttr An attribute in the current theme that contains a reference to a style resource that supplies defaults values for the StyledAttributes. Can be 0 to not look for defaults.

> defStyleRes A resource identifier of a style resource that supplies default values for the StyledAttributes, used only if defStyleAttr is 0 or can not be found in the theme. Can be 0 to not look for defaults.
 
I saw that another issue was created for the Android Annotations, so closing the PR

**Comment by bleege** [comment]
> Sorry, I wasn't aware of that discussion and I completely agree with the decision made!

@tobrun Not a problem at all!  This is a HUGE project with tons of tickets.  No one is (nor can be) aware of everything.  :-)

**Comment by ljbade** [comment]
@tobrun I find it useful to use GitHub's issue filter dropdowns to select only issues tagged with Android. Makes it a lot easier.

**Pull request closed without merging**
