### PR TITLE
Fix code generation

### PR DESCRIPTION
**Pull request by tobrun**
Closes https://github.com/mapbox/mapbox-gl-native/issues/10846.

This PR fixes up the generated code by:
 - removal of the automatic lamba refactor from https://github.com/mapbox/mapbox-gl-native/pull/10549
 - use US local during code generation https://github.com/mapbox/mapbox-gl-native/pull/10810

### CODE REVIEW

**Comment by LukasPaczos** [comment]
@tobrun can we add lambdas to `layer.junit.ejs` template, to keep them in the resulting code?

**Comment by tobrun** [comment]
I'm a bit on the fence about that. Mainly because of the time it would take vs the benefit. Getting this is in would result in a lot of trial/error while the only benefit would be readability. I don't feel the same rules of readability apply to generated code as it does with normal code. 

Above is very opinionated so happy to hear your thoughts on it, am I missing something here? 

If possible I would prefer the gameplan of ticketing out the lamba optimization and picking it up when we work on the template files themselves.

**Comment by LukasPaczos** [comment]
> If possible I would prefer the gameplan of ticketing out the lamba optimization and picking it up when we work on the template files themselves.

 It's mainly internal tests, so let's ticket them out and come back later.

**Comment by tobrun** [comment]
Ticket to update the template files in https://github.com/mapbox/mapbox-gl-native/issues/10868

**Pull request merged**
