### PR TITLE
[iOS] - Update telemetry certificate pinning

### PR DESCRIPTION
**Pull request by rclee**
This is update our certificate pinning for china.

### CODE REVIEW

**Comment by 1ec5** [comment]
Looks like you’ll need to rebase this branch atop the latest release-agua commit and change the target branch to release-agua instead of master.

**Comment by rclee** [comment]
Was hoping no-one would see that. Made the PR then saw what I did but couldn't change it because of bad train internet haha. Look good now? @1ec5

**Comment by lilykaiser** [comment]
After discussion with the @mapbox/maps-ios team, let's make a build with the CN endpoint instead of releasing this update broadly, to prevent accidental updates by Global customers.

**Comment by 1ec5** [comment]
ff4c5e12e1f17f216bb405eb18c6dc6ece8f556e comments out some more code so that we don’t end up evaluating a certificate that hasn’t been loaded.

**Comment by rclee** [comment]
@1ec5 Thanks for catching that. We should be loading both CN certs. Fixed here: https://github.com/mapbox/mapbox-gl-native/pull/11845/commits/d661aaf0a4aeee76e6fde327d61ddde5aabcd588

**Pull request merged**
