### PR TITLE
[android] telemetry - horizontal accuracy

### LINKED ISSUE #7235: Add horizontal accuracy to telemetry events
Add horizontal accuracy to location events.

### PR DESCRIPTION
**Pull request by ivovandongen**
Fixes #7235

Review @tobrun

### CODE REVIEW

**Comment by ivovandongen** [comment]
@aaronlidman @l-r Should be sufficient right? I haven't put in any rounding for now.

**Comment by l-r** [comment]
Cool @ivovandongen. Are we going to have some logic to filter out certain values as per https://github.com/mapbox/telemetry/issues/92#issuecomment-263802942? I'm on the fence for this one.

**Comment by ivovandongen** [comment]
> Are we going to have some logic to filter out certain values as per mapbox/telemetry#92 (comment)? I'm on the fence for this one.

Up to you. We can add a 0 check if you don't want those location updates.

**Comment by aaronlidman** [comment]
Yeah
> If this location does not have an accuracy, then 0.0 is returned

Can we only include > 0 for Android?

**Comment by l-r** [comment]
As per https://github.com/mapbox/telemetry/issues/92#issuecomment-263802942, if we can add rounding in there I think this is good to go.

**Comment by aaronlidman** [comment]
> Can we only include > 0 for Android?

Ignore my previous, I've been convinced otherwise.

Sounds like rounding is the only hold up.

**Comment by ivovandongen** [comment]
> If we can add rounding in there I think this is good to go.

https://github.com/mapbox/mapbox-gl-native/blob/fa96c422168c0d5006f81bba5f0c25ed4da2438c/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/telemetry/MapboxEventManager.java#L356

**Pull request merged**
