### PR TITLE
[core] Add support for data-driven styling

### LINKED ISSUE #4860: Port data-driven styling (property functions) from GL JS
Port data-driven styling from GL JS (see mapbox/mapbox-gl-js#1626). DDS is currently exposed as [property functions](https://www.mapbox.com/mapbox-gl-style-spec/#types-function) in the style specification.

Master list of what's needed. Not necessarily in implementation order.

* [x] Refactor existing `LayoutProperty` and `PaintProperty` classes such that unevaluated and evaluated properties live in separate structures (in progress, @jfirebaugh).
* [x] `gl::Drawable`/`gl::Context` need support for multiple vertex buffers.
* [x] Rename `Function` ⇢ `ZoomFunction`.
* [x] Add `PropertyFunction` and `ZoomPropertyFunction`. Add evaluators for them.
* [x] Add `PropertyFunction` and `ZoomPropertyFunction` as variant types for `PropertyValue`.
  * Might need to split `PropertyValue` into one variant for properties that are known to be feature-constant (undefined, constant, or zoom function) and one for properties that are data-driven (property function or zoom property function).
* [x] Paint properties can no longer be fully evaluated by `Style`. Instead, pass cascaded paint properties into the bucket. Bucket figures out which are feature constant and which are data-driven, producing a `ProgramConfiguration` (or `PaintConfiguration`?). In the `ProgramConfiguration`:
  * constant properties have a `ZoomFunction` which will be evaluated by the main thread and the result bound to a uniform
  * data-driven properties have a vertex buffer
* [x] Decision: for feature-constant properties, should we use `glDisableVertexAttribArray`/`glVertexAttrib*` or dynamically-generated shader uniforms?
* [x] Decision: single "interleaved" vertex buffer for all data-driven paint properties of a layer (requires implementing a custom vector type with runtime-sized elements), or one vertex buffer per data-driven property (can keep using `std::vector`).
* [x] Changing a paint property needs to do a worker round trip (if changing to or from data-driven property or updating a data-driven property), or update the `PaintConfiguration` for each bucket in place (if not).
* [x] Implement support in SDK bindings.

### LINKED ISSUE #6518: Add support for identity function type
Parity with https://github.com/mapbox/mapbox-gl-function/pull/25 and https://github.com/mapbox/mapbox-gl-js/pull/3274.

### PR DESCRIPTION
**Pull request by jfirebaugh**
Core implementation of data-driven styling. Now needs SDK bindings.

Fixes #4860.
Fixes #6518.

### CODE REVIEW

**Comment by jfirebaugh** [comment]
@brunoabinader Did you say you were able to reproduce the mysterious valgrind errors (`Assertion 'tres.status == VexTransOK' failed.`)? I haven't been able to reproduce them in my Ubuntu 14.04 VM.

**Comment by brunoabinader** [comment]
@jfirebaugh not that I remember of e.g. running the unit tests from this branch using valgrind 3.12.0 on my Linux Desktop (Ubuntu 16.04) it passed through w/ only minor suppressions from the NVIDIA GL driver.

**Comment by ivovandongen** [comment]
@jfirebaugh While implementing some examples for Android, I noticed that the source functions seem to have some caching issues:

sourcefunction-cache-issue

This is on a fill layer with a categorical source function with three stops:
- `Jordaan, rgba(0, 0, 1, 1)`
- `Prinseneiland, rgba(0, 1, 0, 1)`
- `Westerpark, rgba(1, 0, 0, 1)]]`

Similar behaviour on the examples for exponential and interval source functions.

**Comment by jfirebaugh** [comment]
@ivovandongen Should be fixed in the latest push.

**Comment by ivovandongen** [comment]
@jfirebaugh Thanks for merging in #7752. Two things that I wanted to verify are not in this version yet:
- Exponential Functions: [colorSpace](https://www.mapbox.com/mapbox-gl-style-spec/#function-colorSpace)
- Categorical Functions: default value

Both, I couldn't find in the [conversion templates](https://github.com/mapbox/mapbox-gl-native/blob/d5a6b8eba87791f5f401418928b23a6a3a31cfb2/include/mbgl/style/conversion/function.hpp)

@tobrun / @zugaldia Would you mind reviewing here instead of in #7752?

**Comment by ivovandongen** [comment]
@jfirebaugh The source/composite functions work great with the last fix. Thanks.

**Comment by 1ec5** [comment]
> Exponential Functions: [colorSpace](https://www.mapbox.com/mapbox-gl-style-spec/#function-colorSpace)

That’s being tracked in #6442.

**Comment by jfirebaugh** [comment]
> Categorical Functions: default value

That's tracked in https://github.com/mapbox/mapbox-gl-style-spec/issues/480. The current behavior is to return a default initialized value of the property type (e.g. `0.0f`, `rgba(0,0,0,0)`).

**Comment by ivovandongen** [comment]
@jfirebaugh I want to verify one more time that default values for categorical stops are not supported ATM. @boundsj implemented this for [ios](https://github.com/mapbox/mapbox-gl-native/blob/boundsj-dds-darwin-wip/platform/darwin/src/MGLStyleValue_Private.h#L215), but the [conversion templates](https://github.com/mapbox/mapbox-gl-native/blob/d5a6b8eba87791f5f401418928b23a6a3a31cfb2/include/mbgl/style/conversion/function.hpp#L120) don't support it. Shall I add this to make both implementations the similar in functionality?

**Comment by jfirebaugh** [comment]
Yeah, go ahead and add it to the API. I'll probably be adding style spec support this week or next.

**Comment by ivovandongen** [comment]
@jfirebaugh I've added a commit for the default value conversion and squashed the android api + unit tests into the android commit. 

Besides that, I've fixed up some issues from a recent rebase for the android side of things, but I think there are still some issues on the iOS side and with the codestyle script; it generates a lot of new files ending in `"` when running `make codestyle` cc @kkaefer

**Comment by jfirebaugh** [comment]
@ivovandongen Could you do a pass over the Android SDK to update it for 744487194e79badc91531ac31c11a0a7cf7c67fb (native counterpart of https://github.com/mapbox/mapbox-gl-js/pull/4175)? Basically, the default value moved from being a member of `CategoricalStops` up to a property of `SourceFunction` and `CompositeFunction`.

**Comment by ivovandongen** [comment]
@jfirebaugh Worked in `defaultValue` for composite and source functions. Assuming CI clears, Android is good to go.

**Comment by albanm** [comment]
Hello,

I only read about IOS and android support, is data-driven styling available for node version too ?

I have a property based exponential function for a fill-color style that doesn't seem to work, but I am not sure if it is supposed to work.

**Comment by kkaefer** [comment]
@albanm data-driven styling is a feature of the renderer and stylesheet format. This is shared across all platforms, so you can use a stylesheet that uses data-driven styling with the Node.js bindings as well. The mentions of iOS/Android are specific to runtime styling support for data-driven styling. The Node.js bindings never had runtime-styling, so it doesn't apply to them.

**Comment by albanm** [comment]
@kkaefer Ok, thanks for the quick and clear reply !

**Comment by 1ec5** [comment]
> The Node.js bindings never had runtime-styling, so it doesn't apply to them.

Basic runtime styling support was added to the Node module in #5318, but it doesn’t include property functions. You can set property functions via style JSON but can’t yet manipulate them via the runtime styling API. #8495 tracks the remaining work.

**Pull request merged**
