### PR TITLE
[android] - build only SDK module with make apackage

### LINKED ISSUE #7641: Make apackage builds phone and wear module
Noticed with #7640 that we are building the phone and wear module as part of `make apackage`, this is not required since we only want to build the .so and .aar files. This should help decrease the build times for release workflows on CI.

### PR DESCRIPTION
**Pull request by tobrun**
closes #7641, TODO need to test publishing a SNAPSHOT.
Review @zugaldia

### CODE REVIEW

**Comment by tobrun** [comment]
Afterbuilding the different ABI, I'm seeing this gradle output:

```
:MapboxGLAndroidSDK:preBuild UP-TO-DATE
:MapboxGLAndroidSDK:preDebugBuild UP-TO-DATE
:MapboxGLAndroidSDK:checkDebugManifest
:MapboxGLAndroidSDK:preDebugAndroidTestBuild UP-TO-DATE
:MapboxGLAndroidSDK:preDebugUnitTestBuild UP-TO-DATE
:MapboxGLAndroidSDK:preReleaseBuild UP-TO-DATE
:MapboxGLAndroidSDK:preReleaseUnitTestBuild UP-TO-DATE
:MapboxGLAndroidSDK:prepareComAndroidSupportAnimatedVectorDrawable2510Library
:MapboxGLAndroidSDK:prepareComAndroidSupportAppcompatV72510Library
:MapboxGLAndroidSDK:prepareComAndroidSupportDesign2510Library
:MapboxGLAndroidSDK:prepareComAndroidSupportRecyclerviewV72510Library
:MapboxGLAndroidSDK:prepareComAndroidSupportSupportCompat2510Library
:MapboxGLAndroidSDK:prepareComAndroidSupportSupportCoreUi2510Library
:MapboxGLAndroidSDK:prepareComAndroidSupportSupportCoreUtils2510Library
:MapboxGLAndroidSDK:prepareComAndroidSupportSupportFragment2510Library
:MapboxGLAndroidSDK:prepareComAndroidSupportSupportMediaCompat2510Library
:MapboxGLAndroidSDK:prepareComAndroidSupportSupportV42510Library
:MapboxGLAndroidSDK:prepareComAndroidSupportSupportVectorDrawable2510Library
:MapboxGLAndroidSDK:prepareComAndroidSupportTransition2510Library
:MapboxGLAndroidSDK:prepareComJakewhartonTimberTimber431Library
:MapboxGLAndroidSDK:prepareComMapzenAndroidLost200Library
:MapboxGLAndroidSDK:prepareDebugDependencies
:MapboxGLAndroidSDK:compileDebugAidl
:MapboxGLAndroidSDK:compileDebugNdk UP-TO-DATE
:MapboxGLAndroidSDK:compileLint UP-TO-DATE
:MapboxGLAndroidSDK:copyDebugLint UP-TO-DATE
:MapboxGLAndroidSDK:compileDebugRenderscript UP-TO-DATE
:MapboxGLAndroidSDK:generateDebugBuildConfig
:MapboxGLAndroidSDK:generateDebugResValues UP-TO-DATE
:MapboxGLAndroidSDK:generateDebugResources UP-TO-DATE
:MapboxGLAndroidSDK:mergeDebugResources
:MapboxGLAndroidSDK:processDebugManifest
:MapboxGLAndroidSDK:processDebugResources
:MapboxGLAndroidSDK:generateDebugSources
:MapboxGLAndroidSDK:incrementalDebugJavaCompilationSafeguard
:MapboxGLAndroidSDK:compileDebugJavaWithJavac
:MapboxGLAndroidSDK:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
:MapboxGLAndroidSDK:extractDebugAnnotations
:MapboxGLAndroidSDK:mergeDebugShaders
:MapboxGLAndroidSDK:compileDebugShaders UP-TO-DATE
:MapboxGLAndroidSDK:generateDebugAssets UP-TO-DATE
:MapboxGLAndroidSDK:mergeDebugAssets
:MapboxGLAndroidSDK:mergeDebugProguardFiles UP-TO-DATE
:MapboxGLAndroidSDK:packageDebugRenderscript UP-TO-DATE
:MapboxGLAndroidSDK:packageDebugResources
:MapboxGLAndroidSDK:processDebugJavaRes
:MapboxGLAndroidSDK:transformResourcesWithMergeJavaResForDebug
:MapboxGLAndroidSDK:transformClassesAndResourcesWithSyncLibJarsForDebug
:MapboxGLAndroidSDK:mergeDebugJniLibFolders
:MapboxGLAndroidSDK:transformNative_libsWithMergeJniLibsForDebug
:MapboxGLAndroidSDK:transformNative_libsWithSyncJniLibsForDebug
:MapboxGLAndroidSDK:bundleDebug
:MapboxGLAndroidSDK:compileDebugSources
:MapboxGLAndroidSDK:assembleDebug

BUILD SUCCESSFUL
```

This shows that only the SDK module is being build

**Comment by zugaldia** [comment]
> TODO need to test publishing a SNAPSHOT.

Let's wait then until https://github.com/mapbox/mapbox-gl-native/issues/7640 is solved?

**Comment by tobrun** [comment]
To test I started a schedulded build on this branch [here](https://www.bitrise.io/build/5490aebd9d6fca0c)

**Comment by zugaldia** [comment]
@tobrun Looks like the build in https://github.com/mapbox/mapbox-gl-native/pull/7655#issuecomment-272784473 was aborted. Rerun?

**Comment by tobrun** [comment]
Obsolete with https://github.com/mapbox/mapbox-gl-native/pull/7771

**Pull request closed without merging**
