### PR TITLE
[core] Implement "smart setStyle"

### LINKED ISSUE #7893: Implement 'smart' setStyle using diff-and-patch technique
**tl;dr:** port [smart setStyle](https://github.com/mapbox/mapbox-gl-js/pull/3621) from GL JS.

@jfirebaugh @lucaswoj  @mapbox/gl here's my thinking after my (_very_) initial digging around the gl-native world.  Feedback of course very welcome -- my hope is to dive in and start making a mess mid-next week.

## Motivation

 - Force a helpful refactor making `mbgl::Style` independent of `mbgl::Map`
 - Provide an alternate path for paint-class-specific properties, which are now deprecated in the style spec, GL JS, and the iOS SDK.

## Plan

- [ ] Make mbgl::Style independent of mbgl::Map
- <del>Introduce ['nested styles'](https://github.com/mapbox/mapbox-gl-js/issues/4000), or some alternative.</del>
  - <del>Reason: on its own, a smooth setStyle implementation is not a complete replacement for paint classes.  The problem is that the Style can accumulate state--e.g., by way of runtime styling or `GeoJSONSource#setData()`/`mbgl::GeoJSONSource::setGeoJSON`.  With paint classes, it's very easy to have a set of basemap layers with alternative styling for, say, 'day' and 'night' and some interactive layers on top of it.  Nested styles doesn't address the GeoJSON source part, but see below under "Design mbgl::Map::setStyle".</del>
- Expose means to create independent style in SDKs
  - [ ] iOS/macOS (related: https://github.com/mapbox/mapbox-gl-native/issues/6386)
  - [ ] Android
  - [ ] Qt
  - [ ] RNMBGL
- [ ] Design `mbgl::Map::setStyle(Style, ...?)`
  - How should this handle Sources that carry state? (See https://github.com/mapbox/mapbox-gl-js/issues/4006#issuecomment-275811568)
- [ ] Implement `mbgl::Map::setStyle()` using diff-and-patch method and expose it in SDKs
  - Not having dug into this yet, it seems like a clean way to do this would be to diff the given `Style` against the `map`'s current one, and then apply the necessary operations to the current one.  But doing it this way, it might be weird that after calling `map->setStyle(nextStyle)`, `nextStyle` won't refer to the map's actual style object.

---

Related: [Efficiently apply style changes #2445](https://github.com/mapbox/mapbox-gl-native/issues/2445)

### PR DESCRIPTION
**Pull request by jfirebaugh**
Implements automatic "smart setStyle" behavior for existing style-setting APIs: `Map::setStyleURL` and `Map::setStyleJSON`. Both of these APIs will now smoothly transition between the prior and new style (providing equivalent layers/sources/etc. use the same IDs).

gl

Besides the obvious behavioral change, several changes are worth calling out for consideration of their downstream impact:

* Paint property mutations now transition by default over a 300ms duration. This can be overridden via `Map::setTransitionOptions` (already existed), or within the style via the [`"transition"` property](https://www.mapbox.com/mapbox-gl-js/style-spec/#root-transition) (support added in this PR). A 300ms transition was always the intended default behavior according to the style specification, and is what's implemented in gl-js, but for whatever reason was not the default for gl-native. This change is included because it makes smart setStyle look cool.
* For `Map::setStyleURL`, the prior style remains in effect until the asynchronous network request for the new style has completed. Previously, the map would have an empty style in the interim. This caused flashing and flickering which, if not fixed, would be especially noticeable with smart setStyle.
* The internal `Style` object held by `Map` has a lifetime coincident with the `Map` lifetime itself. This was the most straightforward implementation of the prior point, but I think it's also a reasonable change on the grounds that it eliminates corner cases from the API. Specifically:
   * A `Map` now actually _has_ an (empty) style from the get go. Previously, runtime styling APIs were explicitly no-ops or errors prior to a style being loaded.
  * `Map::setStyleURL`/`setStyleJSON` update the existing internal style object in place, rather than creating a new one. There isn't currently a `Map::getStyle` method, so this is unlikely to be an externally visible change. If we add `Map::setStyle(std::unique_ptr<Style>)`, it _will_ replace the existing style object, rather than updating it in place.

Fixes #7893.

TODO:

* [x] Enable `set-style-*` integration tests and make sure they pass

### CODE REVIEW

**Comment by brunoabinader** [comment]
Beautiful @jfirebaugh!

**Comment by tmpsantos** [comment]
RIP style classes

**Comment by jfirebaugh** [comment]
Updated the description and this is ready for review.

**Comment by 1ec5** [comment]
> Paint property mutations now transition by default over a 300ms duration.

#9270 tracks documenting this default.

**Comment by 1ec5** [comment]
> A Map now actually has an (empty) style from the get go. Previously, runtime styling APIs were explicitly no-ops or errors prior to a style being loaded.

`-[MGLMapView styleURL]` currently [compensates](https://github.com/mapbox/mapbox-gl-native/blob/66c2a2a0b7c42e1947f57a412ece66fa8eaac149/platform/macos/src/MGLMapView.mm#L610) by returning the “default style URL” (currently Streets v10). I wonder if we should account for this change by making the property nullable instead of null-resettable or (if we’re concerned about backwards-compatibility) return `about:blank` as the URL. The iOS and macOS SDKs automatically load Streets unless otherwise configured, so this edge case would only occur while loading the initial style or if Streets fails to load (due to a missing access token).

/cc @boundsj

**Comment by jfirebaugh** [comment]
> Does the root property affect the transition to or from the style it’s on?

The value from the new style takes precedence, so the former.

> If the former, then is it the case that, by the time the developer has the opportunity to set this property, the transition will’ve already commenced?

No, the user has opportunities to override the style default. When using `setStyleJSON`, you can do:

```
map.setStyleJSON(newJSON);
map.setTransitionOptions({ Duration::zero() });
```

When using `setStyleURL`, you can call `setTransitionOptions` in an `onDidFinishLoadingStyle` handler.

**Comment by 1ec5** [comment]
Sounds good. In that case, the `MGLStyle.transition` documentation should mention that it affects inter-style transitions as well. A more natural way to expose transition options to the SDKs would involve something like `-[MGLMapView setStyleURL:duration:delay:]`, since a transition is by definition distinct from the start and end states. With these changes, it would be feasible to implement such a method at the SDK level, but we might need to hold off until https://github.com/mapbox/mapbox-gl-native/issues/6386#issuecomment-249033669 is completely unblocked.

**Comment by nitrag** [comment]
So to clarify, `mapViewDidFinishLoadingMap` won't fire after a style change? Only `onDidFinishLoadingStyle`?

Referencing discussion in: https://github.com/mapbox/mapbox-gl-native/issues/6180

My current code:
```swift
func mapViewDidFinishLoadingMap(_ mapView: MGLMapView) {
        //Fired each time map is changed (changing styles)
        //
        // Set up Map Data/Styles only once!
        //
        guard let style = mapView.style else {
            print("Can't load styles yet! You shouldn't be seeing this!!")
            return
        }

        //add sources
        //add layers
        ....
}

**Comment by qrh672114236** [comment]
setStyleUrl

{y.mango_measure}[Setup]: loading style failed: Attempt to invoke virtual method 'java.lang.String okhttp3.HttpUrl.host()' on a null object reference

**Pull request merged**
