### PR TITLE
[android] Adds gradle-dependency-graph-generator-plugin to Android project

### PR DESCRIPTION
**Pull request by zugaldia**
This helps us visualize the dependency tree for Mapbox dependencies. To generate the chart, run the following Gradle task:

```
$ ./gradlew generateDependencyGraphMapboxLibraries -Pmapbox.abis=armeabi-v7a
```

Graphviz needs to be installed following the instructions on the [plugin README](https://github.com/vanniktech/gradle-dependency-graph-generator-plugin).

Related: https://github.com/mapbox/mapbox-android-demo/pull/671

cc: @tobrun  @LukasPaczos  @Guardiola31337

### CODE REVIEW

**Comment by Guardiola31337** [comment]
> To generate the chart, run the following Gradle task:
>
> ```
> $ ./gradlew generateDependencyGraphMapboxLibraries -Pmapbox.abis=armeabi-v7a
> ```

No need to set an ABI to run the `generateDependencyGraphMapboxLibraries` task, `none` is fine:

```
$ ./gradlew generateDependencyGraphMapboxLibraries -Pmapbox.abis=none
```

**Comment by Guardiola31337** [comment]
Same comments as in https://github.com/mapbox/mapbox-android-demo/pull/671 👀

https://github.com/mapbox/mapbox-android-demo/pull/671#pullrequestreview-109984481
https://github.com/mapbox/mapbox-android-demo/pull/671#pullrequestreview-109985499
https://github.com/mapbox/mapbox-android-demo/pull/671#pullrequestreview-109986010

**Comment by zugaldia** [comment]
@Guardiola31337 Ready for another pass.

**Comment by zugaldia** [comment]
@tobrun `make` target added with https://github.com/mapbox/mapbox-gl-native/pull/11603/commits/4330dc9ad0f104c1aa3a3a8fc2ae7be7616242df.

**Pull request merged**
