### PR TITLE
[android] Update attribution wordmark

### PR DESCRIPTION
**Pull request by ericrwolfe**
@langsmith can you give this a run through and let me know if anything else needs to change?

### CODE REVIEW

**Comment by zugaldia** [comment]
Adding this to the 5.1 milestone for visibility.

cc: @tobrun for extra 👀 .

**Comment by langsmith** [comment]
@zugaldia @tobrun , my additions on @ericrwolfe 's PR move the attribution logo to the right of our new logo for when the map's rendered **and** in the preview image that's used when a `MapView` is added to an XML layout file.

@ivovandongen was of great help too. In our hunting down where the margins a






device-2017-04-20-094356

**Comment by langsmith** [comment]
I should add that I'm not confident that I actually went about moving the attribution over in the correct way. I suggest you look at my frazzled commit history somewhat closely so that I don't aversely affect the SDK.

@zugaldia @tobrun

**Comment by ericrwolfe** [comment]
Thanks for the corrections @langsmith.

Is there an easy way to nudge the `i` button up a pixel or two? Also, now that the logo is a bit wider, can we reduce the padding to the left and bottom of the attribution by half?

**Comment by 1ec5** [comment]
> Is there an easy way to nudge the `i` button up a pixel or two?

Could we make the logo a pixel or two smaller (maintaining the aspect ratio)? That way the helmet will be the same size as the ℹ️ button.

**Comment by tobrun** [comment]
PR is looking good, but echoing what others have mentioned, the alignment is a bit off between the logo and the attribution icon. 

device-2017-04-24-190149

**Comment by langsmith** [comment]
Ok folks. I worked a bit more on this. I haven't figured out how to adjust the equal padding around the ℹ️  button, but I'm able to move the button around to improve things.

The ℹ️  button and the helmet truly look the same size to me at this point. Using the ol' check-the-alignment-by-holding-a-piece-of-paper-up-to-the-screen-and-use-the-edge-of-the-paper trick, it appears that the height of the ℹ️  button matches the height of the helmet. The bottoms and tops are aligned. The ℹ️  button might need to move a little to the left if you all want it a bit closer to the wordmark.

Thoughts? The more specific, the better...

device-2017-04-27-193454

**Comment by zugaldia** [comment]
Great job @langsmith here and thanks @tobrun for the 👀 .

@ericrwolfe we're good to go on the Android side, anything else that you'd like to change before we 🚢 ?

**Comment by langsmith** [comment]
The failed test is because of line length in two places. I will fix when I get into the office.

**Comment by langsmith** [comment]
Do we need anything else @ericrwolfe ?

**Comment by ericrwolfe** [comment]
@langsmith sorry to leave you hanging on this. Updates look good.

If it's quick to try, would it be possible to reduce the padding around the mapbox wordmark itself? (Specifically: halve the padding to the left and bottom of the Mapbox logo; consequently, there would be approx no padding below the `i` button and the bottom screen edge). 

If not, let's go ahead and 🚢 what we have until we can spend more time on a proper mobile attribution redesign (cc @mgosline).

**Comment by tobrun** [comment]
I would love to see this PR moving forward so we can include this in next beta release. 
Will work on finalizing the changes.

**Comment by tobrun** [comment]
final result, note that info icon size was adjusted to match height icon:

image

**Comment by tobrun** [comment]
Before the final 5.1.0 release I'm suggesting to do an AWS device run to validate if the appearance is looking :ok_hand: on the diverse range of devices. For now let's get this in beta.2.

**Pull request merged**
