### PR TITLE
Add scaling marker activity to TestApp using the View Marker API

### LINKED ISSUE #5409: Add scaling marker activity to TestApp using the View Marker API
The new Android View Marker API let's you use an android View as a marker. We want to add more examples of this functionality and start by showing how scaling of views work.

Let's add a new activity to the TestApp showcasing this.

/cc: @tobrun @cammace

### PR DESCRIPTION
**Pull request by zugaldia**
`MarkerViewScaleActivity` added.

Fixes #5409.

/cc: @tobrun @cammace

### CODE REVIEW

**Comment by zugaldia** [comment]
This is how it looks like:

video

**Comment by zugaldia** [comment]
Before merging, I'd like to have @tobrun's eyes -- you're more familiar with the new API and I want to make sure I'm doing this The Right Way.

**Comment by tobrun** [comment]
LGTM :shipit:

**Comment by xinnong** [comment]
image

**Comment by zugaldia** [comment]
@tobrun @xinnong thank you for your 👀 . Rebased and merged 🚢 .

**Pull request merged**
