### PR TITLE
[core] Singleton pattern for mbgl::gl::{ObjectStore,TexturePool}

### PR DESCRIPTION
**Pull request by brunoabinader**
These objects can be safely using singleton pattern, which reduces a lot of redundant code and improves readability. Both objects resides on the same thread thus no need for ThreadLocal storage.

:eyes: @tmpsantos @kkaefer @jfirebaugh

### CODE REVIEW

**Comment by kkaefer** [comment]
Did you test this with more than one map view being present, e.g. on iOS or Android? Seems like this could cause issues.

**Comment by tmpsantos** [comment]
It was like this before (actually using TLS), the reason why it isn't anymore is because we moved rendering to the main thread so all map objects would unintentionally share the same store.

**Comment by brunoabinader** [comment]
Yes, having multiple map/view objects is exactly one of the target scenarios:
- Instead of cleaning up the objects from a single map instance, we now clear them all (specially useful for `onLowMemory()`
- TexturePool can now act in a much broader scale

However, @kkaefer is right - there is one corner case in which I didn't account for: when calling for `TexturePool::clear()` inside the Map`s dtor. I guess we could solve that by using a shared_ptr to store the TexturePool on its factory. Thoughts?

**Comment by brunoabinader** [comment]
> ~~Both objects resides on the same thread thus no need for ThreadLocal storage.~~

This isn't true in cases e.g. where multiple Map/View instances resides in different threads. Capturing the conversion with @kkaefer:

> so, in overall, the idea is 1) reduce the size of each batch of texture pools from 64 to a smaller value, and 2) have the object store and texture pool being shared among map/view instances as long as they reside on the same thread and share the same gl context

**Comment by jfirebaugh** [comment]
👎 . Not using a singleton pattern for these was very much intentional. The singleton pattern is typically an anti-pattern, making the code harder to modify (what if it turns out you _do_ need more than one) and test (you frequently _do_ need more than one in tests). In addition, being required to have access to a `gl::ObjectStore` in order to create GL resources provides an assurance that we don't try to do so on background threads.

**Comment by jfirebaugh** [comment]
9c26f063187b129218910dbb86eb21215a2cdf40

**Pull request closed without merging**
