### PR TITLE
[docs]: Add segment.io (and thus GA) to iOS doc theme

### PR DESCRIPTION
**Pull request by tmcw**

### CODE REVIEW

**Comment by 1ec5** [comment]
This template is also used for the docset that's bundled with the SDK for offline viewing. Can we find a way to inject this into the online version only? We have a deployment script for the /ios-sdk site that could do this on the fly.

**Comment by friedbunny** [comment]
@1ec5 I’m not sure it’s worth the additional complexity — chances are that people are going to be online during development (and the failure case is not catastrophic here, if offline). If offline use wouldn’t provide meaningful metrics, then I think we should go ahead and exclude.

**Comment by 1ec5** [comment]
I would prefer if we exclude this markup from the generated local documentation. The most straightforward way to do that would be to allow an include file to be passed in on the command line (or in a script). #7396 plumbs that include file through to jazzy’s existing `<head>` injection option.

**Comment by friedbunny** [comment]
#7396 looks like a workable improvement over hardcoding.

**Comment by tmcw** [comment]
Closing in favor of #7396

**Pull request closed without merging**
